### ISSUE TITLE
external library can`t use in the vst3 plug format

### ISSUE THREAD

**Issue by meghadutam** [plugdata-team/plugdata#1015]
hi,i added some external library in the plugdata(for example ZEXY）. it works very well in the standalone plugdata app.

but when i use the vst3 format plugdata . it crashed.and  shows "can`t find zexy.m_amd64" and "failed to load the library:ZEXY"

why?

THX.

**Comment by tomara-x** [comment]
externals only work in standalone version (for now at least)

**Comment by meghadutam** [comment]
ok. i got it.
thank you very much.

**Comment by timothyschoen** [comment]
More about it here: https://github.com/plugdata-team/plugdata/issues/34
