### ISSUE TITLE
Automation parameter issues

### ISSUE THREAD

**Issue by agraef** [plugdata-team/plugdata#1024]
Since the most recent JUCE update, there seems to be an issue with the range of automation controls. With the LV2 plugins at least, Ardour seems to think that they all have a range of 0..127 now, even if I have set them to the 0..1 range in the automation pane. (In the standalone, they also default to 0..127 now, but I can change them to 0..1 and then they will work correctly.)

Here's a screenshot of Ardour illustrating the issue (note the flat automation curve in Ardour, that's because the range of automation values for the control is wrong):

![image](https://github.com/plugdata-team/plugdata/assets/2853977/06fcbf29-7df3-4533-9a5c-e908b4deb980)

While I'm at it, what's up with the name editing of the params in the automation pane? After editing the name (say, `param1` to `volume`) and hitting return, it just changes back to `param1` again. Still, Ardour knows the control under the name `volume` I entered. (This isn't a recent regression, I already noticed this earlier, but haven't reported it yet.) Here's a short screencast showing the issue:

![Peek 2023-08-05 09-03](https://github.com/plugdata-team/plugdata/assets/2853977/fc0da7c0-0c01-4ca9-82e5-886690064dda)

**Comment by agraef** [comment]
Do I get a prize for submitting ticket 0x400 = #1024? :wink:

**Comment by timothyschoen** [comment]
I did change the default parameter range from 0-1 to 0-127, as that's consistent with the default range of Pd sliders. Let me know if you don't like it, I'm not completely sure about this yet either.

I'm now testing this, I couldn't reproduce the issue with VST3 and AU (tested under REAPER and Logic). The parameters of the LV2 version don't work at all in REAPER, I'll check now if that's new or if it's always been that way. I'll start Linux up to do some LV2 testing under Ardour.

**Comment by timothyschoen** [comment]
Okay I understand what's happening here now, it's kind of funny. There is a default parameter named volume, which controls the master volume in the statusbar. This is why you're seeing the volume control as a parameter, and why the parameter won't accept the name "volume". So it's not really a bug, just unfortunate behaviour. I can rename the default volume parameter name to something longer so this accident won't happen as easily.

Other than that, I do see that LV2 parameters are weird on basically every DAW, in a different way. In Ardour, changing name or range doesn't do anything. In REAPER, the parameters don't show up at all. I'll see if this is a JUCE 7.0.6 regression or if it always has been this way.

**Comment by agraef** [comment]
Yes, 0-127 does make sense as default range for sliders, but it doesn't make much sense for the default volume parameter. That parameter (whose range can't be changed AFAICT) now also goes from 0 to 127, with predictable results. If you want that to be the default range, then you also need to scale the value back to 0-1 internally, which doesn't seem to be the case currently.

And then there's the problem that with the LV2 plugins modifying the range in the parameter pane doesn't have any effect externally (the host still thinks that the range is 0-127). With VSTs changing the range (and name) does work. But with LV2 it seems that the name and range of the parameters is set statically in the dsp.ttl file. Here's an excerpt from the beginning of that file:

~~~
plug:volume
	a lv2:Parameter ;
	rdfs:label "volume" ;
	rdfs:range atom:Float ;
	lv2:default 127 ;
	lv2:minimum 0 ;
	lv2:maximum 127 .

plug:param1
	a lv2:Parameter ;
	rdfs:label "(DISABLED) param1" ;
	rdfs:range atom:Float ;
	lv2:default 0 ;
	lv2:minimum 0 ;
	lv2:maximum 127 .
~~~

I think that with LV2 you'd have to use dynamic manifests if you want to be able to change that information dynamically, but I'm not sure whether all LV2 hosts support these nowadays.

**Comment by agraef** [comment]
> This is why you're seeing the volume control as a parameter, and why the parameter won't accept the name "volume".

Yep, I now came across this, too. ;-) No reason to change that, though, it's just a quirk that you have to know about.

**Comment by timothyschoen** [comment]
> Default volume parameter. That parameter (whose range can't be changed AFAICT) now also goes from 0 to 127

Oof, quite a mistake. I see where it went wrong.

> I think that with LV2 you'd have to use dynamic manifests if you want to be able to change that information dynamically, but I'm not sure whether all LV2 hosts support these nowadays.

I didn't realise this, it makes sense, now I understand why JUCE starts the plugin up during LV2 compilation. It loads the plugin so it can inspect what parameters we added and generate the manifest. The good news is that we can ask JUCE what plugin format we're currently using, so we can just disable the min/max and rename abilities for LV2. I don't think a dynamic manifest is feasible right now, because all the LV2 handing happens inside JUCE.

**Comment by agraef** [comment]
> I don't think a dynamic manifest is feasible right now, because all the LV2 handing happens inside JUCE.

So that means that JUCE doesn't have a dynamic manifest option with LV2? That's a bummer.

Can you adjust the port names for the parameters at least? Seeing something like "(DISABLED) param1" doesn't inspire much confidence.

**Comment by agraef** [comment]
Also, that change of the default parameter range make me very uneasy.

I think that you could avoid much breakage and backward incompatibility by just going back to the 0-1 default parameter change. Having such a normalized range is much more useful for most use cases, especially if you can't really adjust the range, as with LV2.

I see the point of Pd sliders having the same range as a MIDI data byte, but I don't see any good reason why automation parameters need to follow suit there. If you want MIDI data byte values, you can always use MIDI automation via CCs in the host instead.

**Comment by timothyschoen** [comment]
> > I don't think a dynamic manifest is feasible right now, because all the LV2 handing happens inside JUCE.
> 
> So that means that JUCE doesn't have a dynamic manifest option with LV2? That's a bummer.
> 
> Can you adjust the port names for the parameters at least? Seeing something like "(DISABLED) param1" doesn't inspire much confidence.

I added this:

```
    // Reports whether the current DAW/format can deal with dynamic
    static bool canDynamicallyAdjustParameters()
    {
        // We can add more DAWs or formats here if needed
        return PluginHostType::getPluginLoadedAs() != AudioProcessor::wrapperType_LV2;
    }
    
    void setName(String const& newName)
    {
        name = newName;
    }

    String getName(int maximumStringLength) const override
    {
        if (!isEnabled() && canDynamicallyAdjustParameters()) {
            return ("(DISABLED) " + name).substring(0, maximumStringLength - 1);
        }

        return name.substring(0, maximumStringLength - 1);
    }

```


canDynamicallyAdjustParameters() will also be checked the make the name label, parameter type and range non-editable.

**Comment by agraef** [comment]
That should help a bit. But what about the default parameter range? Can we go back to 0-1 please. ;-)

**Comment by timothyschoen** [comment]
> That should help a bit. But what about the default parameter range? Can we go back to 0-1 please? ;-)

I made the volume go from 0-1 again. But since we can't change the range for LV2, I could set 0-1 everywhere, it might make it easier to scale yourself.

**Comment by agraef** [comment]
> But since we can't change the range for LV2, I could set 0-1 everywhere, it might make it easier to scale it yourself.

Yes, please! :)

I don't really see *any* compelling advantage of 0-127 over 0-1. But there are many good arguments why normalized floats are better than this accident of MIDI history.

**Comment by agraef** [comment]
Ok, then I get at least some sensible automation curves back with LV2 in Ardour, hurray! Thanks a bunch.

**Comment by timothyschoen** [comment]
I think this is as close to a solution as we'll get right now. CLAP does have working parameters FWIW, but I don't think Ardour supports it.

**Comment by agraef** [comment]
Nope, no CLAP in Ardour yet. IIRC the Ardour team would gladly accept it if anyone contributed a CLAP backend, but they won't work on it themselves.

**Comment by agraef** [comment]
Now, this looks a lot better now, thanks! :)

![Peek 2023-08-05 16-16](https://github.com/plugdata-team/plugdata/assets/2853977/5d993591-7aeb-4ef8-99b0-612f0bd1b8e9)
