### ISSUE TITLE
issues when pasting resized subpatches

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#1030]
this has been there for a long time but i wasn't able to reproduce it, i figured out today that it's about the width line after the restore

https://github.com/plugdata-team/plugdata/assets/86204514/9f4ba8aa-e507-4efe-9234-ba1f62b87755

backtrace from the crash: [pasting-resized-subpatch.txt](https://github.com/plugdata-team/plugdata/files/12267781/pasting-resized-subpatch.txt)

**Comment by timothyschoen** [comment]
Fixed it!
