### ISSUE TITLE
Plugin parameter name/range can't be edited in Ardour on the Mac

### ISSUE THREAD

**Issue by agraef** [plugdata-team/plugdata#1033]
When trying to edit a parameter name or range in the automation pane of the plugin, nothing happens. It's the same with both AU and VST3. I can select those entry fields, and double-clicking highlights their contents, but typing on the keyboard doesn't have an effect.

This only affects the plugins in Ardour on the Mac (in Reaper this works alright), and only the automation pane (editing entries in the properties pane works alright). Ardour on Linux doesn't have this defect either.

The JucePlugin_EditorRequiresKeyboardFocus compilation flag seems to be set in the plugdata source, so there's probably not much to do about it, and the fact that it works in Reaper probably means that Ardour is the culprit.

But it's such an odd little bug and other people might come across it, so I thought I should report it.

**Comment by agraef** [comment]
I should also mention that in the plugins, various keyboard shortcuts that one might expect to work, like cmd+e to toggle edit mode, cmd+1 to create a new object box, etc., might not work on the Mac either, even if the plugin editor has the keyboard focus. I noticed this with both Ardour (cmd+e is affected, cmd+1 etc. work fine) and Reaper (both cmd+e and the cmd+*digit* shortcuts are affected).

This is unrelated to the topic of this ticket, and is likely a consequence of how these keyboard shortcuts are processed on the Mac (on Linux these shortcuts work for me). In either case a keybinding of the host is executed instead (with Reaper even disabling the "Ignore FX chain keyboard shortcuts" option in the FX window menu doesn't appear to have an effect on this). But you can work around this issue by changing the host's keybindings (both Ardour and Reaper allow you to do this). Maybe this should be in a FAQ somewhere?

**Comment by timothyschoen** [comment]
On REAPER, this is fixed by enabling the "Send all keyboard input to plugin" option. But the way DAWs handle keyboard input for plugins varies a lot, it should help that all keyboard shortcuts in plugdata are configurable in the settings.

**Comment by agraef** [comment]
Indeed. Which is in the FX, not in the Options menu of the FX window. :facepalm: 

Thanks for pointing that out. Reaper is an *awesome* program, with an abundance of functionality, but its menus are a big mess. ;-) Has always been that way. Thankfully, it has this searchable action list now, but that only covers the main menu system.

**Comment by agraef** [comment]
And I now also found a similar option in Ardour's plugin window, it's that keyboard icon in the upper right corner. With that enabled, I can now also edit the parameters in the automation pane without any issues. All problems solved.

If you had a FAQ, this should definitely go into it. Or maybe we should just create a Wiki page for it, something like "plugdata in the DAW"?

**Comment by agraef** [comment]
I just quickly cobbled together a page over at my fork, see https://github.com/agraef/plugdata/wiki/plugdata-in-the-DAW. Maybe you can just pull that over to the wiki here, for the benefit of people like me who run into this and have a hard time finding this information anywhere on the web. ;-)

**Comment by timothyschoen** [comment]
Oh yeah, this should move to the wiki, I've lost count of how many times people have asked about keyboard shortcuts in REAPER

**Comment by agraef** [comment]
I can take care of this myself is you give me write access to the wiki. I promise not to vandalize it. ;-)

**Comment by timothyschoen** [comment]
> I can take care of this myself is you give me write access to the wiki. I promise not to vandalize it. ;-)

I've sent an invite, I hope I'm doing this right?

**Comment by agraef** [comment]
Works, thanks! See https://github.com/plugdata-team/plugdata/wiki/plugdata-in-the-DAW

**Comment by agraef** [comment]
I also took the freedom to add some information adjusted from the README to the Home wiki page which was basically empty and not very welcoming. ;-) Feel free to edit this as needed or just revert my changes if you don't like them.

**Comment by timothyschoen** [comment]
Looks good, thanks!
