### ISSUE TITLE
Compile mode: `[table]` erroneously marked as unsupported

### ISSUE THREAD

**Issue by dromer** [plugdata-team/plugdata#1056]
We get this in the console: `Warning: object "graph  -> array" is not supported in Compiled Mode`

**Comment by timothyschoen** [comment]
So I should just add "array" to the accepted list?

**Comment by timothyschoen** [comment]
03e9e612569afc12fbf6ef7508d0f3db57f33af2 should do it, also fixed a memory bug in hvcc compatibility mode

**Comment by dromer** [comment]
@timothyschoen noooooh! `[array]` is _not_ supported at all!

Array and Table are _not_ the same object. HVCC supports Table, but it does _not_ support Array!

**Comment by timothyschoen** [comment]
It is though, table is just an array wrapped in a subpatcher, also in pd-vanilla.

**Comment by dromer** [comment]
Well this is not how heavy interprets the object. We absolutely cannot support the array object.

**Comment by timothyschoen** [comment]
Ah okay, we'll have to find another way then

**Comment by dromer** [comment]
Yes that was my point with this bugreport. We need a different way of detecting table.

**Comment by dromer** [comment]
@timothyschoen please re-open this issue (and revert the addition of `array`) as it is not resolved.

**Comment by timothyschoen** [comment]
No need: 7a07cab0d214446348637990bb55472b1ba2eb95

**Comment by dromer** [comment]
@timothyschoen ah, thnx. bit annoying to have to resort to extra logic for this though. And it would still not resolve the issue of `pd @hv_obj` as I described.

Do you think we can do some other checks on `gui->getText()` ?

**Comment by dromer** [comment]
Hmm, I tried adding a `|| gui->getText().contains("pd @hv_obj")`, but this doesn't work:

![](https://i.imgur.com/PxsFFGb.png)

It would be nice if we could just ignore the subpatch contents when we get a match.

**Comment by dromer** [comment]
Neither using `.startsWith("pd @hv_obj")`

**Comment by dromer** [comment]
I'll open a new issue for this.
