### ISSUE TITLE
Compile mode: `[pd @hv_obj ..` should be accepted regardless its contents

### ISSUE THREAD

**Issue by dromer** [plugdata-team/plugdata#1061]
These objects/subpatches get replaced by the Heavy compiler, so whatever "incompatible" contents we can ignore.

I have tried adding `|| gui->getText().contains("pd @hv_obj")` or `.startsWith("pd @hv_obj")` , but these do not work:

![](https://i.imgur.com/PxsFFGb.png)

(the second warning only shows up when opening the main abstraction)

**Comment by timothyschoen** [comment]
I think 4b068d331c3522be481787ad104b9e5ed6ea3363 works? It will still show errors when you open the subpatch (which is probably hard to prevent), but it won't show any warnings from the parent patch.

**Comment by dromer** [comment]
Nice! Yeah this seems to do the trick. Getting the warning when opening the subpatch is fine I think. A user would typically never get there.

This just makes it so particularly optimized heavylib abstractions don't flag warnings and confuse users!
