### ISSUE TITLE
need to remove repeated spaces while creating new objects

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#1073]
https://github.com/plugdata-team/plugdata/assets/86204514/8c745312-cfb1-4ee0-bf5a-74a56bea3b83

changing the logic here fixes the spaces getting turned into zeros, but i don't know how to actually remove them (yet)

https://github.com/plugdata-team/plugdata/blob/39419851601ec8743b902b1e5c313b0c863e177d/Source/Pd/Patch.cpp#L325

**Comment by timothyschoen** [comment]
I didn't entirely understand this part of the code yet:

 auto charptr = tokens[i].getCharPointer();
auto ptr = charptr;
if (ptr - charptr) ...

Isn't ptr-charptr always 0?

Also, I think we might be able to check for empty tokens and then just continue.

**Comment by timothyschoen** [comment]
c956a8f6e91d63e3fd751ee8fc0acb8ecf20ebc2 Seems to fix the problem!

**Comment by tomara-x** [comment]
oooh! nice! that's where you add the removeEmptyStrings! i added it after the argc that's why it didn't work for me lol
