### ISSUE TITLE
list box outputs negative numbers as symbols

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#1087]
only noticeable when using the list box as a single item (so it can't update a numbox for example)

https://github.com/plugdata-team/plugdata/assets/86204514/77ccbc1a-b2e0-4910-b9cd-ae5fd08fdb5b

**Comment by timothyschoen** [comment]
Fixed with 6e1f2bd4086cad72281ebbf7a8063831bf596c84
