### ISSUE TITLE
graph~ issues

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#1092]
width message doesn't work... (it seems this is true for all arrays*) background color also doesn't seem to be happening....

* related, check more array messages

**Comment by timothyschoen** [comment]
Good to know, TIL [graph~] is a thing

**Comment by timothyschoen** [comment]
Should be fixed. I also made sure the "style" and "rename" methods work properly, and fixed an issue that caused "edit" to not work sometimes. I think we have it all covered now!

**Comment by timothyschoen** [comment]
<img width="256" alt="Screenshot 2023-08-25 at 19 16 32" src="https://github.com/plugdata-team/plugdata/assets/44585538/14217bd5-b78f-4b6b-bc8f-183ae1ccde3f">

Also added "Line width" to the inspector properties
