### ISSUE TITLE
graph on parent flag for coords message doesn't update canvas

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#1096]
works when set to 0, but setting it to 1 or 2 doesn't update

https://github.com/plugdata-team/plugdata/assets/86204514/734fe8e1-23ef-4a3f-acf6-4501ba50dcd2

https://github.com/plugdata-team/plugdata/assets/86204514/ffa26aa3-3686-4328-861d-a81d98820c5b

**Comment by timothyschoen** [comment]
Should be fixed with a565fc33561304a772a395069138b1fd7c9df301

**Comment by tomara-x** [comment]
mmm! beautiful! <3
