### ISSUE TITLE
subpatches aren't opened when clicked (sometimes)

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#1097]
right after running plugdata, when creating a new patch it doesn't work, but opening amaranth fixes it for some reason

https://github.com/plugdata-team/plugdata/assets/86204514/f429de78-2ac2-40aa-8f73-06b9dab7dda5

**Comment by timothyschoen** [comment]
Fixed with 679dc1ca6584b1b271875ad749fe962ffd2b04ec
