### ISSUE TITLE
error ctrl+click only highlights the object if it's in visible canvas

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#1098]
we need to switch to the tab containing it (if open), or open it if it's in a subpatch

https://github.com/plugdata-team/plugdata/assets/86204514/4a2c101c-2e38-49e8-98ee-c83e69ff6ed1

**Comment by timothyschoen** [comment]
We might need to change the way it works too then, opening a new tab when selecting a console message seems undesirable. There are other reasons why you might select a console message, like if you want to copy it. Maybe the "reveal object" option should be in the right click-menu, and then we also add "copy" there?

**Comment by tomara-x** [comment]
yeah, that sounds better

**Comment by timothyschoen** [comment]
https://github.com/plugdata-team/plugdata/assets/44585538/a59f689a-b689-4d71-8ee6-ad1e45aa0ffb

Done!
