### ISSUE TITLE
Deleting array-graph that is stored in the patch doesn't delete the data.

### ISSUE THREAD

**Issue by dromer** [plugdata-team/plugdata#1099]
Found this one out the hard way.

When deleting an `#X array ..` we also need to delete the associated `#A ..` data.

In pd the array needs to be deleted manually from the properties:

![](https://i.imgur.com/bQKKMZc.png)

This leaves behind an empty graph canvas, which is weird.

I'd think the best UX would be to just delete all the data when you delete the array-graph.

**Comment by dromer** [comment]
Just to confirm the last bit ^ in pd the data is deleted together with the array-graph. So that would be the main bug.

Also being able to delete the array, while keeping the canvas, would be a secondary "feature" in order to get parity.

**Comment by timothyschoen** [comment]
https://github.com/plugdata-team/plugdata/assets/44585538/b263284e-dc4e-4e55-b095-87abeb423ee2

I can't reproduce this here, if I delete the array, the data disappears too

**Comment by dromer** [comment]
Hmm .. and now it works for me as well .. that is odd ..

I had a severe case of very big stray array-graphs littering my patch (like several mb) and had to manually remove them.

If it comes up again I'll try to come with a reproducible example and we can reopen the issue ..
