### ISSUE TITLE
[knob] Angular offset error / inconsistent with vanilla 

### ISSUE THREAD

**Issue by nuoun** [plugdata-team/plugdata#1111]
Noticed some `JUCE Assertion failure in juce_Slider.cpp:1483`  errors ( https://github.com/juce-framework/JUCE/blob/2a27ebcfae7ca7f6eb62b29d5f002ceefdaadbdb/modules/juce_gui_basics/widgets/juce_Slider.cpp#L1483 ) in console while opening or saving a patch made in vanilla which turned out to be [knob]'s angular offset setting. In vanilla it accepts values [0, 360] while in plugdata the inspector only allows up to 180. Patch made with vanilla seems to work fine apart from this error in console which get printed twice for every offending knob for some reason.
[knobangerr.zip](https://github.com/plugdata-team/plugdata/files/12448783/knobangerr.zip)

**Comment by porres** [comment]
added to task list in https://github.com/plugdata-team/plugdata/issues/901

**Comment by porres** [comment]
I am closing this as it is listed in https://github.com/plugdata-team/plugdata/issues/901 though we can still use this issue for discussion
