### ISSUE TITLE
Plugdata 0.7.1  OSX 10.13 Mac Pro

### ISSUE THREAD

**Issue by pereshaped** [plugdata-team/plugdata#1113]
When trying to open a patch the interface freezes the open dialog such that you cannot choose a patch or anything else. YOu cannot close the dialog window and you loose access to Plugdadta. The only remedy is to force quit. Going back to 0.6

**Comment by pereshaped** [comment]
The PlugData download page offers 0.7 not 0.8? Hence one think they are download the latest?

**Comment by timothyschoen** [comment]
Version v0.7.1 is the last stable release, however, we are close to the release of v0.8.0 so at this point v0.8.0 is more stable than the last version. In a few weeks it will be released!

**Comment by pereshaped** [comment]
This one worked. Many thanks for that. Look forward to it.
