### ISSUE TITLE
Nightly Build 0.8 for Mac Universal. Package doesn't work. 

### ISSUE THREAD

**Issue by pereshaped** [plugdata-team/plugdata#1115]
I gives this error

![Screen Shot 2023-08-28 at 16 06 44](https://github.com/plugdata-team/plugdata/assets/4076334/08e49281-d933-43d3-8e09-d835343569a5)

**Comment by pereshaped** [comment]
It seems this has been fixed. Thank you

**Comment by timothyschoen** [comment]
These builds get automatically updated, so I guess there was just one where something went wrong

**Comment by pereshaped** [comment]
Unfortunately this version 0.8 freezes Logic completely. Im not sure what issue to raise because I can;t get a report on it. Last stable version as AU on my system is 0.7

Out of 5 tries it didn't freeze the first time but when I saved and came back to open it later it freezes within seconds and have to force quit

![Screen Shot 2023-08-28 at 21 57 37](https://github.com/plugdata-team/plugdata/assets/4076334/396c410a-2daa-43fe-aa73-019d38e23e1b)

Logic 10.4.8

**Comment by timothyschoen** [comment]
Can you try the new v0.8.0-test version? I hope it's fixed now, it worked well on both of my macbooks

**Comment by pereshaped** [comment]
Ok, thank you, I'll give a whirl later!
