### ISSUE TITLE
[oscope~] doesn't save buffer size value in patch

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#1119]
https://github.com/plugdata-team/plugdata/assets/86204514/97579df2-f45c-43c7-9e95-7504a5435a28

**Comment by timothyschoen** [comment]
It appears [oscope~] has the same problem in pd-vanilla, so this is an ELSE bug.

**Comment by tomara-x** [comment]
ah! sorry, i'll take it there <3
