### ISSUE TITLE
float values get truncated in some object properties

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#1120]
knob initial value (gets truncated when saving)

https://github.com/plugdata-team/plugdata/assets/86204514/30fd610f-f9f1-4d93-bb5d-59a628a17741

**Comment by tomara-x** [comment]
hmm we seem to have wild truncation issues

https://github.com/plugdata-team/plugdata/assets/86204514/19f90131-e97c-48d3-abaf-8d7267829b11

**Comment by timothyschoen** [comment]
Thanks, both fixed!
