### ISSUE TITLE
pressing up or left when the canvas is active causes a quantum leap

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#1129]
both on edit mode and run mode, just click on an empty space, then press up or left arrow key

only with up and left

https://github.com/plugdata-team/plugdata/assets/86204514/ea4796d6-bc61-4dc4-9750-e1cedbb3099c

notice with higher scale factor the vertical slider completely disappears

https://github.com/plugdata-team/plugdata/assets/86204514/279c5e98-42e6-48c8-ad29-17430cbf73b1

**Comment by timothyschoen** [comment]
Fixed!
