### ISSUE TITLE
save dialog is messed up for [text]

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#1134]
do we need the icon?

https://github.com/plugdata-team/plugdata/assets/86204514/77f423ee-dad9-453c-852e-80ac991f7bf1

**Comment by timothyschoen** [comment]
<img width="609" alt="Screenshot 2023-09-03 at 15 32 45" src="https://github.com/plugdata-team/plugdata/assets/44585538/c1022723-8b4d-4ca8-8933-d321f9198c07">

Fixed! It now shows no logo for small windows, and also is properly centered. I also think it makes sense that the logo only appears when closing the whole app.
