### ISSUE TITLE
initmess and display help not working

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#1141]
trying .8 and for some reason the "list a b c" message is not being sent to the list object, we get "0 0" instead.
![Uploading Screen Shot 2023-09-04 at 23.25.53.png…]()

**Comment by 60-hz** [comment]
Confirm only for "display" help  here under MacOS 12.6
Since we now have the "listbox" object in all pd distributions, do a "display" abstraction is still relevant to maintain/distribute in pd?

**Comment by porres** [comment]
> Since we now have the "listbox" object in all pd distributions, do a "display" abstraction is still relevant to maintain/distribute?

yes it is, [display] is quite different than the list box object

**Comment by timothyschoen** [comment]
The problem was that listbox was automatically sending a "0 0" message on init, whoops. Fixed now!
