### ISSUE TITLE
openfile with -h flag not working yet

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#1143]

**Comment by timothyschoen** [comment]
https://github.com/plugdata-team/plugdata/assets/44585538/c5bcf0a9-32bb-4aec-bd6e-818221314d49


Fixed! Could still be improved a bit in the future though.

**Comment by porres** [comment]
object is still malfunctioning, in your example it should not display the first symbol which is the file name ("readme.pdf"), just the rest of the list. This is happening for all examples

**Comment by porres** [comment]
![Screen Shot 2023-10-03 at 21 40 52](https://github.com/plugdata-team/plugdata/assets/5360142/4fa6bb25-3fd0-4604-9bfb-64a31d3b2971)
![Screen Shot 2023-10-03 at 21 40 59](https://github.com/plugdata-team/plugdata/assets/5360142/65697196-acb8-41ef-9e73-1556bceae3f3)

**Comment by timothyschoen** [comment]
Should be all good now :)

**Comment by porres** [comment]
this is not good, why can I not reopen the issue?

<img width="513" alt="Screenshot 2024-06-24 at 21 34 56" src="https://github.com/plugdata-team/plugdata/assets/5360142/8ca1b8d3-2065-47d2-a7ea-1259295e2d62">
