### ISSUE TITLE
Feat - auto-select search box when opening object browser

### ISSUE THREAD

**Issue by PowerUser64** [plugdata-team/plugdata#1145]
The object browser is a very nifty way to find objects, but it would be even faster to use if it auto-selected the search box for typing to search for objects. It even has the text "*Type to search for objects*", as if you could type to search without clicking in the search box.

**Comment by timothyschoen** [comment]
https://github.com/plugdata-team/plugdata/assets/44585538/9aceca79-4713-49f9-9bb2-d3bf0d7cb758

This has been superseded by the new search design that is consistent between all dialogs. Sorry!
