### ISSUE TITLE
Bug - object spawned from object browser is "offset" from its drawn position

### ISSUE THREAD

**Issue by PowerUser64** [plugdata-team/plugdata#1147]
After adding an object from the object menu, its position is offset from the position it is drawn at.

Version: 5a4716252036fa42fedc68bc9d02877820db97e5

**To reproduce:**

1. Find an object in the object menu and click "add object"
2. After placing it, try to select it with the marquee selector

Its apparent position is separated from where it is drawn.

[object-menu-offset.webm](https://github.com/plugdata-team/plugdata/assets/24578572/518eb14c-7b84-4f4b-9329-c277ee5b5f07)

**Comment by alcomposer** [comment]
Just to clarify, this is related to the `Object Browser`. Another hint is that once the object is selected from it's offset, it is then able to be select correctly.


https://github.com/plugdata-team/plugdata/assets/12004932/c39f341d-fdda-4418-ba37-2f1563ed72d9

**Comment by PowerUser64** [comment]
Ah yes, my bad. I was talking about the object browser.

**Comment by alcomposer** [comment]
Currently we have removed the add object button, and opted for a drag and drop unified UX.

So users can now drag and drop the objects from the object browser to any canvas.

Search results have not yet been updated to use this new system. However there may be a small redesign of this UI. 

@timothyschoen not sure if we should do this for 0.8.0 or 0.8.1? I'm not keen to hold up 0.8.0 any further, however this is a known missing feature ATM.

**Comment by timothyschoen** [comment]
We might do it for search results later too!

I think this bug is now fixed right?
