### ISSUE TITLE
Feat - allow double clicking on object browser results to add object

### ISSUE THREAD

**Issue by PowerUser64** [plugdata-team/plugdata#1149]
Allowing double-clicking on search results in the object browser to add objects would be a big efficiency boost to mouse navigation of the object browser. The "Create Object" button in the corner works, but it requires clicking on the result and then clicking on the "Create Object" button to add it, which is a lot of mouse movement for something that could be accomplished by allowing double-clicking on it.

**Comment by alcomposer** [comment]
The plan is to replace the current add system for `Object Browser` anyway. The new system may use the current Drag-n-drop. Which allows dragging to any split.

**Comment by timothyschoen** [comment]
We have the DnD system now!
