### ISSUE TITLE
Can't connect object in vu meter~ vis obj

### ISSUE THREAD

**Issue by charlesneimog** [plugdata-team/plugdata#1152]
Hi,

I don't use `meter~` abstraction, I like to connect `else/vu~` to the object vis `vu`, but seems that this is not possible. I need to copy and paste the floats box and connect my `else/vu~` info on that on Linux.

![image](https://github.com/plugdata-team/plugdata/assets/31707161/c968abef-cd29-49de-a7f5-233db72b2da3)

[Screencast from 2023-09-05 10-17-45.webm](https://github.com/plugdata-team/plugdata/assets/31707161/8abd4a0b-b682-4503-be34-64480e7ec72d)

**Comment by timothyschoen** [comment]
<img width="180" alt="Screenshot 2023-09-30 at 17 28 58" src="https://github.com/plugdata-team/plugdata/assets/44585538/37dcba49-111e-483e-9f94-f4d5622eb826">

Strange, [vu] does have inlets for me. Is this still an issue with the latest nightly builds?

**Comment by charlesneimog** [comment]
Hi, it is fixed on nightly builds!

**Comment by timothyschoen** [comment]
> Hi, it is fixed on nightly builds!

Nice! Thanks for confirming!
