### ISSUE TITLE
float2sig~ not working

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#1153]
this is now an abstraction and trying the help file does not seem to be effective.

also, there's a copy of the help file now to be called when you're using the abbreviated form [f2s~] and plugdata can't find this help file

ps. I hope you take some time to test this release out. I made many many changes to ELSE and we should test all changes carefully :)

**Comment by porres** [comment]
i can try and make it a compiled object again, I should actually

**Comment by timothyschoen** [comment]
I feel like f2s~-help should perhaps be in the "Help-files" folder instead of the "extra_files" folder? It is the only helpfile in extra_files, so at that point it's probably more consistent to put it with the other helpfiles.

For this version, I've now made sure f2s~-help gets copied though
