### ISSUE TITLE
CLAP crashes Reaper.

### ISSUE THREAD

**Issue by BrokenGravityMusic** [plugdata-team/plugdata#1158]
I do:
* launch reaper
* add track
* add fx to track and pick CLAPi plugdata
* click "new patch"
* i hit the "plugin mode" button (the plug icon)
* i hit the "Show editor" icon (the pencil)
* crash.

happens every time on this machine. Doesn't happen in the VST3 version.
I'm on Windows 10. Reaper version 6.82, which is the newest currently.

**Comment by timothyschoen** [comment]
Should be fixed, thanks @haenkel!
