### ISSUE TITLE
pipe2 "couldn't create"

### ISSUE THREAD

**Issue by brendanmatkin** [plugdata-team/plugdata#1159]
`plugdata v0.7.1`
(`ELSE v1.0-rc8`)

`pipe2` doesn't seem to exist. To replicate, open `osc.receive.pd` - you should see pipe2 highlighted red and a console output that says 
```
pipe2
... couldn't create
```

It _does_ work on vanilla, so I'm assuming it's a plugdata issue. 
`pd v0.54`, Both `ELSE v1.0-0 rc8` & latest (`ELSE 1.0-0 rc9`).

**Comment by brendanmatkin** [comment]
Also forgot to mention that the behaviour is the same with either `else/pipe2` or just `pipe2`.

**Comment by timothyschoen** [comment]
Hi, I believe this is fixed if you try the plugdata v0.8.0-test version.

**Comment by brendanmatkin** [comment]
Thanks @timothyschoen. Just tested on latest v0.8.0 nightly and it is working. Probably should've tested this before making the issue. Thanks for your work!

**Comment by timothyschoen** [comment]
NP, glad it's working!
