### ISSUE TITLE
Bug - shift-drag adds multiple items to undo stack

### ISSUE THREAD

**Issue by PowerUser64** [plugdata-team/plugdata#1160]
When shift-dragging a module that is connected to other modules, many items are added to the undo stack, meaning shift-dragging takes multiple undos to reverse something that was a single action.

[shift-drag.webm](https://github.com/plugdata-team/plugdata/assets/24578572/3c4f6992-bb5e-46bb-a31f-19e0726b0cbf)

**Comment by timothyschoen** [comment]
Fixed!
