### ISSUE TITLE
Bug - alt-dragging resets UI values

### ISSUE THREAD

**Issue by PowerUser64** [plugdata-team/plugdata#1161]
When alt-dragging certain objects such as the knob, the value of the control get reset to their lowest value. This could be problematic if the lowest value was something like zero or a negative number, which could cause imaginary values or dc offset.

[alt drag UI values.webm](https://github.com/plugdata-team/plugdata/assets/24578572/1fecfaee-b38b-4605-a1b4-ec1380143fe0)

**Comment by tomara-x** [comment]
this is actually a knob (else) issue, since the object doesn't have an initialize function (like numbox and other iem objects) it has no way of remembering its value
the way around it would be to connect a loadbang and a message like so:
```
#X obj 369 259 loadbang;
#X msg 369 289 18;
#X obj 369 319 knob 50 0 127 0 0 empty empty #191919 #606060 #d4d4d4 1 0 0 0 1 270 0 0 0;
#X connect 0 0 1 0;
#X connect 1 0 2 0;
```
idk why tho, i think init is useful on gui objects

**Comment by timothyschoen** [comment]
I guess this isn't really a plugdata bug, more of a limitation for the [knob] object in general
