### ISSUE TITLE
Bug - Alt-dragging has a grid snap offset

### ISSUE THREAD

**Issue by PowerUser64** [plugdata-team/plugdata#1162]
When alt-dragging an object, the object is offset on the grid until it is released and dragged again. This results in objects being placed 0.5 units offset on both the X and Y axis from where they should be.

[alt-drag-offset.webm](https://github.com/plugdata-team/plugdata/assets/24578572/40a2ca03-acba-4cd6-971d-ba7faf9a2585)

In this example, grid snapping is the only snapping I have on.

**Comment by timothyschoen** [comment]
I've now set the offset to be equal to the grid size, so this should no longer happen :)
