### ISSUE TITLE
should connections be locked in temporary run mode?

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#1166]
when holding down ctrl, connections are still interactive, is that needed?

https://github.com/plugdata-team/plugdata/assets/86204514/b8468414-28c0-416e-8840-7d22ad377f0d

**Comment by caitp** [comment]
Personally, because I can be a bit clumbsy and accidentally click a connection, I'd prefer that it did lock them.

**Comment by timothyschoen** [comment]
I agree, fixed with c59c2bbcf4e055fe1a84a92024072f635db19363
