### ISSUE TITLE
Displaying of non english special characters is wrong

### ISSUE THREAD

**Issue by 60-hz** [plugdata-team/plugdata#1169]
<img width="327" alt="Capture d’écran 2023-09-08 à 14 43 32" src="https://github.com/plugdata-team/plugdata/assets/5449719/92347bcf-cbe6-49f4-9152-ee5354c5ff84">

<img width="624" alt="Capture d’écran 2023-09-08 à 15 17 54" src="https://github.com/plugdata-team/plugdata/assets/5449719/fe6476b4-df87-4b0e-b16c-938a0ceba2d6">

**Comment by timothyschoen** [comment]
<img width="198" alt="Screenshot 2023-10-29 at 00 04 55" src="https://github.com/plugdata-team/plugdata/assets/44585538/c6a35d57-c086-489b-8dff-62eeeede6cd8">

Fixed!
