### ISSUE TITLE
Feat - allow space bar to "click" UI elements

### ISSUE THREAD

**Issue by PowerUser64** [plugdata-team/plugdata#1170]
It is common for applications to allow the use of the space bar as an alternative method of clicking the selected UI element.

A specific example of where I would like to use this in plugdata is in the "would you like to save?" menu, where the save button is clearly selected and pressing tab selects the next button, but pressing space doesn't select the button, only enter or click does.
<img src="https://github.com/plugdata-team/plugdata/assets/24578572/cfbe84a0-3999-4aa2-8c59-7f5ac8a08362" width="400" />

The reason for this action is that the space bar is often easier to reach than the enter key when navigating an interface with the keyboard because it is accessible on the left side of the keyboard.

**Comment by timothyschoen** [comment]
I think this would be very tricky since spacebar is currently used already for panning the canvas. We are also thinking of not needing to click to do panning (since mouse users tend to use it a lot).
