### ISSUE TITLE
arrays expand $0 in their names

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#1172]
that's confusing to beginners (and vanilla doesn't do it)

![Screenshot_2023-09-08_16-27-30](https://github.com/plugdata-team/plugdata/assets/86204514/f2b0df24-ed9c-40ae-82ed-45205dce3a3a)

**Comment by 60-hz** [comment]
I confirm this is a bit confusing too.
Can put the expended name in parenthesis or better: reveal it on mouse over $0.

**Comment by timothyschoen** [comment]
Fixed!
