### ISSUE TITLE
protection mode causes output gain

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#1184]
posted this in the discord, but just to be sure it doesn't get forgotten

careful, it gets loud

https://github.com/plugdata-team/plugdata/assets/86204514/3ddb6ff5-4750-4c27-b47c-3fc98790a144

**Comment by timothyschoen** [comment]
Fixed! I added a custom limiter because for some reason, JUCE::Limiter adds output gain, and that's not configurable.
