### ISSUE TITLE
Reload previous patch into Logic X hangs Logic permanently

### ISSUE THREAD

**Issue by pereshaped** [plugdata-team/plugdata#1194]
Started working on apatch to learn the automation "param" object. 

ISSUE 1
When attempting to save the plugdata patch within the Plugdata filing system, it saves fine.
However, after saving the Logic fileworking patch, I close and save the logic file and then restart Logic later and load the same Logic file with an instance of Plugdata it hangs permanently (beachball)

ISSUE 2
When working on a plugdata patch and saving the Logic file it hangs permanently (beachball) after saving.

Issue 3
Reloading the Plugdata patch plugdata/DAW doesn't remember the param objects assignment and have to be recreated in order for automation parameters to appear. Params on pacth do not show up in Automation list either

![Screen Shot 2023-09-25 at 12 20 55](https://github.com/plugdata-team/plugdata/assets/4076334/562cf097-aebe-4109-844c-b10fa7e07d7f)

Logic 10.4.8

![Screen Shot 2023-09-25 at 12 25 57](https://github.com/plugdata-team/plugdata/assets/4076334/aadecca4-0942-4b12-8a6e-169ad458f661)

**Comment by timothyschoen** [comment]
Unforunately I can't reproduce this, I think you might be right about it being based on the version of macOS you use

**Comment by pereshaped** [comment]
Oh well. Thats a shame because this project would have a been a seriously
good showcase for you platform.
Now that I know this I can concentrate on Pisound and see how it goes with
Cammomile.

Thanks for letting me know

**Comment by timothyschoen** [comment]
I ended up finding and fixing a bug when loading a patch in Logic that has automation parameters. Hope it helps!

**Comment by pereshaped** [comment]
Hi Tim, thanks, I'll have a go now

**Comment by pereshaped** [comment]
Hi Tim, that seems to have nailed it. Managed to reload 5 times so far and no crashes or hangs at all and all params there intact. Only one thing I could spot was that when you reload, the params say they are disabled in the Logic automation pulldown (see screenshot) but I just ignored it and it still worked. The disable disappears after creatong a new param for some other purpose. Minor issue as there is a simple work around.

Thanks for taking the trouble to sort the crashes out. Very very happy as can now get to work on this processor. 
![Screen Shot 2023-10-02 at 10 28 44](https://github.com/plugdata-team/plugdata/assets/4076334/362ef0c3-683d-4691-91c1-a6aaf51f4c01)

**Comment by timothyschoen** [comment]
> Hi Tim, that seems to have nailed it. Managed to reload 5 times so far and no crashes or hangs at all and all params there intact. Only one thing I could spot was that when you reload, the params say they are disabled in the Logic automation pulldown (see screenshot) but I just ignored it and it still worked. The disable disappears after creatong a new param for some other purpose. Minor issue as there is a simple work around.
> 
> Thanks for taking the trouble to sort the crashes out. Very very happy as can now get to work on this processor. ![Screen Shot 2023-10-02 at 10 28 44](https://user-images.githubusercontent.com/4076334/271921491-362ef0c3-683d-4691-91c1-a6aaf51f4c01.png)

I see, that's a bit annoying! Logic doesn't allow me to notify it of parameter changes while it's loading a patch, that caused it to crash. But if I don't notify it of the change, it will leave the params disabled. For now, I think we'll need to live with that one, fortunately you can work around it.

**Comment by pereshaped** [comment]
No worries, its only cosmetic, so not worried. Thanks for the head's up.
