### ISSUE TITLE
CLAP version of plugdata crashes REAPER when going back from plugin mode

### ISSUE THREAD

**Issue by Someone65** [plugdata-team/plugdata#1197]
Running REAPER 7.0 rc2 and plugdata 0.7.1 commit a16c664 on Windows 11, using both the fx and instrument versions of the CLAP plugin in REAPER will crash when you do the following:

1. Add the plugin to a track and open the GUI.
2. Create a new patch and then go into plugin mode from the burger menu.
3. Press the Show Editor button.

**Comment by timothyschoen** [comment]
I think @haenkel fixed this recently, could you try a nightly build? You can find them here: https://plugdata.org/download.html, under "Latest nightly".

**Comment by Someone65** [comment]
Fixed with the latest nightly. :)
