### ISSUE TITLE
when creating arrays using ctrl+shift+a they're created really far

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#1198]
all the more reason to use the drag and drop i guess xD

https://github.com/plugdata-team/plugdata/assets/86204514/40d0633e-2be5-46f6-bb51-fcd735fa5e1e

**Comment by tomara-x** [comment]
whoops that looks like my bug. it only happens wish default zoom 150

**Comment by tomara-x** [comment]
we really should get rid of the array creation dialog

**Comment by timothyschoen** [comment]
Fixed! Array dialog is no more!
