### ISSUE TITLE
segmented connections are not saved

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#1200]
https://github.com/plugdata-team/plugdata/assets/86204514/879e091f-1bb8-4859-966a-55e8f9e66d9b

**Comment by timothyschoen** [comment]
Does this always happen for you? I can't reproduce it

**Comment by tomara-x** [comment]
ooo interesting! yes, it happens all the time here. existing segmented connections (in old patches) are saved fine, even if i edit them. those edits are saved. but make a new connection and segment it, and that will reset

(idk why it didn't happen the first time)

https://github.com/plugdata-team/plugdata/assets/86204514/4828b3fa-5cd9-4f34-8c48-ee106bcfb2f2

**Comment by tomara-x** [comment]
oh! i have a480f824 and it doesn't happen there

**Comment by timothyschoen** [comment]
Oh yeah, it also happens on Linux for me

**Comment by timothyschoen** [comment]
I think it's better now?

**Comment by tomara-x** [comment]
yess! perfect!
