### ISSUE TITLE
Support for Pof library (Pd + OpenFramework)

### ISSUE THREAD

**Issue by 60-hz** [plugdata-team/plugdata#1204]
The library Pof is crashing on window's creation.
https://github.com/Ant1r/ofxPof

**Comment by timothyschoen** [comment]
Makes sense, that's for the same reason that Ofelia initially didn't work. Unfortuately running 2 windows by different frameworks (JUCE + OpenFrameworks) was not really possible, so the only way to solve it is to make it run as a separate app, and then send the Pd messages to that app :(

I think it would be better to focus on Gem first, it would be a lot of work, but it might be possible to implement it in a more normal way.

**Comment by timothyschoen** [comment]
Not planned, since including any external that uses OpenFrameworks has proven to be a major hassle
