### ISSUE TITLE
[ofelia] constant sigpipe makes ofelia unusable

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#1208]
- when an ofelia window is open it doesn't happen (edit: if you leave it open long enough, it will actually close the window and start sending sigpipe)
- if you open a window then close it, after waiting a few seconds there will be a sigpipe, and then you need to restart that patch to be able to open the ofelia window again (can't just send the `setPosition, setSize, create` messages, they don't work after a sigpipe)
- if the patch uses an external lua script instead of ofelia objects, even if the window is open, a sigpipe will happen and then causes the window to be closed, and same as above, it can't be reopened

https://github.com/plugdata-team/plugdata/assets/86204514/0ff04af5-103b-4080-8ef9-9fcf5bb1eeff

**Comment by tomara-x** [comment]
another problem is that when it happens, i think it tries to create a new window for a split second? which steals the focus, so it results in exiting the object you're editing and you have to double-click it to go back to typing..

coding difficulty = infinity

https://github.com/plugdata-team/plugdata/assets/86204514/7fd72357-5075-45fa-8b55-168369e82d18

**Comment by timothyschoen** [comment]
This is now fixed, but there is still a bug where you can get many ofelias running in the background

**Comment by timothyschoen** [comment]
Closing because I'm (for now) abandoning plugdata-ofelia

I might revive it later if I have the time, but plugdata-gem works a lot better

**Comment by tomara-x** [comment]
hehe! hi tim!
rip plugdata-ofelia
gem gonna be awesome tho
