### ISSUE TITLE
No aftertouch output in the CLAP version of plugdata

### ISSUE THREAD

**Issue by SonicAP** [plugdata-team/plugdata#1211]
Hi, I noticed that plugdata won't send aftertouch information in the CLAP version in Bitwig. I tried it with touchout and touch.out.
I just tried the VST3 version of plugdata and there it works.

**Comment by timothyschoen** [comment]
I think that may be a limitation of clap-juce-extensions :(

**Comment by SonicAP** [comment]
Thank you, that confirms my suspicion. ;-)
