### ISSUE TITLE
[note], commas get escaped

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#1213]
if you have a comma in your comment in [note], after the patch is saved, they get escaped with a backslash, probably other characters that are escaped in Pd will work the same.

**Comment by porres** [comment]
![Screen Shot 2023-10-09 at 14 32 26](https://github.com/plugdata-team/plugdata/assets/5360142/1aee22b3-78f5-4979-b858-16e136c49b28)

**Comment by timothyschoen** [comment]
Fixed it!
