### ISSUE TITLE
Icon | Dock Gnome

### ISSUE THREAD

**Issue by charlesneimog** [plugdata-team/plugdata#1214]
Hi, there is a problem related to the icon in the Dock of Gnome. 

https://github.com/plugdata-team/plugdata/assets/31707161/f6b9cd1b-7d42-4de8-a0c6-6896594b4058

When I click to open PlugData (fixed icon), it creates a new icon for software without an icon.

**Comment by timothyschoen** [comment]
No idea why that happens, but would be great to fix this!

**Comment by timothyschoen** [comment]
![Screenshot from 2023-10-20 00-33-51](https://github.com/plugdata-team/plugdata/assets/44585538/5131e909-e442-48ed-90fe-bf1d07ad03cb)

I fixed the icon issue!

I'm not sure about the extra icon appearing, that might need to be solved in the .desktop file somehow?

**Comment by charlesneimog** [comment]
It is fixed for me too!
