### ISSUE TITLE
Window drag error on Linux

### ISSUE THREAD

**Issue by charlesneimog** [plugdata-team/plugdata#1215]
It is not possible to drag the window when we have `Global scale factor` != 1. See the error with `1.1`

https://github.com/plugdata-team/plugdata/assets/31707161/249e12a3-7cb8-4d25-83bb-8839071c7688

**Comment by anaday** [comment]
This is also an issue for me. I'm on MacOS Catalina.

**Comment by timothyschoen** [comment]
Fixed, thanks for reporting!
