### ISSUE TITLE
[key] and [keyname] don't work inside subpatches

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#1217]
have to open the subpatch for it to work

https://github.com/plugdata-team/plugdata/assets/86204514/9de2edaf-e426-4c23-bdfa-c409a21c6a43

**Comment by timothyschoen** [comment]
aaahh this used to work!

**Comment by tomara-x** [comment]
yeah i have a480f824 and it work there

**Comment by timothyschoen** [comment]
Fixed!
