### ISSUE TITLE
overlay menu can't be configured

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#1219]
fresh settings file 

https://github.com/plugdata-team/plugdata/assets/86204514/0f8db2e4-a57a-4777-9d6c-dfcffef3553d

y'all wouldn't happen to have my old settings file, would you? ;-;

**Comment by tomara-x** [comment]
backup your file if you go messing around with this one, it will get corrupted and plugdata will delete it (0 byte file)

**Comment by timothyschoen** [comment]
Fixed, sorry for your settings file :(

**Comment by tomara-x** [comment]
great work as always!
don't worry it's just 3 shortcuts hehe
