### ISSUE TITLE
[pdcontrol]  and message [isvisible( inside a gop subpatch

### ISSUE THREAD

**Issue by jyg** [plugdata-team/plugdata#1220]
[pdcontrol] doesn't return 1 when responding to the  [isvisible(  msg, when inside a closed GOP subpatch.

![image](https://github.com/plugdata-team/plugdata/assets/1431894/896f4491-8d0d-4900-ad83-85d8b277b56a)
In Vanilla it does.
![image](https://github.com/plugdata-team/plugdata/assets/1431894/cb8c051e-08b8-4863-84c9-d231fb64ce6b)

Not in plugdata
![image](https://github.com/plugdata-team/plugdata/assets/1431894/c091607c-be73-4dd2-8629-d42247893b80)

(EDIT : On the left, GOP-subpatches, on the right, non-GOP subpatches)

This is why examples such as pp.spectrum~ in audiolab lib (available on deken) do not work.

**Comment by timothyschoen** [comment]
Ah, so I should set the visible flag to true even on regular non-GOP subpatches? That can be done

**Comment by jyg** [comment]
> Ah, so I should set the visible flag to true even on regular non-GOP subpatches? That can be done

Yes, a regular non-GOP subpatch is flagged as visible as soon as its window is opened in editor. (this is already OK in plugdata)

But the documentation of pdcontrol is incomplete and doesn't consider the case of :

- a GOP-subpatch whose window is closed, but with the GOP rectangle zone visible in parent patch (this one being opened). In this case, it should be flagged as visible, as pd-vanilla does, but not plugdata.

**Comment by timothyschoen** [comment]
I think I see the issue. In Pd, a GOP should use the "gl_mapped" value from the parent canvas, but that can only happen is gl_havewindow is set to false, which is currently not what it's doing.

**Comment by timothyschoen** [comment]
I made a small change to Pd, this issue is solved!
