### ISSUE TITLE
[keyboard] is not colored?

### ISSUE THREAD

**Issue by H-MLim** [plugdata-team/plugdata#1222]
![image](https://github.com/plugdata-team/plugdata/assets/68152553/4d9934be-d4f0-4d07-98c8-b2dc1ce3eab1)

hello, I just found this great program, and I've been testing my previous patches made from vanilla. and I found the `keyboard` is not colored when the key is triggered sent by `makenote`, which was a quite important feature for my previous work. moreover it responds (click-and-sound) quite slow than vanilla. is there any settings to make it colored or would it be improved later? thanks in advance.

**Comment by timothyschoen** [comment]
Hi!

I'm not sure I completely understand, I do get coloured keys when I attach makenote:

https://github.com/plugdata-team/plugdata/assets/44585538/a5e34368-0fac-48b5-a431-3a2ae41b69fb

Or do you mean multiple different colours?

**Comment by H-MLim** [comment]
hello, thank you for your reply!

but that's weird, it doesn't be colored at all when I tried same thing on my patch. what could be a problem?

https://github.com/plugdata-team/plugdata/assets/68152553/eed04b01-d528-4a5c-bb76-88f6e2f6d743

**Comment by H-MLim** [comment]
ohhh wait I figured out what was the problem. just my PlugData is not the newest. it worked fine when I updated the recent one. sorry for inconvenience and will close it seems it's ok.

**Comment by timothyschoen** [comment]
> ohhh wait I figured out what was the problem. just my PlugData is not the newest. it worked fine when I updated the recent one. sorry for inconvenience and will close it seems it's ok.

No problem, glad it's working now :)
