### ISSUE TITLE
canvas.mouse doesn't transmit values with 3rd parameter on 1, and parent patch in edit mode

### ISSUE THREAD

**Issue by jyg** [plugdata-team/plugdata#1223]
The third parameter should enable to output mouse values even if canvas is in edit mode.
This is true for the patch in which the object stays : [canvas.mouse 0 0 1].
But if we ask to get canvas.mouse information from parent patch (for example:  [canvas.mouse 1 0 1] or [canvas.mouse 2 0 1] ), it doesn't transmit anything if (grand)parent patch is in edit mode.

**Comment by timothyschoen** [comment]
Fixed!

**Comment by jyg** [comment]
Thanks a lot !
