### ISSUE TITLE
[keypress] issues

### ISSUE THREAD

**Issue by 60-hz** [plugdata-team/plugdata#1225]
[keypress]  object often don't return bang on keypress even if in runmode.
Need to build the object again, leading to crash under MacOS Sonoma 14.0, and PlugData 0.8.0.

**Comment by timothyschoen** [comment]
I think this is fixed now, there was a problem with canvas.edit that caused both the crash and wrong behaviour.

There is a tiny mistake in the helpfile, you need the "learn" message to activate key learn, not bang. I've told porres about that.

(let me know if there are still some issues though)
