### ISSUE TITLE
[ofelia] Freeze Pluggata if loaded under MacOs

### ISSUE THREAD

**Issue by 60-hz** [plugdata-team/plugdata#1239]
Ofelia lib is freezing plugdata at start under MacOs.

- The lib is loaded at start (ex: "ofelia v4.1.0")
- when loading the ofelia object, plugpata freeze and user need to kill the process to exit
- Plugdata will always freeze at exit after the external is loaded, user need to remove completely the lib's folder from the external folder to be able to exit plugdata normally again.
- Tested with Denken plugdata-ofelia and last v4.1.0 Actions builds
- Tested under different MacOS version: Sonoma, Ventura and Monterey.
- Clearing the apple quarantine attribute with the command "sudo xattr -cr /Users/raphaelisdant/Documents/plugdata/Externals/ofelia" doesn't fix the issue

**Comment by timothyschoen** [comment]
Unfortunately I have to abandon plugdata-ofelia for now.

Hoping to bring it back someday... But for now our Gem implementation is gonna work much better.
