### ISSUE TITLE
problems on saving patch

### ISSUE THREAD

**Issue by H-MLim** [plugdata-team/plugdata#1241]
![image](https://github.com/plugdata-team/plugdata/assets/68152553/94d1330a-d874-4a23-9646-1ff9994d9c1c)

hello again, I also found that when I save the new patch on the plug, it makes me only indicate the directory of save location, but can't choose the name and save the patch itself. 

for example when I try to save it on desktop, it forces to choose any save locations as folder, so when I click any folder to choose location and click on "select folder" button, suddenly the patch is saved on desktop with the folder name I chose. it occurs on v0.8.1 (not tested on 0.8.0), Windows 11

**Comment by timothyschoen** [comment]
Hi!

Could you try the latest nightly build again now? I think this is fixed

**Comment by H-MLim** [comment]
super cool. it works fine. thank you!
