### ISSUE TITLE
click message not implemented for [text] object

### ISSUE THREAD

**Issue by zealtv** [plugdata-team/plugdata#1242]
It seems the built editor for the text object isn't implemented via the click and close messages.
I have some vanilla patches that lean on the built in editor quite heavily.  

Any plans to implement this in the future?

**Comment by timothyschoen** [comment]
Whoops, it was only supported by directly clicking on the object. I'll fix it :)

**Comment by timothyschoen** [comment]
Fixed!

**Comment by zealtv** [comment]
Amazing.  Thank you so much 🙂
