### ISSUE TITLE
patch crashes when open help file

### ISSUE THREAD

**Issue by H-MLim** [plugdata-team/plugdata#1243]
hello. I found that there are some troubles with help file. when open a new patch, patching with them, opening help file has no problems. but when I save the patch (as *.pd), and try to open any help files from any objects, it suddenly crashes. this is with ver.0.8.1 (Nightly build: f6f6e26b),  Windows 11

**Comment by timothyschoen** [comment]
I think this should be fixed now. The problem was that opening the helpfile did a recursive search, which can lead it to freeze for a long time if you loaded your patch from a very full folder (like home or documents). This is now fixed!
