### ISSUE TITLE
problem with labels of number boxes and list boxes.

### ISSUE THREAD

**Issue by sevdh** [plugdata-team/plugdata#1246]
When opening a patch in Pure Data vanilla that has been created in Plug Data and contains number boxes and/or list boxes (without labels), Pure Data will show these objects with the label text "empty" (instead of no label text).

<img width="505" alt="Screenshot 2023-10-29 at 08 56 16" src="https://github.com/plugdata-team/plugdata/assets/16959264/4e7ab549-40ea-4f69-92b3-372856e0b99a">

Furthermore, the inspector in Plug Data doesn't show any label text and also doesn't allow you to edit the label text field.

When creating a patch in Pure Data with labels and opening it in Plug Data the labels are shown properly and it is possible to edit the labels in Plug Data.

(using latest nightly)

**Comment by timothyschoen** [comment]
Fixed! The problem was that the default atom objects that get created with keyboard shortcuts had "empty" as a default label.
