### ISSUE TITLE
float/symbol text always appears white at first

### ISSUE THREAD

**Issue by H-MLim** [plugdata-team/plugdata#1255]
https://github.com/plugdata-team/plugdata/assets/68152553/19a70cb4-d67e-4e2d-8076-bfbe41032219

hi. I'm now working with classic_dark theme, and I set canvas text as black. so the object or message went well in black text color. but for float and symbol, it always created with white text and it turns suddenly black as soon as I change any colors in the preferences. (Win 11/plug v.0.8.1 Nightly build f6f6e26b)

**Comment by timothyschoen** [comment]
Fixed with 39d2764a0fdf83f4b6a8ef60a7697714c2377d79!

**Comment by H-MLim** [comment]
thank you!
