### ISSUE TITLE
[note] cannot receive messages remotely

### ISSUE THREAD

**Issue by H-MLim** [plugdata-team/plugdata#1263]
Hi. it seems `note` couldn't receive any messages remotely from receive symbol in inspector, while it goes well when directly connected with `receive` object (Win 11/plug v.0.8.1 Nightly build f6f6e26b)

https://github.com/plugdata-team/plugdata/assets/68152553/9bffae6e-dc5c-48bd-80f2-52cb5b72276d

**Comment by timothyschoen** [comment]
Fixed with f0ee1acdb4b946073edebe77c2fc934d2f1c528d, thanks for reporting!

**Comment by H-MLim** [comment]
thanks!
