### ISSUE TITLE
Heavy-Daisy: customBoardDefinition not saved in dialog state tree

### ISSUE THREAD

**Issue by dromer** [plugdata-team/plugdata#1266]
This means that when you re-open the dialog you immediately get the file-browser opening up forcing the user to re-select the custom file.

**Comment by timothyschoen** [comment]
88da9dd42472c6a924b4c61074a22b6e48e4d630 should fix it!

**Comment by dromer** [comment]
Sweet! will test it. This will also come in handy when I finish up https://github.com/plugdata-team/plugdata/compare/develop...Wasted-Audio:plugdata:feature/daisy_custom_linker?expand=1

(really need a way to at least be able to point to custom linker files)

**Comment by dromer** [comment]
Nope, still tries to open the file. I think that `ScopedValueSetter` line should go to `getState()` section instead?

**Comment by timothyschoen** [comment]
265db74f65ef9bd9791605a49fd6f714165258d2 should really fix it

**Comment by dromer** [comment]
@timothyschoen yes! (now to replicate on my feature branch ..)
