### ISSUE TITLE
Bug: plugin builds can't correctly retrieve getSearchPaths()

### ISSUE THREAD

**Issue by dromer** [plugdata-team/plugdata#1276]
We see this with a simple patch like this:

![](https://i.imgur.com/ofi1wcI.png)

```gcc
--> Generating C
  1) [91mError[0m pd2hv:  in "" @ (x:0, y:0): Don't know how to parse object "hv.osc~". Is it an object supported by Heavy? Is it an abstraction? Have the search paths been correctly configured?
```

In standalone this works correctly.

**Comment by dromer** [comment]
Did a little test to print the resulting `paths` variable in the exporter and this is the difference:

standalone:
```
-p /tmp /home/dreamer/Documents/plugdata/Abstractions/else /home/dreamer/Documents/plugdata/Abstractions/cyclone /home/dreamer/Documents/plugdata/Abstractions/heavylib /home/dreamer/Documents/plugdata/Abstractions /home/dreamer/Documents/plugdata/Externals /home/dreamer/Documents/plugdata/Extra/else /home/dreamer/Documents/plugdata/Extra /home/dreamer/Documents/plugdata/User_Externals
```

plugin:
```
-p /tmp
```

Even though during runtime `searchPaths` seems to be complete (since we can load these abstractions/objects just fine).

The patchfile parent dir also gets added, when available, so I suspect that something is going wrong with `pd::Interface::getSearchPaths()`

**Comment by dromer** [comment]
Ok confirmation the issue is with `pd::Interface::getSearchPaths()`.

On desktop `numItems` returns `8`, but in the plugin (ie. VST3) it returns `0`.

**Comment by dromer** [comment]
@timothyschoen do you have an idea how we can solve these search paths for the plugin version?

**Comment by timothyschoen** [comment]
Does 5e0dd1cc1 solve it?

**Comment by dromer** [comment]
Nope.

**Comment by timothyschoen** [comment]
I think 31006f3f28b762e93e04539192797d32e8d13451 will solve it!

**Comment by dromer** [comment]
looks promising. will give it a spin!

**Comment by dromer** [comment]
I think it works, nice!
