### ISSUE TITLE
old version not deleted when update

### ISSUE THREAD

**Issue by H-MLim** [plugdata-team/plugdata#1284]
![image](https://github.com/plugdata-team/plugdata/assets/68152553/5865fd79-4102-4f98-a35a-e50e87c8c179)

hi. I assume the old version of plug should be deleted automatically as soon as update into the new version (as vanilla or Max, and many other program does). but it seems the versions are stocked instead. (in Win11)

**Comment by timothyschoen** [comment]
Unfortunately this is a problem with the nightly builds. Since it has the same version number, the installation handler (WIX) cannot deal with this correctly :(

I'll look for a solution, but last time I checked there was no workaround for this

**Comment by H-MLim** [comment]
oh I see. at least I'm relieved that's only occurs on nightly builds!

**Comment by timothyschoen** [comment]
This should be fixed since v0.9.0
