### ISSUE TITLE
Ctrl key only changes the mode but not creating objects

### ISSUE THREAD

**Issue by H-MLim** [plugdata-team/plugdata#1285]
https://github.com/plugdata-team/plugdata/assets/68152553/c5d43d79-c001-4132-b558-6d6bc4de1e73

hi. it seems in the most recent nightly build (1d843ba) it seems when I press the Ctrl key, it only changes the mode between edit and run, but it fixed after that and not creating the new objects while I try to press any number keys. (Win11)

**Comment by timothyschoen** [comment]
Fixed!

**Comment by H-MLim** [comment]
thank you!
