### ISSUE TITLE
Bug: documentation search extremely slow input and results

### ISSUE THREAD

**Issue by dromer** [plugdata-team/plugdata#1306]
Typing in the search box for the Documentation Browser is very slow and poorly responsive, this can probably use some improvement for better UX.

Next to that de-duplication is probably useful. You now get an entry for every time a query matches, but this can result in many many identical hits which makes the results difficult to browse.

**Comment by timothyschoen** [comment]
This might be hard to get around without indexing the whole thing (which we also don't really want to do). So not sure if this is fixable.

**Comment by dromer** [comment]
I think deduplication of the file-names should be doable. Speed improvements maybe not, but right now the poor UX makes it nearly useless.

**Comment by timothyschoen** [comment]
Fixed, it's an indexed search now.

It does exclude the "Toolchain" and "Versions" folder from the docs browser. Including them makes the indexing a bit too CPU intensive, since these folders have a lot of files. And the users has no reason to browse that anyway.

**Comment by dromer** [comment]
Yeah I was wondering about that. I have some copies of the toolchain in there for testing and I guess it is going to index those as well? Since I see them in the browser tab.

Maybe use a whitelist instead of a blacklist for folders to include?

**Comment by timothyschoen** [comment]
> Yeah I was wondering about that. I have some copies of the toolchain in there for testing and I guess it is going to index those as well? Since I see them in the browser tab.
> 
> Maybe use a whitelist instead of a blacklist for folders to include?

I think users should still be allowed to put folders in there, that would be a good feature imo?

If you want to exclude directories, you can make them hidden folders, or put them inside a hidden folder.
