### ISSUE TITLE
else/function can't delete points with click->delete

### ISSUE THREAD

**Issue by anxefaraldo** [plugdata-team/plugdata#1308]
Hi, 

A short note on an incomplete behaviour: the [else/function] object can not delete points in the function once created (by click - delete, as stated in the helpfile). This works fine in vanilla.

cheers.

(OS Ventura on a Mac Intel 2019)

**Comment by angelfaraldo** [comment]
Thanks, Tim. I was unaware of that.

**Comment by timothyschoen** [comment]
Added it!
