### ISSUE TITLE
Bug: crash when version is not in Heavy Toolchain COMPATIBILITY file

### ISSUE THREAD

**Issue by dromer** [plugdata-team/plugdata#1312]
With 0.8.2 - not 0.8.0

Some user reported it on the Daisy forums: https://forum.electro-smith.com/t/plugdata-new-pd-environment-that-can-flash-straight-to-daisy/3352/40

**Comment by timothyschoen** [comment]
Fixed with 45c3c44e1

**Comment by dromer** [comment]
nice!
