### ISSUE TITLE
[rm~] outputs wrong help file

### ISSUE THREAD

**Issue by H-MLim** [plugdata-team/plugdata#1316]
hi. I just found that when I try to see the helpfile of `rm~`, it  outputs the helpfile of `norm~`. I checked it outputs right helpfile in vanilla. so it might be only a problem in plug?
(Win11, Nightly build: e968785e  /  plugdata v0.8.1)

**Comment by timothyschoen** [comment]
Hi, this should be resolved in v0.8.2 and the latest nightly builds. v0.8.2 will fail to start on some Windows machines, so if that's the case for you, it should be fixed on the nightly builds.
