### ISSUE TITLE
Bug: no name in Heavy compiler remains empty and then fails

### ISSUE THREAD

**Issue by dromer** [plugdata-team/plugdata#1322]
It should pick the current patch name by default, otherwise compilation will fail.

**Comment by timothyschoen** [comment]
<img width="462" alt="Screenshot 2023-12-27 at 22 00 39" src="https://github.com/plugdata-team/plugdata/assets/44585538/ff53584f-7a74-421b-b50b-99dc2d557d6e">


I see we currently have this in the code, but I guess this somehow doesn't do it?

**Comment by dromer** [comment]
Maybe somehow `""` is considered `notEmpty()` ?

**Comment by timothyschoen** [comment]
Ah! So in that case:

```
        if (!projectTitle.unquoted().containsNonWhitespaceChars())
            projectTitle = patchFile.getFileNameWithoutExtension();

```

Should take care of everything right?

**Comment by timothyschoen** [comment]
I've pushed that: a4cd180ac

Let me know if it works now!

**Comment by timothyschoen** [comment]
Not completely sure if using patch name is the best idea, the filename could include characters that Heavy doesn't like?

**Comment by dromer** [comment]
Well this is why I was researching some input sanitization. replace any characters we don't like with `_` for instance.

**Comment by dromer** [comment]
Hmm this doesn't work! because now it will use the temp-name that is created in `/tmp/` /o\

**Comment by timothyschoen** [comment]
Ahh yeah we can test "isTempFile()" on the patch file first too

**Comment by dromer** [comment]
How do we test this? I don't see a method like this anywhere.

**Comment by dromer** [comment]
oh, I think we just need to use `realPatchFile` instead?

I'm also a bit confused by `auto searchPaths = StringArray { patchFile.getParentDirectory().getFullPathName() };` as this Would then add `/tmp/` to the search path? that seems a bit wrong.
