### ISSUE TITLE
[float] not in suggestions list

### ISSUE THREAD

**Issue by sevdh** [plugdata-team/plugdata#1332]
The [float] object does not show up in the suggestions list and is therefore difficult to create. There is no problem with the abreviated version [f].

**Comment by timothyschoen** [comment]
Fixed! Also for [symbol], which had the same issue

**Comment by sevdh** [comment]
Fantastic!On 16 Dec 2023, at 02:11, Timothy Schoen ***@***.***> wrote:﻿
Fixed! Also for [symbol], which had the same issue
