### ISSUE TITLE
[key] inputs bang twice when clicked once (with [count(er)]).

### ISSUE THREAD

**Issue by H-MLim** [plugdata-team/plugdata#1335]
https://github.com/plugdata-team/plugdata/assets/68152553/de6adc78-f2a5-496f-ac87-c7919f871f50

when I count number with `count` or `counter`, with key input using `key`, it inputs bang twice while vanilla is still OK. maybe the problem of `key`? (Win11/Nightly build: 99a1e2388)

**Comment by timothyschoen** [comment]
2c348af8f fixes it for me!
