### ISSUE TITLE
iOS issues 1

### ISSUE THREAD

**Issue by cotik1** [plugdata-team/plugdata#1337]
Hello Tim,
here a re some initial issues trying to use Plugdata on iOS (tried both on iPhone and iPad)
plugdata version 0.8.2 (last available on the App store)

1) cannot delete patchcords (as there is no touch selection helper with cords selected)
2) cannot work out how/where to save patches, trying to save them in  folders it gives the error "operation not permitted"
   I dont know much about iOS but it seems each app has its own folder where its allowed to store/read its data?

at your disposal with any questions

thank you!

Coti (on facebook with my full name as Costantino Luca Rolando Kyriakos)

**Comment by timothyschoen** [comment]
The issue with removing connections and opening files are fixed. The app now also accounts for the "safe area" for iPhones that have an inset speaker, and the AUv3 plugins will also be included in the next version :)

For saving, iOS doesn't allow apps to save to any location, it only allows saving inside the app's own container. So when saving, you'll always want to save it inside of the "plugdata" folder that should be in your documents. Sadly there is no way around that AFAIK :(
