### ISSUE TITLE
Simply does not run on Windows 10

### ISSUE THREAD

**Issue by YutMarma** [plugdata-team/plugdata#1338]
After multiple attempts at clean installs, I've come to the conclusion that plugdata just does not want to run on my Windows 10 install. I don't think there's too much mind-boggling-out-of-the-ordinary stuff going on with my computer. Vanilla PureData and PurrData both run fine.

The standalone simply will not launch. There's no outward indication that it's crashed, though Windows, to its credit, does silently create an AppCrash report. The VST3 throws a crash message when a program attempts to scan it. 

I've attached a slightly-sanitized Report.wer (renamed to .txt because github) below.
[Report.txt](https://github.com/plugdata-team/plugdata/files/13642572/Report.txt)

**Comment by timothyschoen** [comment]
We are aware of this issue, it's fixed with the latest nightly builds!

You can get them on the website: https://plugdata.org/download.html, at the bottom of the page.

**Comment by timothyschoen** [comment]
I'll also upload a new release that fixes this completely
