### ISSUE TITLE
Bug: browsing tabs with ctrl+PageUp/Down no longer works

### ISSUE THREAD

**Issue by dromer** [plugdata-team/plugdata#1339]
Very sure this still worked recently, but right now it seems we can no longer move between tabs :(

**Comment by timothyschoen** [comment]
The shortcut was changed to ctrl+shift+[], which is what most other apps seem to do. Firefox has the same shortcut here for example. If this is not a standard on Linux, let me know

**Comment by dromer** [comment]
Eh? that's really odd. Every single application with tabs that I use has ctrl+pageup/down.
I've never heard of this combo and it certainly doesn't work on any application here.

Examples that use ctrl+pageup/down and do not work with ctrl+shift+[]:

- Firefox
- Chromium/Google-Chrome
- Vscode
- Terminator

There are probably more but I'd have to go search for them.

**Comment by dromer** [comment]
Luckily we can change the keymapping ourselves (I forgot to check if this function was mappable).

One small styling gripe: the mapping popup uses JUCE default styling ;)

**Comment by timothyschoen** [comment]
> Eh? that's really odd. Every single application with tabs that I use has ctrl+pageup/down. I've never heard of this combo and it certainly doesn't work on any application here.
> 
> Examples that use ctrl+pageup/down and do not work with ctrl+shift+[]:
> 
>     * Firefox
> 
>     * Chromium/Google-Chrome
> 
>     * Vscode
> 
>     * Terminator
> 
> 
> There are probably more but I'd have to go search for them.

Ah so the standard is not the same across platforms.

I'll also look at the JUCE styling (yikes!)

**Comment by timothyschoen** [comment]
ctrl+pageup/down is now the default on Linux and Windows again.

Also, keyboard shortcut selection popup is less horrendous

**Comment by dromer** [comment]
Yay!

**Comment by dromer** [comment]
@timothyschoen it looks better, but the warning is still JUCE-y:

![](https://i.imgur.com/i8BpajN.png)
