### ISSUE TITLE
DSP problems?

### ISSUE THREAD

**Issue by H-MLim** [plugdata-team/plugdata#1341]
https://github.com/plugdata-team/plugdata/assets/68152553/35a0f229-db5c-4e4c-8e7e-4d49bae21a6d

in the recent build (Nightly build: 69268e2b2), there are no problem when I test audio on settings, but when I try to sound anything, it outputs with very disturbing jittering noises (Win11). 
(I don't know why, but these jittering noises still sound even when I turned off the DSP)

**Comment by H-MLim** [comment]
that's great to hear. look forward to the fixed one!

**Comment by timothyschoen** [comment]
Fixed!
