### ISSUE TITLE
[makenote] duration doesn't change

### ISSUE THREAD

**Issue by H-MLim** [plugdata-team/plugdata#1342]
https://github.com/plugdata-team/plugdata/assets/68152553/b1c792f7-01e6-4080-b3c1-22e193eb09e0

hi, there are also an issue on the recent build (Nightly build: 69268e2b2) that the MIDI note duration doesn't change and fixed as long note.

**Comment by timothyschoen** [comment]
I can't reproduce this on the latest nightly, is it fixed?

**Comment by H-MLim** [comment]
yeah. I think it's fixed now. thanks!

**Comment by H-MLim** [comment]
oh wait. I thought it was fixed, but it seems it's not. actually I believe I found what is problem. the `duration` input only triggered by the multiples of 10 (and/or plus 1). so when duration argument was 10, 11, 20, 21, 30... it was OK. but other numbers are not triggered. (please check the video for details) I hope you could reproduce this.

https://github.com/plugdata-team/plugdata/assets/68152553/724da717-102f-4f76-a0af-f7f63d6e4a5a

**Comment by H-MLim** [comment]
solved in Nightly build: 7ad736537
