### ISSUE TITLE
Bug: documentation window collapses tree automatically

### ISSUE THREAD

**Issue by dromer** [plugdata-team/plugdata#1345]
This one is quite annoying. You are just quietly browsing the docs and then suddenly it collapses the tree every ~20-30 seconds or so.

**Comment by timothyschoen** [comment]
https://github.com/plugdata-team/plugdata/assets/44585538/e3b09921-5759-4d16-9f49-b56508dd8ac5


This was hard to work around with the JUCE Directory viewer, so I'm rewriting all of it now. It also has faster search.

**Comment by dromer** [comment]
Sweet! Are you also deduplicating results? ;)

**Comment by timothyschoen** [comment]
Kind of? The duplication came from the fact that it will find the file through a regular path and as a symlink. That is still the case, but since it show the whole tree structure, it's not a problem anymore.

**Comment by timothyschoen** [comment]
<img width="426" alt="Screenshot 2023-12-15 at 23 30 23" src="https://github.com/plugdata-team/plugdata/assets/44585538/4972f4c1-ae6e-4e6a-a34e-80984c70dc59">

The reason I can't ship this yet, is that indexing the plugdata folder puts a thread at 100% CPU usage for about 0.5s. If you have enough threads, it's no problem, but it's still not great.

**Comment by timothyschoen** [comment]
It should now at least now collapse every 30 seconds anymore due to autosave. But the main issue that the docs browser items collapse when the shown directory changes is still there, and will be fixed at some point when I merge my branch.

**Comment by dromer** [comment]
Oh, I didn't see that "main" issue. I was just browsing the docs with no changes happening :shrug:

**Comment by dromer** [comment]
Hmm, still happens with latest commit.

**Comment by timothyschoen** [comment]
I fixed up and merged the new docs browser, so now it should really be fixed
