### ISSUE TITLE
Bug: saving patch with . in the name doesn't use .pd extension

### ISSUE THREAD

**Issue by dromer** [plugdata-team/plugdata#1349]
Might be platform specific, but when you save a patch we should force it to always have `.pd` at the end.

If you manually add a `.` to your name right now it will drop `.pd` and use the new "extension" which is of course faulty.
So you always have to manually add an additional `.pd` to the name, which shouldn't be necessary.

**Comment by timothyschoen** [comment]
0ff86da062c9d2455d42b535a89c65852c6c717f should fix it!

**Comment by dromer** [comment]
yup!
