### ISSUE TITLE
Feature: rename [r playhead] to something more private

### ISSUE THREAD

**Issue by dromer** [plugdata-team/plugdata#1351]
I really like this functionality and am considering to implement this in hvcc (at least for the DPF wrapper), but my suggestion is to rename this receiver to something less generic/public.

Could even just prepend it with a `_` or some other plugdata specific string.

This so that it won't clash with basic strings that a user might use.

**Comment by timothyschoen** [comment]
Done!

**Comment by jamshark70** [comment]
For future readers, the exact fix was to prepend `_`: [r _playhead].
