### ISSUE TITLE
Memory leaks for Linux/Windows file browsers

### ISSUE THREAD

**Issue by dromer** [plugdata-team/plugdata#1362]
I guess we got something new going on? On commit `64a3de1defe93231e4d89db89b2f0b1147da284d`

Simply opening and closing:
```
$ ./Plugins/Standalone/plugdata 
JUCE v7.0.9
Segmentation fault
```

or:
```
$ ./Plugins/Standalone/plugdata 
JUCE v7.0.9
malloc(): unsorted double linked list corrupted
Aborted
```

or:
```
$ ./Plugins/Standalone/plugdata 
JUCE v7.0.9
JUCE Assertion failure in juce_ReferenceCountedObject.h:96
corrupted double-linked list
Aborted
```

**Comment by dromer** [comment]
I guess this is some state very early when starting the program.
After a couple seconds waiting this no longer happens.

**Comment by dromer** [comment]
I'll keep these reports here for now:

Open a patch via the filebrowser. Close plugdata:

```
$ ./Plugins/Standalone/plugdata 
JUCE v7.0.9
*** Leaked objects detected: 1 instance(s) of class URL
JUCE Assertion failure in juce_LeakedObjectDetector.h:92
*** Leaked objects detected: 1 instance(s) of class FileChooser
JUCE Assertion failure in juce_LeakedObjectDetector.h:92
```

**Comment by timothyschoen** [comment]
2ed09f116 should fix the segfault/malloc errors!

**Comment by timothyschoen** [comment]
Ah yeah this was just the segfaults, leaks are still there

**Comment by timothyschoen** [comment]
I can't reproduce the leaks on Linux, but I feel like I have seen it happen in the past.

Does this happen with any file when you open it with the file browser?

**Comment by dromer** [comment]
I can actually trigger this without even opening the file.

- start plugdata
- ctrl+o
- esc
- ctrl+q

```
$ ./Plugins/Standalone/plugdata 
JUCE v7.0.9
*** Leaked objects detected: 1 instance(s) of class FileChooser
JUCE Assertion failure in juce_LeakedObjectDetector.h:92
```

**Comment by dromer** [comment]
Er, I certainly do not get any JUCE-style filebrowser.

It's a native one, but not the one that `xdg-mime query default inode/directory` says, so I'm not sure which one it is :D

**Comment by timothyschoen** [comment]
I suspect this might be a false leak: what happens is that the file browser gets cleaned up after JUCE checks for leaks. Still worth fixing though, but fortunately not a big problem

**Comment by timothyschoen** [comment]
ff0382f108064933d1212cf606183822f5f8afc0 fixes it for me!

**Comment by dromer** [comment]
Cool! I'll give it a test when I get home :)
