### ISSUE TITLE
plugdata plugin crashes in DAWs when trying to drag objects

### ISSUE THREAD

**Issue by ivicamil** [plugdata-team/plugdata#1363]
Add plugdata as a plugin in Logic Pro or Ableton Live and try to drag any object from the side bar. Plugin will crash immediately after the object is clicked. I included crash reports in the attached file. Dragging and dropping works in the standalone version.

plugdata 0.8.2
Abletion Live 11.3.13 (VST3)
Logic Pro 10.8.1 (AU)
macOS Sonoma 14.2.1

[plugdata-crash-logic.log](https://github.com/plugdata-team/plugdata/files/13751578/plugdata-crash-logic.log)
[plugdata-crash-live.log](https://github.com/plugdata-team/plugdata/files/13751579/plugdata-crash-live.log)

**Comment by dromer** [comment]
Can you try the latest nightly build? There have been quite some stability improvements.

**Comment by ivicamil** [comment]
> Can you try the latest nightly build? There have been quite some stability improvements.

The bug is indeed fixed in the latest nightly, thanks!
