### ISSUE TITLE
Auv3 plugin support for Mac, iOS and iPadOS

### ISSUE THREAD

**Issue by aexposit** [plugdata-team/plugdata#1365]
It would be awesome to have Plugadata export to auv3 (in addition to AU). That would open a lot of new possibilities on Apple mobile devices and would integrate on Auv3 hosts (AUM, Camelot Pro Loopy Pro etc..)

**Comment by timothyschoen** [comment]
I would like to do this, but unfortunately when I tried, it crashed instantly on GarageBand on iOS. I'm not sure why, since I have no idea how to debug a plugin on iOS... I could use some help, if anyone has experience with this?

**Comment by o-g-sus** [comment]
You should get prints from Xcode console ... don't you?

**Comment by timothyschoen** [comment]
> You should get prints from Xcode console ... don't you?

I think that's only true for apps, not for plugin you load in GarageBand. At least, I couldn't figure out how to debug something inside GarageBand

**Comment by o-g-sus** [comment]
For plugins you usually also get Xcode console prints. 
Set Executable to "Ask on Launch". Then you will get asked which host to open ... in this case Garage Band. Then inside Garage Band open Plugdata. Then you hopefully see some prints before the app crashes.
For testing I also recommend AUM. That's widely used as an iOS host and very stable app
<img width="936" alt="Bildschirmfoto 2024-01-04 um 15 06 21" src="https://github.com/plugdata-team/plugdata/assets/1574482/6e2e0bc3-a6f9-466e-8d6e-ba308c3cc8d0">

**Comment by timothyschoen** [comment]
All fixed now with a1f12724b750ccc1a98452a69efa644c5025de7c!

I'll upload it to the AppStore soon
