### ISSUE TITLE
Bug: Unwanted MIDI-thru behaviour.

### ISSUE THREAD

**Issue by Omar-Misa** [plugdata-team/plugdata#1366]
Hello Tim and development contributors.  Happy New Year to you.

i tried to build a note filter, whereby only notes within a settable range would be output:
[note_filter.zip](https://github.com/plugdata-team/plugdata/files/13808544/note_filter.zip)
When opened in a DAW, and limiting the key range as set by the two knobs, notes outside of the range are relayed, even though 'noteout' isn't receiving the message for those notes.

i tested this in a couple of DAWs, so it doesn't seem to be an issue borne of them.

Thanks for your time.

Environment:
Win10 64bit
PlugData 0.8.3
Latest official release of FL Studio
Tracktion Waveform 11

**Comment by timothyschoen** [comment]
This one is fixed with https://github.com/plugdata-team/plugdata/commit/2adb535d3fd18f40b94ce0c1530a069dea3ca76d
