### ISSUE TITLE
Bug : VST/Clap Audio I/O issues (Windows) - plugdata 0.8.3

### ISSUE THREAD

**Issue by bobvodka** [plugdata-team/plugdata#1367]
Using a simple pass-thru patch with a DAW (Bitwig 5.1, Windows 10, Artuira ASIO driver) results in broken sound - running a sine way into the plugin has a "clicking" sound which increases in (audio) frequency until it wraps around and starts low again - this is on top of the sine tone. 

Mousing over the connection from the adc to dac node shows the sine wave with a distortion in it.

Setting the over sampling to 1x or 2x has no impact, beyond changing the perceived frequency of the click.
- Setting the oversampling to 4x or 8x causes the plugin to simply pass the audio directly from input to output; clicking goes away but any processing in the patch has no impact. 
 
Changing the latency/samples has no impact - tried matching to DAW samples for both input and output, taking the values directly from the ASIO driver's control panel. 

Upon hitting stop in the DAW the output continues to click for some time afterwards, the sine tone vanishes however. The clicking seems to be coming from the input buffer as the scopes in the attached example show spikes still.

Note: Using a patch which generates sound internally, such as the LIRA-8 instrument, works fine with no output issues.

OS : Windows 10
DAW: Bitwig 5.1
Plugdata : 0.8.3
(Also happens in Nightly build: 7ad736537)
VST3 and CLAP both have issue.

Example patch : [SimplePassThru.zip](https://github.com/plugdata-team/plugdata/files/13810387/SimplePassThru.zip)

**Comment by timothyschoen** [comment]
Fixed with aff9ac6e14b55d908b213182fc7b03f4d56eeeee!
