### ISSUE TITLE
Plugdata does not run!

### ISSUE THREAD

**Issue by Danilorun** [plugdata-team/plugdata#1371]
Hello all!

I tried to run plugdata on windows 10 64bit, but when I double click the icon after the waiting status of the mouse pointer nothing happens. I tried with several plugdata versions. 

Thank you

**Comment by esrsound** [comment]
Same here. Plugins (vst3/clap) doesn't work in bitwig and standalone version does't run. 
Tested on: Windows 11 22H2, plugdata 0.8.2

**Comment by timothyschoen** [comment]
Hi! This is a know issue, please try the latest nightly build for Windows, those will work!

You can get them here, at the bottom of the page: https://plugdata.org/download.html
