### ISSUE TITLE
AUv3 iPad iOS bugs

### ISSUE THREAD

**Issue by alxpsr** [plugdata-team/plugdata#1377]
## Bugs

1. There is no normal scaling of the plugin. Part of the interface is out of view and simple zooming operation does not solve this problem.
1. The program freezes frequently (interface freezes and you can't do anything).
1. You can't save patches. A lot of AUv3 plugins allow you to save and load presets and patches, the problem is solvable.
1. The program often crashes

## Tech info
- iOS version: `iPadOS 17.2`
- App version: `0.8.3`

## Etc
Feel free to ask any additional information. Appreciate your efforts to develop such application

**Comment by timothyschoen** [comment]
Hi, thanks for reporting. I missed this one but it's mostly the same as https://github.com/plugdata-team/plugdata/issues/1378, so feel free to also answer my follow-up questions there :)

**Comment by alxpsr** [comment]
Got it. I'll close the issue then. Thanks
