### ISSUE TITLE
netreceive and netsend throw WSANOTINITIALISED on Windows

### ISSUE THREAD

**Issue by giohappy** [plugdata-team/plugdata#1379]
I'm testing `osc.receive` and `osc.send` objects (ELSE abstractions), but they don't work since the underlying `netreceive` and `netsend` objects throw the following error when trying to connect to any (valid) port:

`netreceive: bad host or port? Either the application has not called WSAStartup, or WSAStartup failed.  (10093)`

10093 is `WSANOTINITIALISED`, which according to Mcirosoft documention means:

>Successful WSAStartup not yet performed.
Either the application has not called [WSAStartup](https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-wsastartup) or WSAStartup failed. The application may be accessing a socket that the current active task does not own (that is, trying to share a socket between tasks), or [WSACleanup](https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-wsacleanup) has been called too many times.

**Comment by giohappy** [comment]
I think the problem is in that [socket_init()](https://github.com/plugdata-team/plugdata-pd/blob/1a23f1368cb5722572310b2579a4c90149da42f8/src/s_net.c#L228) is never called inside PlugData. This is the method that performs the required `WSAStartup`.
This method in Pd is called inside [sys_main()](https://github.com/plugdata-team/plugdata-pd/blob/1a23f1368cb5722572310b2579a4c90149da42f8/src/s_main.c#L413), which is never called vy PlugData.

After executing socket_init() I was able to connect the sockets for both `netsend` and `netreceive`

**Comment by timothyschoen** [comment]
Ohh that makes a lot of sense! Thanks for figuring that out!

**Comment by giohappy** [comment]
I suppose a good place to perform the socket_init() would inside [Setup::initializePd](https://github.com/plugdata-team/plugdata/blob/64a3de1defe93231e4d89db89b2f0b1147da284d/Source/Pd/Setup.cpp#L688) but of course I'll leave the decision to you.

**Comment by timothyschoen** [comment]
Should be fixed with 71a603c22!

**Comment by giohappy** [comment]
Works great, just tested with Open Sound Control. Thanks!

![image](https://github.com/plugdata-team/plugdata/assets/571129/df442abc-b0cd-4228-90eb-757c45a426bc)
