### ISSUE TITLE
bug: when reopening previous patch the console says "Patch is already open"

### ISSUE THREAD

**Issue by dromer** [plugdata-team/plugdata#1380]
It should only gives this warning if we _actually_ have the patch open.

..

I just tried this with several patches and it happens for a specific one. However I'm unable to discern why it gives this warning for this specific patch .. it even says it when I open it on a new session ..

Will try to narrow down when this actually happens ..

**Comment by timothyschoen** [comment]
I believe this has been fixed? Let me know if it still happens!
