### ISSUE TITLE
Pls add Neural network libraries to process audio samples

### ISSUE THREAD

**Issue by aexposit** [plugdata-team/plugdata#1381]
Hi now everything is AI based ;-) 
It would be great to have a NN inference library included in Plugdata for example RTNeural (https://github.com/jatinchowdhury18/RTNeural) and some matrix processing library too (ex. Eigen)

**Comment by dromer** [comment]
Can you point to some PD external that uses this?

Otherwise this is really not a reasonable request to make.

**Comment by aexposit** [comment]
Not yet. I could try to assemble as external and be back on this if useful for others.
Thx

**Comment by timothyschoen** [comment]
Hi, 

We're currently not planning to add any new collections of externals to plugdata before version 1.0

If you're creating a new neural networking external, you could ask @porres if it could be included in ELSE! That way, it will also get included in plugdata.

**Comment by porres** [comment]
> We're currently not planning to add any new collections of externals

As I see this is not any existing collection to add but a new one

> If you're creating a new neural networking external, you could ask @porres if it could be included in ELSE! 

Sure, I don't think I can create one from scratch though :)

> I could try to assemble as external and be back on this if useful for others.

Now we're talking...

**Comment by porres** [comment]
btw, there is this one https://github.com/alexdrymonitis/neuralnet
