### ISSUE TITLE
Bug: abstractions show up without text

### ISSUE THREAD

**Issue by dromer** [plugdata-team/plugdata#1383]
Sometimes when opening a patch an abstraction will show up like an empty object:

![](https://i.imgur.com/y0b5V8u.png)

It's still functional and you can edit the text. It will then only be visible after making a change.
Just double clicking isn't enough. it needs an actual/temporary edit of the text. ie. add space, then remove space, enter.

**Comment by timothyschoen** [comment]
Ah, must be something going wrong with the hash.

I have a new system for object text layouting, where it calculates a very accurate/pleasing layout once, and then reuses that as long as the hash of text and width is the same. Looks like here it never layouts the first time

**Comment by timothyschoen** [comment]
Btw, I couldn't find your comment on Gem, but the commits are a bit messy indeed. I might make a new branch with only minimal changes, but I started working on this outside of a repo (because I didn't expect it to work). Then I had to copy everything back in

**Comment by timothyschoen** [comment]
I wasn't able to reproduce this, but I think b394c5df4 should fix it?

**Comment by dromer** [comment]
I'll give it a test when I get home!

**Comment by dromer** [comment]
Seems to have done the trick. Will close until further notice :)
