### ISSUE TITLE
constant crashes when opening help

### ISSUE THREAD

**Issue by esrsound** [plugdata-team/plugdata#1385]
I constantly get crashes when requesting help on elements (more often when trying open help on ELSE objects, though I don't think it matters.). There is no dependence on which specific elements the help is requested for, it happens all the time. I've already set the autosave to 20 seconds, so I don't lose what was done in the patch. Happens on both macos and windows 11. Tried different versions, stable 0.8.2, night builds, does not help.

**Comment by esrsound** [comment]
> Do you have a crash report on macOS when this happens? That would help a lot!

I work more on windows, I'll try to send a log next time when I get an error on macos.

**Comment by esrsound** [comment]
> Do you have a crash report on macOS when this happens? That would help a lot!

Is any option to run with logging in windows or macos?

**Comment by esrsound** [comment]
Tested it on iOS 17.2.1 on iPad Pro m2. Also got several crashes during the evening. Always just trying to get help on ELSE functions.

**Comment by timothyschoen** [comment]
> > Do you have a crash report on macOS when this happens? That would help a lot!
> 
> Is any option to run with logging in windows or macos?

What kind of logging do you mean?



> Tested it on iOS 17.1.2on iPad Pro m2. Also got several crashes during the evening. Always just trying to get help on ELSE functions.

I've been trying to open a lot of helpfiles here, but no crashes yet. Are there any specific ones that seem to cause problems?

**Comment by esrsound** [comment]
> > > Do you have a crash report on macOS when this happens? That would help a lot!
> > 
> > 
> > Is any option to run with logging in windows or macos?
> 
> What kind of logging do you mean?

I would like to be able to even at least night builds to be able to save a log of the program crash, so that it would be easier for you to even track these errors. Bottom line

> > Tested it on iOS 17.1.2on iPad Pro m2. Also got several crashes during the evening. Always just trying to get help on ELSE functions.
> 
> I've been trying to open a lot of helpfiles here, but no crashes yet. Are there any specific ones that seem to cause problems?

My typical scenario with plugdata is creating a patch and browsing in parallel (opening help files) for various functions. I've noticed that most crashes happen when opening help files, which I open through a browser with documentation or function descriptions in the right-hand side. Most often I look at help files from ELSE library.

**Comment by esrsound** [comment]
> I've been trying to open a lot of helpfiles here, but no crashes yet. Are there any specific ones that seem to cause problems?

I would like to add that it doesn't depend on the number of open files, I've gotten crashes even with two or three files open at the same time.

**Comment by esrsound** [comment]
> Do you have a crash report on macOS when this happens? That would help a lot!
Gotcha!

[macos_error.txt](https://github.com/plugdata-team/plugdata/files/13954314/macos_error.txt)

**Comment by esrsound** [comment]
So, the last two errors sequence of action: click help on "readsf" -> click help "file switch" -> click help "file split on" -> crash.

**Comment by timothyschoen** [comment]
Thanks, that helps a lot!!

c8a1f4b48 fixed it for me
