### ISSUE TITLE
ipad os, standalone, no signal from adc~

### ISSUE THREAD

**Issue by okkobroderson** [plugdata-team/plugdata#1387]
ipad6, ipados 17.2
tested with internal mic and usb zoom u-24
signal input is shown in settings.
but no signal coming from adc~

**Comment by timothyschoen** [comment]
Thanks for reporting, is this in the app or AUv3 plugin?

**Comment by timothyschoen** [comment]
Ah yes, sorry for that. The iOS version is currently a bit experimental, stability should improve over the coming releases.

But good to know it's an issue with the regular app!

**Comment by timothyschoen** [comment]
Fixed once the app is accepted into the AppStore
