### ISSUE TITLE
Plugin Crash in Reaper running in Linux GLIBC problem

### ISSUE THREAD

**Issue by JRSV** [plugdata-team/plugdata#1391]
Hello,

I ran into a crash today while teaching (never good). I updated my reaper installation to 7.08 and istalled the latest LV2 verison but when I try to load I get a "segmentation fault" and reaper crashes. I tried installing VST3 but it fails to be loaded by reaper on startup.

the only info I get when the crash occurs in terminal is "segmentation fault" 
any idea what is going on??

cheers

UPDATE :::::::::::::::::::::::::::::::
I tried with Reaper 6.8 with no luck. I decided to download the binaries and tried with them and now I have more information. Additionally, now reaper does not crash, it just does not load the plug in and terminal says:

"swell: dlopen() failed: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /home/jrsv/lv2/plugdata.lv2/libplugdata.so)"

which I guess I know what goes on, the problem is that glibc is not an "updatable" component. So now I cant run the plug in, I am wondering if it has to do with how it is compiled. The compiled binary version of plugdata does not work in my debian 11 system, even the standalone one. But if I install through repositories, I get a standalone version that does run but a plugin version that does not.

Would this eventually be fixable? or can I expect to not have plugdata running in this computer now?

UPDATE 2 ::::::::::::::::::::::::::::::

Ok, so now I have downloaded version plugdata v 0.8 expecting to downgrade but have a usable version, I suspect that the binaries are being compiled against your machines using glibc versions newer than mine. This apparently makes the binaries unusable if you have an older version of glibc. I am afraid this is a big problem, as plugdata would be limited to run in machines that keep a "rolling release" of linux. Debian, a famously stable distribution holds back. Now the big issue in my end is that if plugdata is developed like this, I will constantly end up in this type of scenario were even if I download an older version that previously worked in my system it would not work then, as a "fresher" build is linking to the latest glibc, this means that i would need to build against my system every time. [131](https://github.com/helgoboss/realearn/issues/503#issuecomment-1506418)

This issue with latest GLIBC is common, I actually ran into something similar with Realearn
[503](https://github.com/helgoboss/realearn/issues/503#issuecomment-1321201416)

When I try to run the standalone version of plugdata 0.8 I get the glibc errors:
"./plugdata 
./plugdata: /lib/x86_64-linux-gnu/libmvec.so.1: version `GLIBC_2.35' not found (required by ./plugdata)
./plugdata: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by ./plugdata)
./plugdata: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by ./plugdata)
./plugdata: /lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by ./plugdata)
./plugdata: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./plugdata)
./plugdata: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./plugdata)
./plugdata: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./plugdata)
./plugdata: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./plugdata)"

finaly, PlugData is offered in different repos, but one does not find the same versions in them. for example Ubuntu 22.04 has the latest "0.83" and "0.82", but Debian 11 repo has the latest "0.83" but then it finds "0.8" and "0.64"

**Comment by JRSV** [comment]
Just tried with Reaper version 6.8 with same outcome. I suspect its something in plugdata as it used to work with that reaper with no problem.

**Comment by timothyschoen** [comment]
Hi!

What distro are you using yourself? That is ususally important when there is a GLIBC version mismatch.

Basically, the distro you are running has an older version of glibc than what plugdata needs. My first recommendation here, is building from scatch, then the problem will definitely get solved. To do so:


```
sudo apt install -y cmake git wget bzip2 build-essential libasound2-dev libjack-jackd2-dev curl libcurl4-openssl-dev libfreetype6-dev libx11-dev libxi-dev libxcomposite-dev libxcursor-dev libxcursor-dev libxext-dev libxrandr-dev libxinerama-dev ccache python3 python3-pip

git clone --recursive https://github.com/plugdata-team/plugdata.git -b develop
cd plugdata
mkdir build && cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
cmake --build .
```

This will take a second, but now you have your own version plugdata, made for your specific OS. The plugins and standalone app will all be in the "Plugins" folder now.


>finaly, PlugData is offered in different repos, but one does not find the same versions in them. for example Ubuntu 22.04 has the latest "0.83" and "0.82", but Debian 11 repo has the latest "0.83" but then it finds "0.8" and "0.64"

There were some problems with the OBS build system, I believe it got solved recently though. So never versions should be on there very soon!

**Comment by timothyschoen** [comment]
> Ok, so now I have downloaded version plugdata v 0.8 expecting to downgrade but have a usable version,

I think you are using debian oldstable right? The binaries we provide are made for debian stable, but when v0.8.0 was released, what is now "oldstable" was then "stable" ;)

**Comment by JRSV** [comment]
yes, sorry

my system is  AVL-MXE 21.3 (Debian 11).
I will try compiling myself, and get back to you if I run into any issues. I hope it maintains its compilation simplicity. if for some reason it gets complicated, it will be difficult for me to keep using plugdata, but your instructions seem simple. Thanks for the help.

**Comment by timothyschoen** [comment]
If manual build fails, I could add another debian build for oldstable. Let me know how it goes!

**Comment by JRSV** [comment]
Ok, great news, after an hour or a bit more or so, Plugdata is compiled and for now working with no issue. As long as these compilation instruction and processes are maintained simple, I think there will be no problem compiling. 
thanks @timothyschoen for this great project and for your help with my problems.

cheers
