### ISSUE TITLE
Full support for dynamically setting properties

### ISSUE THREAD

**Issue by timothyschoen** [plugdata-team/plugdata#140]
Some properties (especially colours, array size and maybe some more) can be set dynamically, but I'm not yet able to do this for all properties :(

For example, you can set the colour of a toggle, but not the non-zero value.

**Comment by phasebash** [comment]
This would be great.  I've noticed that hsliders cannot have their colors reassigned and viewable through a graph-on-parent, but they are visible when the abstraction is opened. Seems there is another issue for that too.

**Comment by timothyschoen** [comment]
I agree, the problem is that there is no way to get a callback whenever one of these parameters changes. So either I'll have to check periodically (which will become more expensive as the patch grows larger), or I'll have to find some kind of mechanism to intercept incoming messages to the inlet. Pd might have a way to do that, but I'm not sure.

**Comment by timothyschoen** [comment]
I've found a way to implement this, it's planned to v0.6.3

**Comment by timothyschoen** [comment]
Should be done!

**Comment by phasebash** [comment]
Awesome, can't wait to try it out, thanks for digging in there.
