### ISSUE TITLE
Wrong buffer size in gem windows

### ISSUE THREAD

**Issue by 60-hz** [plugdata-team/plugdata#1400]
Changing the [gemwin] size, either with mouse or a [dimen( message result in wrong buffer size on screen. 
A square is stretched to a rectangle if the size of the windows is not square...

Tried under MacOS Sonoma 14.0 with dev actions, commit b376343

**Comment by timothyschoen** [comment]
Fixed with 6661e91d9!

Also, the few commits before it have improved stability a lot for me
