### ISSUE TITLE
Colored suggestions for gem objects

### ISSUE THREAD

**Issue by 60-hz** [plugdata-team/plugdata#1404]
In the auto completion list, the gem lib objects should have a green icon to follow the gemlist color logic.

<img width="312" alt="Capture d’écran 2024-01-24 à 22 49 28" src="https://github.com/plugdata-team/plugdata/assets/5449719/ab68c620-1910-4d7c-8704-1624325e63e8">

**Comment by dromer** [comment]
gemlist has "color logic"?

**Comment by 60-hz** [comment]
Yes, tim has just implemented it in the development, so the green color is for representing a gemlist.

<img width="366" alt="Capture d’écran 2024-01-24 à 23 53 38" src="https://github.com/plugdata-team/plugdata/assets/5449719/6b43ba84-0a7b-4684-88d0-9279aa7bd18a">

**Comment by 60-hz** [comment]
At least the inlets color for control / signal / gem can be modified in the theme panel yes.

**Comment by timothyschoen** [comment]
Done!

I also had to make it smart about knowing whether or not gem is a declared lib:

<img width="366" alt="Screenshot 2024-01-25 at 14 34 25" src="https://github.com/plugdata-team/plugdata/assets/44585538/f98b0ff0-e0ed-4263-b2c5-72ca525c23af">

<img width="369" alt="Screenshot 2024-01-25 at 14 34 39" src="https://github.com/plugdata-team/plugdata/assets/44585538/47a1c62e-11ad-40ec-8b0d-ab0411cd1fff">

Unfortunately the tooltips and descriptions are not smart enough to deal with duplicate object names yet...

Also, I think we could maybe use a slightly less bright shade of green?

**Comment by dromer** [comment]
Yeah it could definitely be a bit darker green, this is bit too neon-like :#
