### ISSUE TITLE
[pix_sig2pix~] and [pix_pix2sig~] couldn't create

### ISSUE THREAD

**Issue by 60-hz** [plugdata-team/plugdata#1405]
both [pix_sig2pix~] and [pix_pix2sig~] couldn't create, I guess because they are using signal and gem_state.

**Comment by timothyschoen** [comment]
<img width="180" alt="Screenshot 2024-01-25 at 15 24 09" src="https://github.com/plugdata-team/plugdata/assets/44585538/7b4ae912-3217-4540-a347-b9be46324f00">


Fixed!
