### ISSUE TITLE
can't hear Internal GM Synth

### ISSUE THREAD

**Issue by H-MLim** [plugdata-team/plugdata#1411]
hi. I can hear Microsoft GS Wavetable synth, but I can't hear any MIDI sounds (for example from `keyboard`-`noteout`) with Internal GM Synth, in stable v0.8.3, probably in 0.8.4 builds too. (Win 11) maybe something went wrong?

**Comment by dromer** [comment]
Are you unpacking the note and velocity values?

This works for me if I enable the Internal GM Synth in the midi-out settings:

![](https://i.imgur.com/RjdVmwx.png)

**Comment by H-MLim** [comment]
thank you. but I still can't hear it. actually I don't thinks it's a problem of unpacking since I still can hear via MS GS Wavetable Synth, as I wrote before. so since you are OK, maybe a problem of my computer..? (but I don't know where should I see...)

**Comment by H-MLim** [comment]
woops. sorry. it found that's a problem of my audio preference settings. now it's fine.
