### ISSUE TITLE
can't see icon on 0.8.3

### ISSUE THREAD

**Issue by H-MLim** [plugdata-team/plugdata#1412]
![image](https://github.com/plugdata-team/plugdata/assets/68152553/177b01fe-42a3-4a5e-8aec-b09239fd1456)

currently in my PC, I can't see icon of plug on v0.8.3. this was OK on 0.8.4 builds. Win11
(poked from discord)

**Comment by 60-hz** [comment]
Did you try to rebuild icon cache on windows?

**Comment by H-MLim** [comment]
Not yet. How can I do it?

**Comment by H-MLim** [comment]
oh. I'm back home just before. after googling how I do it, it worked. thanks!
