### ISSUE TITLE
patch crashed after opening helpfile of [keyboard]

### ISSUE THREAD

**Issue by H-MLim** [plugdata-team/plugdata#1413]
in 0.8.3 stable (Win11), plugdata crashed after opening helpfile of `keyboard`. (I'm not sure other objects would do either).

**Comment by dromer** [comment]
Can confirm, this just completely freezes up plugdata.

**Comment by timothyschoen** [comment]
Does this still happen on nightly? I can't reproduce this

**Comment by H-MLim** [comment]
in the newest nightly (b51a850b2), it doesn't crash but it says 'Couldn't find help file'. I'm not sure if it's related with #1334

**Comment by dromer** [comment]
With fa26fc8ad9fe5fcec54c1ad181e09997743c728f this completely freezes the UI for me. Up to completely affecting the OS as well.

**Comment by timothyschoen** [comment]
Should be fixed!

**Comment by dromer** [comment]
Yup, works for me now!

**Comment by H-MLim** [comment]
yeah. this works for me too. thanks!
