### ISSUE TITLE
ipad os, objects unselected after duplicate/paste

### ISSUE THREAD

**Issue by okkobroderson** [plugdata-team/plugdata#1419]
objects should be selected after duplicate or paste.
it used to be so in 0.8.3

**Comment by timothyschoen** [comment]
Hi, this is already fixed on nightly builds, but the iOS releases tend to happen inbetween plugdata releases, so that I don't have to do everything at once. That will change once the iOS version is more stable and needs less work.

So this will be fixed when the next iOS release comes out
