### ISSUE TITLE
bug: crash from readerwriterqueue.h

### ISSUE THREAD

**Issue by dromer** [plugdata-team/plugdata#1420]
I was playing around with https://github.com/unfamiliartunes/spectralsand/ and can very easily get plugdata to crash with this message:

```
plugdata: /home/dreamer/Sources/_audio/_plugins/plugdata/Libraries/readerwriterqueue/readerwriterqueue.h:681: moodycamel::ReaderWriterQueue<T, MAX_BLOCK_SIZE>::ReentrantGuard::ReentrantGuard(moodycamel::weak_atomic<bool>&) [with T = pd::MessageDispatcher::Message; long unsigned int MAX_BLOCK_SIZE = 512]: Assertion `!inSection && "Concurrent (or re-entrant) enqueue or dequeue operation detected (only one thread at a time may hold the producer or consumer role)"' failed.
Aborted
```

**Comment by timothyschoen** [comment]
Hmm yes this is a false alarm that triggers an assertion :/ kind of annoying.

There are some cases where the readerwriterqueue is accessed from another thread, but in that rare case the thread always has exclusive access. So it's no actual threading issue, but readerwriterqueue will throw an error anyway. Running in Release mode should fix this right?

**Comment by dromer** [comment]
No idea, how do we do this? I just did a standard build of the latest source :thinking: 

I think it's because of a subpatch that runs with `block~ 512`?

**Comment by timothyschoen** [comment]
I haven't seen this happen in a while, I suppose it's fixed?
