### ISSUE TITLE
Float box's standard display capabilities: PD vs Plugdata

### ISSUE THREAD

**Issue by sevdh** [plugdata-team/plugdata#1425]
This post is about comparing the standard (not resized) float box display behavior in Plugdata and Pure Data and the wish that the float box display behavior in Plugdata would behave more identical to the one in Pure Data (and be able to display more digits without resizing it).

Comparing integer number display:
Plugdata can display up to three-digit integer numbers when the number doesn’t have a fraction: “123.”. Larger numbers are shown as “12…”. On the other hand, Pure Data displays up to five-digit integer numbers: “12345” and shows “1234>” when the number has six digits or more.

Comparing numbers with a fraction:
For numbers with a fraction Plugdata can only show one or two-digit numbers. Three-digit numbers with a fraction are displayed as “12…” and you have no idea how many digits the number actually has. On the other hand, Pure Data can display up to four-digit numbers with a fraction as "1234.".

Another small difference between the two is that Pure Data doesn’t show the decimal separator when the number has no fraction while Plugdata does. I'm not sure that this should be changed...

I would really like that the standard float box behavior in Plugdata to have the ability to display the same number of digits as the standard float box in Pure Data. This makes opening patches made in Pure Data much easier because currently the float boxes often have to be widened in Plugdata while there was no need for it in Pure Data.

The J.A.G.S. interface is a good example demonstrating the issue: https://github.com/Limulo/Jags

**Comment by timothyschoen** [comment]
Working on it!

<img width="392" alt="Screenshot 2024-02-06 at 16 32 34" src="https://github.com/plugdata-team/plugdata/assets/44585538/a24a0340-3fbb-4ecc-8f92-c0e68f6e4aba">

> The issue of integers showing with a decimal point at the end is prevalent throughout plugdata, so likely needs a more thorough solution.

For floats inputs (like object boxes), I think the dot should always be there, because it makes it more clear where you can drag the integer and decimals. It should be hidden for integer-only inputs though, I agree

**Comment by sevdh** [comment]
Great!On 6 Feb 2024, at 16:33, Timothy Schoen ***@***.***> wrote:
Working on it!
Screenshot.2024-02-06.at.16.32.34.png (view on web)

**Comment by timothyschoen** [comment]
a52e8e843 fixes it! But let me know if there are any more issues here :)
