### ISSUE TITLE
ipados gem

### ISSUE THREAD

**Issue by okkobroderson** [plugdata-team/plugdata#1426]
i noticed gem folders all over the place...
is this now implemented?

couldn't try because of plugdata ios file system problem i think

**Comment by timothyschoen** [comment]
Unfortunately no, Apple doesn't support openGL anymore on iOS.

I forgot to exclude those Gem folders for iOS though, so I'll do that!

**Comment by okkobroderson** [comment]
ah, ok. but would have been nice:)

**Comment by timothyschoen** [comment]
Yeah, I tried but couldn't get it to work :(

Just made the changes to the build system, so next version on iOS should no longer include Gem folders
