### ISSUE TITLE
Palette visualisation not showing on Mac Catalina

### ISSUE THREAD

**Issue by lixt-code** [plugdata-team/plugdata#1431]
objects with palette version (visual interface) are not loading/showing properly when putted inside patch. The standard object version loads normally. 

Console window says "palette/xxxx ... couldn't create"

![Captura de Tela 2024-02-07 às 12 36 42](https://github.com/plugdata-team/plugdata/assets/121124712/25506f9d-6c27-41eb-9884-63569d11b935)

TY!

I'm on:
Mac OS Catalina (10.15.7)
MacBook Pro (15-inch, Mid 2012)
plugdata v0.8.4
Nightly build: c6624bd03

**Comment by lixt-code** [comment]
ahh, forgot to tell. I have installed ONLY the standalone version.

**Comment by timothyschoen** [comment]
Hmm very strange!

Are there any files inside of "~/Documents/plugdata/Versions/0.8.4-4/Extra/palette"? 

And is "~/Documents/plugdata/Extra/" in your search paths?

**Comment by lixt-code** [comment]
yes and yes 

T.T

![Captura de Tela 2024-02-07 às 21 58 26](https://github.com/plugdata-team/plugdata/assets/121124712/211b7e83-feaf-447a-9db8-050449619d46)
![Captura de Tela 2024-02-07 às 21 58 32](https://github.com/plugdata-team/plugdata/assets/121124712/a27febc0-4c48-4f6a-bdcd-256eb41d7de8)

**Comment by lixt-code** [comment]
and when I drag and drop from the folder to a blank patch it comes like this...
![Captura de Tela 2024-02-07 às 22 12 51](https://github.com/plugdata-team/plugdata/assets/121124712/036fde81-342a-4ed3-8645-e680cceac303)

**Comment by timothyschoen** [comment]
Thanks for confirming, I'll see what I can do...

**Comment by lixt-code** [comment]
NP! TY for looking into it. And let me know if I'm doing something wrong with the installation or anything else.

**Comment by timothyschoen** [comment]
What happens if you just type "palette/plaits.m~" into an object box? Does it find it then?

**Comment by lixt-code** [comment]
nothing. I get the "couldn't create..." message

![Captura de Tela 2024-02-20 às 17 01 45](https://github.com/plugdata-team/plugdata/assets/121124712/34e505fd-2b49-420c-8e70-dcfb3735aa46)

**Comment by timothyschoen** [comment]
Oh, I think I might know what's causing this!

If you delete the ~/Documents/plugdata/Extra folder, and restart plugdata, is it fixed then?

**Comment by 60-hz** [comment]
palette/gendyn.m~ is not loading under MacOS

**Comment by lixt-code** [comment]
> Oh, I think I might know what's causing this!
> 
> If you delete the ~/Documents/plugdata/Extra folder, and restart plugdata, is it fixed then?

YES!! it does!! Seems to work now. But what to do with Extra folder? No Extra from now on?

**Comment by timothyschoen** [comment]
The "Extra" folder should be a symlink/shortcut to the ~/Documents/plugdata/Versions/VERSION_NUMBER/Extra folder. This automatically gets recreated everytime you start plugdata, so that's all good!

There was a bug earlier that caused the "Extra" folder to be a real folder, instead of a symlink. And that problem then derailed our symlink system. But that problem should also be solved now!
