### ISSUE TITLE
bug: some outlets misaligned

### ISSUE THREAD

**Issue by dromer** [plugdata-team/plugdata#1433]
Was showing a quick example to a user and saw that the `[int]` object has a weird position for the outlet now. I think there are various other objects with the same issue.

![](https://i.imgur.com/eaMneX4.png)

Previously we would be able to just get a straight line, now it looks really weird and wonky.

**Comment by 60-hz** [comment]
Yes, it looks like when number of chars in boxes are < 5 (including space), the outlets are centered...

**Comment by dromer** [comment]
I would really expect the first outlet to always be aligned with the first inlet and for them to have a fixed distance from the left side of the box. So that both boxes and connections remain aligned and straight.

**Comment by timothyschoen** [comment]
Fixed!
