### ISSUE TITLE
Message box issue

### ISSUE THREAD

**Issue by 60-hz** [plugdata-team/plugdata#1439]
"Enter" don't do a carriage return anymore but validate the message box.
It's not possible to do a new line with messages.

**Comment by dromer** [comment]
Use shift+enter (it will automatically add the `;` for newline as well, apparently)

**Comment by timothyschoen** [comment]
Yes, this is indeed by design. I think it's more convenient to be able to use enter to close the object editor

**Comment by 60-hz** [comment]
Ok thanks, I didn't use Plug for some times and didn't know that new way of using message.
I think this should be specified in help files... or maybe better : in tool tips when hovering message box.
Something like "store message (shift+enter to add new line)"

**Comment by crosswick** [comment]
Ha, having the exact same issue today, thanks for clarifying.
