### ISSUE TITLE
Allow new lines in object boxes

### ISSUE THREAD

**Issue by 60-hz** [plugdata-team/plugdata#1441]
Following [this thread](https://github.com/plugdata-team/plugdata/issues/1439#issuecomment-1951253965), object boxes should also allow to add new line.

For example, Gem is using a (not yet documented) [special feature](https://github.com/umlaeute/Gem/issues/312#issuecomment-1398187152) which is adding any arguments and their parameters on a new line in object boxes. 

A gem window could be created like this in Puredata:

<img width="111" alt="Capture d’écran 2024-02-18 à 15 34 57" src="https://github.com/plugdata-team/plugdata/assets/5449719/6c5a3523-a047-4849-9815-80b8fbc89a2a">

Some help files like [pix_sig2pix~] is already using this feature.

**Comment by timothyschoen** [comment]
Fixed!
