### ISSUE TITLE
Zoom to fit all

### ISSUE THREAD

**Issue by 60-hz** [plugdata-team/plugdata#1448]
The "zoom to fit all" works well when the patch is bigger than the screen (so it resizes the patch to fit screen), but if the patch is smaller, or very tiny it will only re-center it on screen.

**Comment by timothyschoen** [comment]
Currently, it only adjusts the zoom amount if the total object bounds do not fit at your current zoom level. But we could change that if it would make more sense?

**Comment by timothyschoen** [comment]
Fixed with 9c85c3d40

Of course, there are limits to zoom that prevent very small patches from being fit, but if you need less than 300% magnification, it will now work!
