### ISSUE TITLE
Gem ";" character as argument

### ISSUE THREAD

**Issue by 60-hz** [plugdata-team/plugdata#1449]
After [this issue](https://github.com/plugdata-team/plugdata/issues/1441) been fixed, Gem object don't understand the ";" character as arguments.

This patch create a window in pure data but do nothing in Plugdata:
<img width="155" alt="Capture d’écran 2024-02-21 à 17 43 56" src="https://github.com/plugdata-team/plugdata/assets/5449719/debbd0a1-8606-4efb-9bac-c1dac8f90888">

**Comment by timothyschoen** [comment]
<img width="776" alt="Screenshot 2024-05-04 at 21 44 23" src="https://github.com/plugdata-team/plugdata/assets/44585538/0162bce8-7750-4caf-97a2-0445287e2dc9">


Fixed!
