### ISSUE TITLE
else/circle's circle too small

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#1451]
![Screen Shot 2024-02-22 at 21 34 14](https://github.com/plugdata-team/plugdata/assets/5360142/87a8ebdd-a558-431a-b481-31d7c4497d6a)

![Screen Shot 2024-02-22 at 21 35 39](https://github.com/plugdata-team/plugdata/assets/5360142/8e4ab306-92ef-435d-9a02-58a5107d3acd)

**Comment by timothyschoen** [comment]
Ah yeah, because it's a bang underneath. Maybe we can draw it using drawpolygon instead?

**Comment by porres** [comment]
well, this should in fact be a compiled object... drawing circles with data structures hard, I don't really know...

pdlua? :)

**Comment by 60-hz** [comment]
Another idea would  be to add a "circle" constrain mode to "slider2d", so that circle object won't be that useful what do you think? Slider2d's drawing feels much smoother and efficient than circle also.

**Comment by timothyschoen** [comment]
> well, this should in fact be a compiled object... drawing circles with data structures hard, I don't really know...
> 
> pdlua? :)

If we get pdlua graphics into ELSE, I think that would be a great idea. Writing this with with lua graphics should be much simpler than with data structures!

**Comment by timothyschoen** [comment]
Something like this, to start with:

```
local circle = pd.Class:new():register("circle")

function circle:initialize(sel, atoms)
    self.slider_position_x = 75
    self.slider_position_y = 75
    self.inlets = 1
    self.outlets = 1
    self.gui = 1
    gfx.set_size(150, 150)
    return true
end

function circle:mouse_down(x, y)
    self.mouse_down_x = x;
    self.mouse_down_y = y;
    self.mouse_down_slider_x = self.slider_position_x;
    self.mouse_down_slider_y = self.slider_position_y;
end

function circle:mouse_drag(x, y)
    local width, height = gfx.get_size()

    local dx = x - self.mouse_down_x
    local dy = y - self.mouse_down_y

    local new_x = (self.mouse_down_slider_x + dx) - width / 2;
    local new_y = (self.mouse_down_slider_y + dy) - height / 2;

    local distance = math.sqrt(new_x^2 + new_y^2)
    local angle = math.atan(new_y, new_x)

    distance = math.max(0, math.min(width / 2, distance))

    self.slider_position_x = math.cos(angle) * distance + (width / 2)
    self.slider_position_y = math.sin(angle) * distance + (height / 2)

    self:outlet(1, "list", {self.slider_position_x / width, self.slider_position_y / height})
    self:repaint()
end

function circle:paint()
    local width, height = gfx.get_size()

    gfx.set_color(255, 255, 255, 1)
    gfx.fill_all()

    gfx.set_color(0, 0, 0, 1)
    gfx.fill_ellipse(self.slider_position_x - 4, self.slider_position_y - 4, 8, 8)

    gfx.stroke_ellipse(1, 1, width - 2, height - 2, 1)
    gfx.draw_line(width / 2, 0, width / 2, height, 1);
    gfx.draw_line(0, height / 2, width, height / 2, 1);

    gfx.draw_line(self.slider_position_x, self.slider_position_y, self.slider_position_x, height / 2, 2);
    gfx.draw_line(self.slider_position_x, self.slider_position_y, width / 2, self.slider_position_y, 2);
end


```


<img width="289" alt="Screenshot 2024-02-23 at 14 21 17" src="https://github.com/plugdata-team/plugdata/assets/44585538/240bd757-f521-4791-9e33-c183b7598356">

This also has much better performance under plugdata than using data structures.

**Comment by timothyschoen** [comment]
https://github.com/plugdata-team/plugdata/assets/44585538/99c4c38e-648f-4c9e-a9f6-9a59d3bea553


It even performs much better in pd-vanilla!

**Comment by porres** [comment]
awesome, so, let's fork lua and put it into ELSE? :) for now you can just make your own version for plugdata, I am not touching/changing it... just be sure it can be resized and all...

**Comment by timothyschoen** [comment]
> awesome, so, let's fork lua and put it into ELSE? :) for now you can just make your own version for plugdata, I am not touching/changing it... just be sure it can be resized and all...

I'll see if I can steal the resizing code from [oscope~]

**Comment by porres** [comment]
btw, Gem's [circle] object description is wrong :) and it's nice you're suggesting Gem with the namespace to avoid name clashes!
![Screen Shot 2024-02-23 at 15 23 06](https://github.com/plugdata-team/plugdata/assets/5360142/821b7bad-f6cd-40a2-b96a-33d92f04f868)

**Comment by 60-hz** [comment]
I think that's part of the name clash issues, because now, [scale] and [circle] are wrong... and they don't have the green inlet. Scale is messed with cyclone and circle with else.

**Comment by porres** [comment]
> Avoiding name's conflict in a "education oriented" pd distribution would be nice if possible.

It isn't, you can't change the name of these objects, it will break either Gem, cyclone or ELSE. Arguably you could ask me to fix this in detriment of ELSE, by breaking ELSE, I wouldn't like it at all and even there'd still be the clash between Cyclone and Gem... try bringing this idea to the list :) or, one could just change names in plugdata, breaking Pd compatibility...

Dealing with name clashes can be a bit of a pain but it is an essential and basic structural thing in Pd. There are different ways to manage this, one being the use of 'namespaces' and it works quite nicely in Plugdata as I tested it. If you click the help file of the objects above, the correct help file opens with the correct loaded object and it all works. It's nice that the autocomplete suggests namespaces for Gem to differentiate it. So what's wrong?

The only problem is that it is not getting the right description in the autocomplete plugin and I bet this is a very minor issue with a simple and easy fix that doesn't require the harsh and drastic measure of changing object names from legacy objects that have been there for decades in the Pd ecosystem.

**Comment by dromer** [comment]
Maybe the objects that have clashes should always be prepended with their external module name?

**Comment by 60-hz** [comment]
> It isn't, you can't change the name of these objects, it will break either Gem, cyclone or ELSE. Arguably you could ask me to fix this in detriment of ELSE, by breaking ELSE, I wouldn't like it at all and even so there'd still be the clash between Cyclone and Gem... try bringing this idea of changing these objects name to the list :) or, one could just change names in plugdata, breaking Pd compatibility...

Yes, choosing object's name in pd world is always a tough task... That's also why I like naming convention of ceammc with dot in the middle that have thousand of objects with almost no conflicts in pd world.

>Dealing with name clashes can be a bit of a pain but it is an essential and basic structural thing in Pd. There are different ways to manage this, one being the use of 'namespaces' and it works quite nicely in Plugdata as I tested it. If you click the help file of the objects above, the correct help file opens with the correct loaded object and it all works. It's nice that the autocomplete suggests namespaces for Gem to differentiate it. So what's wrong?

Of course we'll need to use namespaces then... Usually I prefer not, for patch readability, objects size and concept simplification during class (students already find pd full of complex rules...). Also because I remember a student had bad experience once, with namespace and messed paths, that made things break with pd-else on RaspberryPi (maybe old version since I see now that else is using namespaces in all help files). It's just another rules to explain and follow, but it looks like there is no choice...

>Maybe the objects that have clashes should always be prepended with their external module name?

You mean add a kind of exception for those 2 objects?

**Comment by timothyschoen** [comment]
I think namespaces are a fine solution for Gem, since you can just add "Gem" to the libraries to load list. And most Gem patches you find online have [declare -lib Gem] in it anyway. Only a subset of plugdata users is interested in graphics, so I think it makes sense to make the ELSE/cyclone objects take precedence over the Gem objects.

I should fix the .md issues though! But it's definitely a tricky problem.

**Comment by porres** [comment]
> it looks like there is no choice...

been saying several times now, hope you finally accept this reality :) 

> it makes sense to make the ELSE/cyclone objects take precedence over the Gem objects.

sure
