### ISSUE TITLE
enable jack for standalone plugdata.

### ISSUE THREAD

**Issue by pspbar** [plugdata-team/plugdata#1452]
For linux, with standalone plugdata, uncommenting these 2 lines:

```
    #JUCE_JACK=1
    #JUCE_JACK_CLIENT_NAME="plugdata"
```

in  CMakeLists.txt , will allow to manage connections to input and output sources, via qpwgraph, helvum or carla. 

I've tested this in voidlinux, using pipewire.

**Comment by timothyschoen** [comment]
Hi!

I believe this has already been done on the latest nightly builds?
