### ISSUE TITLE
Heavy: export window takes a long time to output

### ISSUE THREAD

**Issue by dromer** [plugdata-team/plugdata#1453]
A week or so ago this was still as fast as expected.

Seems to me that it takes a very long time to even start the subprocess as the actual transpile should be very quick.

We get a blank export screen for over 20 seconds which is much too long and could leave the user thinking there is a problem.

**Comment by dromer** [comment]
Hmm, tried a commit from pre JUCE update (https://github.com/plugdata-team/plugdata/commit/cf2fb0c7ac51c590001d6423be1472be644a6f3e) and still the same.
Now I am trying a pretty big patch, but I'm pretty sure that it didn't take _that_ long before ..

**Comment by dromer** [comment]
Just a little hvcc timing comparison of the same patch:

- local - Total compile time: 949.65ms
- plugdata - Total compile time: 33097.69ms

**Comment by timothyschoen** [comment]
Hmm weird! Are you running a release build? Starting processes can be very slow in debug mode

**Comment by dromer** [comment]
How can I check this? :thinking:

**Comment by dromer** [comment]
Hmm, from `build/CMakeCache.txt` I see `CMAKE_BUILD_TYPE:STRING=Debug` so I guess this maybe has something to do with it :#

**Comment by dromer** [comment]
Hmm, nope.

Reconfigured and rebuilt with `-DCMAKE_BUILD_TYPE=Release` and the Heavy compile time is still:

`Total compile time: 30510.57ms`

**Comment by dromer** [comment]
I figured I'd try to run our pyinstaller build of Heavy from the cli and see how it compares directly:

`Total compile time: 12091.99ms`

So more than twice as fast as from the subprocess, but still 12x slower than hvcc python :thinking:

**Comment by dromer** [comment]
I created a local pyinstaller build and it's performance is much more reasonable:

`Total compile time: 1312.25ms`
