### ISSUE TITLE
Failed compilation - Debian 12

### ISSUE THREAD

**Issue by JRSV** [plugdata-team/plugdata#1456]
Hello

I am having an issue compiling plugdata with the following instructions

git clone --recursive https://github.com/plugdata-team/plugdata.git
cd plugdata
mkdir build && cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
cmake --build .

I get the following error and I have no idea what is going on.
____
CMake Error at Libraries/CMakeLists.txt:397 (add_library):
  Cannot find source file:
   /home/jrsv/plugdata/Libraries/pd-lua/pdlua_multi_instance.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc

CMake Error at Libraries/CMakeLists.txt:397 (add_library):
  No SOURCES given to target: externals

CMake Error at Libraries/CMakeLists.txt:398 (add_library):
  No SOURCES given to target: externals-multi

any ideas?

**Comment by dromer** [comment]
If you don't know how to do this then you shouldn't be building the development branch :)

If you just want to try the latest nightly builds you can go here: https://plugdata.org/download.html

**Comment by JRSV** [comment]
I am doing this because of this issue https://github.com/plugdata-team/plugdata/issues/1391#issuecomment-1895459240
even though I updated my system, plugdata is behaving unstable, so I want to compile it myself.

cheers

**Comment by dromer** [comment]
The current builds are for Debian 12, so if you find some specific instabilities it's better to report those so they can be fixed.

**Comment by timothyschoen** [comment]
Hi, I temporarily broke the builds. I think they should be fine again now?

**Comment by dromer** [comment]
@timothyschoen `Libraries/CmakeLists.txt` is still looking for `pdlua_multi_instance.cpp`

**Comment by JRSV** [comment]
> The current builds are for Debian 12, so if you find some specific instabilities it's better to report those so they can be fixed.

Sure... but that does not mean I cannot try to first look for a stable option for my system and for my work. I see no harm in trying to compile myself even if I do not know how to git download another version of the repo. If you are not willing to provide the information I need that is fine, but I will still press on with this issue and hope for an answer from another contributor.

thanks @timothyschoen, I will try it out again today and hope its fixed.

cheers

**Comment by dromer** [comment]
Latest develop should build again.

**Comment by JRSV** [comment]
Builds with no issue, but I am getting segmentation faults still... could it be pipewire? anyway, I will close this ticket as its related to building.

**Comment by dromer** [comment]
> I am getting segmentation faults

Create a debug build, run with gdb. Then post stacktrace in a ticket.

**Comment by JRSV** [comment]
> > I am getting segmentation faults
> 
> Create a debug build, run with gdb. Then post stacktrace in a ticket.

with what command? I tried 
`cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_BUILD_TYPE=Debug`

**Comment by dromer** [comment]
@JRSV you can only create one build type. set the one you want.
