### ISSUE TITLE
UI is slow as hell on Windows

### ISSUE THREAD

**Issue by imau5tin** [plugdata-team/plugdata#1461]
### Hello. 
I noticed that whenever i zoom in/out screen i am faced **fps** drops, but 100/200/300% zoom rates work well.
 
Why does it happens? In non-dividible to 100 sizes have blurred text font.

`Windows 10, 0.8.3 Plug Data`

**Comment by timothyschoen** [comment]
Hi,

UI is indeed slow as hell on Windows right now, we're looking at various solutions. JUCE has implemented a direct2d renderer for Windows that should be faster, but it's not completely stable yet. We're also looking at possibly using nanovg for rendering in the future.

**Comment by timothyschoen** [comment]
This is now definitely fixed on the latest nighly builds, since we are now rendering everything on the GPU with nanovg. This also solves some other performance problems we had on Windows because of the way we used rounded cornders.
