### ISSUE TITLE
Output level is limited to -6 dB (float value 0.5)

### ISSUE THREAD

**Issue by Terygit** [plugdata-team/plugdata#1462]
Using plugdata on Windows, version 0.8.3.
When I create a osc~ and directly route it to a dac~ , the extreme values of the wave recorded with audacity are 0.5 and -0.5, respectively. They should be 1.0/-1.0.
I tried different output devices, like DirectSound or Exclusive Mode, and got the same results.  I checked with different outputs and different settings. 
I played back a 0 dB sine wave from a wave file and got the full wave (1.0/-1.0) back with audacity so not a computer issue.

**Comment by timothyschoen** [comment]
Hi! You should be able to disable this by clicking the shield icon in the bottom right.
