### ISSUE TITLE
[Gem/circle] mixed with [else/circle]

### ISSUE THREAD

**Issue by H-MLim** [plugdata-team/plugdata#1464]
![image](https://github.com/plugdata-team/plugdata/assets/68152553/a42a5fc2-f722-4e13-9413-42df3937cc4a)

![image](https://github.com/plugdata-team/plugdata/assets/68152553/802d0ded-ca1f-4038-8ea2-a72f608b3155)
![image](https://github.com/plugdata-team/plugdata/assets/68152553/7a220d74-bdb6-4c91-9e66-244d1f19dbb8)

maybe it seems the description of `Gem/circle` mixed with `else/circle`?  (and perhaps `rotate` too)

**Comment by H-MLim** [comment]
![image](https://github.com/plugdata-team/plugdata/assets/68152553/6cf5d6a0-08a7-451e-947f-b1c0d91fb344)
I found in cyclone lists too (`Gem/scale`)

**Comment by 60-hz** [comment]
Yes, already talked about it [here](https://github.com/plugdata-team/plugdata/issues/1450#issuecomment-1957377153) and [here](https://github.com/plugdata-team/plugdata/issues/1451#issuecomment-1962331694)

The solution is that we need to live with it and use namespace like Gem/circle or else/circle for those objects...
