### ISSUE TITLE
cyclone headers in helpfiles are not shown well

### ISSUE THREAD

**Issue by H-MLim** [plugdata-team/plugdata#1465]
![image](https://github.com/plugdata-team/plugdata/assets/68152553/9d0108b2-6e83-417f-8756-ec876b840921)

![image](https://github.com/plugdata-team/plugdata/assets/68152553/9564ccc7-c07b-4c37-b23c-6bd39f7fc01e)

I don't know about this exactly, but it seems every cyclone helpfiles are not showing header files (Nightly build: d5498b418)

**Comment by 60-hz** [comment]
I reported this [here](https://github.com/plugdata-team/plugdata/issues/1446) already.

The issue was closed but I see it still not fixed in the last nightly build.

**Comment by timothyschoen** [comment]
Hmm looks like I may have accidentally messed it up again when I updated cyclone...

**Comment by timothyschoen** [comment]
No idea how I messed this one up, but it's fixed now on the nightly builds
