### ISSUE TITLE
Some "else" help files cannot be found when using namespace

### ISSUE THREAD

**Issue by 60-hz** [plugdata-team/plugdata#1467]
In plug data, asking help files of some "else" objects using namespace returns "Couldn't find help file" 

--- 
Scenario 1 example:

- Create a new patch
- [else/amean] -> help
- "Couldn't find help file"

--- 

Scenario 2 example:

- Create a new patch
- [amean] -> help
- [else/gmean] -> help
- "Couldn't find help file"

---

Other objects like [else/loop] works well...

PlugData last nightly
MacOSX Sonoma 14.3.1

**Comment by timothyschoen** [comment]
This should be fixed now!
