### ISSUE TITLE
cyclone issues

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#1468]
Help files are not loading a couple of helper abstractions, see 

![Screen Shot 2024-03-06 at 20 34 52](https://github.com/plugdata-team/plugdata/assets/5360142/d0b16ed4-5f22-46e2-bf2e-7f97f1972493)

Also, autocomplete doesn't suggest cyclone objects that have the same name as vanilla objects, and that also need to be loaded with the 'cyclone/' prefix. They are: line~. table, append, clip and snapshot~

**Comment by 60-hz** [comment]
First issues is already  fixed here https://github.com/plugdata-team/plugdata/commit/16c5a42387edc2b9378fedc24747de4c874b0757

Moreover, I would add that search box doesn't works with namespace... which don't show any object proposal for cyclone/*
That's an issue for a "search box"... Systematic use of namespaces seems a bit painful at different level.

**Comment by timothyschoen** [comment]
Seems to work now on v0.9.0
