### ISSUE TITLE
Help menu not always shown

### ISSUE THREAD

**Issue by 60-hz** [plugdata-team/plugdata#1469]
- Right-click an object, the property show help option file once.
- At this step, directly right clic another object: the next property don't show its help file since two object are selected.

Attended behaviour : the first object should be deselected and the second object should show help option.

<img width="419" alt="Capture d’écran 2024-03-08 à 10 32 16" src="https://github.com/plugdata-team/plugdata/assets/5449719/da31dbf6-dfba-47e8-8463-24e3f4f7fa55">

MacOS Sonoma 14.3.1
Latest nightly

**Comment by timothyschoen** [comment]
Fixed!
