### ISSUE TITLE
number box filters out repeated numbers (like if it had a built-in [change]

### ISSUE THREAD

**Issue by angelfaraldo** [plugdata-team/plugdata#1470]
Hello,

I've spotted a weird behaviour which I am not sure if it is intentional or buggy. I often use number boxes to introduce numeric values with the keyboard, rather than mouse-dragging from the number box. That is, by a click > type > enter procedure. 

And while (1) receiving redundant numbers via inlet connections works fine
and (2) mouse-dragging from number boxes works also fine (cause with this method, there are no redundancies)

(3) when "clicking+typing+enter" the same number, only the first one gets through its outlet, as if it were a [change] logic within the object. 

This (3) is a bit annoying –at least for my working methodology– and to me, it seems inconsistent with behaviours (1) and (2), which feel more natural to me. 

I attach a short video, but unfortunately, it can't be seen very well when I re-introduce the number "3" for up to 3 times without response in the console.

Thanks very much in advance. Best!
__

https://github.com/plugdata-team/plugdata/assets/6861193/df600444-9a30-479a-b678-8236d490996a

**Comment by timothyschoen** [comment]
Should be fixed now!
