### ISSUE TITLE
Compile: missing objects

### ISSUE THREAD

**Issue by konsumer** [plugdata-team/plugdata#1471]
When I try to compile to any target, it fails due to `loadmess` not being defined.

I can fix it by replacing with `[loadbang] -> [message]`, but then I get an error about `[sfont~]`, for example.

Even a very simple start to plugin for tap-tempo (just the incoming param) fails when I try to compile:

<img width="229" alt="Screenshot 2024-03-09 at 1 30 35 PM" src="https://github.com/plugdata-team/plugdata/assets/83857/54978f80-ab86-447a-b396-ff96c1dcc5dd">

Here is the error with C target:

```
--> Generating C
  1) [91mError[0m pd2hv:  in "/" @ (x:242, y:149): Don't know how to parse object "list". Is it an object supported by Heavy? Is it an abstraction? Have the search paths been correctly configured?
  2) [91mError[0m pd2hv:  in "/" @ (x:242, y:149): Don't know how to parse object "list". Is it an object supported by Heavy? Is it an abstraction? Have the search paths been correctly configured?
  3) [91mError[0m pd2hv:  in "/" @ (x:242, y:149): Don't know how to parse object "loadmess". Is it an object supported by Heavy? Is it an abstraction? Have the search paths been correctly configured?
  4) [91mError[0m pd2hv:  in "/" @ (x:242, y:149): Don't know how to parse object "gate". Is it an object supported by Heavy? Is it an abstraction? Have the search paths been correctly configured?
  5) [91mError[0m pd2hv:  in "/" @ (x:242, y:149): There was an error while connecting two objects. Have all objects been correctly instantiated? Have all inlets and outlets been declared?
  6) [91mError[0m pd2hv:  in "/" @ (x:242, y:149): There was an error while connecting two objects. Have all objects been correctly instantiated? Have all inlets and outlets been declared?
  7) [91mError[0m pd2hv:  in "/" @ (x:242, y:149): There was an error while connecting two objects. Have all objects been correctly instantiated? Have all inlets and outlets been declared?
  8) [91mError[0m pd2hv:  in "/" @ (x:242, y:149): There was an error while connecting two objects. Have all objects been correctly instantiated? Have all inlets and outlets been declared?
  9) [91mError[0m pd2hv: [comment null object placeholder (list)] in "/" @ (x:0, y:0): Connection made to non-existent inlet at [comment {'text': 'null object placeholder (list)'}]:0.
 10) [91mError[0m pd2hv: [comment null object placeholder (list)] in "/" @ (x:0, y:0): Connection made to non-existent inlet at [comment {'text': 'null object placeholder (list)'}]:0.
 11) [91mError[0m pd2hv: [comment null object placeholder (list)] in "/" @ (x:0, y:0): Connection made to non-existent inlet at [comment {'text': 'null object placeholder (list)'}]:0.
 12) [91mError[0m pd2hv: [comment null object placeholder (list)] in "/" @ (x:0, y:0): Connection made to non-existent inlet at [comment {'text': 'null object placeholder (list)'}]:0.
 13) [91mError[0m pd2hv: [comment null object placeholder (gate)] in "/" @ (x:0, y:0): Connection made to non-existent inlet at [comment {'text': 'null object placeholder (gate)'}]:1.
Total compile time: 8.03ms
```

I am on an Intel mac, running Ventura 13.6.4 (22G511).

Is there some config I need to do for heavy?

**Comment by dromer** [comment]
You are using unsupported objects: https://github.com/Wasted-Audio/hvcc/blob/develop/docs/09.supported_vanilla_objects.md

**Comment by konsumer** [comment]
> You are using unsupported objects

That is what I am saying. unsupported objects are built into the standard things (see screenshot.) Should these be structured differently? (for example, use `inlet` instead of `param`)

> Please enable compiled mode in the menu so you get early warnings about such objects.

I am doing this. I am getting lots of warnings for objects that are includedin the plugdata UI (param, all the sidebar things, etc.)

**Comment by konsumer** [comment]
I am seeing some things that are part of vanilla on the "not implemented" list that are pretty basic, too, like `[list]`. This seems like it would be very challenging to make actual compilable code with.

**Comment by dromer** [comment]
Correct, not all vanilla objects are implemented and some will likely never be.

If you want to help the project you can read the source here: https://github.com/Wasted-Audio/hvcc

**Comment by dromer** [comment]
> built into the standard things

You are using cyclone external objects. How are these "standard"?

The only way is to rewrite your code to not use externals and unsupported objects.

See it as a challenge to be creative with the limitations :)

**Comment by konsumer** [comment]
> You are using cyclone external objects. How are these "standard"?

In the above example, I just added `param` (which seems to be how to get incoming VST params in plugdata) and that is essentially all. By "standard" I mean it's built into how plugdata works. If these are not meant to be compiled, then what is?

> See it as a challenge to be creative with the limitations :)

Yeh, I can dig this. I make standalone pizero devices that use only vanilla (with `pd -nogui`) now. In this mode, I can add any externals I want, too, though, but I am willing to drop that, if it's more efficient. I think I am just unclear on how it's supposed to work in plugdata-compiled stuff.

In this example, I would do tap-tempo like this (this is from a working vanilla patch that runs on a pedal):

<img width="353" alt="Screenshot 2024-03-09 at 3 02 12 PM" src="https://github.com/plugdata-team/plugdata/assets/83857/775a9b46-4898-4999-9841-e1c46fda7faf">

How would I even do this without `list`?

**Comment by dromer** [comment]
`[param]` is an abstraction from cyclone that uses cyclone objects (among others).

It is not available from the auto-complete or the direct object menu at the top. If you choose to create this object yourself then you have to deal with the consequences :shrug: 

How it's "supposed to work" is that you create patches without these objects. That's it.
You don't have to expect to be able to do everything exactly as you are used to, you can't.

What you can also do is wrap specific elements into heavy compiled externals, to optimize just specific DSP routines.

There are many ways to effectively use Heavy, you just have to try and step out of your comfort zone.

**Comment by dromer** [comment]
You can also look at included Heavylib abstractions to both expand the vanilla capabilities and see how advanced Heavy compatible patching is done.

**Comment by konsumer** [comment]
> [param] is an abstraction from cyclone that uses cyclone objects (among others).

I get that. It's built into the UI of plugdata though (which is why I am asking the question here.)

<img width="566" alt="Screenshot 2024-03-09 at 3 12 09 PM" src="https://github.com/plugdata-team/plugdata/assets/83857/adf01d1c-cf1d-4dcd-9e51-9160cfdbb155">

> It is not available from the auto-complete or the direct object menu at the top. If you choose to create this object yourself then you have to deal with the consequences

Not sure what you mean by this. it's there in the plugdata UI. I'm not making anything, myself. I just dragged it in. If this is not how to make a VST param for compiled-mode, then what is?

> How it's "supposed to work" is that you create patches without these objects. That's it.
> You don't have to expect to be able to do everything exactly as you are used to, you can't.

Ok, that is fine.

> What you can also do is wrap specific elements into heavy compiled externals, to optimize just specific DSP routines.

Maybe I missed it, but heavy isn't mentioned in the plugdata UI anywhere. I am ok with writing code (I am a programmer, as my day-job) but it's not clear what is necessary to make a pretty basic patch that runs, compiled.

> There are many ways to effectively use Heavy, you just have to try and step out of your comfort zone.

This is not a "comfort zone" issue, I am comfortable doing it however it works, but it's not clear how it works. compiled-mode may just not be for my usecase. `pd -nogui` works really well for me. I haven't really experienced any performance issues, but the idea of compiling VSTs from puredata patches appeals to me.

> Please read the Heavy documentation and possibly code to understand the limitations and work with them.

Or not. It seems like Heavy solves a problem I don't have, and I will just go back to regular pd. Thanks for your time.

> Anyway, this is really a non-issue with plugdata or with Heavy and I'd suggest to close this ticket.

It seems to me, at the very least, this is a documentation issue. I think I misunderstood the purpose of compiled-mode, and from the main site, and any docs I read, it was not clear "make a VST from a puredata patch" would not include basic things like `list`. I will close, anyway.

**Comment by dromer** [comment]
> If this is not how to make a VST param for compiled-mode, then what is?

Oh, these are for using plugdata as a plugin and have nothing to do with the Heavy compiler.

Please read the Heavy documentation on how to interface with patches: https://wasted-audio.github.io/hvcc/docs/02.getting_started.html

**Comment by konsumer** [comment]
> Oh, these are for using plugdata as a plugin and have nothing to do with the Heavy compiler.

Right, which is why I opened an issue on plugudata repo, not hvcc. If "compiled mode" in plugdata doesn't work like this, it's no prob, it's just not at all clear how it works. I pulled that example of "how to interact with VST host" directly from plugdata docs, and the UI supports that method, as long as it's not compiled.

> Please read the Heavy documentation on how to interface with patches

Ah, see, this should be linked in the plugdata docs, in my opinion. It was not at all clear that instead of `param` (the standard way to do VST params in plugdata, that the UI directly supports) I should use sends. That makes sense, ad is completely workable!

This does bring me to another thought, which is maybe there should be a simple single way to do VST params. It's not too complicated to make a receive/send that acts like `param`, here, and it would make the same patch work roughly the same way. Is there a way to adapt hvcc, like "when you see `param`, load this vanilla pd patch that just does `send`/`receive`"? It's just one example, but I think it could clear up a lot of this kind of confusion.

> If you want some examples of PD patches converted to Heavy compiled "VST" plugins

This is really cool. I will take a close look. Seems like even if it doesn't fit my usecase, it could be very cool for making VSTs or bare-booting chips.

**Comment by konsumer** [comment]
@dromer watching [your video](https://youtu.be/XKohpWGTKsQ) actually helped answer a lot of my questions/misunderstandings, and it looks like it was added to [these more detailed instructions](https://jonwaterschoot.github.io/plugdata-daisy-simple/). Very helpful.
