### ISSUE TITLE
`[else/keyboard]` buggy for polyphonic notes

### ISSUE THREAD

**Issue by charlesneimog** [plugdata-team/plugdata#1472]
See the difference between `else/keyboard` in PureData and Plugdata.

https://github.com/plugdata-team/plugdata/assets/31707161/e27460c7-ce95-404e-9190-abc7d795a7e1

**Comment by timothyschoen** [comment]
I believe this should be fixed in the latest nightly builds, if it's the same issue as #1234

**Comment by charlesneimog** [comment]
Hi timothyschoen, it is not fixed for me...

**Comment by timothyschoen** [comment]
Oh, good to know, then I'll take another look!

**Comment by timothyschoen** [comment]
611eed343 seems to fix this for me, does it also for you?

**Comment by charlesneimog** [comment]
Yes, thanks!
