### ISSUE TITLE
Horizontal scrolling not working

### ISSUE THREAD

**Issue by heyarne** [plugdata-team/plugdata#1479]
Heya,

I'm running plugdata 0.8 on NixOS (this is the latest available version -- I tried to update the package to 0.8.3 but ran into build issues unfortunately). I'm using Gnome 45.4 on Wayland.

Horizontal scrolling is not working. This is both on the touchpad, as well as when using the trackpoint of my thinkpad. Vertical scrolling works fine. Also, pinch gestures are not supported (but from my understanding those were only implemented very recently).

Is this a bug or is this expected?

Thanks for your work on this. I'm using it to learn pd and I enjoy it a lot. :)

**Comment by dromer** [comment]
Try shift+scroll instead.

**Comment by heyarne** [comment]
That works! So this is intended behavior?

**Comment by dromer** [comment]
I think "horizontal scrolling" is a type of multi-touch gesture, just like the pinch you mentioned.

Afaik these are currently not supported (the only multi-touch that is being worked on is not gesture based).

shift+scroll is a typical UX that can be found throughout just about every program and OS and easy to support.

**Comment by timothyschoen** [comment]
For now, shift+scroll is the way
