### ISSUE TITLE
Feature request - include pd-faustgen2 in plugdata

### ISSUE THREAD

**Issue by sidec** [plugdata-team/plugdata#1486]
Hi,
Is this possible to include [faustgen external](https://github.com/agraef/pd-faustgen) in plugdata? The question is partly motivated by the fact that pd-lua by the same mainteiner (Albert Graef) is already shipped with plugdata. Also Faust seems to be a perfect complement to Lua in a signal domain, not to mention the width, depth and quality of available Faust libraries.

**Comment by dromer** [comment]
This would require the entire Faust JIT compiler. That is quite a big ask.
Next to this being quite a big project to build, which adds a lot of complexity. Doing it cross-platform for all targets makes it quite non-trivial.

I don't think it's realistic to have this built-in, but maybe a compatible external binary could be done as a separate project.

**Comment by sidec** [comment]
Right, I wasn't aware of these technical chalenges. Including build of pd-faustgen in CI/CD would be indeed a huge burden, but adding precompiled compatible binary in the distribution (isn't Gem included in such a way already?) could be then feasible? 
TBH speaking of pd-lua I would love to have pd-lua that is included in plugdata as independent compatible external which I could use in pd vanilla independently (via deken). In this way it would be possible to work on the same projects in both environments having a features parity.

**Comment by timothyschoen** [comment]
> Right, I wasn't aware of these technical chalenges. Including build of pd-faustgen in CI/CD would be indeed a huge burden, but adding precompiled compatible binary in the distribution (isn't Gem included in such a way already?) could be then feasible? TBH speaking of pd-lua I would love to have pd-lua that is included in plugdata as independent compatible external which I could use in pd vanilla independently (via deken). In this way it would be possible to work on the same projects in both environments having a features parity.

My improvements to pdlua will be released into the next regular pdlua release, so you'll be able to use signals and GUIs from Lua in pd-vanilla as well! You can do this now if you compile it yourself, it's already compatible with pd-vanilla.

I'm not sure about Faust yet, we might do it someday, but indeed the main issue is that LLVM is a pain to include as a dependency.

**Comment by sidec** [comment]
> My improvements to pdlua will be released into the next regular pdlua release, so you'll be able to use signals and GUIs from Lua in pd-vanilla as well! You can do this now if you compile it yourself, it's already compatible with pd-vanilla.
That's great!

So, the only way to have pd-faustgen2 in plugdata is to compile it to compatible binaries that work well in multi-instance runtime and add it to the library path?

**Comment by sidec** [comment]
If I understand it correctly - this is how it might work if this or any other external is re-compiled with patched m_pd.h? https://github.com/plugdata-team/plugdata/issues/34#issuecomment-1186720205
