### ISSUE TITLE
PlugData crashes when clicking on "Help" for [pdlua]

### ISSUE THREAD

**Issue by alexdrymonitis** [plugdata-team/plugdata#1489]
Right-clicking on a [pdlua] object and choosing help crashes PlugData. PlugData version 0.8.3 on Debian 12. This does not happen with [pdluax].

**Comment by dromer** [comment]
Can you try the latest nightly? I'm on Debian 12 and can open the help file just fine.

**Comment by timothyschoen** [comment]
The pdlua object has had some major changes since 0.8.3, so I'd recommend trying the nightly builds, it's probably fixed!

**Comment by alexdrymonitis** [comment]
Sorry for the late reply, the nightly built did it. Though now I get another issue, can't open [oscope~] from the Show Object Browser. I'll open a new issue for this. Closing this one.
