### ISSUE TITLE
PluginProcessor.cpp: line 856, sends "position" info to wrong object

### ISSUE THREAD

**Issue by jocphx** [plugdata-team/plugdata#1490]
Hi,
I noticed that the `position` param of `playhead` is not receiving any data from the DAW. I tested this in FL Studio and Ableton.

I gave a quick look at the code, and beside seeing a comment in `playhead.md` in regard to the `position` param not working, I saw that in `PluginProcessor.cpp` at line 856 of `main`, the `position` message is sent to a wrong object:

`sendMessage("playhead", "position", atoms_playhead);`

Shouldn't that be 
`sendMessage("_playhead", "position", atoms_playhead);` ? (that is underscore prepended to `playhead`)

It looks like the `playhead` object in 8.0.2 was changed to `_playhead` in 8.0.3 but that last message fell through the cracks.

**Comment by dromer** [comment]
Indeed, this last one hasn't been changed yet: https://github.com/plugdata-team/plugdata/blob/develop/Source/PluginProcessor.cpp#L901

(the receiver was renamed in order to have lower chance of clashing with user patches)

**Comment by jocphx** [comment]
Any idea when you'll be able to address that?

I have a few generative sequencers that I wrote using Camomile, (which rely on `position`) and I was hoping to port them to your environment.

**Comment by dromer** [comment]
> Any idea when

Create a pull request, get it merged.

**Comment by jocphx** [comment]
when I clone the project locally, do I make my feature branch from `develop` , `nvg_test`,  `main`?
I gave a quick look to the other pull requests and they all seem to be merged with `nvg_test`, but it doesn't hurt asking.
