### ISSUE TITLE
PlugData v0.8.3 fails to scan in Reaper (Ubuntu 22.04)

### ISSUE THREAD

**Issue by jamshark70** [plugdata-team/plugdata#1493]
Updated PlugData, rescanned in Reaper (7.09), and the result is:

![Screenshot_2024-03-28_11-37-57](https://github.com/plugdata-team/plugdata/assets/318301/0b17aacd-03b7-4894-a613-3b978d2d542f)

So it's deactivated.

~~LV2 seems OK.~~ No it's not: It crashes Reaper.

SuperCollider VSTPlugin says:

```
probing /home/dlm/.vst3/plugdata.vst3... error! subprocess was terminated with signal 11 (Segmentation fault)
probing /home/dlm/.vst3/plugdata-fx.vst3... ok!
```

But:

```
(
SynthDef(\vst, { |out = 0|
	Out.ar(out, VSTPlugin.ar(numOut: 2));
}).add;
)

a = Synth(\vst);

c = VSTPluginController(a);

c.open("plugdata-fx.vst3");

Server 'localhost' exited with exit code 0.
server 'localhost' disconnected shared memory interface
```

So I have plugdata crashing multiple hosts in multiple plugin formats.

0.8.2 seems fine.

0.8.3, I can use only standalone on my system. LV2 and VST3 both crash in all cases.

**Comment by timothyschoen** [comment]
Does this still happen on the latest nightly builds? It loads over here in REAPER on Fedora 39
