### ISSUE TITLE
RMB doesn't open dialog any more

### ISSUE THREAD

**Issue by dromer** [plugdata-team/plugdata#1501]
On latest nanovg build: it seems to multi-select objects now o.O
This is a very strange UX.

How are we supposed to get to options and help files now?

**Comment by dromer** [comment]
Or is this one of the compositing quirks again?

**Comment by timothyschoen** [comment]
> This is a very strange UX.

This is obviously not done on purpose, it's a non-compositing issue. Should be fixable.

**Comment by timothyschoen** [comment]
Fixed! App is also more usable with non-compositing now, thought there are still some artifacts left to fix.

**Comment by dromer** [comment]
Cool, will test when I get home!
