### ISSUE TITLE
Big error messages are truncated

### ISSUE THREAD

**Issue by charlesneimog** [plugdata-team/plugdata#1504]
Hi,
I have the py4pd object (which allows running Python inside Plugdata), but when I print errors, I receive truncated messages. I am not sure why this is happening. Is there something that I can do within the py4pd code to address this?
Thanks!

![1712090427_grim](https://github.com/plugdata-team/plugdata/assets/31707161/c60b1554-80e2-4137-a305-70b306b10c74)

Edit:

![1712090869_grim](https://github.com/plugdata-team/plugdata/assets/31707161/07826bb5-fcdb-4f3f-9bd3-4515965fed38)

for this code:

``` python
def readSvg(svg_file):
    pd.error("One line")
    pd.error("One line\n second line")
    pd.error("One line\n second line\n third line")
```

**Comment by timothyschoen** [comment]
Oof, thanks for reporting, I'll make sure this is fixed before the next release.

**Comment by timothyschoen** [comment]
I think b5ebe2ba8 should fix it! I just realised I never tested this since it's nearly impossible to do it from pd itself. But since stuff like pdlua, s4pd and py4pd exists, it's definitely good to support it.

**Comment by charlesneimog** [comment]
Thank you very much!
