### ISSUE TITLE
[bug] savepanel doesn't return valid path on Windows 11, doesn't open dialog in currend dir neither

### ISSUE THREAD

**Issue by sidec** [plugdata-team/plugdata#1508]
Nightly build: 256af9b44
OS: Windows 11 23H2

Description:
[savepanel] doesn't return valid path on Windows 11, doesn't open dialog in currend dir neither.
Steps to reproduce:
1. reproduce patch from attached screenshot
2. click [dir( attached to [pdcontrol] and choose any file in file picker. 

This bug is not present in the latest v0.8.3 release. 

![image_2024-04-08_102948923](https://github.com/plugdata-team/plugdata/assets/2880084/362e8ef6-ebc8-4a60-95e3-f993a00935e3)

**Comment by sidec** [comment]
[the latest build 02d661e](https://github.com/plugdata-team/plugdata/commit/02d661e52b56b425ca6a0fbf0e5612f4843e8ac9) still consists this regression. Is there any chance this will be addressed before v0.9.0 @timothyschoen ? I did quick search in code tree for a savepanel to compare what might have changed but strangely haven't found anything meaningful. Is this possible that the bug comes from upstream? However, Pd, the newest and previous version, works just fine, otherwise I would quickly learn as I have patches I use daily with savepanel in it.

**Comment by timothyschoen** [comment]
Hey, sorry I missed this! Should be fixed with e49f9a8c9e40adf1ccde1acb655ebb277b922c52
