### ISSUE TITLE
Can't save patches with "." without put the ".pd"

### ISSUE THREAD

**Issue by charlesneimog** [plugdata-team/plugdata#1515]
Hi,

On Linux systems, saving patches with dots in the filename, apart from the extension dot, it's impossible. Consequently, a patch intended to be named as `c.test.pd` will be automatically renamed to `c.pd` if we don't put the `.pd`. 

Not really a bug, but it is weird! :)

https://github.com/plugdata-team/plugdata/assets/31707161/b8381153-9cc0-4843-9052-c93f4ed5e7fb

**Comment by dromer** [comment]
Hmm, I thought I had reported this before and it got fixed.

Very annoying indeed.

**Comment by timothyschoen** [comment]
I think 997293ba367e56e84f1a5c5645888f075dac263d fixes it

**Comment by dromer** [comment]
Seems to work for me.
