### ISSUE TITLE
6 OP FM synth Feature Add: envelopes and key scaling

### ISSUE THREAD

**Issue by muziker** [plugdata-team/plugdata#1516]
In the DX7, there are envelopes that control how each operator works. Looking through some of the youtube footage out there, it seems like these are vitally important to how the timbres operate across the keyboard. 

https://www.youtube.com/watch?v=Bj_fM7ONaCw
https://www.reddit.com/r/synthesizers/comments/x94nxj/the_most_confusing_envelope_generators_of_all/?rdt=52692

There's this other thing with keyboard scaling as well. 

https://djjondent.blogspot.com/2019/10/dx-7-keyboard-level-scaling.html

There's also a fixed frequency mode for the operators as well instead of ratios, usually for use as a slow LFO.

**Comment by porres** [comment]
this thing already has inlets for envelopes for all operators...

a velocity curve is also something easily applied via a tranfers function, but overall, I think your request is really vague, so try to be more objective and clear, what exactly would you like, taking into account the existing module, and for what?

anyway, this is part of "MERDA", a submodule of ELSE, so maybe not the best place to open a feature request for it
