### ISSUE TITLE
Feature Request: ctrl / and ctrl . for dsp on/off

### ISSUE THREAD

**Issue by muziker** [plugdata-team/plugdata#1518]
It would be nice to have the ctrl+/ and ctrl+ . for dsp on off. Sometimes the unfortunate twist of the wrist results in loud audio spiking through, so it would be nice to be able to turn off dsp as fast as possible instead of trying to find the power button.

**Comment by timothyschoen** [comment]
In the latest nightly builds, there is a "toggle dsp" keyboard shortcut option in settings that you can assign :)

I could set a nice default for it too though!

**Comment by timothyschoen** [comment]
Done with 275beffdf
