### ISSUE TITLE
GEM Library is crashing when creating a window (Plugdata version 0.8.3, GEM version 0.94)

### ISSUE THREAD

**Issue by izeKake** [plugdata-team/plugdata#1522]
A crash occurs when sending "create, 1" messages to the "gemwin" object on Plugdata version 0.8.3.
This crash seems to occur on MacOs or Windows (no idea if this is the case on Linux).
Does anyone have any idea what this might be?
Thanks in advance for your reply,
IzeKake

**Comment by timothyschoen** [comment]
Hi!

plugdata v0.8.3 doesn't support Gem, if you want to use Gem, you'll want to try the latest nightly builds which comes with Gem built in!

**Comment by izeKake** [comment]
Ok, thank you very much for your help !

**Comment by timothyschoen** [comment]
Gem just got added, so let me know if you run into any more issues. Would be great to resolve that before the next release :)

**Comment by timothyschoen** [comment]
Gem is included in the v0.9.0-test release. There are still some issues we're working out, but the basics should all work!
