### ISSUE TITLE
Develop `Branch` - Mouse Position Issue

### ISSUE THREAD

**Issue by charlesneimog** [plugdata-team/plugdata#1529]
Hi,

When I test #1504, I had some problems with version `0.9`. 

Some info: 
* I am using Arch Linux;
* Window Tiling Manager (but this don't happens on version `0.8.3`) 

https://github.com/plugdata-team/plugdata/assets/31707161/4406a4a5-efb0-434a-906a-446696d8113a

**Comment by charlesneimog** [comment]
The problem is with `global scale factor`. With 100% it works, I use 125%.

**Comment by timothyschoen** [comment]
> The problem is with `global scale factor`. With 100% it works, I use 125%.

Oh thanks for reporting, I easily could have missed that! We switched the canvas over to a whole new rendering system in v0.9.0 which makes the GUI a lot faster, but that's also why there are still some issues left like this one :)

**Comment by timothyschoen** [comment]
I think this is now fixed on the develop branch?

**Comment by charlesneimog** [comment]
Fixed :). 

Thankssss

**Comment by charlesneimog** [comment]
Note: 

This new GUI is really crazy, seems amazing. I hadn't noted this before, but now seems veryyy smooth.
