### ISSUE TITLE
Number box doesn't show numbers

### ISSUE THREAD

**Issue by rahji** [plugdata-team/plugdata#1534]
If I type a number in a number box, the cursor moves but the typed numbers don't appear. Also, sending a number to the box doesn't show the number. The numbers seem to work - they just don't appear.

![numberbox](https://github.com/plugdata-team/plugdata/assets/442495/f64122bc-1f4e-48f9-a473-18bf26cfbd55)

* Windows 11 Pro
* AMD Radeon RX 580
* plugdata v0.9.0 but it was the same on 0.8.3

**Comment by timothyschoen** [comment]
Oh, that's really odd, I've never seen this before. I'm also kind of clueless about what could be causing this

**Comment by rahji** [comment]
I tried with one display instead of two and the issue is the same. If you have any suggestions for troubleshooting, let me know. I'm hoping to teach using plugdata in the Fall but this would obv be a showstopper. :/

**Comment by rahji** [comment]
Unfortunately, that doesn't seem to be the issue. I tried changing colors within the theme to make sure there were no overlaps. I also tried changing the font, resetting to default theme, dark vs light theme. Nothing seemed to matter. Highlighting the number shows that I'm highlighting but doesn't show the numbers - copy and pasting works even though the numbers don't show up.

**Comment by jocphx** [comment]
@timothyschoen 
I just started to see this issue in nightly build `fec0312` 
It was working fine in nightly build `d1e144e`

**Comment by timothyschoen** [comment]
I think fc003c013 should fix it?

**Comment by rahji** [comment]
Should I download the next nightly build to see if that fixes it for me?

**Comment by timothyschoen** [comment]
Yep, if you get the last commit now, it should hopefully be fixed

**Comment by rahji** [comment]
Sorry for the dumb question, but if I want to see the update now, I'd need to clone the repo and build it from source, yes? Or I could wait until the nightly build shows up on the website? Just checking. Thanks.

**Comment by timothyschoen** [comment]
No problem!

You can either download it from the website, from github, or build from source, both work. On Windows, using the nightly builds is a bit easier than setting up Visual Studio, python and cmake for most people.

You can either get the nightly builds here: https://plugdata.org/download.html
Where the colour of the commit hash indicates if it's the absolute latest build, or if a newer version is being processed right now.

If you have a GitHub account, you can also get them from here: https://github.com/plugdata-team/plugdata/actions
This gives you more information about the commit you're downloading, and you can see the build status. To find the download, click on a build with a green checkmark, and scroll down to find the downloads. Don't click any OS in the sidebar, many people (understandably) think that's where the download is gonna be.

**Comment by rahji** [comment]
Perfect - thanks for the help! And,  yes, it looks to be fixed in the latest finished build 👍🏽👍🏽
