### ISSUE TITLE
[Feature request][External] ReacTIVision TUIO client 

### ISSUE THREAD

**Issue by rexendevar** [plugdata-team/plugdata#1540]
So I've tried my damnedest for about an hour or so to figure out what exactly I need to do to compile an external alongside Plugdata. Unfortunately I have no idea how C++ works, nor the compiling process, so not only do I not know how to do it but I have absolutely no idea how close my attempts got me. I must now throw up my hands and say please do it for me.

https://reactivision.sourceforge.net/

for the purposes of this tutorial: https://www.youtube.com/watch?v=yKK1lwddfyM

I did end up building the TUIO client in question for regular puredata (and had to correct many of the developers' foolish errors along the way) but I'm now burned out on actually doing anything with it right now. Also I can't stand the regular pd interface.

**Comment by rexendevar** [comment]
Would also accept a significantly more in-depth guide on how to add my own externals so I can actually do it myself instead of floundering blind

**Comment by dromer** [comment]
I could build the external and load it in both pd and plugdata.
(only thing I had to modify was an additional include path in the Makefile)
