### ISSUE TITLE
[0.9.0-test] The color of object's name is not updated after switching themes.

### ISSUE THREAD

**Issue by charlesneimog** [plugdata-team/plugdata#1545]
Result after switch the theme:

![1714344695_grim](https://github.com/plugdata-team/plugdata/assets/31707161/dbc65b34-7d72-4df3-9073-a73b66cd5398)

dark -> light

![1714344768_grim](https://github.com/plugdata-team/plugdata/assets/31707161/e2f21f09-7fee-4676-83da-c5563d652ef3)

**Comment by dromer** [comment]
I believe this is because the object color is embedded in the object itself.
(you will also see this when you open the patch in Pd)

**Comment by timothyschoen** [comment]
Fixed, thanks for reporting!

> I believe this is because the object color is embedded in the object itself. (you will also see this when you open the patch in Pd)

I think this is just about text objects, which should switch automatically since the colour is not configurable. For GUIs though, what you said does apply

**Comment by dromer** [comment]
@timothyschoen right, didn't notice the text derp :D
