### ISSUE TITLE
[bug} Settings and Compile menus make entire program stuck "on top"

### ISSUE THREAD

**Issue by dromer** [plugdata-team/plugdata#1548]
These always stay on the very top of the rendering which means file dialogs etc are completely obscured.

**Comment by dromer** [comment]
Example of file dialogs being covered:

![2024-04-30_13-15](https://github.com/plugdata-team/plugdata/assets/1185977/a9c27c0c-98ce-484b-8287-50a9c07b6855)

**Comment by timothyschoen** [comment]
It shouldn't be stuck on top anymore, though there are still some small other issues. Dragging the window by a dialog toolbar is not working for example.

**Comment by dromer** [comment]
yes, much better!

although it's still weird how you can move around the "composited" compile or settings dialog:

![2024-05-01_17-41](https://github.com/plugdata-team/plugdata/assets/1185977/0c78f495-d0d1-4dd2-9644-566e606242e8)

**Comment by dromer** [comment]
This is still a problem for the plugin version!

![2024-06-03_07-26](https://github.com/plugdata-team/plugdata/assets/1185977/a0f93ec1-df97-450a-af95-58066c25088d)

**Comment by dromer** [comment]
Can even get the menu _behind_ the main window:
![2024-06-12_14-22](https://github.com/plugdata-team/plugdata/assets/1185977/186dd768-102b-4eec-b08b-71078dfbfbe8)

**Comment by timothyschoen** [comment]
All dialog crap should be fixed now!

When dialogs are shown, we render openGL/Metal content off-screen, and copy it into a JUCE image. It's a bit of a workaround, but it works! 

The reason we can't use nanovg for all rendering is that it's text rendering isn't good enough (nor fast enough). Someday we could write our own text rendering system for nanovg, but that's a bit much for now.
