### ISSUE TITLE
[bug] file dialog doesn't close when compile dialog is closed

### ISSUE THREAD

**Issue by dromer** [plugdata-team/plugdata#1550]
ie: 

![2024-04-30_16-40](https://github.com/plugdata-team/plugdata/assets/1185977/21bd19a9-22d7-4203-b791-e58c792cb75d)

**Comment by dromer** [comment]
If I were to press `OK` we get a segfault `Aborted`.

**Comment by timothyschoen** [comment]
Oh wow, on macOS, it'll block all mouse interaction with the windows behind it!

I hope 5a884d60d fixes it?

**Comment by dromer** [comment]
I think so!
