### ISSUE TITLE
Button widget doesn’t respond to Toggle message

### ISSUE THREAD

**Issue by DeepSeaHaggis** [plugdata-team/plugdata#1566]
The button widget doesn’t seem to respond to a “toggle” message to change the button type. The included patches in the documentation for Button don’t work, as well. I did notice that the autofill message for a Message box hooked up to a button gives “togl” as the appropriate message but that gives an error in the information bar. No such error is given for “toggle”.

**Comment by DeepSeaHaggis** [comment]
Should have source. I see you have toggle as a todo in ButtonObject.h.

**Comment by timothyschoen** [comment]
Fixed with e7bab3b49fa6c8c83b048b30e703b830282fa124


(btw, the mentions of toggle in the Button source code are unrelated, those are for the API that allows plugdata to trigger the button automatically)

**Comment by DeepSeaHaggis** [comment]
Thanks for the fix! What’s the timeline where that’ll be in the App Store version?

**Comment by timothyschoen** [comment]
Unfortunately App Store version will take some time, but hopefully within a month. First I'm finishing off the next version for desktop, then I'm need to port all of that, and fix some of the bugs that still plague the iOS version (like not being able to read files from filesystem, crashes on some iOS devices, etc.)
