### ISSUE TITLE
Rendering / Disabling Track / Exporting VST3

### ISSUE THREAD

**Issue by MEOWXXOFFICIAL** [plugdata-team/plugdata#1575]
Mac M1 - Monteray 12.4
Cubase 13 - using Rosetta
Plugdata 0.8.3

G'Day!

I am loving messing around on this thing and making effects that i have usually bought. Love it. I'm a beginner to this sort of thing, so im only making basic stuff but it just feels to good to have this much more control over my art. 

Here are 3 things that have been happening that have been slowing the workflow, and disrupting my inspiration:

- When using plugdatafx on a track, then trying to render the track to printed audio, it crashes Cubase, Every time.
- When i have plugdatafx on a track and try to disable the track, it crashes Cubase. Every time.
- When i try to export a VST3, it fails every time, claiming to not know the objects im using... such as knobs... and floats,,,which come with plugdata... and not knowing the filepaths, except that everytime i open these patches they work straight away, so not sure why it all fails when exporting.

Anyway, loving creating anyway. 

Cheers, 

Mitch

<img width="1247" alt="Screen Shot 2024-05-21 at 11 42 38 am" src="https://github.com/plugdata-team/plugdata/assets/170289978/929af2aa-8363-4429-8073-4659182c3715">

**Comment by dromer** [comment]
For the last point: please enable "compiled mode" so you get warnings about incompatible objects.
Not all objects in plugdata are available for compiled mode.

There was a bug with the path in plugin mode which has been solved in latest builds, so please try the nightly for that.
Still not all objects will work so you _need_ to enable compiled mode.

**Comment by MEOWXXOFFICIAL** [comment]
Ok I’ll have a go and let you know how it goes :)

**Comment by MEOWXXOFFICIAL** [comment]
ok - switched to Compiled mode: still some problems

![Screen Shot 2024-05-21 at 9 22 36 pm](https://github.com/plugdata-team/plugdata/assets/170289978/747519d6-1297-40bc-b7a8-83bc21978de2)
![Screen Shot 2024-05-21 at 9 21 56 pm](https://github.com/plugdata-team/plugdata/assets/170289978/8ddec9ca-0f53-4e44-8d12-428e024458d3)
<img width="1261" alt="Screen Shot 2024-05-21 at 9 22 23 pm" src="https://github.com/plugdata-team/plugdata/assets/170289978/1a4ab26a-d3a0-4b22-9316-4bf5fcfe735d">

**Comment by MEOWXXOFFICIAL** [comment]
waittttttttt

it just worked! i pressed a different button

**Comment by dromer** [comment]
You have to fix the warnings before you can compile. As I said: these objects are not supported so you have to replace them.

**Comment by MEOWXXOFFICIAL** [comment]
for sure - i am a beginner to this sort of thing

what should i replace all these objects with? i have no idea how to move forward...

**Comment by dromer** [comment]
You'll have to rewrite your patch so it does not need these objects.
