### ISSUE TITLE
heavy compiled vst3 with custom GUI

### ISSUE THREAD

**Issue by lokkiikkol** [plugdata-team/plugdata#1598]
as the title suggests, is there a way to create a custom GUI for a compiled heavy plugin?
has anybody attempted this? I could not find a mention in the DOCs (or I did not look close enough)

Thanks

**Comment by dromer** [comment]
See https://github.com/wasted-Audio/wstd-eq and all the other Wasted Audio plugins.
It being custom means you'll have to write this yourself.

Imo this topic does not warrant a ticket, maybe a discussion.

There is an idea to one day use the nanovg widgets in the new canvas drawing in plugdata to export custom nanovg code for plugin GUI, but this is still very far off.

**Comment by lokkiikkol** [comment]
thanks for the pointer! That is a great starting point and the plugins look great! If it is not too much asked, could you walk me through the steps needed to get from a plugdata export to your plugin with custom UI? From your GitHub, it is not obvious to me where I would put the heavy export etc.

Questions that I have:

-Do I export as DPF but with sourcecode from plugdata?
-what changes/additions do I have to make to that export in order to get a custom UI? (I see you have an override and dep folder in the repository, do I simply add them to the exported structure?

sorry if this is all very obvious, I am usually a bit slow at these things until I get the concept...

**Comment by dromer** [comment]
I have been thinking of adding an `Export Source + GUI` option, which will require you to try and build (and maybe modify) the code by hand on your specific system.

This will at least give you a starting point. The Heavy compiler options configure some specific DPF settings that you will need to have a GUI.

We currently also don't include any UI libraries that would be required. The WSTD plugins use a fork of DPF-Widgets, but we would include the standard version with the basic ImGui UI: https://github.com/Wasted-Audio/hvcc-examples-dpf

At the moment the only way would be to use hvcc/heavy directly from the commandline. 
A version is included in the plugdata toolchain somewhere on your computer like `Documents/plugdata/Toolchain/bin/Heavy/Heavy`

**Comment by lokkiikkol** [comment]
I see. An export Source + GUI would be awesome, and surely appreciated.

**Comment by dromer** [comment]
> I still get the plugin with a GUI

You mean _without_ a GUI? This is correct, the Source code from plugdata does not contain the options for enabling the UI.

You could modify the file `DistroPluginInfo.h` by hand and add `dpf-widgets` to the export directory, but this is a lot of manual steps and you will likely make mistakes.

**Comment by dromer** [comment]
@lokkiikkol once the latest develop build finishes you should be able to export a basic GUI!

https://github.com/plugdata-team/plugdata/actions/runs/9414668579

**Comment by lokkiikkol** [comment]
@dromer thanks, will give it a try..

**Comment by lokkiikkol** [comment]
cool, after adding the dpd-widgets directory it compiles fine and spits out a plugin with GUI. now further on to check out how to customise parameter representations (i.e. knob instead of fader, buttons, drop-down etc.)

thanks!

**Comment by dromer** [comment]
Nice!

**Comment by lokkiikkol** [comment]
got it all working on a test plugin, amazing! switches, knobs...custom placement. great. thanks so much for your work!!

**Comment by dromer** [comment]
@lokkiikkol do share an image (or even better: code :D) if you will

**Comment by lokkiikkol** [comment]
@dromer sure...code makes not much sense, since it is only an example of a useless plugin. but here is a screenshot:

<img width="950" alt="Screenshot 2024-06-10 at 17 51 10" src="https://github.com/plugdata-team/plugdata/assets/13051503/807f60d0-4f36-4165-89a7-ad7cb0c50dad">

**Comment by dromer** [comment]
Haha, sure. Thnx! Hope this will help you create some interesting custom UI at least :)

**Comment by lokkiikkol** [comment]
it sure does. thnx!
