### ISSUE TITLE
Bugs with pop up boxes.

### ISSUE THREAD

**Issue by Carambolooo** [plugdata-team/plugdata#1613]
One of these happens when I try to save a patch. The pop up box for saving appears behind the canvas, and it is only accessible if I use the program not maximized.

![Captura desde 2024-06-05 08-51-43](https://github.com/plugdata-team/plugdata/assets/171201984/af9933d8-5536-45c8-aadb-4c5390490633)

Another one is, for example, when I try to assign a key for a shortcut, the pop up box that tells me which key to assign and save or cancel, appears behind the whole plugdata interface and is inaccessible. It is only visible from the system “taskbar”.

![Captura desde 2024-06-05 08-53-22](https://github.com/plugdata-team/plugdata/assets/171201984/5d151027-a4e3-4989-bffe-785c18268216)

All this happens on my laptop with Arch Linux, using the pre release 0.9.0 for Arch.

**Comment by dromer** [comment]
You will have to give more details about your OS.

Which graphics system do you use? (X11/Wayland)
And what Window manager?

Arch shipping a development version is really dumb imo.

**Comment by Carambolooo** [comment]
My windowing system is Wayland, with GNOME 46 as desktop environment.
64-bit laptop.

Specifically I am using the package marked as “plugdata-Arch-x64.tar.gz” that appears in the latest pre-release.

**Comment by Carambolooo** [comment]
UPDATE:

I am now using the same Arch Linux system but with MATE as my desktop environment, which uses X11 as the windowing system.

All the bugs mentioned here are not present using my system configured as it is currently.

**Comment by Carambolooo** [comment]
NEW UPDATE:

(Everything mentioned here has to do only with the first bug).

This bug was replicated even in X11, specifically in the Openbox window manager.
So it doesn't seem to have to do exactly with the windowing system used.

What I noticed is that, in the MATE desktop environment, where this bug does not appear to me, Plugdata uses MATE's own, more visually compact file selector.
This is a bit different from those of say, GNOME or Plasma. Both environments where I was able to replicate the bug.

In openbox, plugdata used a similar file selector if not the same as GNOME, environment that I didn't even have installed, showing the same bugs mentioned.

**Comment by timothyschoen** [comment]
That makes sense, it will try to use a native file browser, unless it can't find one for your desktop. This is handled by JUCE, so I don't know exactly how it works. Strange that it can't find the file browser, especially on KDE and GNOME. It does work with GNOME 46 on Fedora for me.

I'll see if I can solve this!

**Comment by timothyschoen** [comment]
Does 480d3e084 fix this problem?

You should be able to get it for arch here: https://github.com/plugdata-team/plugdata/actions/runs/10798169998
(once it's done building)

**Comment by Carambolooo** [comment]
Still no luck, Now in i3, pure data's own file browser appears when I try to open a file (Ctrl+O), but it still doesn't appear when I try to save a file, it's as if it appears behind the canvas.

**Comment by timothyschoen** [comment]
Hmm, seems like I only applied it for open dialogs there, not save dialogs!

Does d55a06d71 help?

**Comment by Carambolooo** [comment]
How can I test the last one? It only redirects me to a section with code.

I really don't know how to work with it.

**Comment by Carambolooo** [comment]
Oh never mind, I downloaded the latest nightly from the plugdata page and the bug seems to be fixed!
Thx!!

**Comment by timothyschoen** [comment]
Yay!
