### ISSUE TITLE
no help file for [else/count]

### ISSUE THREAD

**Issue by Marco-56** [plugdata-team/plugdata#1619]
I am on Win 11 and PlugData 0.9.0. I can create [else/count] but when I call for help file, the console says that could not find help file, and nothing appears.

**Comment by timothyschoen** [comment]
Do you also have this problem for other ELSE helpfiles, or just [count]?

**Comment by porres** [comment]
I can't reproduce this on mac

**Comment by timothyschoen** [comment]
Yeah, I think it has been fixed!
