### ISSUE TITLE
[feature request] switching ON/OFF integer/float mode in number box?

### ISSUE THREAD

**Issue by H-MLim** [plugdata-team/plugdata#1622]
![image](https://github.com/plugdata-team/plugdata/assets/68152553/356a08b7-eb0e-4476-b577-433c243b3d0c)

the number box became more convenience than vanilla, that simply dragging numbers to make integer to float. but it seems showing dot in the box is kinda compulsory. and it sometimes really bothering me when making GUIs in my patch, and I want to hide it and shows only number(integer)s.

although there are `note` object that shows only numbers via sending messages, it still has a problem that since `note` cannot send the message. or is there already any ways to hide the dot in the box?

**Comment by porres** [comment]
> but it seems showing dot in the box is kinda compulsory. and it sometimes really bothering me when making GUIs in my patch, 

I'm also highly annoyed by the dot, specially regarding some GUIs as [brane.m~]. I don't want the preset number, which is only supposed to be an integer, to show this dot...

The solution I'm seeing is to use a list box instead!

But I think that the atom number box should behave the same and only show the dot when there is an actual need for it...

I see that you want to be creative and offer design revisions and all, but it's so easy to introduce conflicts and noise, so so so so easy... and you'll probably be too excited in offering something you wish and you'll just end up missing and overlooking possible issues.

Anyway, this seems to be a MAX influence, that has a box for floats and another for ints... but applied in a Pd paradigm and it doesn't sit right.

And now, why does the list box behave differently than the atom number box? Seems also weird for me

I've been finding many issues that come from this...

So, my basic idea and solution is:

- Try not to be creative, just keep the original behaviour and stuff

- If you want, you can create a new object and go crazy on it, and I'll include in ELSE for compatibility. So it'd be like a new number box that you can configure to show a dot or not, make it only integer and prevent floats, make it display hexadecimal values. I remember we talked about this actually, and I'm totally up for it.

**Comment by porres** [comment]
I see same goes for [nbx] and, well, maybe just suppress the dot completely and only show it when hovering the mouse to right of if when it also shows non highlightes 0s to show you can click and drag from there...

cause, why do we need the dot?

MAX needs it because it has a float number box and an integer number box... but we're not MAX.

Is it to make MAX people comfortable and not lost?
