### ISSUE TITLE
Possible to have mac DLS Synth as midi output?

### ISSUE THREAD

**Issue by tmhglnd** [plugdata-team/plugdata#163]
Hi!

In MaxMSP the default midi output on Mac is the `AU DLS Synth`. I'm curious if it would be possible to have this as an output in the standalone version of plugData as well? I realize that this synth is also not an option in pd vanilla or the l2ork version, so maybe it is more challenging to add this, I don't know. In the meantime I can of course use SimpleSynth :).

**Comment by timothyschoen** [comment]
Unfortunately this is not implemented yet, but I would be interested in adding this! It's very useful for testing algorithmic composition ideas. 

Another option is to use the [sfont~] object, which can load soundfonts. It accepts raw MIDI input.
