### ISSUE TITLE
incorporate vanilla's "intelligent patching" features

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#1635]
I see most of the "intelligent patching" features are missing, can you implement them all? for reference, see 2.3 section on the current manual

https://msp.ucsd.edu/Pd_documentation/x2.htm#s2.3

**Comment by porres** [comment]
Intelligent patching is a broad term in Vanilla that includes different things. Let's detail it 

- Tab navigation
- Autopatching 
- Duplicate connections 
- Managing connections with the shift key 
- (Dis)Connect selection 
- Triggerize 
- Paste replace

I see PlugData already has Triggerize and  Connect and Disconnect selection, but connect and disconnect use two different shortcuts... right? hmmmm, if so.... why?

One thing to consider is that these extra elements are also presented in the 'edit menu', which is also a way of letting users know that such a feature exist and what the shortcut is.

Paste replace has no shortcut (at least yet) in Vanilla, but it could have one in PlugData by default.

**Comment by porres** [comment]
> I see PlugData already has Triggerize and Connect and Disconnect selection,

Ok, I also see now there is also autopatching enabled in PlugData, but this feature wasn't evident to me as creating another object don't connect them right away as it happens in vanilla, so I assumed it wasn't happening.

So this is what seems to be missing

- Tab navigation
- Duplicate connections 
- Managing connections with the shift key 
- Paste replace

**Comment by porres** [comment]
Well, I actually need to throw back in the  "(Dis)Connect selection" section, with ctrl+k, as I see only a minimal part of it is implemented in Plugdata, but other things still remain not implemented

**Comment by alcomposer** [comment]
Let's have one issue for this, the newest one is: #1701
