### ISSUE TITLE
allow configuring of some patching features

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#1638]
In Vanilla, one can disable autopatching if desired, can we do this in plugdata? 

I think there could be some configuration possible for other things that plugdata offer, like, disabling creating connection from the outlet if the user desires

**Comment by timothyschoen** [comment]
> In Vanilla, one can disable autopatching if desired, can we do this in plugdata?

Yeah, this is in Settings -> Advanced -> Enable autopatching

**Comment by porres** [comment]
cool, so maybe also add  disabling creating connection from the outlet if the user desires, and I'm not sure what else
