### ISSUE TITLE
Bugs with canvas split

### ISSUE THREAD

**Issue by dromer** [plugdata-team/plugdata#1640]
Hard to describe, but it seems that on latest develop we can no longer cycle tabs as expected when we have a split.

When you cycle tabs on the right their view appears on the left. Once you reach tabs on the left you can no longer get to the right.

**Comment by dromer** [comment]
Another quirky bug I find is when you open an abstraction with split it always shows the abstraction on the left pane.
I think it used to open in the same pane as where you clicked.

Even when you already have the abstraction open (it should go to the existing pane) it will show it on the left one.

**Comment by timothyschoen** [comment]
> Hard to describe, but it seems that on latest develop we can no longer cycle tabs as expected when we have a split.
> 
> When you cycle tabs on the right their view appears on the left. Once you reach tabs on the left you can no longer get to the right.

Should be fixed with c708cabfa

**Comment by timothyschoen** [comment]
> Another quirky bug I find is when you open an abstraction with split it always shows the abstraction on the left pane. I think it used to open in the same pane as where you clicked.
> 
> Even when you already have the abstraction open (it should go to the existing tab) it will show it on the left one.

Hopefully fixed with fb54bd0f2

**Comment by dromer** [comment]
Sweet! will give it a test!

**Comment by dromer** [comment]
> Should be fixed with [c708cab](https://github.com/plugdata-team/plugdata/commit/c708cabfa1f3cc752405dd82a36e03a0a8cda6db)

Now we can cycle per split, but not across splits. Is that intended?
I think before we could cycle all the way around no?

**Comment by dromer** [comment]
> Hopefully fixed with [fb54bd0](https://github.com/plugdata-team/plugdata/commit/fb54bd0f288f6b1ece6527e20d6feed26823c961)

Seems mostly fixed, the only odd thing I see is that the left split resets its orientation to origin when opening the (new) abstraction pane.

**Comment by timothyschoen** [comment]
> > Should be fixed with [c708cab](https://github.com/plugdata-team/plugdata/commit/c708cabfa1f3cc752405dd82a36e03a0a8cda6db)
> 
> Now we can cycle per split, but not across splits. Is that intended? I think before we could cycle all the way around no?

Hmm I thought cycling the active split made more sense, but idk, not sure. I'll think about this

**Comment by timothyschoen** [comment]
> ah and it opens the abstraction in the last active split

Hmm that's not what's supposed to happen? Also, how can you open an abstraction without also making the split active?

**Comment by dromer** [comment]
> Seems mostly fixed, the only odd thing I see is that the left split resets its orientation to origin when opening the (new) abstraction pane.

Hmm, same happens when you close the abstraction pane again.

**Comment by dromer** [comment]
https://github.com/plugdata-team/plugdata/assets/1185977/537a9a37-87f6-43f9-ba5b-7faa33dd4992

**Comment by timothyschoen** [comment]
Ok, I think that's also fixed now!

**Comment by dromer** [comment]
Yup. only thing is the jump to origin bug:

https://github.com/plugdata-team/plugdata/assets/1185977/62780243-b8ba-48b8-a059-ed9c4bec94fe

**Comment by timothyschoen** [comment]
> Yup. only thing is the jump to origin bug:
> plugdata-2024-06-16_21.01.30.mov

Also fixed now!

**Comment by dromer** [comment]
Yes!
