### ISSUE TITLE
"recently open" bug

### ISSUE THREAD

**Issue by higaru2** [plugdata-team/plugdata#1645]
thanks Tim for such an amazing playground.

found a small bug in latest:
- I open a pd file from a path
- it appears in recently open
- I move the pd file from initial path
- when I try to open it from "Recently open" it will crash the plugdata and the host instead of saying that the file cant be open or the file was moved or smth that makes sense:)

*this is in Intel Mac version and the host is latest Reaper.

thnx

**Comment by timothyschoen** [comment]
Fixed! Thanks for reporting!
