### ISSUE TITLE
make pd~ open a Pd Vanilla version in plugin mode

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#1648]
I'm still not sure how [pd~] works in plgdata, can it open vanilla in standalone?

**Comment by dromer** [comment]
It wouldn't make sense to open vanilla, but opening another plugdata as a subprocess would also not make much sense.

What I see both without and with `-nogui` is:

```
pd~ startup failed
pd~: can't stat /pdsched.pd_linux
```

I would think a `-nogui` could be possible, but the way pd is embedded in plugdata may not allow this. For plugin context this is for sure more difficult (symbol conflicts in the host), but for standalone it would be nice to at least be able to run the `-nogui` version.

**Comment by porres** [comment]
> It wouldn't make sense to open vanilla

why?

**Comment by dromer** [comment]
> why?

Because:
* A user may not have it installed.
* There are symbol conflicts if you have different versions. 
* Other technical or practical reasons.

At most, with the gui, I'd expect to open in a separate tab (but that would be quite confusing in plugdata)

**Comment by dromer** [comment]
Nothing you are saying makes sense now :shrug:

**Comment by dromer** [comment]
For plugin mode this will likely not/never work. Very much for technical reasons.

**Comment by porres** [comment]
> For plugin mode this will likely not/never work

It works in Camomile and Max4Live and I bet you it can happen with PlugData...  so I'm sorry if I don't believe it might be likely impossible  for whatever reason you're not sharing.  And anyway, if you're not gonna discuss this in a constructive way, bring up issues and aim for strategies to overcome them and just show up to say "nah... I don't think that will work", then it really doesn't make sense for you to join the discussion :)
