### ISSUE TITLE
Window crash in Bitwig Studio 5.1 / VST3 + CLAP on Fedora 40

### ISSUE THREAD

**Issue by yioannides** [plugdata-team/plugdata#1651]
Hi all, I also posted on the Discord channel about a week ago, but for the sake of documentation, I figured I also post here.

Not sure if it's a duplicate of #719, but I'm experiencing similar trouble: when I try to launch plugdata within Bitwig Studio (via both VST3 and CLAP), the moment I try to close the window, the plugin crashes within Bitwig's VST sandbox. I tried the latest stable version, as well as 0.9.0-test2 and commit 4286078 and they all produce the same result. If I remember correctly, it doesn't seem to crash in REAPER.

Here is a demonstration of the problem:

https://github.com/plugdata-team/plugdata/assets/154235768/eeb7675e-73fa-46f9-8b87-23f077b78dfa

Please let me know whether I can provide you with more information. Thank you!

**Comment by timothyschoen** [comment]
I can reproduce this with Bitwig on Ubuntu, investigating it now! Thanks for the report

**Comment by timothyschoen** [comment]
Hmmm this is a really strange one. Somehow, it seems like Bitwig is closing the X11 window without letting JUCE know when we close the editor. I'm not sure how this happens, but I'll keep looking. I'll need to check if this also happens with other JUCE apps.

**Comment by timothyschoen** [comment]
Should be fixed in the nightly builds now!
