### ISSUE TITLE
allow click on object file in autocomplete

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#1653]
when plugdata suggests a list of objects to autocomplete to I'd expect to be able to click on an item in the shown list so that the object is created with that option. But if I do that what I get is an empty object box.

**Comment by timothyschoen** [comment]
I think this is fixed since today's nightly builds

**Comment by porres** [comment]
I see that it works sometimes, but sometimes not, and that it is kinda funny in general. I will test the new nightly build and try to make a better report of the experience

**Comment by porres** [comment]
I can confirm it behaves now in a better and more intuitive way!
