### ISSUE TITLE
closing a windows should go back to the last opened tab

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#1654]
when closing a tab, plugdata loads the first opened tab, but most of the times we open a new tab because we click on a subpatch and then when we close it we'd probably expect to go back to the parent patch, but I get some other patch that was loaded and opened as the first tab.

This happens a lot when opening a help file, then a subpatch in that help file, cause when we close it, it goes back to our patch that we used to call a help file from instead of the help patch again.

Plugdata needs to keep track of the order the tabs were focused and move backwards in that timeline when tabs get closed

**Comment by timothyschoen** [comment]
Fixed!
