### ISSUE TITLE
improve alignments! 

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#1655]
ok, I get this was surely a design choice, so an intentional and known issue, but the different position of inlets in plugdata do create offsets that are very annoying for me when opening patches that were create in one platform than opened on another.

I wonder why this choice though, cause when resizing GUIs in plugdata, the inlet/outlet offset unaligns the cords as the inlet offset is proportional and changes with the GUI size. Anyway, I just can't see a problem in having things like in vanilla, where the inlets are to the extremes of the object and all of that is avoided.

Only reason I can think of is to mimmic MAX's design. On that respect, resizing sa bang button in MAX doesn't ruin the alignment, unless the button gets ridiculously too small... go ahead and test it please! The inlet has an offset alright, it is not on the extreme left, but resizing the GUI does not shift the offset and it remains constant. PlugData should then also mimic that!

Anyway, one way or another, I think and hope that alignment issues could be better avoided when opening patches from Vanilla in PlugData or vice versa

let's compare

A Vanilla patch

<img width="156" alt="Screenshot 2024-06-24 at 13 40 28" src="https://github.com/plugdata-team/plugdata/assets/5360142/73bde778-6297-4e5e-9cf3-5a25471cef08">

so, perfectly aligned, let's open in PlugData...

<img width="154" alt="Screenshot 2024-06-24 at 13 40 16" src="https://github.com/plugdata-team/plugdata/assets/5360142/00556398-4ffb-49f1-b35a-86daf7686475">

We can see that the inlets in objects are kind of unaligned in comparison to other elements in the patch. If you want to keep the offset, make it exactly the same and also constant when resizing GUIs please. Please fix that.

What I also wound't mind is a "vanilla mode" for inlets, how about that? :) I will treat this in depth in a new issue, but having an option for inlets to the extremes would also fix this issue and improve composing a Vanilla theme.

**Comment by alcomposer** [comment]
Latest work I have been doing passes, however we still need to work out a few things before merge.

![image](https://github.com/plugdata-team/plugdata/assets/12004932/02c18ebd-0bb9-4875-a51b-73c02c118693)

[alignment-test.zip](https://github.com/user-attachments/files/16115081/alignment-test.zip)

**Comment by timothyschoen** [comment]
Should be fixed now I think, with the new iolet spacing option
