### ISSUE TITLE
Add a Vanilla theme

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#1656]
Hi, I see many options for configuration in PlugData, and a few make it more Vanilla.

I propose other configuration options and also a pre configured Vanilla mode.

You already provide straight lines that never bend or curve, squared objects.

What seems to be missing is
- [x] allow one to configure the colors of inlets/outlets
- [x] #1715
- [ ] allow themes to set the font of comments and etc (see https://github.com/plugdata-team/plugdata/issues/1691 )
- [x] #1716

**Comment by porres** [comment]
BTW, Purr Data has a nice 'Vanilla mode'

**Comment by porres** [comment]
Ok, I now see that a 'classic' mode gets pretty close, but misses the inlets/outlets on the extremes of the object

**Comment by porres** [comment]
> Ok, I now see that a 'classic' mode gets pretty close, but misses the inlets/outlets on the extremes of the object

it also misses painting the inlets fully black and having a cord connection that is thicker for signals...

**Comment by porres** [comment]
and why the dot on subpatches in classic mode huh?

<img width="185" alt="Screenshot 2024-06-24 at 14 22 48" src="https://github.com/plugdata-team/plugdata/assets/5360142/5aa3215d-48aa-49a0-8e66-0f8554cebcd1">

**Comment by porres** [comment]
> and why the dot on subpatches in classic mode huh? 

I see what this is now, will open a new issue about it

**Comment by alcomposer** [comment]
Inlet & Outlet colour is already in theme:
![image](https://github.com/plugdata-team/plugdata/assets/12004932/e215c995-6d6b-4142-a2d2-c48619d46c0b)

Would you like more control over this?
* Connection Data Colour
* Connection Signal Colour
* Connection Gem Colour
* Iolet Data Colour
* Iolet Signal Colour
* Iolet Gem Colour

**Comment by porres** [comment]
Hi, I'm checking the nightly build, cool! I guess I missed things as they don't seem all too clear what the options actually are.

I'm testing the "object & connection style", and classic mode.

What I see is that these colors are for like edit mode, huh? And that when I'm on run mode the inlets/outlets are actually grayed out. Can we have a setting to keep the chosen color for the inside area or something? 

As for the alignment issues, they're still there.

I see there is still a minimum offset, I wonder if that is the limit.

And I see that there are still discrepancies between objects and number boxes

by looking closely, I see that the inlet of a number box is a bit narrower, so the alignment fails a bit.

<img width="47" alt="Screenshot 2024-07-05 at 02 00 22" src="https://github.com/plugdata-team/plugdata/assets/5360142/cae0c1fa-990f-4cc3-905e-4a6ef2237a3d">

**Comment by porres** [comment]
canvas text should be 'object text', right? and it should be in "OBJECT" section

and canvas dots colour -> "background dots in edit mode" (no need to mention 'colour', it is obvious we're setting a colour)

data color -> "data inlet/outlet in edit mode" - should be in "OBJECT" section as well

'Signal' -> 'signal connection'
'Gem' -> 'Gem connection'

--------------------

'Inlet/Outlet area' is misleading, it made me think it was the inner area of the inlet/outlet, but you actually mean "top and bottom" area

Anyway, for the Object and IOlet style, I think the color for Inlet/Outlet should not be grayed out and we don't need then any other setting

**Comment by porres** [comment]
The "object and iolet style" could also embrace other elements like message and number boxes

<img width="456" alt="Screenshot 2024-07-05 at 03 05 19" src="https://github.com/plugdata-team/plugdata/assets/5360142/bb3b1f4c-617d-47c2-b712-f2775ee33f67">

We can see that the message boxes and number box have this black area that in Vanilla is just non existent. I see plugdata uses this method to make things squared, but in such a 'clean' visual style, the pure harsh black areas stand out pretty bluntly on the eyes and it differs a lot in style to how these look in Vanilla

<img width="456" alt="Screenshot 2024-07-05 at 03 05 19" src="https://github.com/plugdata-team/plugdata/assets/5360142/0d44c556-8c8d-4079-959f-f88d7d502299">

**Comment by timothyschoen** [comment]
Message and number box style is added now too! I think our vanilla look is vanilla enough for now at least :)

**Comment by porres** [comment]
> Message and number box style was added by Alex now too! 

where can I set it though? testing nightly build... don't see it

>  I think our vanilla look is vanilla enough for now at least :)

I'd hope this issue to be active and not closed until we have an actual preset name for theme style called 'vanilla', cause that's the main point... and also until we deal with this https://github.com/plugdata-team/plugdata/issues/1691 then i think it's good enough and good to go

**Comment by timothyschoen** [comment]
> where can I set it though? testing nightly build... don't see it

Set the "object flag style" setting to "Outlined". You can also just reset your themes and load the classic theme

> until we have an actual preset name for theme style called 'vanilla'

Right now this is the "classic" (and classic-dark) theme. That's fine right?

**Comment by porres** [comment]
> Right now this is the "classic" (and classic-dark) theme. That's fine right?

but it didn't work out of the box for me

**Comment by porres** [comment]
> That's fine right?

could be fine. I still think that a mode named 'Vanilla' would be more straight forward

**Comment by porres** [comment]
I will reboot this into a new issue that gathers other related issues besides https://github.com/plugdata-team/plugdata/issues/1691

**Comment by porres** [comment]
ok, see closing in favor of https://github.com/plugdata-team/plugdata/issues/1882 as a reboot of this and other related issues
