### ISSUE TITLE
improve patch display compatibility between vanilla and plugdata, like in comments

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#1657]
One issue that annoys me the most is how hard it is to make a patch in Vanilla and open it in PlugData

Help files is the biggest challenge in this respect. Comments seem to be the most crucial element, as the explanatory text gets all mashed up.

I opened other issues that are related to this, see https://github.com/plugdata-team/plugdata/issues/1655 and https://github.com/plugdata-team/plugdata/issues/1656 but this is not  enough

And even without a Vanilla mode, or a better management of alginments, there are other issues at hand...

I tried setting the font to 'Menlo' in my theme, which is the same font that Vanilla uses, but it didn't make any miracles and comments still get messed up.

I haven't investigated further and I now nothign, but I'd assume that having the same font and size could make it better to manage this, so I wonder what else is going on and why it is so hard to make patches better presentable if they were designed in Vanilla.

I guess this calls for a discussion, but there is this issue that I really hope could be at least minimized before 1.0 is out!

**Comment by DemandDystopia** [comment]
Just changing the font to the vanilla font likely didn't work because to me it looks like the issue is more font size than the font itself.

At least for the default fonts of plugdata, and all that don't have drastically different widths, heights and spacings, it might even be enough to just have all files ending in -help.pd use a smaller font size.

**Comment by porres** [comment]
well, in Vanilla we can set a font size for every patch and this information is saved within the file...

I thought PlugData was aware of that, so it has a constant font size and is completely agnostic to what the font size of the patch is?

In such a case one solution is to respect the font size that the original file form Vanilla was saved with

**Comment by porres** [comment]
yeah, this is bad :) 

<img width="510" alt="Screenshot 2024-06-24 at 17 55 23" src="https://github.com/plugdata-team/plugdata/assets/5360142/321bd825-284e-4fc8-a818-708766d34559">

**Comment by porres** [comment]
Ok, here's for comparison. I made the font size equal to "12", which I think is what PlugData uses. The help files have font size 10 so that's one thing that makes a difference 


<img width="1126" alt="Screenshot 2024-06-25 at 04 39 19" src="https://github.com/plugdata-team/plugdata/assets/5360142/f2136e59-92d6-4365-a950-f9787d568358">


the patch 
[sig2float~-help-test.pd.zip](https://github.com/user-attachments/files/15966809/sig2float.-help-test.pd.zip)

**Comment by porres** [comment]
from the comparison above, I don't really get why the methods from inlet '0' are all unaligned... 

there is also a problem that object boxes have a wider area/space than the font size, what makes things also unalign.

There are also issues with the font setting os the canvas GUI. In Vanilla we can choose from 3 specific fonts, but in PlugData it uses whatever font you set from the theme... this is a discrepancy that is not good and I should open a new issue about it...

Nonetheless, I chose 'Menlo' for the name of the object and I guess it looks a bit bigger in Vanilla...

**Comment by porres** [comment]
I will just make another consideration here about allowing the inlets to be to be configured to be placed on the edges, as in a vanilla mode proposed in https://github.com/plugdata-team/plugdata/issues/1656

here's a screenshot 
<img width="795" alt="Screenshot 2024-06-25 at 05 13 29" src="https://github.com/plugdata-team/plugdata/assets/5360142/f1e18ba3-73a0-47cc-8cf0-67d088a61719">

as you can see, if the outlet of float has an offset to the right and the 2nd inlet of the object box has an offset to the left, the cord will not align as in Vanilla. So in order for things to be better visually coherent, a Vanilla mode would also help in achieving an equivalent display

**Comment by porres** [comment]
The picture from the above comment is actually distorted to make things visually comparable, but there is actually a bug on how PlugData handles width that is described in https://github.com/plugdata-team/plugdata/issues/1672

**Comment by timothyschoen** [comment]
This I would definitely like to improve. The problem here isn't my unwillingness to do it, but rather that it's really hard to fix. I can try some more though.
