### ISSUE TITLE
[scope~] issues

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#1661]
- clicking is not enabled for [scope~] (it is supposed to freeze the display as explained in the help file).

- the default size is not what it is supposed to be

**Comment by alcomposer** [comment]
> clicking is not enabled for [scope~] (it is supposed to freeze the display as explained in the help file).

This is now in PR #1708 

> the default size is not what it is supposed to be

This is up to @timothyschoen

**Comment by porres** [comment]
The issue is that the object documents particular default settings and it is arbitrarily different and inconsistent and not true here... is there a reason for that?

I like the idea of a freeze message, this was just copied from max/cyclone

I can also add a bang message for freeze mode that updates it

**Comment by alcomposer** [comment]
For info, here is where it's written in the help file:
![image](https://github.com/plugdata-team/plugdata/assets/12004932/a434e41b-6eca-4657-a927-4c8b94d7c2ed)

**Comment by alcomposer** [comment]
> The issue is that the object documents particular default settings and it is arbitrarily different and inconsistent and not true here... is there a reason for that?

Fixed in #1713
