### ISSUE TITLE
allow to set GUI's properties in run mode

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#1668]
I think I discussed this once with @timothyschoen but I can't see any issue so I'm opening this one.

I'd like to be able to change properties while in run mode, like I can in Vanilla.

PlugData forces me to get into edit mode and then go back to run mode after setting properties. In Vanilla you can right click, open properties, change it, and hit enter to go back to where you were in run mode.

**Comment by alcomposer** [comment]
I just tried this now. I looks like a user can also add objects in lock mode to.

In plugdata adding objects via drag-and-drop will make the editor go into edit mode.
However I'm not sure exactly how this FR will work. 

Mainly as plugdata shows the inspector for the selected object (mainly GUI objects) and in run mode you can't select objects- or see what would be selected.

https://github.com/plugdata-team/plugdata/assets/12004932/d005071c-00f6-41ee-b20b-4410a4154a1f

**Comment by porres** [comment]
> I just tried this now. I looks like a user can also add objects in lock mode to.

yes, I mentioned it in https://github.com/plugdata-team/plugdata/issues/1669

**Comment by porres** [comment]
> In plugdata adding objects via drag-and-drop will make the canvas go into edit mode.
> However I'm not sure exactly how this FR will work.
> 
> Mainly as plugdata shows the inspector for the selected object (mainly GUI objects) and in run mode you can't select objects- or see what would be selected.

yeah, I can see that now, it's a whole different paradigm... I guess I was still expecting a right click and then being able to click on 'properties', which is a grayed out option, and that could enable the side bar inspector like thing?

**Comment by porres** [comment]
and then clicking back on the patch goes out of that side window...

anyway, I missed addressing that it's a completely different scenario, I guess I was expecting a pop window :)

**Comment by alcomposer** [comment]
If it's ok with you, I'll close this for now. We will still be thinking about way's to improve the lock/run mode inspector (if possible)

**Comment by porres** [comment]
> If it's ok with you, I'll close this for now. 

well, first I'd like to know exactly why :) 

My suggestion here is to allow right click --> properties to open the inspector

what would be the objection to reject this?

btw, I also see that somehow I'm not allowed to reopen this issue, which is not the case in other repositories like pure data and ELSE, seems like a good thing :)

**Comment by alcomposer** [comment]
Right click -> properties to open inspector in run mode?

As you mentioned plugdata is a different paradigm.

The problem with run mode is objects are not selectable, only their GUIs. So it may not be clear for tightly packed objects which one you have selected.

One solution here is "objects could be selectable via right click". And a blue outline around the object.

**Comment by porres** [comment]
hmmm, yeah, when I do it, the object is not selected indeed, but I never noticed nor found that to be a problem. Anyway, you can call help from run mode, what is the difference? I was never confused in my life to ask for help from the pop context menu not knowing which object I'm getting help for, and I don't remember ever getting the help of the wrong one. The pop up context menu is created right where you clicked so I can't see how it is not clear which object we'd be getting help, checking reference, opening (in case of abstractions) and also accessing properties.

![Screen Shot 2024-06-29 at 03 06 58](https://github.com/plugdata-team/plugdata/assets/5360142/672bb888-9a49-4556-a6a6-7552f1ad4cde)

I can see why in MAX you can't access properties from context menu while in run mode, cause there is no context menu in run mode. Well, in fact, its context menu doesn't even have any entry for properties. But for what it is worth, I can't see where they got that silly idea and I cry every time I need to get into edit mode to ask for help.

PlugData, on the other hand, did not follow this silly max design choice, and allows you to ask for help and also offers a properties entry, but it arbitrarily prevents properties from being called and it doesn't make sense to me that something that was seemingly inspired from the workflow of Pd doesn't work. Pd users that are used to this will find it confusing.

> I use ctrl quite a bit to interact with GUIs while in edit mode. Could that not be a solution to this for you?

The problem is the need to get out of run mode and into edit mode so you can get into properties, so 'be in edit mode' is not a solution.

**Comment by porres** [comment]
Oh, MAX actually allows you to call properties in edit mode, my bad! I missed it, my eye search for 'properties', but it's 'inspector' of course... 

well, I don't use it that much, if course, but if I say I cry when I have to get into edit mode to ask for help (and I felt that terrible feeling), I can say it's a similar suffering to go through the same for properties.

**Comment by porres** [comment]
Now that I'm testing and thinking more about this and also checking MAX, I see MAX forces the inspector window to expand when you right click on it and check for inspector. 

My usual workflow was to click on the 'i' icon instead.

On the other hand, I see that PlugData won't do anything about it if the 'inspector' tab is not already expanded. So you can click for properties and get nothing if it's not expanded.

Somehow you have a mix of both MAX's and Pd's ideas, but both were copied with flaws.

You should be able to let right click -> properties expand the inspector tab if it's minimized, as in MAX.

You should be able to call it in run mode since you have a context popup menu in run mode, as in Pd.
