### ISSUE TITLE
Allow objects to be created with "else/" prefix

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#167]
tried opening 'all objects' and this is what I got

![Screen Shot 2022-08-24 at 15 22 35](https://user-images.githubusercontent.com/5360142/186494346-65b5e5b6-78b6-4b37-9313-875515851fee.png)

![Screen Shot 2022-08-24 at 15 22 27](https://user-images.githubusercontent.com/5360142/186494335-4d652654-1fbd-4e44-8c80-bb03a645041c.png)

**Comment by porres** [comment]
I changed the title, it seems like camomile you don't load objects with the 'else' prefix but some abstractions still have it.

**Comment by porres** [comment]
Well, it's weird, I'm having problems opening many of my patches. Some objects don't load BECAUSE they don't have the 'else' prefix, and some do not load because they have it... see below

![Screen Shot 2022-08-24 at 15 33 23](https://user-images.githubusercontent.com/5360142/186496351-1e331da5-0497-4476-bd1d-9a9ee9cdecc3.png)

If I try just [out~], it load, if I try [else/perlin~], it works...

**Comment by timothyschoen** [comment]
I wrote something pretty hacky to get the "else/" prefixes to work. Guess it's not working at all... The easiest solution thing would be to not support the "else/" and "cyclone/" prefix.

**Comment by porres** [comment]
> The easiest solution thing would be to not support the "else/" and "cyclone/" prefix.

seems simple, we already do that for camomile. It should be easy to remove 'else/' from the help files and all.

But... allowing 'else/' would be ideal

**Comment by timothyschoen** [comment]
I agree! It's just that I have no idea how we can do this correctly. I think it would be best to disable it for the bugfix release, and then reconsider it later.

**Comment by porres** [comment]
question: dont you need [declare -path else] to find else's abstraction inside a foler in your app?

**Comment by timothyschoen** [comment]
I secretly add the direct path to ELSE's externals. This is bad, I'll make it appear in the paths list as well.

**Comment by porres** [comment]
not sure if I get it, but anyway, I can't see it as it's all hidden inside the app, right? The abstractions don't seem to be accessible or replaceable

**Comment by timothyschoen** [comment]
They are accessible, on macOS: ~/Library/PlugData/v0.6.0/Abstractions

The version number thing is new, it's there to make it easier to upgrade ELSE abstractions, while also not deleting any changes the user might make. It's the solution I came up with to the problem we were discussing on Facebook earlier.

That folder is also in the paths. It contains a folder "else" which contains ELSE's abstractions, that folder gets secretly added to the path. I'll stop hiding that soon.

**Comment by timothyschoen** [comment]
Done!
