### ISSUE TITLE
somehow and weirdly enough [drum.seq]'s size is wierd in plugdata

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#1680]
It's not loading the size correctly in plugdata somehow, I'd have to investigate where the bug, I can help, but for now just listing this here...

<img width="889" alt="Screenshot 2024-06-25 at 23 16 58" src="https://github.com/plugdata-team/plugdata/assets/5360142/b0e1ea34-3ef8-4eaf-8dc6-d533009c5078">

**Comment by timothyschoen** [comment]
Doesn't seem to be the case anymore!
