### ISSUE TITLE
[display] doesn't flash when receives a different message

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#1681]
and only if it gets a repeated message!

**Comment by alcomposer** [comment]
Tim and I are working on a new system for activity overlay.

Can you provide a minimum PD example of this behaviour, I don't 100% understand.

However as we are working on this for 0.91 I think we can address it!

**Comment by porres** [comment]
> Can you provide a minimum PD example of this behaviour, I don't 100% understand.

try the help file... click on repeated messages

**Comment by alcomposer** [comment]
Looks like it's working here? 
Can you post a screenshot of this bug?

https://github.com/plugdata-team/plugdata/assets/12004932/f4ddddcb-dca7-4120-b403-a56c80602b46

[display-flash-test.zip](https://github.com/user-attachments/files/16010115/display-flash-test.zip)
d

**Comment by porres** [comment]
it's working here now, but I have a new nightly build installation

**Comment by alcomposer** [comment]
@porres please check with latest nightly when you find an issue so we can know for sure if it's a current bug.
