### ISSUE TITLE
resizing atom number box is freezing plugdata

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#1684]
I was testing crazy resizing with handles for GUI elements and when resizing an atom number box in the helo file of the [float] object by making it too small in width and height PlugData just froze!

I was able to try this twice and in both cases the application stopped responding

macOS sonoma, macbook air M3, a recent nightly build

**Comment by porres** [comment]
while we're at it, it seemed that the number box was able to be resized to a rather too much narrow size that makes it impossible to see any number at all...

and i don't think that should happen. A minimum of one digit size must be the rule and maybe that's when the software might be going crazy and freezing?

**Comment by timothyschoen** [comment]
I had made some fixes for float box resizing v0.9.2 earlier, and I think this bug is fixed. At least, I'm unable to reproduce on the latest nightly builds
