### ISSUE TITLE
create plaits from browser without args

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#1687]
you have this object browser on top (which by the way, fails to show most of objects and I already have a suggestion for a better browser experience like I offer in vanilla via a right click but anyway) and when I select plaits~ it creates with arguments... when it shouldn't, just default values would be good

<img width="395" alt="Screenshot 2024-06-25 at 23 44 51" src="https://github.com/plugdata-team/plugdata/assets/5360142/9c7ca183-1a87-44c3-a73b-909742d32d45">

while we're at it... I/O section could have "OSC" objects, huh?

<img width="537" alt="Screenshot 2024-06-25 at 23 44 05" src="https://github.com/plugdata-team/plugdata/assets/5360142/94136df2-2f04-46e5-8c9f-b240b42cf601">

**Comment by alcomposer** [comment]
Can you elaborate on this? It's not clear what you are suggesting in the second part.

> when I select plaits~ it creates with arguments... when it shouldn't, just default values would be good

The idea here is to allow the objects to be usable when added into a canvas.

**Comment by porres** [comment]
> Can you elaborate on this? You mean [osc.send] & [osc.receive]?

yup, I think that'd be nice

and plaits~ should not have all those arguments, that's weird :)

**Comment by alcomposer** [comment]
> and plaits~ should not have all those arguments, that's weird :)

Can you let us know what arguments you think it should have? Is this the only one that has in your eyes wrong arguments?

**Comment by porres** [comment]
> Can you let us know what arguments you think it should have?

None! 

let it load its default parameters

**Comment by alcomposer** [comment]
Both fixed in: #1714

![image](https://github.com/plugdata-team/plugdata/assets/12004932/d8374d4f-1c63-4887-9845-86af4d54d836)
