### ISSUE TITLE
cyclone [coll] does not have an editor window

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#1693]
clicking on [coll] should open an editor window, nothing happens in PlugData

**Comment by tmhglnd** [comment]
+1, just encountered this same issue.

**Comment by timothyschoen** [comment]
3297af5c58a7a5d17c9fdfcf30c7df6b9e7bbedb should fix it. I still need to test a bit more, but the editor opens up, and I can make changes :)

**Comment by timothyschoen** [comment]
Yep, looks like it works now

**Comment by tmhglnd** [comment]
This works yes!

**Comment by tmhglnd** [comment]
I think somewhere along the way this got broken again. For me in the latest nightly the [coll] won't open anymore.

**Comment by timothyschoen** [comment]
Oops, fixed with cb320b0a2

**Comment by tmhglnd** [comment]
Yes, works again!

**Comment by tmhglnd** [comment]
I think this might be related to the same issue as coll. The `[presets]` object from the else library also doesn't open the text window when clicking it.
