### ISSUE TITLE
Allow some patching workflow configurations so connections aren't that easy to make and there are less things to click and mess with

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#1697]
This is a reboot of https://github.com/plugdata-team/plugdata/issues/1670

I have made extensive remarks over there and won't get into the details, people can read it, but the bottom line is I am really not comfortable in working in a feature creep environment influenced by MAX design choices and I just hope there could be options to configure PlugData to make it a more comfortable environment for people that come from another reality and spirit.

In short, I'd like to be able to reduce information and possibilities for interaction that are getting in the way of my workflow and making it really hard to do simple things like making connections and moving objects around. I won't repeat myself, remarks were written here https://github.com/plugdata-team/plugdata/issues/1670#issuecomment-2195620688

I can of course keep on elaborating and discussing this by requests.

Here's what I'd like to configure
- Don't allow connections to be dragged and made from inlets
- Reduce the area where connections are made possible
- Reduce the handles to resize things (if only horizontal resizing is possible, leave it to the right one, If both horizontal/vertical is possible, leave it to the bottom right handle)

please don't close this issue without a reasonable discussion

thanks

**Comment by alcomposer** [comment]
An update:

> Don't allow connections to be dragged and made from inlets

This is currently PR: #1699 that I worked on.

> Reduce the area where connections are made possible

This will be addressed in a future Vanilla Object look style

> Reduce the handles to resize things (if only horizontal resizing is possible, leave it to the right one, If both horizontal/vertical is possible, leave it to the bottom right handle)

We will address this in future, maybe not for V1, but it's on our radar. We will also be able to use side resize for changing aspects ratio locked objects (such as Keyboard & Button)

**Comment by porres** [comment]
good, no need to rush anyway

>  The size of the hit area will be reduced to look similar

for the record, they way it works in Vanilla is that you need to drag the cord anywhere in the object's area, and it'll connect to the nearmost inlet

Also, as for the outlet, you don't need to drag from exactly it. If you click on anywhere in the bottom area it'll allow you to drag a connection from the nearmost outlet. In Plugdata if you try to do that you end up dragging the object. 

I'm not saying that this should be also in the Vanilla mode, but it's something worth noting I guess

This was a recent change by the way, to make it easier to create connections. 

I haven't fully adapted yet and I still find myself accidentally making connections when I want to drag the object in Vanilla but it's easy to release the cord in a safe area and try again.

Well, I dunno, maybe you like this idea too and would think it'd be desriable for PlugData to make it easier dragging connections from outlets?

In PlugData you also have handles to resize the object. Well, actually so does vanilla in many cases. Let's take a regular object for example, it can be resized to the right in Vanilla and same goes for PlugData. So, in the bottom area this would be disabled.

Things get complicated in plugdata for something like a bang, as it has it's bottom right handle to resize diagonally. In this case if one goes for the handles, it's fine, but anywhere else in the bottotm area could favor dragging connections from an outlet

what do you think?

**Comment by alcomposer** [comment]
I think we should have separate tickets for these suggestions. 
As it's hard to talk about multiple things at once. 

In the last week Tim implemented many auto-patching features, and now there is the `Patch downwards` mode.
How about we see how this feels for 0.9 and regroup and plan out past that?

Some may need to wait till after V1, depending on how large the change is.

**Comment by porres** [comment]
sure, sounds good

**Comment by alcomposer** [comment]
> for the record, they way it works in Vanilla is that you need to drag the cord anywhere in the object's area, and it'll connect to the nearmost inlet

We are 100% thinking about this, we may also be able to improve it with a movement vector of the mouse, select inlet if mouse is moving up inside object, outlet if moving down inside object. 

> Also, as for the outlet, you don't need to drag from exactly it. If you click on anywhere in the bottom area it'll allow you to drag a connection from the nearmost outlet. In Plugdata if you try to do that you end up dragging the object.

This is a bit harder to implement. Even inside a vanilla mode, it would change our patching paradigm. We are also thinking of having a drag area  on the sides to resize some objects. Which would mean it would become very confusing if there is a hidden area at the bottom of an object that is an outlet hit area. 

Below is what I deduce is the outlet / inlet area:
![image-12.png](https://github.com/plugdata-team/plugdata/assets/12004932/2ce1c1db-1908-4990-bfb8-456556708c00)

**Comment by timothyschoen** [comment]
> Don't allow connections to be dragged and made from inlets

This is an option now

> Reduce the area where connections are made possible

Did that a little while ago. It's not gonna be as small as Pd, but at least a bit smaller.

**Comment by porres** [comment]
> This is an option now

where?
