### ISSUE TITLE
autocomplete bug

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#1700]
sometimes I am finding autocomplete to repeat the last character when writing an object name, for reference:

<img width="172" alt="Screenshot 2024-06-30 at 13 55 19" src="https://github.com/plugdata-team/plugdata/assets/5360142/7a76503a-5591-447c-85d8-3fc17d3f9175">

**Comment by timothyschoen** [comment]
When did you last update? I tried to fix this a few days ago, so maybe this is already fixed on nightly?

**Comment by porres** [comment]
I will update now, do we already have some inteligent patching? what can I test as well?

**Comment by porres** [comment]
ok, seems fine, now having fun with autocomplete :) AWESOME!!!!!
