### ISSUE TITLE
plugdata does not tell us we can click on GUIS

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#1717]
related to https://github.com/plugdata-team/plugdata/issues/1660

plugdata does not tell us we can click on GUIS, like a bang object or that it is possible to click on an array to edit its contents. It will also tell you that you CANNOT click on it if array editing is disabled.

I also just tested a few things and I see that plugdata still fails to show users that they can click on [array define] or [text define] for instance.

Note that some objects in ELSE can be clicked, such as [loadbanger], but in PlugData that is not evident.

It is not evident as well that you can click on a GUI like [function].

I see that highlighting the [pd] subpatches and abstractions work great and feels nice, but we still need to work on these other cases.

**Comment by timothyschoen** [comment]
I fixed this for all text objects, like [text define], [array define], [loadbanger] and all abstractions with [else/click] in it!

Regarding GUIs: we used to have this for a while, where all GUIs had a hover colour. The problem with any kind of visual feedback we give for GUIs (mouse cursor or hover colour), is that we are forcing people who design plugins with plugdata to use it. You can easily add a hover colour to an object yourself with some [pad] tricks, but it's much harder to get rid of it. Same goes for cursor changes: if we add this, we are forcing a very specific (and uncommon) design choice onto our users.

All GUIs have the same default background colour in plugdata though, so this already makes them stand out from non-interactive objects. I think this is clear enough. Besides, most audio applications don't have hover/cursor changes for their knobs and sliders, and this never seems to lead to any confusion.

So I think that was all for this issue?

**Comment by porres** [comment]
can I test this with the nightly build?

I guess GUIs are pretty clear to be clickable. The one thing I can still think about is that we can have arrays that are not editable and this is clearer in Vanilla, but that's all.

**Comment by timothyschoen** [comment]
> The one thing I can still think about is that we can have arrays that are not editable and this is clearer in Vanilla, but that's all.

I agree, we should improve that!

**Comment by timothyschoen** [comment]
Nightly builds should be done in 5 minutes or so!

**Comment by porres** [comment]
> Nightly builds should be done in 5 minutes or so!

just tested macOS legacy, [loadbanger] does not give any hint it can be clicked

**Comment by porres** [comment]
> I fixed this for all text objects, like [text define], [array define], [loadbanger] and all abstractions with [else/click] in it!

I can't see it for [text define] and [array define] as well as [loadbanger]. On the other hand, I see that all abstractions change the background color, and not just one with [else/click], which I think it's what should happen anyway :)

**Comment by porres** [comment]
oh, maybe there is a new nightly coming, I see

**Comment by timothyschoen** [comment]
Whoops, I forgot to push!

It's building now: https://github.com/plugdata-team/plugdata/actions/runs/11503664324

**Comment by timothyschoen** [comment]
I think this is all good now?
