### ISSUE TITLE
dragging dialogs drags the main window instead

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#1722]
first thing is unrelated (i think) then when trying to drag dialogs (i tried compile, settings, find externals, and about) the dialog disappears and you end up dragging the main window

i tried with system titlebar, same thing happens. it doesn't happen with the array dialogue

https://github.com/plugdata-team/plugdata/assets/86204514/a3f55b45-0792-4271-b9a8-e3d6358eeb33

**Comment by dromer** [comment]
Settings and Compile dialogs are now embedded in the main window and drag the entire screen.
It seems less inconsistent and these dialogs also no longer close when doing this.

So I think the issue is now outdated/resolved?

**Comment by timothyschoen** [comment]
> Settings and Compile dialogs are now embedded in the main window and drag the entire screen. It seems less inconsistent and these dialogs also no longer close when doing this.
> 
> So I think the issue is now outdated/resolved?

Yep, seems like this has fixed it! Let me know if it still gives you issues!
