### ISSUE TITLE
unwanted suggestion panel

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#1723]
i have finally caught my foe and made it reproducible! (been hunting this on and off for a few days)

1. be in a patch (any help file will do)
2. go to edit mode
3. look for another object and drag it (it's important you drag it)
4. alt+click that object to open its help file

you'll find that the suggestion panel is now open

https://github.com/plugdata-team/plugdata/assets/86204514/4c68922a-ead1-41b0-ba29-a56e447d1362

**Comment by timothyschoen** [comment]
Should be fixed now!

**Comment by tomara-x** [comment]
great work! 💜
