### ISSUE TITLE
[bug] Shift-click mouse drag on hsl/vsl lacks high resolution

### ISSUE THREAD

**Issue by jayrope** [plugdata-team/plugdata#1729]
Bug: shift-click mouse-drag on both an [hsl] or [vsl] in order to increase resolution by 100 
only works in "steady on click"-mode, not in in "jump on click" mode.

Tested using plugdata-fx in Reaper as well as plugdata standalone, on macos 13.6.7.

It does work in PD vanilla 0.54.-1.

I suppose there is a routine checking for a click in jump click mode, which doesn't stop triggering, when moving the mouse.

Thanks for all you do!
@timothyschoen

**Comment by timothyschoen** [comment]
Thanks for reporting, should be fixed on the develop branch now!
