### ISSUE TITLE
daw crashes if bezier array mode is selelcted with too few points

### ISSUE THREAD

**Issue by KallynMusic** [plugdata-team/plugdata#1730]
If you have an array set to points or polygon with 1 data point, and then switch to bezier, I assume the array doesnt work with a bezier curve so the plugin breaks and crashes the daw. This also happens if you change the number of points to a low number when bezier is selected. I have only tried this in FL Studio but I assume the issue is consistent across daws.

**Comment by alcomposer** [comment]
Hello.

Thank you for logging this issue. I am unable to replicate this behavior, can you please provide:
* DAW version
* plugdata version
* OS

**Comment by KallynMusic** [comment]
I tried this again and it still happens. If you try to move the number of
points for the bezier curve to 1, it crashes the daw. I think it would
probably be smart to cap it at 2 or 3 automatically when using the bezier
mode.

Daw version: 24.1.4225
plugdata version: 0.54.1
OS: Windows

The issue occurs on both the fx and generator version of the plugin.

**Comment by timothyschoen** [comment]
Sounds like you're using plugdata v0.8.3 (based on Pd 0.54.1), I think this bug should be fixed if you download one of the nightly builds. At least, it doesn't happen for me anymore :)

You can get the nightly builds here, at the bottom of the page: https://plugdata.org/download.html
