### ISSUE TITLE
knob object - range not invertable

### ISSUE THREAD

**Issue by jayrope** [plugdata-team/plugdata#1731]
I guess this is a feature request.

When replacing [hsl] with [knob] objects it becomes obvious, that
- i can't inverse minimum and maximum (as possible in hsl)

The lack of such feature needs me to me rewrite parts of a vanilla patch often. 
Min-max inversion comes in handy very often in order to save on further objects needed.

Thank you for all you do.

@timothyschoen

**Comment by dromer** [comment]
With "invertable" you mean setting the minimum and maximum values to say `127-0` instead of the default `0-127`?

I indeed see the min/max values reset to to the other one and they are unable to "cross over" to have minimum be higher than maximum.

When I try this in vanilla this error happens:
```
can't read "::dialog_iemgui::var_width(gfxstub559ed441bcf0)": no such element in array
can't read "::dialog_iemgui::var_width(gfxstub559ed441bcf0)": no such element in array
    while executing
"clip $::dialog_iemgui::var_width($vid) $::dialog_iemgui::var_minwidth($vid)"
    (procedure "::dialog_iemgui::clip_dim" line 4)
    invoked from within
"::dialog_iemgui::clip_dim $mytoplevel"
    (procedure "::dialog_iemgui::apply" line 4)
    invoked from within
"::dialog_iemgui::apply $mytoplevel"
    (procedure "dialog_iemgui::ok" line 2)
    invoked from within
"dialog_iemgui::ok .gfxstub559ed441bcf0"
    (command bound to event)
```

**Comment by jayrope** [comment]
@dromer @alcomposer Thanks for looking into this. I can't follow this up in Vanilla, as a [knob] object doesn't exist there, and 0.55.0 is unable to load the else library via deken for me on macos 13.6.7

**Comment by alcomposer** [comment]
I had a quick look, and yes we need to deal with this correctly. 

IIRC slider does this correctly now, but knob is a bit harder on our end. 

We will 100% get this working at some point!

**Comment by porres** [comment]
>  knob is a bit harder on our end.

why is that? I see [knob] is the most problematic and less compatible object in ELSE, with many issues listed in https://github.com/plugdata-team/plugdata/issues/901 and more not yet listed, and also https://github.com/plugdata-team/plugdata/issues/1111

Can we add this and the other issue into the list provided at https://github.com/plugdata-team/plugdata/issues/901 and then we can just close these issues and refer to them in this global issue with many tasks?

I will revise this global issue and do this, but I can't close these issues.

**Comment by porres** [comment]
I am closing this as it is listed in https://github.com/plugdata-team/plugdata/issues/901 though we can still use this issue for discussion

**Comment by timothyschoen** [comment]
This issue is also already fixed on nightly!

**Comment by porres** [comment]
awesome, thanks
