### ISSUE TITLE
Loading Audio Sample Files into Soundfiler?

### ISSUE THREAD

**Issue by nstarke** [plugdata-team/plugdata#1739]
forgive me if this is a dumb question, but I don't see a `read` object in Plugdata.  I've checked on iOS and Ubuntu 24.04.  

is there a way in iOS to load samples from the file library?  If so, how does that work?  If I can get some input, I'm happy to submit a pull request to the documentation.  Thanks for your help.

**Comment by timothyschoen** [comment]
Hi! There are some problems currently with the iOS version not being able to read resource files. You might have better luck if you place .wav files in one of plugdata's global search paths, like "plugdata/Abstractions" in your Documents folder. These problems will be resolved next version!

Unfortunately it seems like [soundfiler] doesn't look for files in the search path. So perhaps you have to pass in the full path, [openpanel] could be useful for that. Good luck!

**Comment by porres** [comment]
> Unfortunately it seems like [soundfiler] doesn't look for files in the search path

but it should, right?

**Comment by timothyschoen** [comment]
> > Unfortunately it seems like [soundfiler] doesn't look for files in the search path
> 
> but it should, right?

Oh, nvm, I was wrong about that. It does look in the search path.

Also, this is fixed in the upcoming version :)
