### ISSUE TITLE
Add object implementations for all ELSE objects

### ISSUE THREAD

**Issue by timothyschoen** [plugdata-team/plugdata#174]
The ones that are missing are: 
- [x] [button] (0.6.1)
- [x] [oscope~]. (0.6.2)
- [x] [function] (0.6.2)
- [x] [bicoeff] (0.7.0)
- [x] [colors] (v0.7.1)
- [x] [messbox] (0.7.0)
- [x] [note] (0.7.1)
- [x] [click] (0.7.1)
- [x] [pic] (0.7.1)
- [x] [properties] (0.8.0)
- [x] [keycode] (0.8.1)
- [x] [openfile] (0.8.1)
- [x] [canvas.bounds] (0.8.1)
- [x] [cyclone/mousestate] (0.8.1) (this one also appears to be pretty broken in pd-vanilla)

Need to be checked again:
- [x] [canvas.active] (0.6.2)
- [x] [canvas.mouse] (0.6.2)
- [x] [canvas.vis] (0.6.2)
- [x] [canvas.zoom] (0.6.2)
- [x] [canvas.edit] (0.6.2)

Numbers indicate the versions that I'm planning to implement them at.

**Comment by charlesneimog** [comment]
Pic does not work on Windows!

``error opening file 'tklogo.gif'``

...

**Comment by charlesneimog** [comment]
I **believe** that is because the backslash and forward slash in the pathname of the pic.

**Comment by porres** [comment]
yeah, I was just about to say canvas.mouse is not working well

**Comment by timothyschoen** [comment]
What's wrong with [canvas.mouse]? I think the y-axis is also inverted there?

**Comment by porres** [comment]
seems weirder than that, but yeah, output is wrong and you had it in your list already

**Comment by tomara-x** [comment]
[canvas.bounds] also doesn't work

**Comment by porres** [comment]
ok, add else/click to the list :) but note that also click functions from other objects are not working, see https://github.com/plugdata-team/plugdata/issues/635

**Comment by porres** [comment]
add also [else/properties] to the list

**Comment by porres** [comment]
canvas.setname doesn't seem to be working either and seems crazy but [namecanvas] isn't either, which will force me to open a new issue.

**Comment by porres** [comment]
at this point I would go ahead and list all "canvas.*" objects into the list to check

**Comment by porres** [comment]
the 'pick' message to [colors] is not working (so is not the clicking)

**Comment by porres** [comment]
add [keycode] to the list :)

**Comment by porres** [comment]
openfile doesn't seems to work with the -h flag yet, is it actuallt ready or not"

**Comment by timothyschoen** [comment]
Added keycode implementation now, looks like we're basically done!

I'll check keycode some more, then hopefully close this issue (meaning pretty much complete ELSE support!)

**Comment by timothyschoen** [comment]
I've tested keycode on every OS, seems to work perfectly! Let's goooo

**Comment by porres** [comment]
Does [cyclone/mousestate] really appear to be pretty broken in pd-vanilla?
