### ISSUE TITLE
'classic theme' issues

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#1741]
This theme can't show me the item I am selecting from the dropdown menu, it ends up showing a black bar and we can't read what it covers (check screenshot below, the black bar is on top).

<img width="157" alt="Screenshot 2024-07-09 at 13 08 30" src="https://github.com/user-attachments/assets/af974f70-8d5f-4bba-9408-655e32659f85">

**Comment by porres** [comment]
I can't see the black bar because the background of my github is also black, but if you save the picture you'll see what I mean, I'm selecting above "Compile mode" but it can't be shown

**Comment by timothyschoen** [comment]
Fixed by @tomara-x!

**Comment by porres** [comment]
still finding this in the current nightly build...

**Comment by tomara-x** [comment]
plugdata is still reading the old themes from the documents folder. go to settings and reset the themes to fix this
