### ISSUE TITLE
Right mouse button registers as left for menus and landing page

### ISSUE THREAD

**Issue by dromer** [plugdata-team/plugdata#1752]
Not sure if intentional, but both left and right mouse clicks can be used for interacting with the menu or the landing page objects.

I would expect this behavior to be handled by the OS/desktop and plugdata to simply follow the environment rules (left or right handedness)

**Comment by timothyschoen** [comment]
Mostly fixed with 035126804. Might be some cases where it still happens, like default JUCE buttons, but it's mostly fixed.

> I would expect this behavior to be handled by the OS/desktop

Unfortunately it's not. We need to manually check if it's the left mouse button everywhere

**Comment by dromer** [comment]
Hmm, so we can't detect if a user has reversed their mouse buttons?

This seems to solve the case for the main window (opening previous patches).


Only edge-case for me is `alt+rmb` for resizing, this will still open help dialogs on patches and such.
This is already being tracked here: https://github.com/plugdata-team/plugdata/issues/1751
