### ISSUE TITLE
Include pdvjtools external

### ISSUE THREAD

**Issue by hellocatfood** [plugdata-team/plugdata#1759]
Can the pdvjtools be updated and included in plugdata? It hasn't been updated in a very long time but could be a useful set of tools for making visual art in pd. Source code is here: https://sourceforge.net/p/pure-data/svn/HEAD/tree/trunk/externals/pdvjtools/

Original source code link:
https://web.archive.org/web/20091006101841/http://artefacte.org/pd/
https://web.archive.org/web/20090729211010/http://hangar.org/wikis/lab/doku.php?id=start:puredata_pdvjtools

A presentation about pdvjtools

https://archive.org/details/Piksel-piksel_pdvjtools412-2

**Comment by dromer** [comment]
Doubtful. On the one hand this hasn't been supported in about a decade. Next to that it seems to rely on quite some other externals that may not be included (yet).

Of course not saying it isn't cool, but very unlikely to be included without some proper support from the developers.

**Comment by timothyschoen** [comment]
This looks cool, but we're not looking to include more externals at the moment. And I'd also rather not include externals that are not actively maintained anymore.
