### ISSUE TITLE
crash with 0.9.0 macOS 

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#1765]
Hi, on my m3 macbook air I'm getting pretty bad crashes.

One way to reproduce it.

- create a [resonant~] object
- go to its help file
- open the first [pd resonance] subpatch
- close the help file patch
- BOOOOM

**Comment by porres** [comment]
If I close the subpatch before closing the help file patch, then it's ok... so maybe the issue is closing patches with subpatches opened...

**Comment by timothyschoen** [comment]
Thanks, fixed on nightly now
