### ISSUE TITLE
Windows Defender interrupts download due to a virus detected - Windows 11

### ISSUE THREAD

**Issue by sidec** [plugdata-team/plugdata#177]
Windows Defender interrupts download due to an alleged virus. As a result, it is not possible to download the latest release neither for Win64 nor Win32.
System: Windows 11 for x64-based Systems with update KB5016691 (2022-08)

**Comment by timothyschoen** [comment]
I was recently made aware of this. Probably caused by the new installer for Windows, which is necessary to get externals to run on Windows. Very annoying, looks like I'm gonna have to pay Microsoft money to get my app verified.

The only solution right now is to disable defender temporarily. I'll see if I can find a permanent solution.

**Comment by sidec** [comment]
Is it possible then to have as a temp solution an archive with only vst3 for Windows? If I understand it correctly, the problem is with an installer of a standalone PlugData?

**Comment by timothyschoen** [comment]
I'll do that!

**Comment by timothyschoen** [comment]
I'm working on a new version which will probably be out in 2/3 days, I'll also upload a zip file for Windows for that.

**Comment by sidec** [comment]
Is this issue caused by no signing the app as described in this [stackoverflow thread](https://stackoverflow.com/questions/252226/signing-a-windows-exe-file)?

**Comment by timothyschoen** [comment]
Yes! Thanks for linking that resource, that'll help when I have time to fix this.

**Comment by timothyschoen** [comment]
I see there are free certificates for open-source projects!

**Comment by timothyschoen** [comment]
I'm now using a better installer in the latest builds, so this might be fixed

**Comment by timothyschoen** [comment]
I think Windows Defender likes my new installer better. Someday I'll properly codesign everything for Windows!
