### ISSUE TITLE
0.90 and Previous. Gui elements (Numboxes, resizing to defaul of 17 instead of size specified by user.

### ISSUE THREAD

**Issue by pereshaped** [plugdata-team/plugdata#1774]
Numboxes insist on being 18 wide. Cannot display numbers greater than 1000s because it hides digits.

I noticed this happens to other GUI elements too, in that that they get randomly resized. At the moment.

For maximum compatibility with Vanilla make them digit widths (as in Vanilla) rather than pixels?

Thank you

**Comment by pereshaped** [comment]
Used text editor to edit the resized GUI elements, so there is a workaround (albeit long one). Interestingly the text files show the numboxes in widths but the PlugData environ properties shows it as pixels. I can see why they would be both convenient. One to specify the number of digits, the other to accomodate to the size of other GUI elements. Is it possible to include both in properties or would this be a onerous task?
![Screen Shot 2024-07-27 at 11 55 22](https://github.com/user-attachments/assets/62a97ccf-259a-4ff0-a7d7-771722dfa8f3)

**Comment by pereshaped** [comment]
In fact this is worse than I thought. Plug Data is overriding the inputted dimensions once saved. Either Plug Data ignores the changes to the number box dimensions entered when saving or else it ressets to the default number boxes of 18 pixels wide.
Here is a demo of it doing it.



https://github.com/user-attachments/assets/3c52bdfe-dd86-474d-ac1c-9c83bac40505

**Comment by jayrope** [comment]
+1 Having the same issue here, in both Mac and Mac-Legacy versions.

**Comment by timothyschoen** [comment]
I think this should be fixed now too, since 8d88defd5?
