### ISSUE TITLE
Bug: right canvas connections draw on left

### ISSUE THREAD

**Issue by dromer** [plugdata-team/plugdata#1787]
Since recent update (8750336aadc0415d9835d1ca0f1af9705aee58e9)

![2024-08-09_01-01](https://github.com/user-attachments/assets/10639ffb-ff33-497b-9aa1-ddaa337dc3a2)

**Comment by dromer** [comment]
I saw some nanovg changes in the log, but this is still the case in e77369219364090b689696dd30e42c16bbe8a847

**Comment by timothyschoen** [comment]
Fixed it!

**Comment by dromer** [comment]
@timothyschoen something got unfixed. Now I see iolets on the left canvas:

![2024-08-22_19-49](https://github.com/user-attachments/assets/492ddd4b-a14f-42df-93f8-b64a2c9025e7)

**Comment by timothyschoen** [comment]
oh yep, fix is coming

**Comment by timothyschoen** [comment]
Fixed it!
