### ISSUE TITLE
v0.9 and v0.9.1 crashing on Windows 11 

### ISSUE THREAD

**Issue by shakfu** [plugdata-team/plugdata#1793]
I have a strange case where plugdata v8.3 works fine, but v9 and the recent v9.1 open seemingly. ok, but then crash half a second or so after opening. I'm on Windows 11 pro. I'm not asserting that this is the case on all windows 11 machines, just mine.

Is there a way to run plugdata in debug mode to understand precisely what is causing the crash?

**Comment by FedeRepic** [comment]
Same here. Appreciate the help.

**Comment by timothyschoen** [comment]
I'd assume this is related to our GPU renderer. Does you graphics card support OpenGL 3?

**Comment by shakfu** [comment]
I'm not sure it does (see below).

Operating System: Windows 11 Pro 64-bit (10.0, Build 22631) (22621.ni_release.220506-1250)
Processor: Intel(R) Celeron(R) N5105 @ 2.00GHz (4 CPUs), ~2.0GHz
Memory: 8192MB RAM

I've attached a GPU-Z analysis as a screenshot:

![gpu-z-screenshot](https://github.com/user-attachments/assets/3da93202-2066-4ffe-97f5-53c626b76bc8)

**Comment by timothyschoen** [comment]
It looks like you're missing GPU drivers, since your processor's integrated graphics do support OpenGL 3, but it's not showing up here. Also, "Microsoft Basic Display Adapter" seems to suggest that.

I think you might find that here: https://www.intel.com/content/www/us/en/support/products/80939/graphics.html

**Comment by shakfu** [comment]
@timothyschoen Thanks for your help.

I tried to use the [Intel Driver & Support Assistant](https://www.intel.com/content/www/us/en/support/detect.html), but it gives an error when clicked on.

Basically, it looks like I'm running a generic driver provided by Microsoft, a dedicated Intel driver may work (if I can get one).

No biggie. I will see what can be done.

**Comment by shakfu** [comment]
Ok, I fixed it after installing the latest [Intel Graphics Driver](https://www.intel.com/content/www/us/en/download/776137/intel-7th-10th-gen-processor-graphics-windows.html?wapkw=gfx_win_101%202128%20exe): the installer file is gfx_win_101.2128.exe

This worked in my case, I'm not suggesting it will work for everyone with the same issue. they should check the intel driver site.

Thanks for your help @timothyschoen !!

**Comment by dromer** [comment]
* v0.9

(1.0 isn't even out yet, so 9.0 isn't out either ;) )

**Comment by shakfu** [comment]
I will close this as resolved for my case.
