### ISSUE TITLE
0.9.1 Crashing on MacOS Big Sur 11.7.10

### ISSUE THREAD

**Issue by jastro-dev** [plugdata-team/plugdata#1800]
Getting crashes when trying to open up plugdata on both standalone and vst3. This only started with the newest 0.9.1 version. 

"*** Terminating app due to uncaught exception 'CAMetalLayerInvalid', reason: 'invalid pixel format 70'
terminating with uncaught exception of type NSException
abort() called"

**Comment by timothyschoen** [comment]
Hi, 

There is a small mistake in the Metal code that prevents it from working on some Intel macs. For now, you can use the 'macOS Legacy' version to work around it. Hopefully soon a fix will be on nightly too

**Comment by wrkdat** [comment]
i think he doesn't use a intel one. it's the same problem a lot of people have. anyone here can fix this??

**Comment by alcomposer** [comment]
Tim is the developer that will fix this! I'm sure that patch is coming soon.

**Comment by wrkdat** [comment]
ok, looking forward and kudos to Tim for making it happen!

**Comment by timothyschoen** [comment]
The Metal version should work on Intel again!
