### ISSUE TITLE
0.9.1 export binary dpf hangs on ubuntustudio 24.04

### ISSUE THREAD

**Issue by sensorium** [plugdata-team/plugdata#1807]
Hi,
on a fresh install of ubuntustudio 24.04, the first time I tried to export a compiled patch using dpf, the toolchain window seemed to freeze after downloading.  Since then, no toolchain window appears and the program returns immediately, exporting nothing.  

Is there a way to make sure the toolchain has installed properly?  I tried purging and reinstalling plugdata, but nothing changed and the toolchain was not reinstalled when attempting to export again.

Thanks for any help...

**Comment by dromer** [comment]
Try deleting the `Documents/plugdata/Toolchain` directory to force a re-install of the toolchain.

**Comment by sensorium** [comment]
Thankyou!  It took a couple more tries before I finally noticed an icon in the desktop taskbar, which when opened showed a request for permission to install the download.  Maybe the window initially opens hidden behind the plugdata windows?  When plugdata is moved, the Toolchain window disappears (closes?), so perhaps the permissions window is first hidden, then closed before being seen... (on this platform)?

**Comment by dromer** [comment]
In the latest nightly the compile dialog is more integrated and is not a separate window, but if you click outside of it it will still close.

Does the toolchain work for you now? Then you can close these issues (as they are not really issues but "user error" in a way)

**Comment by sensorium** [comment]
Yes, the toolchain works here now.  It's great!  Thanks for your help and patience.
