### ISSUE TITLE
autocomplete issues

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#1808]
using nigthly

This is the intuitive workflow that I'm hoping for but it's not happening

Say I want to create a [keyboard] object, I start typing "key" and first option that comes is obvioulsy the [key] object, but the second is "keyboard". So I use the arrow down to select this second entry in the suggested autocomplete menu and I hit "Enter"/"Return" hoping to create the object, but what I get is the [key] object instead.

anyway, I don't know what is the expected way to use this, but it seems we have a bug

**Comment by timothyschoen** [comment]
Should be fixed with d04d35b58f3ef74e87faba73b5312f408c326d10!

Still need to test if this causes other issues, but so far it's looking good.
