### ISSUE TITLE
Gem / ofelia compatibility

### ISSUE THREAD

**Issue by 60-hz** [plugdata-team/plugdata#182]
When I copy gem or ofelia libraries in Deken folder of Plug Data, I can load both libraries without problems. (using Rosetta compatibility with PlugData on my M1 macbook)

I can even load objects and create a window with both libraries. But as soon as I render a frame, both freeze and crash PlugData.

I saw gem/ofelia before on the roadmap but not anymore, so I guess it's not a high priority... But if it is possible I might use Plug Data during my class which would be nice as pedagogic tool.

**Comment by timothyschoen** [comment]
I've noticed that too, honestly it's a miracle that creating a window works. I'll re-add it to the list, it would be very nice to get that working. I'm not sure how much effort it will be, in the best case scenario it's a quick patch, but it's also possible that something in JUCE conflicts with Gem/Ofelia, in which case it might be impossible/very difficult.

Another obstacle is that it crashes somewhere inside the Gem code, so I'll have to compile Gem along with PlugData to find out what's going on.

**Comment by 60-hz** [comment]
Ok, I keep my finger crossed then!

**Comment by timothyschoen** [comment]
Gem is currently being included!

There are still some small issues to work out, but mostly it works

**Comment by jamshark70** [comment]
Hi, glad to see this, but I haven't been able to make it work yet.

If Gem is included, I haven't found a folder for it -- neither Extra nor Externals contains it.

So I created a symlink under Externals to /usr/local/lib/pd/extra/Gem/.

[declare -lib Gem] doesn't do anything -- despite ~/Documents/plugdata/Externals being in the path preferences, somehow it doesn't find ~/Documents/plugdata/Externals/Gem.

[declare -lib /home/xxx/Documents/plugdata/Externals/Gem] does load the library.

But, "create, 1" to a [gemwin] causes, at different times, without any clear pattern I can discern, a/ Pd GUI objects to be unresponsive (always); b/ the patch display to flicker; c/ the patch display to disappear. This was not even running any drawing objects. The Gem window appeared, but the only thing I could do in the PlugData window was to close the patch, after which PlugData crashed.

(I can do what I need to do in plain Pd, but I am *so over* the tcl/tk UI... was really hoping to use PlugData for this.)

Ubuntu Studio 22.04, XFCE 4.something, PlugData v0.9.1.

**Comment by timothyschoen** [comment]
Hi!

Gem was temporarily disabled because it has some issues. It came back on recent nightly builds.

It mostly works, but there can be some glitches when you use Gem framebuffers
