### ISSUE TITLE
Crash in REAPER when hitting escape during object creation

### ISSUE THREAD

**Issue by williamfields** [plugdata-team/plugdata#1821]
To reproduce:
1. Open REAPER
2. Add plugdata or plugdatafx to a track
3. Click "New Patch"
4. Double-click to create new object with blinking text cursor
5. Hit the "Escape" key

REAPER crashes immediately.

I am running Plugdata 0.9.1 in REAPER 7.21 on Windows 10.

Details from Event Viewer:

Log Name:      Application
Source:        Application Error
Date:          8/24/2024 5:53:06 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      LAPTOP-Q8L5KDM9
Description:
Faulting application name: reaper.exe, version: 7.2.1.0, time stamp: 0x66ca0b52
Faulting module name: plugdata.vst3, version: 0.9.1.0, time stamp: 0x66c3422a
Exception code: 0xc0000005
Fault offset: 0x00000000002b7c36
Faulting process id: 0x26fc
Faulting application start time: 0x01daf66ff607f194
Faulting application path: C:\Program Files\REAPER (x64)\reaper.exe
Faulting module path: C:\Program Files\Common Files\VST3\PlugData.vst3\Contents\x86_64-win\plugdata.vst3
Report Id: 9475057b-4060-4b24-96ad-adb3de9c4f78
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-08-24T21:53:06.3321200Z" />
    <EventRecordID>72955</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>LAPTOP-Q8L5KDM9</Computer>
    <Security />
  </System>
  <EventData>
    <Data>reaper.exe</Data>
    <Data>7.2.1.0</Data>
    <Data>66ca0b52</Data>
    <Data>plugdata.vst3</Data>
    <Data>0.9.1.0</Data>
    <Data>66c3422a</Data>
    <Data>c0000005</Data>
    <Data>00000000002b7c36</Data>
    <Data>26fc</Data>
    <Data>01daf66ff607f194</Data>
    <Data>C:\Program Files\REAPER (x64)\reaper.exe</Data>
    <Data>C:\Program Files\Common Files\VST3\PlugData.vst3\Contents\x86_64-win\plugdata.vst3</Data>
    <Data>9475057b-4060-4b24-96ad-adb3de9c4f78</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by williamfields** [comment]
I just tested the standalone version of Plugdata, and it is also affected by this problem.

**Comment by timothyschoen** [comment]
Thanks for reporting!

Should be fixed with 905765061
