### ISSUE TITLE
Crashes on M1 Big Sur 11.5.2 / Ableton and Bitwig

### ISSUE THREAD

**Issue by wrkdat** [plugdata-team/plugdata#1823]
hence the title, couldn't get AU / VST / VST3 and CLAP to work, always the " A serious Problem, will shut down immediately" warning occurs.

I installed and used it on my Mac around 4 months ago with no problems!

Please help! 
thanks in advance! 🖤

**Comment by timothyschoen** [comment]
Hi!

When does this crash happen? On startup, or when using a specific patch?

**Comment by wrkdat** [comment]
if you need any more info please let me know. again i can't install universal AND legacy, both do not work (anymore)

tested on two Version of Bitwig and Ableton Live 10,11,12 

thanks in advance!

**Comment by lockee951** [comment]
Hi,

brandnew to Plugsdata and Github. Just for the Info

I got the same crash on trying to load Plugdata in Bitwig 5.2.1 on Mac M1 with Vst3 and Clap

regards Laurent

**Comment by wrkdat** [comment]
HELP HELP HELP

**Comment by lockee951** [comment]
> HELP HELP HELP

👀

**Comment by lockee951** [comment]
I have tried it with the
"Merge pull request #1825 from alcomposer/button-fixes #6025" built. The same crash with both Clap and Vst3.

**Comment by timothyschoen** [comment]
Hi! I'll take a look at the as soon as I can! It's strange because I'm running on a 2020 M1 MBP myself, and I don't have this issue :(

**Comment by lockee951** [comment]
Hi, yes this sounds a bit strange. I'am running a MBP M1 (2022) as well. I will tty to install an older version and test if this work and report back.

Regards and thank you for looking at it 😌

**Comment by timothyschoen** [comment]
For anyone who has there crashes, can you find a crash report?

On macOS, you might be able to find them in the "Console" application. Select "Crash Reports" in the sidepanel, and then look for processes that belong to Logic, Bitwig or Ableton.

For Logic, it will probably be called "AUHostingServiceXPC_Arrow". For Ableton, just "ableton". Not sure about Bitwig.

But if I had some crash reports, that would help a lot!

**Comment by lockee951** [comment]
I am quite new to Mac... i will try later to find this "console" app and the belobging file from Bitwig 🤞

**Comment by offchristianamr** [comment]
Having the same issue — instant crash as soon as I attempt to open Plugdata in Ableton Live 12 ;(
The plugin window is visible for a fraction of a second and then the program closes. For some reason, no crash reports are appearing in Console; I don't suppose the crash report generated by Ableton would be of any help?

**Comment by vb-steph** [comment]
I'm having these same crashes with the VST3, AU, and Standalone versions. I tested this in Live 10.1.43, Logic Pro 10.7.4, and FL Studio 21.2.1.3430 running on an M1 MacBook Pro with macOS Monterey version 12.2.1. I sent the crash report that was generated from the Standalone version crash, hopefully this helps.

**Comment by timothyschoen** [comment]
I think I see the pattern now, it seems all these crashes happen on versions of macOS that are older than what I'm running here.

Could anyone try the latest nightly build (https://glyphpress.com/plugdata/plugdata-macOS-Universal.pkg) and confirm if it's fixed or not?

**Comment by offchristianamr** [comment]
Still crashing right away on the nightly build, unfortunately. Thanks for following up on this.

**Comment by lockee951** [comment]
Following from holidays. will try it as well when at home (Monte rey)

**Comment by timothyschoen** [comment]
> Still crashing right away on the nightly build, unfortunately. Tried out v0.9.0 and it does not crash. Thanks for following up on this.

Does the standalone also crash instantly for you? Or only the plugin in Ableton?

**Comment by timothyschoen** [comment]
Just installed macOS Monterey in a virtual machine, I can reproduce the crash there!

**Comment by offchristianamr** [comment]
I tried out Nightly Build 164b1c6d4 today and it is no longer crashing on startup on Monterey 12.7.2. Thank you!!

**Comment by vb-steph** [comment]
I am still getting the same crash on startup issue on 164b1c6. I updated my OS to Monterey 12.7.6 and the issue still remains. 
- macOS Universal download commit 164b1c6
- tested VST 3, AU, Standalone plugin
- M1 MacBook Pro on Monterey 12.7.6
- happens on 3 different DAWs: Logic 10.7.4, Ableton Live 10.1.43, FL Studio 24.1.1.3936
- the crash happens when the plugin is clicked on and the plugin window would normally open, not when the plugin is initially loaded in. For example, I can load the plugin in the bottom bar in Ableton but once I click the button to open the plugin window, it crashes.

**Comment by timothyschoen** [comment]
> I am still getting the same crash on startup issue on [164b1c6](https://github.com/plugdata-team/plugdata/commit/164b1c6d4449658aa081bcbf9b6f8b0a069ce5bb). I updated my OS to Monterey 12.7.6 and the issue still remains.
> 
>     * macOS Universal download commit [164b1c6](https://github.com/plugdata-team/plugdata/commit/164b1c6d4449658aa081bcbf9b6f8b0a069ce5bb)
> 
>     * tested VST 3, AU, Standalone plugin
> 
>     * M1 MacBook Pro on Monterey 12.7.6
> 
>     * happens on 3 different DAWs: Logic 10.7.4, Ableton Live 10.1.43, FL Studio 24.1.1.3936
> 
>     * the crash happens when the plugin is clicked on and the plugin window would normally open, not when the plugin is initially loaded in. For example, I can load the plugin in the bottom bar in Ableton but once I click the button to open the plugin window, it crashes.

Could you send me the crash report? When if crashes, click "send report", and paste the content of the error message over here. Thanks!

**Comment by vb-steph** [comment]
I just downloaded and tested in the standalone and AU versions - the plugin is working again, this issue has been resolved for me. Thanks!
