### ISSUE TITLE
unexpected result when inserting an escaped space in list box

### ISSUE THREAD

**Issue by ben-wes** [plugdata-team/plugdata#1827]
when entering `bla\ bla` in a list box, the expected outcome (according to Pd vanilla) would be a `symbol bla\ bla`.

in case of plugdata, it is `list bla\\ bla` (where the backslash gets escaped instead of the space)

just seeing that in case of a symbol box, the result is `symbol bla\\\ bla`, where both characters get escaped. in that case, i can achieve `symbol bla\ bla` by just entering `bla bla`. but the list box in the current version doesn't allow entering symbols including spaces, i guess.

tested with current nightly [a310336](https://github.com/plugdata-team/plugdata/commits/a3103363c483f3af2277bf102c5aaaab95e76d9f)

**Comment by timothyschoen** [comment]
Should be fixed with 8aaba4064, thanks for reporting!
