### ISSUE TITLE
May need an 0.9.2 for GUI badfloat fix

### ISSUE THREAD

**Issue by jamshark70** [plugdata-team/plugdata#1829]
https://github.com/pure-data/pure-data/pull/2260 fixes a bug with sliders and vu meters, where they can no longer be programmatically set to 0. Unfortunately the bug does affect plugdata... so perhaps there's a need for a bugfix release.

**Comment by timothyschoen** [comment]
I merged in the latest Pd changes, so this should be fixed on nightly.

We have some more v0.9.2 changes that aren't ready yet, so it's probably take about a month to get a new release out. In the meantime, you can use the nightly builds if you need to work around this bug
