### ISSUE TITLE
Multiple Midi Devices Order Issue

### ISSUE THREAD

**Issue by pereshaped** [plugdata-team/plugdata#1838]
version 0.91 on Osx 10.13, 12 and 13

In Vanilla it's easy to set the order of MIDI devices (Ports) by selecting the order they are in in the "Midi Settings".

There is no way to do this in Plug Data?

I have ported a Vanilla patch that uses two different hardware controllers (Korg NanoKontrol on Port 1 and 12Step on Port 2 (17)) Loading the same patch into Plugdata has reversed the port order (Korg on port 2(17) and 12astep on port 1) so that the CC ma[ppings for each port make no sense and are unusable.

I have tried pluging the hardware devices in different orders but plug data has decided it will decide what hardware is on what port no matter what I do.

Is there something in the system I can edit to change this by hand?

**Comment by pereshaped** [comment]
This is in standalone by the way.

**Comment by pereshaped** [comment]
Ive got around it at the moment by changing the MIDI note range on the 12Step controller and changing my code to allow Omni operation from the ctlin object and just letting plug data decide the ports but it would be great if we were able to choose the ports, if possible.

**Comment by timothyschoen** [comment]
On the latest nightly builds, you can assign each MIDI device to a port. This is more flexible than what Pd offers, as you can also choose to route multiple devices to the same port. Hope it helps!

**Comment by pereshaped** [comment]
thats great news. Thank you for doing that, it is very much apreciated.

**Comment by dromer** [comment]
> This is more flexible than what Pd offers

That depends on your system. On Linux with ALSA Pd is still more flexible as there the OS can route any MIDI port to any other MIDI port. (I explicitly don't say "device" here because you can route software ports as well).

**Comment by timothyschoen** [comment]
> I needed both the Korg nanoKontrol and 12-Step ports to talk to the same midiinput. Totally different physical controls both serving a purpose in the patch with a single midi input. You can see this in operation on the Organelle video.

I think that's what I described right? You want to send 2 midi inputs to the same port in Pd, so what plugdata does allows for that:

<img width="632" alt="Screenshot 2024-12-01 at 15 54 07" src="https://github.com/user-attachments/assets/db607e42-d75a-4079-983f-a0debc837515">

Whereas with pd-vanilla, you cannot do this:

<img width="361" alt="Screenshot 2024-12-01 at 15 54 43" src="https://github.com/user-attachments/assets/2a9f97a0-1554-4c62-91f6-b9a4e25a050b">


The point is, pure-data allows you to do this instead:


<img width="361" alt="Screenshot 2024-12-01 at 15 55 10" src="https://github.com/user-attachments/assets/9518c818-7670-49ed-a7d9-92af9ede0977">

Now, both port 1 and 2 receive from the same single device. So port 1 and 2 become interchangable, you might as well just use port 1 everywhere or port 2 everywhere.

**Comment by pereshaped** [comment]
Spot on! thank you!

**Comment by pereshaped** [comment]
What Dromer says about Iinux is true though, aconnect is so flexible.
