### ISSUE TITLE
Plug Data 0.91 still resizing number boxes after saves

### ISSUE THREAD

**Issue by pereshaped** [plugdata-team/plugdata#1845]
Plug Data 0.91. Osx High Sierra, Ventura.

Numboxes are still being resized automatically after saving

This is what Im editing and saving

![Screen Shot 2024-09-07 at 12 29 31](https://github.com/user-attachments/assets/cf75c3e9-6ee2-4c3b-9ea3-3fbe37f41993)

and this is what is loading

![Screen Shot 2024-09-07 at 12 28 30](https://github.com/user-attachments/assets/99a9c0bf-d7ba-47da-8ad1-16c31c8bf766)

I can edit it in a text editor and saving that and then it honors the edit, but that is too old skool lol.

**Comment by timothyschoen** [comment]
Hi!

I tried to fix it with 8d88defd5

This also makes it behave the same as pd-vanilla, where label size controls the number text size.

**Comment by pereshaped** [comment]
Ok, thank Tim. What I have been doing is taking it to a text editor and just changing the size there and that then sticks it. Even in vanilla there are some inconsistencies with regards nbx sizes, which can now and again throw a slightly different size, but at least its a fix now. Thanks for that.
