### ISSUE TITLE
Does the 'fuzzysearchdatabase' library seem to no longer exist?

### ISSUE THREAD

**Issue by crisqyxw** [plugdata-team/plugdata#1848]
I tried to build Plugdata but encountered an error " can't find the header file ". I found that the directory 'fuzzysearchdatabase' that was pulled was empty. I am also unable to access this submodule on Github and it shows ' Page Not Found '. But I found it on BitBucket（ https://bitbucket.org/j_norberg/fuzzysearchdatabasehttps://bitbucket.org/j_norberg/fuzzysearchdatabase ）, successfully built after replacing the original directory. 

I don't think this is my problem, but rather that this directory does not exist. Perhaps there is a way to fix this issue?

**Comment by dromer** [comment]
How did you clone the repository?

**Comment by crisqyxw** [comment]
Yes, I can manually clone and check it out and find it normally. Perhaps it's an issue with the AUR build script. I will close this issue and apologize for any inconvenience caused.
