### ISSUE TITLE
Feature request: destroy method for param

### ISSUE THREAD

**Issue by DemandDystopia** [plugdata-team/plugdata#1851]
**Description:** parallel to create, a message with destroy/delete/whatever should remove an automation parameter, same as clicking "x" on it in the sidebar

Right now, everything about parameters can be controlled via patch, except deletion

**Use case:** (Semi) Modular patches.

As param works with $, we can easily create patches that load abstractions as needed yet give them individual automatability.

It may be desirable, to delete unneeded automation slots when such an abstraction is unloaded

**Comment by timothyschoen** [comment]
Done with 6182c2ed6!
