### ISSUE TITLE
Unable to drag data structure grahic

### ISSUE THREAD

**Issue by sahver** [plugdata-team/plugdata#1852]
I am building a patch where I use data structures to visually (filledpolygon) represent screens. It works fine in Vanilla where I can drag these screens around in edit mode, but I am unable to change their placement in PlugData.

Is this a known limitation?

PlugData 0.9.1 / Pd vanilla 0.55.1 on MacOS 14.5
[patch.zip](https://github.com/user-attachments/files/17011122/patch.zip)

**Comment by timothyschoen** [comment]
Oh, I didn't know this was a feature!

I can add this. Looks like this only applies to [filledpolygon] etc, but not to [plot]?

**Comment by timothyschoen** [comment]
fb8240426 should help!

**Comment by timothyschoen** [comment]
ce79c4b2b finishes this!

**Comment by sahver** [comment]
Thanks! 

I was now testing it with the latest nightly ([8180617](https://github.com/plugdata-team/plugdata/commits/8180617966fad0383510370a1f5faaa80e8e5442)). It basically works, I did notice a few things though:

(1) When I resize the graphic in view mode then the bounding box retains its original size and I can move it then by clicking within the bounding box without actually clicking on the graphic.
(2) I also have some text within the data structure and that doesn't move along

Here you can see what I mean, the first is PlugData and second PD Vanilla.

![PlugData](https://github.com/user-attachments/assets/93cf1d60-b01f-4a9a-9f0c-9372319dcd06)

![PDVanilla](https://github.com/user-attachments/assets/8f9b0d27-99d5-49ea-9b34-c5e6b76ab6ed)
