### ISSUE TITLE
Go back to last viewed tab when closing another tab (Request)

### ISSUE THREAD

**Issue by tmhglnd** [plugdata-team/plugdata#1864]
Currently, (in 0.9.2), when I open an abstraction, subpatcher or help-file it opens this as an extra tab at the end of the tab list, which is fine. But then when i close this tab (by click `x` or by using `cmd + w`) it shows me the next-to-last tab.

In my workflow I would prefer that when I close a tab PlugData goes back to the tab I had open before that (which in many cases was the patcher I used to open the new tab from). Now it requires me some extra clicks every time, instead of being quick navigating from in-and-out of subpatchers/abstractions.

**Comment by timothyschoen** [comment]
d2be2e9 and d9cc3b4 should fix it!

**Comment by tmhglnd** [comment]
Works great as far as I can tell! Thanks a lot
