### ISSUE TITLE
Don't open in tabs option (Request)

### ISSUE THREAD

**Issue by tmhglnd** [plugdata-team/plugdata#1865]
Can there be an option to not open patches in new tabs? Or am I overlooking the settings and is it already available somewhere?

**Comment by timothyschoen** [comment]
<img width="692" alt="Screenshot 2024-10-07 at 16 24 04" src="https://github.com/user-attachments/assets/174252ac-9707-47c2-bb5c-7e145836454c">

Added it! It works for helpfiles, subpatches and abstractions now, I hope that covers everything?

**Comment by timothyschoen** [comment]
Note that this won't work in the DAW, since the DAW expects one main plugin window

**Comment by tmhglnd** [comment]
Hey! Thanks for giving this feature a thought and adding it. It works! 

>It works for helpfiles, subpatches and abstractions now, I hope that covers everything?

You think it is also possible to open new patchers in a separate window when this feature is enabled?

Some other user feedback:
- When I open an abstraction/help-file I usually use `cmd + w` to close the window again, but this doesn't close the window, it brings me back to the "welcome to plugdata" window. And there is no option to close that with `cmd + w`, only by clicking the X button.
- When follow the steps above to close a window, it seems I lose the ability to work in the previous opened patcher. I first have to open another patcher and then I can edit/click on the other one again. (see gif below)

![ScreenRecording2024-10-07at22 00 47-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/e614bc53-374d-46bb-b471-e7c46c4b154d)

**Comment by timothyschoen** [comment]
> You think it is also possible to open new patchers in a separate window when this feature is enabled?

Yes, but I think it could be counterintuitive if the + button next to the tabbar did that. But we can at least add a keyboard shortcut, so that cmd+t opens a new tab and cmd+n opens a new window? And the "new patch" option in the menu could then also open a new window.


> When I open an abstraction/help-file I usually use cmd + w to close the window again, but this doesn't close the window, it brings me back to the "welcome to plugdata" window. And there is no option to close that with cmd + w, only by clicking the X button.

Hmm yeah... I think it's not useful that it falls back to the welcome screen in here general if there's still other editors open. I think instead, it should close the editor and move another editor window to front? I've implemented this with de8d12215. That also solves the cmd+w issue.


> When follow the steps above to close a window, it seems I lose the ability to work in the previous opened patcher. I first have to open another patcher and then I can edit/click on the other one again. (see gif below)

I can't seem to reproduce that here :(
Not sure why, but I'll look into it some more

**Comment by timothyschoen** [comment]
0d543caee makes it also open a new window if you click New Patch, cmd+N and also the "+" button next to the tabbar (it was easier to implement it that way).

> When follow the steps above to close a window, it seems I lose the ability to work in the previous opened patcher. I first have to open another patcher and then I can edit/click on the other one again. (see gif below)

Since I can't reproduce: does this always happen, or only sometimes? What version of macOS are you on?

**Comment by tmhglnd** [comment]
> Since I can't reproduce: does this always happen, or only sometimes? What version of macOS are you on?

It always happens in the case where I used `cmd + w` to close the patcher window. I'm on MacOS 12.6.

**Comment by timothyschoen** [comment]
Managed to reproduce in a VM running macOS 12

I'll see what I can do about it!

**Comment by timothyschoen** [comment]
I spotted a small issue with how I made the next window grab keyboard focus.

So I hope that's fixed now, but I'm not completely sure.

**Comment by tmhglnd** [comment]
This seems to be fixed now in the nightly! Very nice! The window now closes directly with `cmd + w`, and I can immediately go back to editting the other patcher.

Two points of user-feedback I experience now:
- The windows sometimes open quite partially (or for a big part) outside the range of my screen, depending a bit on where the object is from which I open a help-file or subpatch.
- Similarly as with my request from going back to the previous tab when closing one. Now when I close one window it doesn't go back to the previous window, but the first window I had open.

**Comment by timothyschoen** [comment]
> This seems to be fixed now in the nightly! Very nice! The window now closes directly with `cmd + w`, and I can immediately go back to editting the other patcher.
> 
> Two points of user-feedback I experience now:
> 
>     * The windows sometimes open quite partially (or for a big part) outside the range of my screen, depending a bit on where the object is from which I open a help-file or subpatch.
> 
>     * Similarly as with my request from going back to the previous tab when closing one. Now when I close one window it doesn't go back to the previous window, but the first window I had open.

Both done!

**Comment by tmhglnd** [comment]
Works great!
