### ISSUE TITLE
Can't copy-paste from vanilla Pd to PlugData?

### ISSUE THREAD

**Issue by tmhglnd** [plugdata-team/plugdata#1867]
Is it possible to copy/paste a patch from vanilla Pd to PlugData? For me this does not seem to work. Using PlugData 0.9.2 and Pd 0.55.0. Maybe this is a limitation of vanilla Pd, because when I try to copy-paste something from Pd into a text-editor I also don't see anything pasted. However if I copy from PlugData to a text-editor I do see the patch-description.

**Comment by timothyschoen** [comment]
Yep, this is a something they haven't implemented yet on Pd's side, but I believe they are thinking about adding it.

**Comment by tmhglnd** [comment]
Thanks for the quick reply, and clear! Then we'll just have to wait I guess. For now I'll just save the patch and open it in PlugData when I want to "copy", no big problem.

**Comment by alcomposer** [comment]
Closing the issue as this relates to PD-Vanilla. @timothyschoen copy/paste in plugdata is AMAZING! :-) I also hope Vanilla considers implementing this feature.
