### ISSUE TITLE
How to copy/paste large blocks of the console output?

### ISSUE THREAD

**Issue by jamshark70** [plugdata-team/plugdata#1877]
I see that messages can be individually shift-selected for clipboard copy in the console, but:

1. Click on some message to select it.
2. Shift-click on some message 10-20-30 lines away.

Expected: Selection should be inclusive of all messages in between those two. (UI standard is: Shift-clicking is an inclusive selection, ctrl-clicking is discontinuous.)

Actual: Selection is discontinuous and covers only the two messages clicked.

So there is no practical way to select the entire console contents to copy/paste somewhere else for inspection.

Major hassle for debugging this patch -- ~~I'm gonna have to run my test case in the tcl/tk pd gui now~~ will have to figure out how to hack Pd to print to stdout...?

**Comment by timothyschoen** [comment]
Yeah, good idea. Shift multi selecting and ctrl+a should both be supported. We can also add a "copy console content" option to the menu to copy everything.

**Comment by timothyschoen** [comment]
767cfb1b9 implements both shift to select multiple messages in a row, and ctrl+a to select all!

**Comment by jamshark70** [comment]
Thanks!
