### ISSUE TITLE
Copying Plugdata instances crashes Renoise (and Reaper)

### ISSUE THREAD

**Issue by codecollider** [plugdata-team/plugdata#1880]
Hi, 

Ubuntu 24.04 (Wayland) user here. When trying to copy the plugdataFX VST3 in Renoise or the plugdata instrument in the instrument list Renoise crashes completely. 

Renoise Version: 3.4.4
Plugdata Version: 0.9.1 

Taktik from Renoise wrote the following concerning the crash:

"It’s plugdata that crashes here after collecting its preset data, but this may be a problem with other plugins too, so we should fix this.

Currently, Renoise creates a temporary copy of the plugin in order to load and save the plugin’s preset data to the clipboard. This should generally work, but is also quite a stress test for plugins and thus makes crashes in plugins more likely. I’ll try to avoid this, also to speed up the “copy” process."

He proposed to report it to the plugdata devs. 

Exactly the same problem is present with Reaper. When coyping a track with plugdata on it Reaper crashes. 

In Bitwig it's a bit different. In Bitwig when duplicating a track with plugdata crashes the audio engine only. When activating the engine again, it is possible to copy / paste (= dublicate) a track without any further crashes. 

My system:

Kernel: 6.10.11-2-liquorix-amd64 arch: x86_64 bits: 64
  Desktop: GNOME v: 46.0 Distro: Ubuntu 24.04.1 LTS (Noble Numbat)
Machine:
  Type: Desktop Mobo: ASRock model: B650M PG Lightning WiFi
    serial: <superuser required> UEFI: American Megatrends LLC. v: 3.01
    date: 05/13/2024
CPU:
  Info: 8-core model: AMD Ryzen 7 9700X bits: 64 type: MT MCP cache: L2: 8 MiB
  Speed (MHz): avg: 3314 min/max: 600/5581 cores: 1: 5539 2: 5537 3: 3526
    4: 4409 5: 5528 6: 5535 7: 2763 8: 5540 9: 600 10: 600 11: 600 12: 600
    13: 5529 14: 600 15: 600 16: 5526
Graphics:
  Device-1: AMD driver: amdgpu v: kernel
  Display: wayland server: X.Org v: 23.2.6 with: Xwayland v: 23.2.6
    compositor: gnome-shell driver: X: loaded: amdgpu
    unloaded: fbdev,modesetting,radeon,vesa dri: radeonsi gpu: amdgpu
    resolution: 1920x1080~60Hz
  API: EGL v: 1.5 drivers: kms_swrast,radeonsi,swrast
    platforms: gbm,wayland,x11,surfaceless,device
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 24.0.9-0ubuntu0.1
    renderer: AMD Radeon Graphics (radeonsi raphael_mendocino LLVM 17.0.6 DRM
    3.57 6.10.11-2-liquorix-amd64)
Audio:
  Device-1: AMD Rembrandt Radeon High Definition Audio driver: snd_hda_intel
  Device-2: AMD Family 17h/19h HD Audio driver: snd_hda_intel
  Device-3: AKAI Professional M.I. MPK Mini Mk II
    driver: hid-generic,snd-usb-audio,usbhid type: USB
  Device-4: BEHRINGER GmbH UMC204HD 192k driver: snd-usb-audio type: USB
  API: ALSA v: k6.10.11-2-liquorix-amd64 status: kernel-api
  Server-1: PipeWire v: 1.0.5 status: active
Network:
  Device-1: MEDIATEK MT7922 802.11ax PCI Express Wireless Network Adapter
    driver: mt7921e
  IF: wlp4s0 state: down mac: 2c:98:11:a1:de:6b
  Device-2: Realtek RTL8125 2.5GbE driver: r8169
  IF: enp5s0 state: up speed: 1000 Mbps duplex: full mac: 9c:6b:00:67:a1:af
Bluetooth:
  Device-1: MediaTek Wireless_Device driver: btusb type: USB
  Report: hciconfig ID: hci0 rfk-id: 0 state: down
    bt-service: enabled,running rfk-block: hardware: no software: yes
    address: 2C:98:11:A1:DE:6C
Drives:
  Local Storage: total: 1.82 TiB used: 354.55 GiB (19.0%)
  ID-1: /dev/nvme0n1 vendor: Samsung model: SSD 990 PRO 1TB size: 931.51 GiB
  ID-2: /dev/sda vendor: Samsung model: SSD 870 EVO 1TB size: 931.51 GiB
Partition:
  ID-1: / size: 91.11 GiB used: 20.09 GiB (22.0%) fs: ext4 dev: /dev/nvme0n1p2
  ID-2: /boot/efi size: 1.05 GiB used: 6.1 MiB (0.6%) fs: vfat
    dev: /dev/nvme0n1p1
  ID-3: /home size: 823.11 GiB used: 60.32 GiB (7.3%) fs: ext4
    dev: /dev/nvme0n1p3
Swap:
  ID-1: swap-1 type: file size: 8 GiB used: 0 KiB (0.0%) file: /swap.img
Sensors:
  System Temperatures: cpu: 55.4 C mobo: 36.0 C gpu: amdgpu temp: 40.0 C
  Fan Speeds (rpm): N/A
Info:
  Memory: total: N/A available: 30.48 GiB used: 7.71 GiB (25.3%)
  Processes: 466 Uptime: 2h 7m Shell: Bash inxi: 3.3.34

**Comment by timothyschoen** [comment]
Thanks for reporting! f3f1ae83e2eb391a38534011a838edff925ce19a should fix it

**Comment by jamshark70** [comment]
> Thanks for reporting! https://github.com/plugdata-team/plugdata/commit/f3f1ae83e2eb391a38534011a838edff925ce19a should fix it

Just had a crash creating a second plugdata-fx instance in Reaper. Crash is not reproducible with the latest nightly build, including that commit :+1:
