### ISSUE TITLE
Patch disappears with 100% Zoom shortcut

### ISSUE THREAD

**Issue by tmhglnd** [plugdata-team/plugdata#1881]
Hi! 

When I use the Zoom 100% shortcut the whole patch disappears. Scrolling around it is nowhere to be found. Only when I then zoom out a or in a little bit (with for example `cmd scroll` or `cmd +`) the patch appears again. Using a nightly build version `0.9.2`.

Steps to reproduce:
1. Open a patch
2. Zoom in (or out) a bit
3. Use the shortcut to go to 100%
4. Patch disappears
5. Zoom in (or out) a bit
6. Patch appears again

![ScreenRecording2024-10-04at21 55 23-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/675f6960-68ee-495c-a7c2-6ae1191fec5a)

**Comment by timothyschoen** [comment]
Fixed with 0dd4ae608

**Comment by tmhglnd** [comment]
This is fixed yes! Great!
