### ISSUE TITLE
Inlet hints on abstractions? (Question)

### ISSUE THREAD

**Issue by tmhglnd** [plugdata-team/plugdata#1883]
Hi! This is more a question (and maybe leads to a feature request).

I like the feature in plugdata where you can hover on the inlet/outlet and read a short description on what is expected to be send to that inlet. (For example in `[random]`: `bang: generate a random integer number`).

Is it possible to create these hints for custom made abstractions? And if so, is this documented somewhere?

First I thought it might taken from the code of the built objects, but I see some other abstractions (like `[rev1~]`) have the hints as well. So there must be some other file describing this?

I looked if the `[inlet]` might have a little feature in the properties allowing to type a hint. But it doesn't.

What is the best way to get this up and running? I'm curious! :)

**Comment by timothyschoen** [comment]
Like this:

<img width="230" alt="Screenshot 2024-10-08 at 00 19 09" src="https://github.com/user-attachments/assets/0d336661-3100-42fb-aa77-5de5e311fe26">
<img width="299" alt="Screenshot 2024-10-08 at 00 18 52" src="https://github.com/user-attachments/assets/51a0bd80-dfdf-43ca-a038-784864489a58">

I should document this somewhere though!

**Comment by tmhglnd** [comment]
Ah good to know! Very straightforward, but indeed nice to have this documented somewhere.

**Comment by timothyschoen** [comment]
> Ah good to know! Very straightforward, but indeed nice to have this documented somewhere. I also saw some `.md` files in documentation that had listed things for inlets/outlets/arguments etc, but those are not used in the application anywhere?

That's how we do it for built-in objects, but there's currently no way to add them dynamically. We run it through a python script that creates a compact binary representation of it, so it doesn't have to parse all the text at runtime (which is slow and more fragile). But I'm planning to allow adding your own docs someday
