### ISSUE TITLE
I can't use plugdata v9 in Cubase.

### ISSUE THREAD

**Issue by thewhitething** [plugdata-team/plugdata#1888]
Hello! I can't use plugdata on my system starting from v9.0. Cubase13 Windows11. Error message pops up on opening and most of the user interface is non-responsive. (both as instrument and effect) The .dmp file is in attachment if anyone knows how to use it.

![Screenshot 2024-10-11 170753](https://github.com/user-attachments/assets/9bd9a1ed-a3df-406b-85f7-9e9dfbbb4f31)
[Cubase 13.0.41 64bit2024.10.11 17.06.47.535.dmp](https://github.com/user-attachments/files/17343822/Cubase.13.0.41.64bit2024.10.11.17.06.47.535.dmp)

**Comment by dromer** [comment]
Do you mean `v0.9.1` ?

**Comment by thewhitething** [comment]
Yes. v0.9.1 and v0.9.0.

**Comment by thewhitething** [comment]
I found a solution. The problem was that i am using my pc with graphics card's display adapter disabled. This is the first time when a plugin is not ok with that. The only other app not starting for me was Davinci Resolve. Error massage "DaVinci Resolve could not initialize OpenGL. Please ensure that the latest graphics drivers are installed." Apparently it's a Radeon GPU thing, but error message would have been helpful.
<img width="173" alt="Screenshot 2024-10-11 214545" src="https://github.com/user-attachments/assets/fa7c9074-5407-4ef6-aa91-4c07799c81b7">
Figured out because i read that v0.9.0 introduces some GPU processing.
Thanks to the hard working team for making more music possible!

**Comment by timothyschoen** [comment]
Yay!

That makes sense, plugdata's GUI uses GPU rendering to improve performance
