### ISSUE TITLE
dynamically changed label of horizontal selector is not refreshed when inside GOP subpatch

### ISSUE THREAD

**Issue by jyg** [plugdata-team/plugdata#191]
Hi,
Seems that labels for hradio (I didn't test all guis) are not updated when inside a GOP patch. Moreover, they freeze, and aren't updated even when the subpatch is opened.
(macOS & Linux Ubuntu so far)
![image](https://user-images.githubusercontent.com/1431894/193772260-fa58a327-b355-403d-a50d-70828d727922.png)
[Label_insideGOP.pd.txt](https://github.com/timothyschoen/PlugData/files/9704122/Label_insideGOP.pd.txt)

**Comment by timothyschoen** [comment]
Thanks for reporting, I'll check this out soon! 

I'm a bit busy since Sound Simulator's video has caused more people to discover PlugData, so I've received a lot of new bug reports.

**Comment by timothyschoen** [comment]
Fixed!
