### ISSUE TITLE
Plugdata nightly hangs when opening else all_objects help

### ISSUE THREAD

**Issue by jamshark70** [plugdata-team/plugdata#1918]
Was just trying to look up ELSE objects for audio buffers, but the all_objects help file hangs -- the interface goes completely unresponsive. (Granted, it's a massive file and it's instantiating a lot of objects, but I'm pretty sure I was able to open it with no trouble in an earlier stable release.)

I was using nightly to fix some other issues -- looks like my download is from 10/16. Ubuntu 22.04.

**Comment by jamshark70** [comment]
> I think this is now solved on the latest nightly builds.

OK, would like to try.

https://glyphpress.com/plugdata/plugdata-Ubuntu-22.04-x64.tar.gz says that glyphpress is unavailable, though -- hope that isn't too much trouble to resolve.

**Comment by timothyschoen** [comment]
Yeah, the servers are down at the moment. I'm not exactly sure when they will be back.

For now, you can also grab nightly builds on github: https://github.com/plugdata-team/plugdata/actions/runs/11577061600

Scroll all the way down to find the downloads (don't click any OS in the sidebar).

**Comment by jamshark70** [comment]
> For now, you can also grab nightly builds on github: https://github.com/plugdata-team/plugdata/actions/runs/11577061600

Thanks, confirmed that this fixes the issue.
