### ISSUE TITLE
Open Dialog not scaling on Linux

### ISSUE THREAD

**Issue by hellocatfood** [plugdata-team/plugdata#193]
I am using the PlugData vst with the newly implemented optional native file browser dialog switch (via #189)

I'm using a screen resolution of 3840x2400 on Ubuntu 22.04 and noticed that this new window doesn't scale, so the text is really small

![Screenshot_from_2022-10-05_11-16-23](https://user-images.githubusercontent.com/151947/194276662-cf1cda77-9e1b-4c23-8fa6-6b99b895e8e6.png)

**Comment by tomara-x** [comment]
i used to have this dialog on void with xfce. what helped for me was to install caja, and for some reason juce uses its dialog now

**Comment by timothyschoen** [comment]
I've looked at this issue, and unfortunately it's hard to resolve since for plugins, we'd need to grab the scale from the plugin GUI, but the dialog code is buried deep in JUCE, so there is no simple way we can get the desktop scale factor.
