### ISSUE TITLE
Bug: settings always corrupt

### ISSUE THREAD

**Issue by dromer** [plugdata-team/plugdata#1941]
On latest develop `3b91ea01d24dc8fa14b227aad30d8c792fa8dcf7` - every time when opening the program we get the corrupt settings dialog:

![2024-11-14_11-29](https://github.com/user-attachments/assets/f7fe0457-a8b7-40c4-a332-f61d1b55f2a6)

**Comment by dromer** [comment]
Hmm, I completely removed the settings file and now it started correctly.

Now wondering if this was because I was working on https://github.com/plugdata-team/plugdata/pull/1928 which of course modifies the settings :thinking:

**Comment by timothyschoen** [comment]
Hmm, you're only adding things to HeavyState though right? It should be able to manage that

**Comment by dromer** [comment]
Can no longer be reproduced.
