### ISSUE TITLE
some 'else' instruments shown in sidebar are missing?

### ISSUE THREAD

**Issue by kamomehettapi** [plugdata-team/plugdata#1965]
I noticed that off a new compile, the `plaits~` node can be loaded so the `else` external is definintely being loaded. But some of the other nodes under `Instruments` category seem to be missing like `else/bass.m` and `else/drums.m~`. Maybe they were removed? Confusing as to what happened

**Comment by porres** [comment]
these were not part of else really, but we want to have these modules synced and part of 'MERDA' (a submodule of ELSE). This is a known issue and markes as the "Pair up modules" task in https://github.com/plugdata-team/plugdata/issues/1901
