### ISSUE TITLE
opening settings menu is choppy and sometimes crashes

### ISSUE THREAD

**Issue by kamomehettapi** [plugdata-team/plugdata#1966]
I was thinking, the way the settings menu opens is kind of sluggish UX

![flicker](https://github.com/user-attachments/assets/9f175d64-2e72-48cb-b87f-3e479d98d852)

But more important than that if I go into debug and open/close settings a lot of times sometimes either the window freezes or I get a crash in a `handleAsyncUpdate` call (dont remember which one). And I thought if I open REAPER (Linux DAW) and put in plugdata vst3 then resize their "FX chain" outer window containing the plugdata window before opening settings sometimes it crashes more often

So maybe, if settings needs some time to load should stop that async processing to wait first ?

**Comment by kamomehettapi** [comment]
OK apparently debugging this is hard for something as lowlevel as JUCE if you aren't prepared

Thankfully this kind soul has written a lot about this kind of "jank" specifically about JUCE if it may help

https://melatonin.dev/blog/how-juce-components-work/
https://melatonin.dev/blog/dealing-with-jank-in-juce/
https://melatonin.dev/blog/using-perfetto-with-juce-for-dsp-and-ui-performance-tuning/

**Comment by kamomehettapi** [comment]
I added perfetto in my branch, got some useful stats so far !

A small thing: opening settings dialog is setting theme twice and for some reason the "equivalent theme tree" check in `PluginProcessor::setTheme` is failing, so this is the not necessary work

![](https://github.com/user-attachments/assets/ee256fd3-cd4b-4ff3-854c-663db5322eb4)

So just check if theme-name is set to current theme in `PluginProcessor::setTheme` and skip that case..

Another thing that could be harder: settings dialog is recreated every time it is opened, instead of cached. because this is expensive operation it has a noticable delay

![image](https://github.com/user-attachments/assets/d1974496-3a0f-4524-8988-964495a559e7)

This ^^^ happens on every menu open

Also noticed this when switch dialogs: last dialog is written to some kind of buffer and not updated in the time?

![](https://github.com/user-attachments/assets/0dd564d4-7ffd-404b-b417-3528d06af607)

**Comment by kamomehettapi** [comment]
Another thing found: switching font causes whole-layout refresh but it didnt check if font was same as last. And this is triggered whenever settings is opened. So just compare the last font.

Did those and switching seems faster already !

**Comment by dromer** [comment]
Can you also check the compile menu please? ^_^

**Comment by kamomehettapi** [comment]
Ah yes I was wondering what that meant before I realized you can apparently compile PD patches now :-)

Here is graph for that menu

![](https://github.com/user-attachments/assets/2e454da5-6194-4d7f-9aa8-1e804e0aa7c8)

I think it's not as bad as some of the others but still has that weird issue where the dialog paints a second after the pane is created..

![](https://github.com/user-attachments/assets/37da8466-faee-48d8-a25b-d9b42b9d422c)

**Comment by kamomehettapi** [comment]
Getting warmer...

![](https://github.com/user-attachments/assets/d9ce2cd7-6501-45ad-8f1d-d004a7c0a446)

I realized plugdata uses custom renderer with nanovg under the hood, those `N...` are the nanovg render frame calls. So each is a single frame render

So according to this this is the actual sequence of events (?)
1. Settings menu construction & big render at start
2. Right after that `ThemeSettingsPanel::valueChanged` is called in next frame, though this is hard to see zoomed out. That triggers `PluginProcessor::setTheme`
![](https://github.com/user-attachments/assets/935a88c7-73a9-450f-876e-20a6d6839b43)
3. Next does a whole `updateEditorsLNF` due to theme panel code running. Can't tell if this is due to the last frame or totally separate event?
![](https://github.com/user-attachments/assets/a8b4a8c1-c1f2-4984-978f-adb583d7652b)
4. A whole bunch of things render... two frames in a row
![](https://github.com/user-attachments/assets/ef6926c7-c0bc-4801-9524-ad122377222e)

I am not well understood in how JUCE decides to repaints everything but seems to be happening somewhere

**Comment by kamomehettapi** [comment]
BTW should add this happens every time settings pane is opened, not just once. so that theme updating whole editor every time is probably not correct?

**Comment by kamomehettapi** [comment]
OK might have figured it out

The NanoVG renderer has a function to save its surface to a backbuffer incase something juce needs to render over it because I guess NVG doesn't handle JUCE components on top normally? So it does this by rendering a copy of the last canvas in `NVGSurface` code

However this is what is causing the flickering. If I disable `setRenderThroughImage` call I get no flickering, only time incurred by startup of `SettingsDialog` (would seem)

![](https://github.com/user-attachments/assets/1d0b935a-0e07-4c8f-8bdb-420a3f5e4a26)

This is the origin of that "ghost backbuffer" effect in the earlier video I saw !

Now of course were back to NVG drawing on top which is to avoid. Maybe someone could chime in as to how to render it in a frame without all the other global graphics stuff getting messed ?

**Comment by kamomehettapi** [comment]
Alternately you could just hide the canvas and replace with a blank component space if dialog is open

Only temp fix but would solve the problem with decent UX

**Comment by dromer** [comment]
I think the idea there was that we get a kind of screenshot render of the canvas in the background?

Which certainly looks better than a completely blanked out canvas (which iirc we had before).

**Comment by timothyschoen** [comment]
> Okay been debugging this for a while and got stucked
> 
> It seems whenever you call `updateWindowContextVisibility()` it just instantly shows/hides nanovg window. Which causes flickering. But JUCE `repaint()` only schedules repaint for later. Even moving that `updateWindowContextVisibility()` call directly into the end of `Dialog::paint` still caused flickering because JUCE hadn't finished rendering yet ?
> 
> So I dont understand why that `OpenGLContext` call `setVisible()` instantly changes drawn state of window as opposed to all the other drawing calls

I can explain this!

Basically, the problem is that we render our canvas content using nanovg, but the rest of the window using JUCE. Drawing the settings panel with nanovg is unfortunately not an option, because nanovg's text rendering is not good enough (less sharp, no support for non-latin unicode characters).

So to make it work, we hide our openGL area, render our canvas to an image with openGL, then render the settings panel on top. The problem on Linux is that we need to recreate the openGL context for this to work, for some reason. I'm not exactly sure why.

So the problem is really this bit:

```
#if JUCE_LINUX
    detachContext();
    initialise();
#endif
```

Without this, it doesn't flicker as badly. On macOS and Windows this already works, but if you try to remove this on Linux, it doesn't work anymore, at least for me.

**Comment by timothyschoen** [comment]
> OK still stumped but i dont think its frametiming issue
> 
> When delaying the effect of `updateWindowContextVisibility()` by like 10 frames it still flickers when the glcontext is hidden
> 
> Still happens even with `setOpaque(false)` on NVG surface
> 
> That means whatever is rendering underneath doesn't matter for some reason ?
> 
> ![weasdasd](https://private-user-images.githubusercontent.com/179056474/390547725-e86b8a7b-aa62-4db1-a200-b7af8dca1353.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5MjY0MjUsIm5iZiI6MTczMjkyNjEyNSwicGF0aCI6Ii8xNzkwNTY0NzQvMzkwNTQ3NzI1LWU4NmI4YTdiLWFhNjItNGRiMS1hMjAwLWI3YWY4ZGNhMTM1My5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEzMFQwMDIyMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDcwNmJkMDcyYzY3NThmOTQzOWI5ODEzYTU2ZDEzOWQ4NTlmMDc3ZTg2YzliMjc3MWJiYTYzYTQxN2VlZmVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HxV_kKHLYlKXofSlshXA4O0tfzaEkGZj3TEWbRRM0wo) [ ![weasdasd](https://private-user-images.githubusercontent.com/179056474/390547725-e86b8a7b-aa62-4db1-a200-b7af8dca1353.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5MjY0MjUsIm5iZiI6MTczMjkyNjEyNSwicGF0aCI6Ii8xNzkwNTY0NzQvMzkwNTQ3NzI1LWU4NmI4YTdiLWFhNjItNGRiMS1hMjAwLWI3YWY4ZGNhMTM1My5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEzMFQwMDIyMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDcwNmJkMDcyYzY3NThmOTQzOWI5ODEzYTU2ZDEzOWQ4NTlmMDc3ZTg2YzliMjc3MWJiYTYzYTQxN2VlZmVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HxV_kKHLYlKXofSlshXA4O0tfzaEkGZj3TEWbRRM0wo) ](https://private-user-images.githubusercontent.com/179056474/390547725-e86b8a7b-aa62-4db1-a200-b7af8dca1353.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5MjY0MjUsIm5iZiI6MTczMjkyNjEyNSwicGF0aCI6Ii8xNzkwNTY0NzQvMzkwNTQ3NzI1LWU4NmI4YTdiLWFhNjItNGRiMS1hMjAwLWI3YWY4ZGNhMTM1My5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEzMFQwMDIyMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDcwNmJkMDcyYzY3NThmOTQzOWI5ODEzYTU2ZDEzOWQ4NTlmMDc3ZTg2YzliMjc3MWJiYTYzYTQxN2VlZmVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HxV_kKHLYlKXofSlshXA4O0tfzaEkGZj3TEWbRRM0wo) [ ](https://private-user-images.githubusercontent.com/179056474/390547725-e86b8a7b-aa62-4db1-a200-b7af8dca1353.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5MjY0MjUsIm5iZiI6MTczMjkyNjEyNSwicGF0aCI6Ii8xNzkwNTY0NzQvMzkwNTQ3NzI1LWU4NmI4YTdiLWFhNjItNGRiMS1hMjAwLWI3YWY4ZGNhMTM1My5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEzMFQwMDIyMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDcwNmJkMDcyYzY3NThmOTQzOWI5ODEzYTU2ZDEzOWQ4NTlmMDc3ZTg2YzliMjc3MWJiYTYzYTQxN2VlZmVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HxV_kKHLYlKXofSlshXA4O0tfzaEkGZj3TEWbRRM0wo)

I think I figured this out with a2036e664840b617c69d1313ebe37631bfdeabe0

**Comment by timothyschoen** [comment]
Can confirm: with both our fixes combined, all dialog feel snappy again on Linux!
