### ISSUE TITLE
in LFO module 'Hz' dial can't be controlled well

### ISSUE THREAD

**Issue by kamomehettapi** [plugdata-team/plugdata#1967]
The 'Hz" dial in the builtin LFO module gets stuck frequently. But the other knobs don't. See the video
![](https://github.com/user-attachments/assets/be8403a9-a859-4271-b62b-37a79823c375)

Tested Windows standalone built from `develop`

**Comment by dromer** [comment]
That is `[lfo.m~]` module coming from MERDA.

Can confirm that this instance of `[knob]` somehow gets very flaky (tested on Linux).

Perhaps something to do with its settings? 
![2024-11-23_08-17](https://github.com/user-attachments/assets/d2000291-83aa-4b11-87cb-33ec1d371af6)

**Comment by porres** [comment]
works just fine in vanilla on a mac... but in plugdata on mac it does act pretty funny!

Anyway, a bug in the [knob] port in PlugData

**Comment by porres** [comment]
I have to say the [knob] port never worked properly and there are many other issues, see https://github.com/plugdata-team/plugdata/issues/901

And now I did just include many many new features I hope we can really concentrate on getting it right. The new features will be key and essential for the MERDA modules by the way

**Comment by timothyschoen** [comment]
Fixed!
