### ISSUE TITLE
Bug: saving patch doesn't save

### ISSUE THREAD

**Issue by dromer** [plugdata-team/plugdata#1969]
On current develop, `e93f0f56205b85e5ba06e4c70c38e70631c2fed4`, I somehow am unable to save a patch.

Neither `Ctrl + S` or `Save patch` from the menu work.

The text in the tab stays on "modified" status:

![2024-11-24_01-27](https://github.com/user-attachments/assets/48fe71c9-0133-4317-896d-a57b0e8c8102)

When I close the patch I get a warning about unsaved changes and the save does work:

![2024-11-24_01-27_1](https://github.com/user-attachments/assets/52ec8971-2d78-4706-8aa8-a863fcea4e24)

**Comment by timothyschoen** [comment]
Was this fixed?

**Comment by timothyschoen** [comment]
Ah, but I think it's just the tab text right? The console will say "Saved to..."?

**Comment by dromer** [comment]
No when trying to save it would also try to find a new location. Maybe the save did work there, but the overall "save state" was still messed up.

**Comment by timothyschoen** [comment]
Ah, okay. I do think those are 2 separate bugs: not remembering the last save location, and the patch title not updating. The first one you've reported before I believe, the second one is new.

**Comment by timothyschoen** [comment]
The title now updates correctly. The other issue is still there, because I have never experienced it before somehow. Do you have steps to reproduce it?

**Comment by dromer** [comment]
On Linux latest develop build I can't reproduce this at the moment.

Will close until it maybe reappears again ;)
