### ISSUE TITLE
Welcome tiles get smaller as screen gets bigger

### ISSUE THREAD

**Issue by dromer** [plugdata-team/plugdata#2000]
Seems that resizing is a bit inconsistent and the tiles do not resize relative to the screen width:

https://github.com/user-attachments/assets/e8cd3930-549e-442a-8abb-c86f6b0fac7a

**Comment by timothyschoen** [comment]
This would make more sense if the whole grid is filled:


https://github.com/user-attachments/assets/f952c084-4fe0-4887-abd6-88467a71afce

If we have enough extra space for the minimum width of a new tile, it adds a row, making the other elements smaller.

**Comment by dromer** [comment]
Ah, so the welcome tiles then align with the new grid.

It just looks odd how they jump back at every level.
Mainly looking at the New Patch / Open Patch tiles here. For the Recently Opened I think it makes sense.
