### ISSUE TITLE
I can't hear any MIDI sounds

### ISSUE THREAD

**Issue by H-MLim** [plugdata-team/plugdata#2015]
![image](https://github.com/user-attachments/assets/b83fc104-1a13-40d0-b028-e4bd466a506e)

hi, in the new plug interface, I can't hear any MIDI sounds at all (via `[noteout]`), although I tried all the ports (Port 1~Port 8), both Microsoft GS Wavetable Synth and Internal GM Synth. how can I fix this? tested in Nightly build: d3b7fc68d

+
I found that there are very long delay between triggering keyboard and MIDI sounds in Microsoft GS Wavetable Synth. still no sounds in Internal GM Synth

**Comment by tmhglnd** [comment]
I think this is related to my observations and issue I reported a few days ago as well #2009

**Comment by timothyschoen** [comment]
I tried to fix internal synth not working with 14e2fee24, hope that helps.

Not sure where the latency comes from when sending to GS Wavetable Synth, I'll investigate!

**Comment by tmhglnd** [comment]
The latency could've been part of this weird feedbackloop as well, since when I experienced that sometimes some notes came throught but took long.

**Comment by timothyschoen** [comment]
I this still a problem?

**Comment by H-MLim** [comment]
Sorry for being forgotten about this. for me, I think this was fixed in the latest nightly build. so I'll close this for a while. thank you!
