### ISSUE TITLE
Oversampling also happens when limiter is off

### ISSUE THREAD

**Issue by tmhglnd** [plugdata-team/plugdata#2016]
Hey!

Not really a bug, more an observation:

I was doing some latency testing (sending clicks out the soundcard output), when I noticed that the volume of my click was not 0dBFS, even tho the slider was in the default location in PlugData, and the Limiter was off.

Then I noticed that when I set `oversampling` to 1x, the click goes to 0dBFS, so it seems the oversampling is also happening when the limiter is off, is this correct? I guess this could be a feature, but it wasn't immediately clear to me that this was a separate setting, I thought the oversampling was part of the limiting (made sense to me).

I was also wondering if it is possible to see the `dBFS` value in the gain slider, now I kind of have to guess (and it took me some time to figure out that double-click resets it to 0).

**Comment by timothyschoen** [comment]
Correct, oversampling is applied to audio regardless of the limiter. Any way we could make that more obvious?


Regarding volume, I added this now:

https://github.com/user-attachments/assets/c24e319c-5ffc-47f8-9157-a1e7cfcb27c7

I think that will help!

**Comment by tmhglnd** [comment]
That is perfect, very helpful!

Regarding the oversampling/limiter, I have a few thoughts, but I don't know what is the best, maybe others have some completely different ideas about it. In any case some ideas that could be mixed & matched whatever you think makes sense:

1. There could be 2 pop-up menu's: `Limit` & `Oversample`
    - When clicking limit you see: on/off, threshold
    - When clicking oversample you see: off, 2x, 4x, 8x

2. Maybe get rid of the little `v` (Audio Settings) thing and add all the settings to the preferences under Audio Output, categorized separately for Limiter and Oversampling.

3. Having some visual indication that oversampling is active somewhere

**Comment by timothyschoen** [comment]
<img width="260" alt="Screenshot 2024-12-10 at 18 45 41" src="https://github.com/user-attachments/assets/fdf87045-a35e-48c4-9ea0-8773ddea54b6">

Getting there! I think I'll keep it in the statusbar, since whether or not you want oversampling and limiting often depends on the patch you're using. But this way, the settings are at least clearly catagorized, and you can see the limiter status.

**Comment by tmhglnd** [comment]
You might still be working on this so sorry if this is too early, but I just tried the latest nightly and PlugData crashes when clicking the limiter or oversampling `v` menu. Actually the oversampling menu doesn't show anything.

<img width="257" alt="Screenshot 2024-12-13 at 14 56 39" src="https://github.com/user-attachments/assets/9f307045-41c9-4df7-8795-d90d32396386" />

**Comment by timothyschoen** [comment]
Whoops, fixed it! This was because the new system I used temporarily had a different way of storing the oversampling to the settings file, but I reverted that, which made your settings file incorrect.

**Comment by tmhglnd** [comment]
Yes, now the crash doesn't happen anymore! 

There is still a little bug I think with being able to click enable/disable on the limiter or oversampling. It doesn't register the clicks always. It seems after clicking once I can't click the button again, I first need to do something else with the mouse, like click on the canvas, or click another button.

**Comment by timothyschoen** [comment]
> Yes, now the crash doesn't happen anymore!
> 
> There is still a little bug I think with being able to click enable/disable on the limiter or oversampling. It doesn't register the clicks always. It seems after clicking once I can't click the button again, I first need to do something else with the mouse, like click on the canvas, or click another button.

Fixed that too!
