### ISSUE TITLE
Bug: opening an abstraction marks it as editted

### ISSUE THREAD

**Issue by dromer** [plugdata-team/plugdata#2021]
When opening an abstraction it immediately is marked as edited even though we didn't change anything.
Trying to close it will ask us to save the changes.

![2024-12-16_07-30](https://github.com/user-attachments/assets/384d4ec6-178e-42d0-bb59-86b405a9d4cb)

I thought we had this issue before, but it was fixed (can't find it though).
So could be a regression somewhere.

**Comment by timothyschoen** [comment]
Ah, gonna fix that!

Btw: changed your mind about syntax highlighting?

**Comment by dromer** [comment]
Can't reproduce it atm. Will re-open if it re-appears ..

**Comment by timothyschoen** [comment]
Seems like @porres is running into this issue as well, so worth investigating

**Comment by dromer** [comment]
This still happens regularly on latest nightly, btw.

I've still not detected a straightforward pattern that allows it to be easily reproduced :#

**Comment by tmhglnd** [comment]
I encounter this as well. Also don't see any pattern why.

**Comment by dromer** [comment]
It sometimes also happens for subpatches, which is odd since changes would go to the main patch.

From what I can tell only the sub-patch is marked as edited and when closing it we get a warning.

**Comment by timothyschoen** [comment]
I think I've found a pattern: it asks to save an abstraction if the parent patch if was opened from is marked dirty. That's at least one case I can consistently reproduce

**Comment by timothyschoen** [comment]
I did another fix, hope it doesn't happen anymore now

**Comment by dromer** [comment]
I'll update my local builds and play around .. we'll see what happens :P

**Comment by timothyschoen** [comment]
@dromer @tmhglnd Anyone still has this happening on recent builds?

**Comment by dromer** [comment]
I haven't had it in a while and actually forgot about it :D
