### ISSUE TITLE
Installation patch

### ISSUE THREAD

**Issue by StoredMink** [plugdata-team/plugdata#2030]
Where does VST3 plugin get installed? I can't choose a correct patch and install wizard don't me where does VST3 plugin gets installed. 
My OS is windows 11

**Comment by dromer** [comment]
Without knowing your OS we cannot answer this question.

**Comment by StoredMink** [comment]
> Without knowing your OS we cannot answer this question.

sorry, my OS is windows 11

**Comment by timothyschoen** [comment]
Hi!

On Windows, they should be inside C:\Program Files\Common Files\VST3
