### ISSUE TITLE
Try to force check for modifier keys when initiating canvas drag

### ISSUE THREAD

**Issue by Yzrsah** [plugdata-team/plugdata#213]
If my DAW has focus, then I hold Ctrl on the keyboard and start dragging a control in PlugData, the object's position on the canvas moves instead of tweaking the control's value. You have to remember to always first click on the PlugData window to get focus before trying to ctrl+drag a control. Or always lock the canvas. Despite knowing this I stupidly keep making the same mistake of accidentally moving the object, I guess because needing to do that extra click hundreds of times in a day could lead to an accident.

If I do not let go of Ctrl it starts tweaking the value after the second click attempt, so I'm wondering if it's possible to force checking if Ctrl is held down at the time when a canvas drag starts? It would be getting focus at the same time as the start of the drag event, so maybe there's a way to also check for the modifier key?

**Comment by timothyschoen** [comment]
I already force-check the modifier keys with a timer, unfortunately I don't think those key events will come through without keyboard focus :(

I agree that it would be a good idea to find a solution for this, I run into this issue sometimes as well.

**Comment by timothyschoen** [comment]
Unfortunately I don't think I'll be able to solve this: this is either in the hands of the DAW or the OS.

**Comment by Yzrsah** [comment]
@timothyschoen, What if the drag does not start dragging right away and instead starts a timer event for 17 ms later or the next frame. When the timer fires it then checks for key modifiers, and then continues dragging the objects if Ctrl is not held down. The user wouldn't notice anything, just a frame or two of latency before the drag starts.

When that timer event fires, checking for key modifiers would report an invalid value?

**Comment by Yzrsah** [comment]
@timothyschoen When that timer event fires, would checking for key modifiers report an invalid value?

**Comment by Yzrsah** [comment]
@timothyschoen Please

When that timer event fires, would checking for key modifiers report an invalid value?

This is a really a problem, I believe that it can be fixed

**Comment by Yzrsah** [comment]
@timothyschoen Please

When that timer event fires, would checking for key modifiers report an invalid value?

This is a really a problem, I believe that it can be fixed. This is my #1 problem with Plug Data, please take it seriously.

**Comment by timothyschoen** [comment]
Sorry, I was a bit quick to close this, because if the modifier keys JUCE returns are not valid, I thought there's not much I can do about that.

I did have one idea, instead of calling getCurrentModifierKeys, I could try getCurrentModifierKeysRealtime. This change is online now, so please try it and let me know if this solves it for you :)

> What if the drag does not start dragging right away and instead starts a timer event for 17 ms later or the next frame. When the timer fires it then checks for key modifiers, and then continues dragging the objects if Ctrl is not held down. The user wouldn't notice anything, just a frame or two of latency before the drag starts.

I don't think this is possible with JUCE, it would be better to check for modifier keys in the actual mousedrag event instead. If this fix doesn't work, I'll try that as well.

**Comment by Yzrsah** [comment]
@timothyschoen It's working! You fixed it! This is great! Thank you so much Tim.

**Comment by timothyschoen** [comment]
Nice!!
