### ISSUE TITLE
Fix comment sizes being different than in Pd-vanilla

### ISSUE THREAD

**Issue by alfonso73** [plugdata-team/plugdata#217]
Hi!

In the most "crowded" help files a lot of overlapping goin' on...

![image](https://user-images.githubusercontent.com/3230434/200547639-3236b072-7b39-4ee5-855a-9471af493b21.png)

![image](https://user-images.githubusercontent.com/3230434/200547702-3ccba89a-e46c-4551-a74c-a9564f82e8e7.png)

**Comment by timothyschoen** [comment]
Changed the title, comment sizes are indeed still a big problem. One that I'm really hoping to fix very soon.

**Comment by timothyschoen** [comment]
Should be fixed!
