### ISSUE TITLE
Objects in canvas shrink during mouse-down

### ISSUE THREAD

**Issue by Yzrsah** [plugdata-team/plugdata#225]
- When clicking an object, the object shrinks slightly during the mouse down.

![Throb](https://i.imgur.com/66DmMSA.gif)

**Comment by timothyschoen** [comment]
Oh that's very strange... I'll look at what's happening here!

**Comment by timothyschoen** [comment]
Unfortunately I'm still not able to reproduce this bug. Does this still occur for you with recent builds?

**Comment by Yzrsah** [comment]
@timothyschoen Hi sorry for not responding.

The bug is still occurring with the latest build. I checked on two PCs and it's same on both.

Both machines have:
- Windows 10
- NVidia graphics card with latest drivers
- 4K display
- Recommended 150% display scaling default in Display settings
- Reaper host

I just tried setting display scaling to 100% and it's so small I can barely see it, but the objects do not resize when clicked!
125% also has the problem. So it looks like the bug happens when display scaling is above 100%.

**Comment by alcomposer** [comment]
This happens for me when canvas zoom is < 100%.  I think it is related to int vs float? So when a user clicks on an object, it gets a float position?

**Comment by Yzrsah** [comment]
@alcomposer Yes it looks like it's switching to a buffered image with different resampling and slightly different image size quantization

**Comment by Yzrsah** [comment]
@alcomposer Yes while clicking it looks like it's switching to a buffered image with different resampling and slightly different image size quantization

**Comment by timothyschoen** [comment]
> This happens for me when canvas zoom is < 100%.
> 
> Possibly it is related to buffering the object as an image on click?
> 
> https://github.com/plugdata-team/plugdata/blob/f573d79e7e1315320b89a007c57df0d634a25c15/Source/Canvas.cpp#L1117-L1120

Oh wow, I forgot about that! When dragging objects, it will buffer them to image, to prevent having to redraw all the contents of objects when dragging.

**Comment by alcomposer** [comment]
Maybe we can buffer the image on click, but not swap it out until the user starts dragging? 

Sleight of hand.

**Comment by alcomposer** [comment]
Only issue with buffering the node is any dynamic elements would get frozen? 

Like radios / numbers / sliders etc.

Having the patch still running and responsive would be important.

**Comment by timothyschoen** [comment]
> Maybe we can buffer the image on click, but not swap it out until the user starts dragging?
> 
> Sleight of hand.

Doing this now, that should fix it, or at least make it much harder to spot.
