### ISSUE TITLE
Playhead object causing other objects in PlugData to misbehave?

### ISSUE THREAD

**Issue by mortfell** [plugdata-team/plugdata#226]
Hey there!
I'm attempting to port a random sequencer patch I made for the organelle into plug data for use in DAWs
I'm trying to get clock ticks from playhead to sync my sequencer with the DAW and I can't get any kind of usable output from playhead using the techniques I'd normally use. It's entirely possible I'm using it incorrectly but it does appear to be broken in some way.

I'm on an M1 mac Big Sur 11.6.5, using the version of Plug Data from brew in Bitwig 4.4.2

I'm not really even sure how to describe it!! So I've just made a video:
[playhead bug.webm](https://user-images.githubusercontent.com/4732794/201460077-749b2bfe-b3c8-4c22-b57b-bc509f39ee92.webm)

**Comment by mortfell** [comment]
To explain whats happening in text simply:
playhead
outlet 8 from playhead is being unpacked, time value is getting converted to an integer and through modulo 4 to make it step through numbers. I try to use that to get ticks and print messages sequentially but waaaaay more bangs are coming through and messages are being printed in non sequential order

**Comment by timothyschoen** [comment]
Hi, it looks like PlugData on homebrew isn't at the last version yet (I have no idea who put it on there actually, do I don't know who to contact about it!).

Could you try this version: https://github.com/timothyschoen/PlugData/releases/tag/v0.6.2, and let me know if that works? You might want to do "brew remove plugdata" first just to be sure.

**Comment by mortfell** [comment]
oh wow! ok yes upgraded.
still have the same issue though

it also happens (the behaviour of getting tons of unexpected output) if I use the first output of playhead to toggle a metro object on off. I also tried it in Reaper to check.
<img width="527" alt="Screen Shot 2022-11-12 at 2 47 03 PM" src="https://user-images.githubusercontent.com/4732794/201493949-b01b1920-8b28-476d-92b4-7dfc6f3ec3b7.png">

**Comment by mortfell** [comment]
Hey I tried this in Bitwig on Windows as well, just to check
Seems like the issue is the same, as you can see here, when I use the first outlet of a playback object to activate a metro object I'm getting many more bangs than expected. 
(I installed from the release you linked and did do a purge of my brew install on mac)

Any outlet of playback seems to have this sort of behaviour for me. Just wanted to verify I'm not missing anything and this this is not the intended behaviour. 

[2022-11-14 02-55-38.webm](https://user-images.githubusercontent.com/4732794/201618813-73864357-90ab-4328-8047-a02244fa5f57.webm)

**Comment by mortfell** [comment]
I renamed this because the name I left before didn't really seem useful, and was potentially rude.
I'm still not really sure what to label this issue as, but I think that at least gives a better idea.

Playheads outlets seem to be generating a lot of extra bangs or messages that have made other objects act in unexpected ways. I noticed it was causing an unexpected printing order of messages to the console. I guess messages are being sent faster than the print object is checking? It seems like it's sending bangs/messages related to the counter information from the last outlet to it's other outlets.

**Comment by timothyschoen** [comment]
Oh it wasn't rude, I've seen way worse ;)

This behaviour makes sense, since playhead is just constantly throwing out a "0" or "1" depending on the playing state. This message will go through the toggle and the metro gets reset. Put a [change] in between and you should be good to go.



> time value is getting converted to an integer and through modulo 4 to make it step through numbers

This should work though, not sure what's going wrong there

**Comment by mortfell** [comment]
ahh ok thanks yeah that makes sense.
change works, thanks for the suggestion!

If I mess around more with the playhead counting stuff more and notice anything I'll make note of it here.

**Comment by jamshark70** [comment]
For example, the burst generator approach might look like this.

![pd-burst-ticks](https://user-images.githubusercontent.com/318301/204950753-b1208239-83ca-45b6-82f0-37ca0e499e34.png)

![pd-burst-gen](https://user-images.githubusercontent.com/318301/204950763-608c5d7c-be3c-4177-a517-1f908839cf26.png)

(I did find a problem in playhead-tick -- it only outputs "tempo" once, so later-created objects don't get the message! I can fix that by pushing out a tempo message upon play start -- can't make that change right now but will do so within a day or two.)

**Comment by jamshark70** [comment]
> I did find a problem in playhead-tick -- it only outputs "tempo" once, so later-created objects don't get the message! I can fix that by pushing out a tempo message upon play start...

This is fixed now, so the example patch should work without requiring you to pre-bang the "tempo 120 permin" message box.

**Comment by mortfell** [comment]
Good to know, thanks for that!

**Comment by timothyschoen** [comment]
I think all the issues here are resolved?
