### ISSUE TITLE
Bug - Issue with loading wav files, using soundfiler(PD doesn't seem to remember PD patch location and looses reference to any wave files loaded via soundfiler)

### ISSUE THREAD

**Issue by jaffasplaffa** [plugdata-team/plugdata#228]
Hello :) 

I am having an issue with loading wav files into a table, using soundfiler in the plugin version og PlugData. I am running PlugData in Logic 1.7.1 on an M1 Macbook.

When I open one of my patches in PlugData(plugin version), that uses soundfiler to load wav files into tables, I have to save my patch before PlugData remembers the location of the wav files. It seems like PlugData might not remember the actual location of the patch running and therefor looses the reference to any wav files inside that folder, cause soundfiler uses the patch as a reference to any files loaded into it.

Here is a screenshot of the soundfiler load mechanism:
<img width="326" alt="Screenshot 2022-11-12 at 18 20 57" src="https://user-images.githubusercontent.com/14827192/201486738-bfb933a6-add6-41cf-ac0d-3bad73cc58b7.png">

The +Sounds+ folder is located in the same folder as the PD patch. But I get:
soundfiler read: +Sounds+/Mono/Audio1.wav: No such file or directory

But if I do a save as and save the PD patch to the same location again, the samples are loaded. But if I then close/open Logic, I have to go into PD and save the patch again, for PD to load the wav files.

Not sure if my explanation is clear, I struggled a bit explaining it, I can make a simplified example patch if needed.

Best wishes,
Jakob

**Comment by timothyschoen** [comment]
Thanks for letting me know, I'll have a look!

**Comment by timothyschoen** [comment]
Should be fixed, plugdata will now remember the patch location when loading in the DAW. This does mean that it's now also important to actually save the patch, otherwise you lose your progress.
