### ISSUE TITLE
Issue with flashing to Daisy on Windows

### ISSUE THREAD

**Issue by jpnielsen** [plugdata-team/plugdata#235]
Trying out 6147829 after i saw your Discord message and youtube video.
I'm on Windows 11.

After Compile, I get:

<img width="751" alt="image" src="https://user-images.githubusercontent.com/27916597/202928800-e09c480d-8932-4c1d-8542-e5f0a30514e7.png">

I don't know where to create the tmp dir.

Thank you!

**Comment by jpnielsen** [comment]
"C:\Users\username_deleted\AppData\Roaming\PlugData\tmp"

**Comment by timothyschoen** [comment]
Hi, this is a bug that I'm hoping to fix today! I'll let you know when it's fixed.

The Daisy exports are still in an experimental stage, it will get more stable soon.

**Comment by timothyschoen** [comment]
The tmp warning is not the relevant part here, that's just a warning. The real problem (I think?) is that Windows refuses to execute Heavy.exe, possibly for security reasons.

**Comment by timothyschoen** [comment]
I wonder if it's fixed if you try it again now (using the latest plugdata builds). If it still doesnt work, it's likely caused by Windows Defender or the antivirus you use

I need to get a codesigning certificate for Windows so it won't complain anymore

**Comment by jpnielsen** [comment]
I lost interest in the project.

**Comment by jpnielsen** [comment]
Got the latest bin from actions.

When installing the toolchain i get:

<img width="760" alt="image" src="https://user-images.githubusercontent.com/27916597/208272280-6e06fd17-4ddb-496f-b640-6b5871eb0cca.png">

**Comment by jpnielsen** [comment]
moved "PlugData\Toolchain\usr\*" to "PlugData\Toolchain\"

Building seems to work. 
Thank you.

**Comment by timothyschoen** [comment]
> Got the latest Win64 installer from [actions](https://github.com/plugdata-team/plugdata/actions/runs/3721498508).
> 
> When installing the toolchain i get an error, and a search shows the location of the files:
> 
> <img alt="image" width="760" src="https://user-images.githubusercontent.com/27916597/208272280-6e06fd17-4ddb-496f-b640-6b5871eb0cca.png">

I saw someone had this issue in the Discord as well, I'll investigate it today.



> moved "PlugData\Toolchain\usr*" to "PlugData\Toolchain"
> 
> Building seems to work. Thank you.

Nice!
