### ISSUE TITLE
Click a message or Bang a message results in different behavior

### ISSUE THREAD

**Issue by FlachyJoe** [plugdata-team/plugdata#248]
Hi,
a click or a bang on a message doesn't have the same effect:
![Capture d’écran_2022-12-04_21-23-55](https://user-images.githubusercontent.com/10371513/205513864-1049e479-f9e7-4086-be04-c3caa83f82cd.png)
[print] react to the message click but the destination message doesn't.

This test patch for https://github.com/pure-data/pure-data/issues/1845 is buggy too, message contents only updates at spigot close:
![Capture d’écran_2022-12-04_21-06-37](https://user-images.githubusercontent.com/10371513/205514044-d65f4f0d-3376-4c65-947a-8db6f77f6202.png)

**Comment by timothyschoen** [comment]
Thanks for reporting, I've fixed it!
