### ISSUE TITLE
Objects with negative coordinates are not shown in GoP

### ISSUE THREAD

**Issue by FlachyJoe** [plugdata-team/plugdata#249]
Hi,
when an object in a sub-patch or an abstraction is placed in negative coordinates, it's not shown in parent.
![Capture d’écran_2022-12-05_21-46-10](https://user-images.githubusercontent.com/10371513/205740277-f8f4f641-d48b-4bf3-8256-f77c7156e8fb.png)
![Capture d’écran_2022-12-05_21-47-01](https://user-images.githubusercontent.com/10371513/205740285-c8661f0a-2b88-46be-acea-3182c3ce99e5.png)

**Comment by timothyschoen** [comment]
Thanks for reporting, I'll take a look at this soon

**Comment by timothyschoen** [comment]
Fixed with 698597e825af5181b36d29e434660eeb53143e3a
