### ISSUE TITLE
Access field properties to change width / properties of fields greyed out

### ISSUE THREAD

**Issue by stillpointx** [plugdata-team/plugdata#255]
Access field properties to change width / properties of fields greyed out
see video below

![field width -prop vokoscreen-2022-12-06_08-09-01](https://user-images.githubusercontent.com/28985314/205921643-48632c64-5726-4b30-adc7-be25a2736804.gif)

```
cat /etc/os-release 

NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

cat /proc/version

Linux version 5.15.0-56-generic (buildd@lcy02-amd64-102) (gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #62~20.04.1-Ubuntu SMP Tue Nov 22 21:24:20 UTC 2022
```

**Comment by timothyschoen** [comment]
Normally the sidebar would show you the properties when you select the object with the console open. 

But since the sidebar has gotten a bunch of extra features lately, I agree that it would be a good idea to allow showing them with the properties button in the menu as well!

**Comment by timothyschoen** [comment]
I've changed it so the inspector panel goes above any sidebar panel now, not just the console. You can use the pin at the top if you want to prevent this.

The properties button in the menu will now also show the inspector, although you probably won't need to use that anymore, it's just there for consistency with vanilla.
