### ISSUE TITLE
No access to help patches outside of vanilla, cyclone, else

### ISSUE THREAD

**Issue by jamshark70** [plugdata-team/plugdata#261]
PlugData 0.6.2.

I am able to access my abstractions by:

1. Settings --> Search --> add `/home/xxxxx/Documents/Pd/externals` (where my abstractions live, along with other Deken downloads).
2. Create e.g. [hjh-abs/monitor~].

So far so good.

Then, right-click --> Help --> "Couldn't find help file."

Pd knows where the object came from, and my pack obeys the convention that e.g. monitor~.pd lives alongside monitor~-help.pd.

Pd knows where the abstraction came from, so it should be straightforward to insert `-help` into the path and look for it. But PlugData isn't doing this.

I get the same error if I add `/home/xxxxx/Documents/Pd/externals/hjh-abs` -- then auto-completion works too! But help, nope.

It would be good to have access to help patches other than vanilla, cyclone and else.

**Comment by timothyschoen** [comment]
Thanks for reporting, I agree, this needs to be fixed

**Comment by jamshark70** [comment]
Great, thanks. I plan to run PlugData more over the winter holiday to see if I could use it instead of vanilla in my course (and make bug reports :wink: ).

**Comment by timothyschoen** [comment]
> Great, thanks. I plan to run PlugData more over the winter holiday to see if I could use it instead of vanilla in my course (and make bug reports 😉 ).

Awesome, my current schedule is to finish the next version before the end of the year, and release v0.7.0, (the first beta version) in early February 2023. After that, my focus shift to fixing bugs and Pd compatibility until v1.0.

I'm always happy to receive bug reports, that really helps me to get it to a stable point much faster. Pd is such a dynamic tool that it's hard for me to test everything on my own.

**Comment by timothyschoen** [comment]
Also I fixed this with e810b1425dd2d9ef37153549a1634dd26a6eef0a
