### ISSUE TITLE
Connection & Corner logic issue

### ISSUE THREAD

**Issue by alcomposer** [plugdata-team/plugdata#263]
Currently the user can enter this state:
![connection   corner logic](https://user-images.githubusercontent.com/12004932/206944642-51e61ec0-53fd-4c1b-9362-8f4d488ba5d1.gif)

#### steps to reproduce:
* select object
* click and release on inlet / outlet port
* move cursor to object corner
* click and drag to scale object

**Comment by timothyschoen** [comment]
hahaha wow that's unexpected behaviour. Could be fixed by calling "cnv->cancelConnectionCreation()" when we resize.
