### ISSUE TITLE
Mouse Hold and Drag Reconnect doesn't repaint

### ISSUE THREAD

**Issue by alcomposer** [plugdata-team/plugdata#265]
If a reconnect is entered, and the mouse is held (instead of released) the drag is not repainted

![mouseDown   Drag Reconnect Issue](https://user-images.githubusercontent.com/12004932/206952647-21dc6e28-11d3-4251-9838-40faddd6b26d.gif)

**Comment by timothyschoen** [comment]
I noticed that, I think this is a pretty new bug

**Comment by alcomposer** [comment]
Possibly in `Connection::reconnect()` dragged is not used?
https://github.com/plugdata-team/plugdata/blob/03d17bcf8a7e667dbf0966352a7ea51343f91077/Source/Connection.cpp#L414

**Comment by alcomposer** [comment]
Reconnect bug was introduced in: 2a18ca81 (Finished new auto patch feature)
