### ISSUE TITLE
sidebar bottom icons become `[][]` when too small

### ISSUE THREAD

**Issue by alcomposer** [plugdata-team/plugdata#276]
![Screenshot from 2022-12-20 11-03-00](https://user-images.githubusercontent.com/12004932/208554254-f347ebd0-2008-4f81-8821-4df1d06a26a9.png)

**Comment by timothyschoen** [comment]
I've tested a bit, and I've found that we need at least 200px to make the sidebar useful, so that is now the minimum size. That also fixes this issue!
