### ISSUE TITLE
Blank screen on linux on newer builds

### ISSUE THREAD

**Issue by psethwick** [plugdata-team/plugdata#279]
Blank screen on startup, no crashes/warnings/error messages shown. Doesn't seem to draw. If there's something behind it, it shows what was drawn underneath, just window-dressing with a transparent panel.

System details, not sure how much is relevant:

- Arch linux 5.15.81-1-lts (pretty up-to-date, package-wise)
- Intel integrated graphics
- X11
- herbstluftwm (I'll probably rule this out, shortly)

### Some testing on builds from github actions:
Oldest known broken commit: https://github.com/plugdata-team/plugdata/commit/b517c21b899b50ee474dc96d8133f60ad8d49773
.
(some red builds here)
.
Most recent working commit: https://github.com/plugdata-team/plugdata/commit/e38e25de6e856bd6ff460d95ba84fbcc0dee35e8

**Comment by timothyschoen** [comment]
Could it be the JUCE update? It is inside the range...

**Comment by psethwick** [comment]
it probably is that, trying to confirm that now

**Comment by psethwick** [comment]
I tested with JUCE DemoRunner (e.g. upstream only):
- works on the develop branch (commit 624934b05b0817c085adedac07c711386bcc9591 to be precise)
- blank screen on the 7.0.3 tag on the master branch

For window managers:
Broken:
- herbstluftwm
- awesome
- stumpwm
Working:
- Sawfish

**Comment by timothyschoen** [comment]
> I tested with JUCE DemoRunner (e.g. upstream only):
> 
>     * works on the develop branch (commit 624934b05b0817c085adedac07c711386bcc9591 to be precise)
> 
>     * blank screen on the 7.0.3 tag on the master branch
> 
> 
> For window managers: Broken:
> 
>     * herbstluftwm
> 
>     * awesome
> 
>     * stumpwm
> 
> 
> Working:
> 
>     * Sawfish
> 
> 
> definitely upstream!

That is fantastic news, thanks for figuring that out! I guess I'll move to the develop branch for now, at least until the next version is out. The next version of plugdata is probably coming out sooner than the next JUCE update, I'd like it to work with most Linux WMs.

**Comment by timothyschoen** [comment]
Fixed by moving to the develop branch of JUCE

**Comment by tkna91** [comment]
The window was also displayed in sway. There are a few oddities in the windowing behavior (lack of tiling window manager assumptions in the UI?) but at least I can use it!
```
$ pacman -Q sway-im-git wlroots-git plugdata-git
sway-im-git r7040.bd7466e1-1
wlroots-git 0.17.0.r6053.48a89179-1
plugdata-git r2348.dba2b77e-1
$
```

https://user-images.githubusercontent.com/102382754/210621696-b083823c-c5a1-4147-9109-25039027f767.mp4
