### ISSUE TITLE
Canvas Scrollbars area shown when not needed

### ISSUE THREAD

**Issue by alcomposer** [plugdata-team/plugdata#283]
![scroll_bar_shown_when_not_needed](https://user-images.githubusercontent.com/12004932/209276800-604f9a89-3b7b-45c1-87ef-ce49209b6c0a.gif)

**Comment by timothyschoen** [comment]
I'm aware of this issue, the problem is that JUCE's viewport scrollbars are shown next to the viewed component instead of on top of it. The best way to resolve this would be to create a custom viewport.

**Comment by charlesneimog** [comment]
Hi, I am having a problem that involves scrollbars too. But it is different.

I use plugdata with zoom (170%), and sometimes the Scrollbars disappear when I need them.

https://user-images.githubusercontent.com/31707161/212142087-418525cc-120a-44f2-ae23-c2b50c057709.mp4


The video shows one example when the scrollbars disappear when I need them.

**Comment by timothyschoen** [comment]
@charlesneimog I'm trying to reproduce this, but I'm not getting this bug. Do you know any more specific circumstances when it happens? Or maybe with a specific patch?

**Comment by charlesneimog** [comment]
Weird, it is happening with all patches now, but I really do saw any specific circumstances. 

I am using this version (I am on Fedora)...
![image](https://user-images.githubusercontent.com/31707161/212568264-11712134-5ba1-4399-acb7-432cb2cfbedf.png)


See this video, now seems that just happen when I change the zoom value.

https://user-images.githubusercontent.com/31707161/212568530-6e5a85b1-33a9-4e49-8e27-dda469fae179.mp4

The patch

[bug.zip](https://github.com/plugdata-team/plugdata/files/10421276/bug.zip)

**Comment by timothyschoen** [comment]
I can reproduce it with the patch you sent! Very strange bug, because the canvas size should never change just because of scrolling...

**Comment by timothyschoen** [comment]
Alright, I've managed to fix it by setting the AllowScrollingWithoutScrollbar flag on the viewport. It will still mysteriously hide the scrollbars, but you can now scroll anyway. Not a perfect solution, but at least it's no longer broken.

**Comment by timothyschoen** [comment]
https://user-images.githubusercontent.com/44585538/212569054-2df88588-8a51-4349-8451-9ecd8388a764.mov

**Comment by charlesneimog** [comment]
Great, thank you!

**Comment by timothyschoen** [comment]
Scrollbars are now on top of the canvas instead of next to it!
