### ISSUE TITLE
Comment captures mouse

### ISSUE THREAD

**Issue by alcomposer** [plugdata-team/plugdata#284]
When  a comment box is placed over anther object, the comment will capture the mouseDown when in performance mode:
![comment_captures_mosue](https://user-images.githubusercontent.com/12004932/209288932-32549ea6-1ae9-48a2-a23f-055becf99618.gif)
Placing comments over other elements is used in some of the help files, so using those help files can be problematic, without moving the comments.

**Comment by timothyschoen** [comment]
Fixed!
