### ISSUE TITLE
Mac M1 and Intel compilation problems (sfont~)

### ISSUE THREAD

**Issue by agraef** [plugdata-team/plugdata#299]
I'm trying this for the first time, so bear with me. Any help is appreciated.

I tried to follow the instructions in the README, but it doesn't say anything about dependencies, so I quietly assumed Homebrew since that is what everybody else is using.

On the M1 running macOS Ventura (13.1), it first runs into various issues when trying to build fluidsynth. Even with `cmake .. -DCMAKE_OSX_ARCHITECTURES=arm64` I get a bunch of these:

~~~
/Library/Developer/CommandLineTools/usr/bin/ranlib: for architecture: x86_64 file: /Users/ag/Sources/github/plugdata/build/Libraries/fluidsynth/lib/libvorbis.a(lookup.o) has no symbols
~~~

I'm not sure why it would want to look for x86_64 here, despite my option setting.

Then, a little bit further on, this ominous warning:

~~~
configure: WARNING: Compiler does not support ARM intrinsics
~~~

A few lines further:

~~~
configure: WARNING: *** MPEG (Lame/MPG123) disabled. ***
~~~

I do have Homebrew's lame package installed. The final nail in the coffin then is:

~~~
src/ogg_opus.c:165:10: fatal error: 'opus/opus.h' file not found
#include <opus/opus.h>
         ^~~~~~~~~~~~~
1 error generated.
~~~

That's still during cmake. Again, I do have opus installed.

cmake then goes on to finish, here's the full log: [cmakelog.txt](https://github.com/plugdata-team/plugdata/files/10330725/cmakelog.txt)

If I then try to build with `make` anyway, it fails early on due to a missing fluidsynth include while building ELSE:

~~~
[ 20%] Building C object Libraries/CMakeFiles/externals.dir/ELSE/sfont~/sfont~.c.o
/Users/ag/Sources/github/plugdata/Libraries/ELSE/sfont~/sfont~.c:26:10: fatal error: 'fluidsynth.h' file not found
#include <fluidsynth.h>
         ^~~~~~~~~~~~~~
1 error generated.
make[2]: *** [Libraries/CMakeFiles/externals.dir/ELSE/sfont~/sfont~.c.o] Error 1
make[1]: *** [Libraries/CMakeFiles/externals.dir/all] Error 2
make: *** [all] Error 2
~~~
 
The full buildlog: [makelog.txt](https://github.com/plugdata-team/plugdata/files/10330739/makelog.txt)

I guess that this is to be expected since it failed when building fluidsynth while running cmake. But why would it want to build fluidsynth in the first place if I already have it installed in Homebrew? Shouldn't it pick up the existing package? fluidsynth is installed under Homebrew's default installation prefix, which is /opt/homebrew for the M1:

~~~
ag@mira build % ls /opt/homebrew/include/fluidsynth/
audio.h    ladspa.h   misc.h     seqbind.h  shell.h    version.h
event.h    log.h      mod.h      settings.h synth.h    voice.h
gen.h      midi.h     seq.h      sfont.h    types.h
ag@mira build % ls /opt/homebrew/lib/libfluidsynth.*
/opt/homebrew/lib/libfluidsynth.3.1.4.dylib
/opt/homebrew/lib/libfluidsynth.3.dylib
/opt/homebrew/lib/libfluidsynth.dylib
~~~

On an Intel Mac running Big Sur (11.7.2), I get different errors during cmake ([log](https://github.com/plugdata-team/plugdata/files/10330816/cmakelog.txt)), but the end result is the same: a subsequent `make` fails to find the fluidsynth headers ([log](https://github.com/plugdata-team/plugdata/files/10330820/makelog.txt)).

**Comment by agraef** [comment]
Well, I guess that the issue is with Libraries/ELSE/sfont~. But the README there specifically mentions Homebrew, so the question still is why it's trying to build fluidsynth (and failing) when the fluidsynth Homebrew package is already installed?

**Comment by agraef** [comment]
Ok, with `cmake .. -DENABLE_SFONT=OFF`, cmake and a subsequent make now goes through alright on both M1 and Intel. My guess is that the included fluidsynth source is either too old or needs to be patched up to compile OOTB on the latest macOS versions.

Still, it would be nice to have sfont~ build correctly using a preinstalled fluidsynth from Homebrew. @timothyschoen, @porres, any advice on how to massage Libraries/CMakeLists.txt so that this will work?

**Comment by timothyschoen** [comment]
I'm on M1 Ventura (13.0) myself, it does compile successfully here, I'll try to install the latest update to see if that breaks anything. I do get many of the same warnings you get, lots of "x has no symbols for arch x86_64". Not sure where they come from, I should really investigate that. I do find that the [sfont~] object works on both ARM and x86, so that's why I haven't looked into that yet. I don't get the missing header errors you get, that's where something is really going wrong.

> Well, I guess that the issue is with Libraries/ELSE/sfont~. But the README there specifically mentions Homebrew, so the question still is why it's trying to build fluidsynth (and failing) when the fluidsynth Homebrew package is already installed?

The README is for ELSE's way of building fluidsynth which is a bit different from plugdata's way of building fluidsynth. The existing packages from homebrew only contain dynamic libraries, the reason it builds fluidsynth and all its dependencies from scratch is that I want to link it statically (I am very scared of dynamic linking, as you may have been able to tell). Installing fluidsynth/lame/ogg through homebrew shouldn't be necessary, but it can sometimes help to make sure it finds the headers. In your case it doesn't seem to help though.

You could try clearing out your cmake folder, and try creating an XCode project with cmake instead with the "-GXcode" flag. Sometimes that helps, though I'm not sure why.

**Comment by timothyschoen** [comment]
I could also add a "SHARED_FLUIDSYNTH" flag to link it dynamically, if the static method fails. That would make the version non-portable, since it depends on fluidsynth being installed where homebrew has installed it on your system. Also, homebrew doesn't download universal versions of libraries (they are always the native arch), so it won't work with universal binaries.

**Comment by agraef** [comment]
Unfortunately, `cmake .. -GXcode` doesn't fare much better. On my Intel MB running Big Sur, cmake bails out with the same assembler compilation error as before. On the M1 Air it just doesn't work at all:

~~~
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:33 (project):
  No CMAKE_C_COMPILER could be found.
~~~

This is with the latest Ventura, latest Xcode and command line tools installed, all fully updated. cmake is 3.25.1 from Homebrew, the same that my Intel MB has. Looks like the very latest Xcode version just isn't supported by cmake yet. Bummer.

So it looks like I'll have to live without sfont~ for the time being. It would be nice, though, if you could upload your static macOS fluidsynth build somewhere so that I could maybe get it to work with the CACHED_SFONT option.

**Comment by agraef** [comment]
> I could also add a "SHARED_FLUIDSYNTH" flag to link it dynamically, if the static method fails.

That would be much appreciated as well. :)

> That would make the version non-portable, since it depends on fluidsynth being installed where homebrew has installed it on your system.

It's possible to get that fixed with the otool and install_name_tool utilities. That's what we do in Purr Data. We have a little [script](https://github.com/agraef/purr-data/blob/master/packages/darwin_app/embed-MacOSX-dependencies.sh) (I believe that we originally inherited that from Pd-extended) which does a few iterations to figure out what the dylib dependencies from Homebrew are, copies them over to the bundle, and fixes up the library references in the binary as well as dependent dylibs with install_name_tool, so that it finds all the dylibs inside the bundle. Yeah, it's a bit scary, but it works. ;-)

**Comment by agraef** [comment]
BTW, what is the recommended option to build a native (arm64 only) build? I found that `-DRUN_CLANG_TIDY=ON` works because it disables the x86_64 architecture, but that seems a bit of a kludge. (I don't even have clang-tidy installed.) What's the recommended way to accomplish this?

**Comment by timothyschoen** [comment]
I'm not sure how to do it in cmake, but I know a way to do it in XCode.

<img width="899" alt="Screenshot 2023-01-03 at 12 14 38" src="https://user-images.githubusercontent.com/44585538/210346875-b1180b3d-642e-4221-8f3f-3c6eea199aac.png">

(or remove x86_64 from the "Architectures" list)

**Comment by agraef** [comment]
Well, if there's a way to do it in Xcode then there must be a (better) way to do it in cmake. :)

No seriously, I just thought that there might be an option in the cmake config that I overlooked. This should be easy enough, I can just add another option like NATIVE=ON or UNIVERSAL=OFF which massages the architectures list accordingly. For now, TIDY_CLANG works for me, but I'll look into that asap.

**Comment by agraef** [comment]
Ok, after digging a bit deeper and disabling the OUTPUT_QUIET flag, I think I understand now where the problem is. sndfile's configure will look for the header files of opus using pkg-config, and on current Homebrew this gives:

~~~shell
% pkg-config --cflags opus
-I/opt/homebrew/Cellar/opus/1.3.1/include/opus
~~~

But the src/ogg_opus.c in the bundled sndfile source has these includes:

~~~c
#include <opus/opus.h>
#include <opus/opus_multistream.h>
~~~

Which explains this error which I keep getting during `cmake ..`:

~~~
src/ogg_opus.c:165:10: fatal error: 'opus/opus.h' file not found
#include <opus/opus.h>
         ^~~~~~~~~~~~~
1 error generated.
~~~

I tried to change ogg_opus.c to fix this, to no avail because the sources get unpacked every time `cmake ..` is run. 😒

Of course, the main issue here is that you build the static libs by just running all the configure scripts without adjusting the include paths to point to the proper header files *in the bundled source*. So it will pick up whatever is installed in the system instead, which might not always match what's in the bundled source. 🤦

In any case, the proper fix (fix up all those include paths of all bundled sources, not just for sndfile) seems to be a lot of work, so instead I just linked /opt/homebrew/include/opus to /opt/homebrew/include/opus/opus to make the compiler happy, which is a HUGE KLUDGE, but anyway, it makes the compile go through. Makes my Homebrew wanna cry, though. 😢

I wonder why the compile works for you, though. If you keep your Homebrew updated, it shouldn't. Or maybe you applied the same kludge at some point? 😉

**Comment by timothyschoen** [comment]
> I wonder why the compile works for you, though. If you keep your Homebrew updated, it shouldn't. Or maybe you applied the same kludge at some point? 😉

And perhaps more shockingly, why it works on the Github Actions runner! I don't need any hacks to make this work, which is strange.

Thanks for figuring it out, I'll fix this soon

**Comment by chee** [comment]
i've experienced this same thing, btw, and mentioned it over in this thread: https://github.com/plugdata-team/plugdata/issues/173#issuecomment-1264418192

**Comment by agraef** [comment]
Ok, so this is probably a duplicate of that issue.

**Comment by timothyschoen** [comment]
I'm now strongly considering moving from FluidSynth to [FluidLite](https://github.com/divideconcept/FluidLite).

It supports less file types (no MP3), but really takes the pain out of compilation, and it looks like it supports all the fluidsynth features that the [sfont~] object exposes.

**Comment by porres** [comment]
hmmm, seems interesting, does it make easier to compile statically?

**Comment by agraef** [comment]
Good idea. We might consider that for Purr Data's fluid~, too.

I'm a bit worried about sysex support in the lite version, though. I only care about fluidynth's MIDI Tuning Standard support, to be precise. I'm really using that a lot, it's important for my music and musicology students as well. But then again there's always Qsynth if needed. Still, it's nice to have that available in Pd without having to rely on external software.

**Comment by agraef** [comment]
Well, the code for the sysex handling and tuning is at least included, so it should work I guess.

**Comment by timothyschoen** [comment]
> hmmm, seems interesting, does it make easier to compile statically?

A lot easier! It's just a bunch of source files to add now, nothing more.

> Well, the code for the sysex handling and tuning is at least included, so it should work I guess.

Some of the function names for tuning are different, that's the only thing I had to change to make it work. I also still have to verify that the tuning actually works. But other than that it has all the essential features.

**Comment by timothyschoen** [comment]
(closing this because this must certainly have solved the compilation issue)

**Comment by porres** [comment]
> Good idea. We might consider that for Purr Data's fluid~, too.

it'd be nice if you could also offer it as a statically linked external, it could be easily used in Pd-Vanilla then as well.

It seems pd-ceammc does statically link their version (with the conflicting same [fluid~] name).

**Comment by agraef** [comment]
Well, I might do that someday when I have some copious spare time, but vanilla users just need to install ELSE to have sfont~, which seems to be pretty much on par with Purr's fluid~ functionality-wise. The only thing that fluid~ has going for it is that it takes symbolic input, not just raw MIDI bytes, which simplifies some use cases. And that it allows you to change internal fluidsynth parameters. But those features could also be added quite easily to sfont~, I guess.

**Comment by agraef** [comment]
> (closing this because this must certainly have solved the compilation issue)

Works over here on the Mac without any hitches or opus/opus kludges, thanks!

**Comment by agraef** [comment]
Hmm, @timothyschoen, it looks like the latest HEAD apparently went back to pd-lua 0.11.1, did you accidentally commit the wrong submodule hash again?

**Comment by timothyschoen** [comment]
Oh crap, I keep forgetting! Fixed it!

**Comment by agraef** [comment]
Nope, still the wrong one. Let me send you a PR for that.

**Comment by porres** [comment]
> The only thing that fluid~ has going for it is that it takes symbolic input, not just raw MIDI bytes, which simplifies some use cases. 

I don't think I need to add this because in else you can also use something like [note.out] to codify notes. I should add this to the documentation. One way or another, people might want to use the very same object without adapting in Vanilla and using in both PurrData (or Pd-L2ork) and Vanilla - by the way, is Purr Data still in active development and parallel to Pd-L2ork?

**Comment by agraef** [comment]
Yes, it is. In fact I just released [Purr Data 2.18.0](https://github.com/agraef/purr-data/releases/tag/2.18.0) on GitHub.

**Comment by porres** [comment]
> Yes, it is. In fact I just released [Purr Data 2.18.0](https://github.com/agraef/purr-data/releases/tag/2.18.0) on GitHub.

wow, well, I was waiting for a possible release update and I was wondering if the actuall application could then be renamed to "purr data" instead of "pd-l2ork" to avoid confusion and make the distinction better. I guess this is a topic for the pd-l2ork list or something :)

**Comment by timothyschoen** [comment]
> Yes, it is. In fact I just released [Purr Data 2.18.0](https://github.com/agraef/purr-data/releases/tag/2.18.0) on GitHub.

Nice, congrats! I see M1 is now supported, I'm very happy with that, the previous version I tried on M1 would take about 5 restarts to start up.

**Comment by timothyschoen** [comment]
I do wonder what the difference is with the new Pd-L2Ork that was released recently?

**Comment by agraef** [comment]
Ico's Pd-l2ork 2 was forked from Purr some time in 2020 IIRC. He wanted to work on the JS GUI with some rather disruptive changes we (Jonathan and me) didn't really understand, and so we were worried we wouldn't be able to maintain that code any more. That's why the fork happened.

Pd-l2ork is based on a 2yr old version of Purr at this point, although Ico has backported some of our changes, such as the autocompletion feature which we added during GSoC 2021. OTOH it has the K12 educational mode which is great if you're teaching young people, and its GUI is different in some ways.

I can't tell you much about that version, since I haven't used it myself, but I hear that some people like it, and use it alongside Purr, probably for its K12 mode.

**Comment by agraef** [comment]
> I see M1 is now supported

Well, kind of. ;-) I made sure that it actually compiles on Apple Silicon, and that the x86_64 build runs nicely in Rosetta 2 on the M1.

But the JS runtime we use (nw.js) is only available in x86_64 right now, and that version just doesn't seem to work at all with a native M1 build of the realtime engine, so the native engine crashes a lot in this combo. I'm not sure what causes this, but it seems that we'll just have to wait for a native M1 build of nw.js to see whether we can get it to work together with a native build of the engine.

**Comment by agraef** [comment]
NB: I'm actually building the x86_64 version of Purr on my M1 Air, too, because it's so much faster than my 2013 Intel MB Pro. ;-)
