### ISSUE TITLE
Feature: add heavylib to hvccMode safe found objects/abstractions

### ISSUE THREAD

**Issue by dromer** [plugdata-team/plugdata#313]
So that https://github.com/plugdata-team/plugdata/blob/main/Source/Utility/SuggestionComponent.h#L395-L405 works.

Ideally we allow all safe abstractions from the Path, but we probably need a way to cache this result somehow.

**Comment by timothyschoen** [comment]
I've added the heavylib objects to the compatible objects. When checking for compatibility, this will not be used, because it will see any abstraction as a "canvas", but they will show up in the suggestions this way.

**Comment by dromer** [comment]
Need to do a compatibility round of the heavylib help files. Some of them use incompatible objects for the example, which is a bit silly ;)

Like `[vline~]` which should be replaced by `[hv.line]`.

**Comment by timothyschoen** [comment]
> Need to do a compatibility round of the heavylib help files. Some of them use incompatible objects for the example, which is a bit silly ;)
> 
> Like `[vline~]` which should be replaced by `[hv.line]`.

Oof yeah that sounds like a bad idea
