### ISSUE TITLE
Initialization order

### ISSUE THREAD

**Issue by agraef** [plugdata-team/plugdata#315]
This is probably down to the way JUCE initializes things which, if I understand this correctly, are distributed among the PdInstance and PluginProcessor constructors in plugdata.

Anyway, here are two issues with the initialization order that I keep noticing. They aren't really showstoppers for me, more like paper cuts, and I have work-arounds for each of them, but they're still annoying enough that I decided to report them in the hope that there's an easy fix for them.

## Missing data files

This happens with both the standalone and the plugin when they're run for the first time, i.e., when the plugdata libray directory doesn't exist yet. The problem is that the external initialization (calling the various setup routines) is done right at the beginning of the Instance::Instance() constructor, when the default content for the library directory hasn't been populated yet -- this only happens in the PluginProcessor::PluginProcessor() constructor later.

The symptom is that an external won't be properly initialized if it is looking for data files in the library directory which doesn't exist yet. This affects, in particular, pdlua which needs its pd.lua file to work at all.

To reproduce this, just make sure to get rid of the plugdata library directory, then launch the standalone, and try to create a [pdlua] object in it:

![image](https://user-images.githubusercontent.com/2853977/210696949-2352e086-c05b-43e4-90a8-48cbf7977fc8.png)

The work-around in this case is to just close the standalone or plugin and reopen it. The second time around the data files are all there, so the externals initialize properly. That's easy enough, if a bit annoying.

A proper remedy would be to move the external initialization from Instance::Instance() to a point in PluginProcessor::PluginProcessor() where the data files have been unpacked already. I'm not sure whether that has other unwanted side-effects, though.

## Can't find abstractions in a patch directory

This only happens in the plugin. Try loading a patch which uses some abstraction in the same directory. Of course the main patch is supposed to find the abstraction since it's in the same directory, and this actually works in the standalone. It also works in the plugin when you first open the main patch. If you then save the parent project (DAW session, Bespoke state, whatever) and reopen it at a later time, the main patch is still there in the plugin, but the abstraction fails to be found. E.g., here's how it looks like in Bespoke when that happens:

![image](https://user-images.githubusercontent.com/2853977/210696462-700bff7c-73bb-4ad2-af39-c9ff0a5a28e4.png)

Here's the Bespoke state file for this, it's a very simple project with just one plugdata instance with a simple main patch test-synth.pd and the voice.pd abstraction in it:

[bespoke-plugdata.zip](https://github.com/plugdata-team/plugdata/files/10349056/bespoke-plugdata.zip)

I'm not sure why this happens, but I can imagine that it's another issue with the initialization  order. There are actually three ways to work around this, from super-annyoing to mildly meh:

- Open the plugin GUI, close the main patch in it and reopen it. This time it will find the abstraction and things work alright. Super annyoing, since you have to do it every time you open the project, for all plugdata instances which have this issue.
- In the plugdata plugin, open the abstraction first, then the main patch. If the project is saved with this plugdata state, it will reopen correctly. Still untidy and very annoying, especially if you have a lot of plugdata instances with a lot of different abstractions in them.
- Add the path to the abstraction to the global search path. Meh, because you'll have to add a search path for every abstraction used anywhere, and have them visible at all time for all plugdata instances.

I'm not sure what the proper remedy is here, since it involves both plugdata and the libpd code which actually loads embedded abstractions.

**Comment by agraef** [comment]
Thinking about the second issue some more, this might be more to do with the way the plugdata plugin state is stored, since it seems to include the main patch verbatim instead of a pointer to the patch file. I also tried to work around this by saving a plugin preset in Bespoke, but that didn't help either.

**Comment by timothyschoen** [comment]
Thanks for reporting these, some pretty annoying issues indeed.

> Thinking about the second issue some more, this might be more to do with the way the plugdata plugin state is stored, since it seems to include the main patch verbatim instead of a pointer to the patch file. I also tried to work around this by saving a plugin preset in Bespoke, but that didn't help either.

You're right about this, I have to store the patch itself because I can't assume the .pd file will still exist, or be in the same location. And you can also create a patch from scratch, and not save it to a file at all. My current workaround is that it adds the current path of the patch to the search paths before loading, but something might be going wrong there.

**Comment by agraef** [comment]
> My current workaround is that it adds the current path of the patch to the search paths before loading, but something might be going wrong there.

Care to enlighten me where that code is? Maybe I can spot something. Slim chance, I know, but I'm good at those things. ;-) And if I don't, I can just add some logMessage() calls to see what exactly is going on there.

**Comment by timothyschoen** [comment]
These lines in PluginProcessor::setStateInformation will save the patch content and patch file:


<img width="624" alt="Screenshot 2023-01-05 at 13 27 53" src="https://user-images.githubusercontent.com/44585538/210780224-0e424ea7-82f4-48dd-8d13-dfe65be54a7d.png">

And these lines in PluginProcessor::getStateInformation will read the patches and the paths.

<img width="746" alt="Screenshot 2023-01-05 at 13 28 44" src="https://user-images.githubusercontent.com/44585538/210780368-1d97ce44-797e-48a6-9e0f-708928c2ac12.png">


And I think I can already spot the mistake here: the patch gets loaded before we add the search path!

**Comment by timothyschoen** [comment]
It would also be preferable to set the search path specifically for that canvas, otherwise it might load the wrong abstractions on another patch.

**Comment by agraef** [comment]
Tim, if you can work on this second issue (which I consider the much more important one), I'll have a look at how to move the external setup stuff in order to fix the 1st issue. Ok?

**Comment by agraef** [comment]
Rev. c278b206dc9001d551efaf03812bac34ad47e66f does it for me, 2nd issue solved, thanks! The 1st issue is addressed in #321, as promised.

**Comment by timothyschoen** [comment]
Nice, glad to have all this sorted out

**Comment by agraef** [comment]
I'm afraid that we have to revisit this. Have a look at plugdata-multi-2022-12-30_22-03.bsk in this project:

[bespoke-plugdata2.zip](https://github.com/plugdata-team/plugdata/files/10358507/bespoke-plugdata2.zip)

This has *second* plugdata instance of synth-test.pd in it. The original instance (panned left) now exhibits the same issue as before (voice abstraction not instantiated), where the second instance (panned right) loads fine.

**Comment by agraef** [comment]
Screenie:

![image](https://user-images.githubusercontent.com/2853977/210957444-ce17da88-9dc5-4d3e-b4c2-e7459fbce900.png)

**Comment by agraef** [comment]
@timothyschoen I'd like to reopen this issue, but I can't, I think only you can do that.

**Comment by timothyschoen** [comment]
I think I've found it, we need to call Instance::setThis() to make sure the search path actually gets set on the correct Pd instance.

**Comment by timothyschoen** [comment]
I'm no longer able to reproduce it after 896d8b50fc8c014184e10373e079f7951d4e40bb, so that's good!

**Comment by agraef** [comment]
That seems to have done it now, congrats!
