### ISSUE TITLE
Gui interaction zone in run mode

### ISSUE THREAD

**Issue by 60-hz** [plugdata-team/plugdata#320]
Many times, I found that some ui objets are not very responsive on click, just because the size ist small and the inlets/outlets are preventing the click to interact with the object behind.
Would it be possible to allow all the object zone to interact in run mode?

An exemple of small ui size that trigger this issue:
<img width="99" alt="Capture d’écran 2023-01-05 à 15 48 44" src="https://user-images.githubusercontent.com/5449719/210809083-0619e6aa-751b-4a9b-94bf-9fc2dac69b29.png">

**Comment by timothyschoen** [comment]
I agree, there's currently some behaviour for scaling inlets/outlets when an object has many of them, and is also very small:

<img width="92" alt="Screenshot 2023-01-05 at 16 55 01" src="https://user-images.githubusercontent.com/44585538/210824028-10106d0f-6951-4265-914b-08bfd5ce4153.png">

Making inlets/outlets pass clicks through in run mode seems like a great solution to me, don't know why I hadn't thought about that yet!

**Comment by timothyschoen** [comment]
<img width="301" alt="Screenshot 2023-01-05 at 18 42 40" src="https://user-images.githubusercontent.com/44585538/210845632-ff003120-ef2d-4a55-960f-cce54ed6e2c6.png">

They scale propertly now, and also pass through mouse clicks in run mode. Thanks for reporting!
