### ISSUE TITLE
port [pd~] to plugdata

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#328]
This could actually open "real" Pd instead, like camomile's latest test and unreleased (actually abandoned) version does.

**Comment by timothyschoen** [comment]
I've taken a look at [pd~] and I agree, it would be a great addition.

**Comment by porres** [comment]
for reference

see https://github.com/pierreguillot/Camomile/discussions/233

and https://vimeo.com/showcase/4639971

**Comment by timothyschoen** [comment]
Cool, I still can't really see anything in the code here, is it mostly handled by the [subprocess] subpatch?

**Comment by porres** [comment]
not sure what you ask

**Comment by timothyschoen** [comment]
it works now :)

**Comment by porres** [comment]
YEAH!!!!
