### ISSUE TITLE
Switching mecanism for "Properties" 

### ISSUE THREAD

**Issue by 60-hz** [plugdata-team/plugdata#337]
There is a "Properties" choice when right clicking any gui object.
But the current behavior is: automatic show the property panel when the user click any object box, which make the "Properties" entry from the menu useless... a click on empty space of the patch show the print console back.

Which behavior should be the best? Using "Properties" from the menu OR auto switching to property panel on mouse click?

**Comment by timothyschoen** [comment]
The "Properties" option in the menu is only there so you can open the properties of a canvas. It is set up so it also shows the properties of an object (if not already visible), though I think that's pretty much never necessary.

I could rename it to something like "Canvas Properties"?

**Comment by 60-hz** [comment]
Ok, of course canvas properties are useful... So maybe leave it like that is ok.
I see that right clicking on message have grayed Properties entry, but not for gui.

**Comment by timothyschoen** [comment]
Just gonna leave this as it is for now
