### ISSUE TITLE
no parameters in lv2 version on reaper

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#342]
unlike the vst version, you can't control the parameters of the lv2 version in reaper (reaper 6.73 on void linux)
vst:

![Screenshot_2023-01-20_10-32-42](https://user-images.githubusercontent.com/86204514/213651530-816ac22f-ff94-45bd-b632-5bac3e8bc521.png)
lv2:

![Screenshot_2023-01-20_10-33-18](https://user-images.githubusercontent.com/86204514/213651558-17155a09-0d21-4a9f-9f9a-d73eb90f5b96.png)

**Comment by haenkel** [comment]
This is currently true for all LV2 plugins built with JUCE.
JUCE have decided to use a newer aproach for the parameter handling (patch/property...something),
which reaper doesn't support yet.

**Comment by tomara-x** [comment]
aah! so it's not an issue on our side, thank you for clarifying that!

**Comment by haenkel** [comment]
This is now supported in the reaper dev branch (as of today)
