### ISSUE TITLE
Compile Mode Error

### ISSUE THREAD

**Issue by dimdieo** [plugdata-team/plugdata#344]
Thank you very much for the update, really impressive!

I tried to compile in C++  a simple patch that opens a sound file and plays it, but I get an error.

```
usage: Heavy [-h] [-o OUT_DIR] [-p SEARCH_PATHS [SEARCH_PATHS ...]] [-n NAME]
             [-m META] [-g GEN [GEN ...]] [--results_path RESULTS_PATH] [-v]
             [--copyright COPYRIGHT]
             in_path
Heavy: error: unrecognized arguments: Stems
```
I understand that the compiler does not support  `readsf~`
Is the list of supporting objects the same as that of hvcc?

Are there other objects that can read sound files?

**Comment by timothyschoen** [comment]
Hi, thanks!

You can find a list of supported objects here: https://github.com/Wasted-Audio/hvcc/blob/develop/docs/09.supported_vanilla_objects.md

Unfortunately [readsf~] is not on there :(

**Comment by 60-hz** [comment]
[table] is in the list of compatible object, when creating the object in compile mode, this message is printed:
`Warning: object "graph  -> array" is not supported in Compiled Mode`

Since [readsf~] is not in the list, nor [soundfiler], I don't think playing a soundfile is currently possible...
