### ISSUE TITLE
Installer asks to install Rosetta 2

### ISSUE THREAD

**Issue by postprivee** [plugdata-team/plugdata#347]
tried release+pre release versions. both require rosetta. is it possible to compile to native binaries?

**Comment by timothyschoen** [comment]
The installer for some reason asks to install Rosetta, but the actual binary it installs is a universal binary, so it should run natively on both ARM and x64.

I don't know why the installer asks for this, does it always do this for universal binaries?

**Comment by timothyschoen** [comment]
Found the solution here: https://github.com/fish-shell/fish-shell/issues/8566

Should be fixed!

**Comment by timothyschoen** [comment]
Tested it, and can confirm that this fixed it

**Comment by postprivee** [comment]
fixed! thanks @timothyschoen
