### ISSUE TITLE
Comment sometimes has wrong width

### ISSUE THREAD

**Issue by chkworks** [plugdata-team/plugdata#348]
I am currently making my way through the tutorials of the ELSE library and also tried to open them in Plugdata (as I am actually really curious about this project). They are kind of messed up and misplaced, is this something it has to be done within the file or is something off with how Plugdata displays the patches?

**Comment by chkworks** [comment]
<img width="1192" alt="Bildschirmfoto 2023-01-10 um 20 47 44" src="https://user-images.githubusercontent.com/5701406/211818941-84dbbf74-68a4-4fe1-a30e-803b0ed8aa4c.png">

**Comment by tomara-x** [comment]
hmm.. at first i assumed that's a mistake in some of the files, but now i'm testing in vanilla and yeah, it seems we have an issue with some comments not having the right width

**Comment by tomara-x** [comment]
the more i know, the less i'm certain. i notice the ones ending in just a semicolon (like those in boxes) are the problematic ones. but the ones ending in `, f xx;` do function right even if they're too long
![Screenshot_2023-01-11_18-44-36e](https://user-images.githubusercontent.com/86204514/211867036-f43aff45-04f5-4306-bfd8-77a7f446101a.png)

**Comment by timothyschoen** [comment]
Thanks for reporting!

> i notice the ones ending in just a semicolon (like those in boxes) are the problematic ones. but the ones ending in `, f xx;` do function right even if they're too long

That helps! ```, f xx;``` after a comment indicates the width of the comment in text characters, so it makes sense that these work and the others don't.

**Comment by chkworks** [comment]
So it is indeed a problem with the tutorials files? Makes me wonder though why they are rendered in Pure Data nicely, is there something like a maximum width for comment boxes?

**Comment by timothyschoen** [comment]
> So it is indeed a problem with the tutorials files? Makes me wonder though why they are rendered in Pure Data nicely, is there something like a maximum width for comment boxes?

Oh no, the problem is definitely plugdata! Pd-vanilla is the standard, so if it works there, we should make sure it will also work in plugdata.

**Comment by porres** [comment]
it seems PlugData screws up when comments don't have a width argument. In Vanilla a default max size is used in this case and plugData is wrong about it. Anyway, the title of this issue should be something "ELSE" :)

**Comment by timothyschoen** [comment]
> In Vanilla a default max size is used in this case and plugData is wrong about it

I didn't know it worked like that, that also helps. I'm still not sure what this max width is though?

**Comment by porres** [comment]
> I'm still not sure what this max width is though?

it defaults to 60 characters size

https://github.com/pure-data/pure-data/blob/master/src/g_rtext.c#L162

**Comment by timothyschoen** [comment]
<img width="1246" alt="Screenshot 2023-01-14 at 10 26 33" src="https://user-images.githubusercontent.com/44585538/212469180-e01ee073-5853-4381-b199-29f65cfe9266.png">

Fixed!
