### ISSUE TITLE
Some cyclone objects in red

### ISSUE THREAD

**Issue by paradiddle16** [plugdata-team/plugdata#351]
number~
mtr~
buffer~
funbuff~

a few help files for objects point to a cyclone-help box in red.

Just went through all of them.

**Comment by timothyschoen** [comment]
Thanks for reporting, I'm gonna do a reupload of v0.6.3 soon, I'll make sure to fix this!

**Comment by timothyschoen** [comment]
[funbuff~] and [mtr~] are not existing cyclone objects (or Max objects), I think those are mistakes in the help files. @porres?

[number~] and [buffer~] are now back in plugdata though.

**Comment by timothyschoen** [comment]
Ah I think you meant [mtr] and [funbuff] without ~, I see that those are missing as well. Working on a fix!

**Comment by paradiddle16** [comment]
Ok I didn't know. I was just going through the help file out of curiousity and noticed that. It's such an amazing project, just trying to contribute.  Anyways, no hurry from my part. Cheers!

**Comment by timothyschoen** [comment]
<img width="299" alt="Screenshot 2023-01-13 at 12 45 46" src="https://user-images.githubusercontent.com/44585538/212313158-1c376f80-acf3-48b6-9365-e18e1a0772c1.png">

Should be working again, thanks for reporting!
