### ISSUE TITLE
[function] loses send/receive symbols

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#352]
setting send/receive symbols to a function object from the sidebar, then saving and reloading the patch, those symbols get lost
![they gone](https://user-images.githubusercontent.com/86204514/212255386-7166783b-cc29-4184-8ae0-2c0ad9ddf742.png)
even when set with messages, i still need to click the send message after loading the patch for this to work
![Screenshot_2023-01-13_08-59-59](https://user-images.githubusercontent.com/86204514/212257562-7ee8598e-d62c-4b3b-9c23-0194e8650251.png)
test patch: [function-send.pd.txt](https://github.com/plugdata-team/plugdata/files/10409030/function-send.pd.txt) (will work fine in vanilla)
(looking at which, why does [function] also lose this initial point state after reloading the patch (loads as a flat line), even though it's saved in the object text? it would be really cool if it had the "initialize" option like numboxes)

**Comment by timothyschoen** [comment]
Should be with a1b425e!

**Comment by tomara-x** [comment]
no, sadly that didn't do it. it makes new function objects have both snd and rcv symbols as "empty" but it doesn't solve the issue. also i notice when setting a symbol for them, then saving, then closing the patch, i get the error "symbol-name: couldn't unbind"

another thing, list objects will remember their symbols after a reload, but the sidebar area will appear empty

**Comment by timothyschoen** [comment]
Could you try e96bf7a? I think that really fixes it!

**Comment by timothyschoen** [comment]
Oh wait, try 1ed1749, that should also fix the problem with listbox/floatbox/symbolbox not remembering send/receive!

**Comment by tomara-x** [comment]
you're on a roll today! nice work!

something about atoms though, now if i set the receive for a list object, and when reloading the patch, both send and receive are that symbol (lots of infinite loop errors)

**Comment by timothyschoen** [comment]
> you're on a roll today! nice work!

:)

I'm gonna try to do the reupload for v0.6.3 out today, so the more issues I can fix, the better! So I'm also very happy to get these reports!

Looks like I swapped the send/receive symbols, should be fixed with the last commit.

**Comment by tomara-x** [comment]
yay! good idea, lots of improvements. glad i can help :3

yeah works nicely now! thank you

**Comment by tomara-x** [comment]
side question, if i understand this correctly, what if someone is evil enough to call their symbol "empty"?
https://github.com/plugdata-team/plugdata/commit/e96bf7a2bb9d18c23a7de057450a2e09bc9fb6fc#diff-2f0bf3a240b69399e40c2e9aa3ab3bb7c0ecc43d1eac5c3760cf52912f5a98afR64

**Comment by timothyschoen** [comment]
I thought so, I think it does the same in Pd-vanilla :(

**Comment by timothyschoen** [comment]
Problems are solved now though!

**Comment by tomara-x** [comment]
yeah i think it's expected since that's what vanilla uses to denote a non-existing symbol. i think it's funny, kinda like null

yeah all working great now
