### ISSUE TITLE
graph on parent shows connection cords

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#353]
> so it hides object boxes, message boxes and cord connections, but other GUI elements are shown (including arrays, atom boxes and comments)

everything else works right
![Screenshot_2023-01-13_13-36-24](https://user-images.githubusercontent.com/86204514/212311646-79000c7b-ce93-4b27-bea1-959ff17b72f2.png)
![Screenshot_2023-01-13_13-36-44](https://user-images.githubusercontent.com/86204514/212311664-ed25c297-b900-4a25-bc4a-0abcd67f2550.png)

**Comment by timothyschoen** [comment]
ohh that's a bad one, thanks for reporting!

4032746 fixes it
