### ISSUE TITLE
Windows 10: v0.6.3 doesn't run with "Microsoft C++ Runtime Error"

### ISSUE THREAD

**Issue by fotisandstuff** [plugdata-team/plugdata#355]
Hello! I updated PlugData to both the latest release (v0.6.3) and the latest nightly as of this post, but the standalone version doesn't run at all and Reaper v6.73 shows a "Microsoft C++ Runtime Error" when trying to scan the VST3's. I updated to the latest C++ Redistributable and still nothing. I had to roll back to v0.6.2. I use Win 10 x64.

**Comment by timothyschoen** [comment]
That's disappointing, I can run it here on both my Windows 10 and Windows 11 installations, so that makes it hard for me to find out what's going on

**Comment by timothyschoen** [comment]
I hope to find out what's causing this, since I'm going to create a small update soon with important fixes.

Do you happen to have any other Windows installations that you could test it on?

**Comment by timothyschoen** [comment]
Okay, I'm now linking the Windows Runtime statically, so it will no longer have to find DLL's, I'm hoping that will solve the issue.

Could you try this one when it's done?

https://github.com/plugdata-team/plugdata/actions/runs/3918778711

**Comment by timothyschoen** [comment]
Hold on, that one didn't work yet :(

**Comment by timothyschoen** [comment]
If you get the latest nightly build now, it should work!

**Comment by fotisandstuff** [comment]
Nope, still doesn't work

**Comment by timothyschoen** [comment]
:(

Thanks for trying it though

**Comment by timothyschoen** [comment]
<img width="1036" alt="Screenshot 2023-01-16 at 05 06 43" src="https://user-images.githubusercontent.com/44585538/212596573-b4dc38fb-ad18-48a3-9a03-5a6b2080438a.png">

Here I have plugdata installed in a Windows 8.1 VM, clean install, no Visual C++ Redistributables

So the problem must be something else.

**Comment by fotisandstuff** [comment]
I fixed it!!! Turns out my antivirus (Kaspersky) was blocking both the installer AND the standalone. I whitelisted them both, did a clean install and both the standalone and the VST3's work perfectly. Thank you!!!

**Comment by timothyschoen** [comment]
> I fixed it!!! Turns out my antivirus (Kaspersky) was blocking both the installer AND the standalone. I whitelisted them both, did a clean install and both the standalone and the VST3's work perfectly. Thank you!!!

Nice!!! Thanks for letting me know!
