### ISSUE TITLE
please port/fix else/display

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#356]
This is a very important object used in ELSE's documentation (help files and live electronics tutorial), but it can't resize properly and I don't know why, probably some incompatibilty/issue with Vanilla since this is an abstraction that uses canvas ([cnv]) and its label.

**Comment by timothyschoen** [comment]
I think the problem is that the "vis_size" and "coords" messages are currently not implemented, I'll see if I can fix that.

**Comment by timothyschoen** [comment]
Done!

It required some improvements to plugdata, but also a small change to [display]
