### ISSUE TITLE
else's slider2d's y value is flipped

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#359]
I don't know why but slider2d behaves differently, in ELSE 'y' value is counted by increasing from bottom to top, in plugdata this is inverted

![Screen Shot 2023-01-14 at 12 55 51](https://user-images.githubusercontent.com/5360142/212481280-72d67084-ff3c-4ba7-a55d-7340196b8cff.png)

**Comment by porres** [comment]
multi.vsl has the same issue and is even worse, I guess the bottom issue is that they use [else/pad] so the problem might be in it.

**Comment by timothyschoen** [comment]
> multi.vsl has the same issue and is even worse, I guess the bottom issue is that they use [else/pad] so the problem might be in it.

That's probably it!

**Comment by timothyschoen** [comment]
Fixed!
