### ISSUE TITLE
mtx.ctl blew up plugdata

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#362]
to reproduce, open help file, click on a cell to activate, then click 'clear' message, you will see that the activated cell is still there, so it doesn't work (and maybe we should just see why and fix it). Now, if you click on the activated cell to deactivate it, plugdata blows up, this is what I got...

[error.zip](https://github.com/plugdata-team/plugdata/files/10418174/error.zip)

**Comment by timothyschoen** [comment]
This one is a mystery, I'm not going to be able to solve this before the next release :(

I'll have another look later though!

**Comment by porres** [comment]
I can help you later as well

**Comment by timothyschoen** [comment]
Fixed with 569ae848f6f905cb10810fc75ce674f27b9da6c2

I didn't support the "clear" message to canvas yet, that's fixed now!
