### ISSUE TITLE
[pic] is it ported? why can't it find files in the help file?

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#363]
pic's seems to be ported as it displays a "?" image, but I couldn't get it to open files and it also complains it can't find files in the help file (which means they might not be there somehow)

**Comment by timothyschoen** [comment]
I did an implementation for [pic] ages ago, but I didn't completely finish it, so it's been broken for a while

**Comment by porres** [comment]
I see you're aware and put it in the list... now this issue should just fix the missing or can't find files

**Comment by timothyschoen** [comment]
Pic now kinda works and it can find the helpfile resources, I only still need to implement all the properties.
