### ISSUE TITLE
else/pad   phantom behaviour when outside GOP zone in subpatch

### ISSUE THREAD

**Issue by jyg** [plugdata-team/plugdata#368]
Let's have a patch with a gop subpatch. If you click on a pad inside the gop area, everything is ok.
Then if then you drag to the position of a second pad (but this one ishidden because outside the GOP area), this "phantom" pad will send data when mouse is over it's position.
(This behaviour only with plugdata, not with puredata vanilla)

![image](https://user-images.githubusercontent.com/1431894/212568502-443dbacb-727f-4734-b504-886967df9140.png)

[test-pad.pd.txt](https://github.com/plugdata-team/plugdata/files/10421253/test-pad.pd.txt)

**Comment by timothyschoen** [comment]
Thanks for reporting, I've fixed it with b3c036d: it now checks if the mouse-down event was on the pad, otherwise it will ignore the mouse event.
