### ISSUE TITLE
comment still bad?

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#370]
If I create a comment in 0.6.4 and start typing, it doesn't break the line when reaching the limit of 60 characters

**Comment by timothyschoen** [comment]
This is because plugdata will itself always assign a number to the width, its just easier that way. Also, in plugdata it won't get limited to 60 characters, but to the width of 60 characters in Pd's font, if that makes sense.

What matters is that if it finds a width of 0 in the patch, it limits it to the width 60 characters.

**Comment by porres** [comment]
so if I save the patch and reopen, it finds this limit?

**Comment by porres** [comment]
oh, I see it breaks when you click outside

**Comment by porres** [comment]
why not break while editing it?

**Comment by porres** [comment]
> oh, I see it breaks when you click outside

no it doesn't not sure whay that happened

**Comment by porres** [comment]
I think this is still a bug then, patch created in plugdata opens with lines broken in vanilla but keeps a single line in plugdata when reopening, this means that vanilla comments get displayed wrong


![Screen Shot 2023-01-15 at 23 45 01](https://user-images.githubusercontent.com/5360142/212587657-64cbf835-bf35-4865-b845-e78ca723822a.png)

**Comment by porres** [comment]
can we reopen this?

**Comment by timothyschoen** [comment]
> I think this is still a bug then, patch created in plugdata opens with lines broken in vanilla but keeps a single line in plugdata when reopening, this means that vanilla comments get displayed wrong

No it doesn't!

plugdata and Pd have different fonts, so there will always be some difference in the line-wrapping. As long as Pd-vanilla has more wrapping than plugdata, there shouldn't be many layout problems. What's important, and what's good here, is that the width is the same.

**Comment by porres** [comment]
I think I get it now, but I still find it weird that you can create a comment and start typing in it forever and it will never break a line. Why is it hard to check for a 60 character limit or something?

**Comment by tomara-x** [comment]
this is okay if you're going for shorter comments, but if you're trying to write a longer one it.. it's gonna be difficult. (and even writing something in an external editor, and then pasting it will still leave you with a reeeeaaaalllllyyy loooooong comment that you need to resize. it would be very convenient if it remembered the maximum width and broke the lines at that (increasing in height instead)

**Comment by porres** [comment]
yeah @timothyschoen can we reopen this? it really seems like an issue to me. I just tried copying tomara's text above into a comment and I got a single very long line. The comment should really break. And I still also think it shouldn't be called as an object, because that's not how it works in Pd Vanilla (I discussed this in the other issue)

**Comment by timothyschoen** [comment]
I'm gonna look into this now!

I also thought it might be nice to automatically add ";" at the end of a line when you press enter/return?
That way you create an actual newline in Pd instead of one that will be forgotten on save/load or copy/paste.

**Comment by timothyschoen** [comment]
Never mind, that's a terrible idea

**Comment by timothyschoen** [comment]
https://user-images.githubusercontent.com/44585538/214185503-33f8846d-5138-4b7b-b25b-5caf9b4d113e.mov

I think this is much better already! I still want to fix the jumpiness of the text though.

**Comment by tomara-x** [comment]
ooo i like this!

**Comment by porres** [comment]
perfect ";" was also necessary, thanks

**Comment by timothyschoen** [comment]
I made some final improvements, the text shouldn't jump around as much anymore.

I think this is solved now, but if you know of any other improvements I can make, let me know!
