### ISSUE TITLE
Package ELSE's help file resources with plugdata

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#373]
for instance, [player~] cannot find audio files like stereo.wav

**Comment by porres** [comment]
this is all in the same folder for else in vanilla of course

**Comment by timothyschoen** [comment]
ELSE's resources should be packaged, they are currently not, and maybe some vanilla resources as well?

**Comment by porres** [comment]
> maybe some vanilla resources as well

not sure if they're missing, I could load the famous bell.aiff file in readsf~ help file for instance

**Comment by timothyschoen** [comment]
<img width="692" alt="Screenshot 2023-01-20 at 01 45 59" src="https://user-images.githubusercontent.com/44585538/213594027-0d203914-3e35-4a51-baac-d754945e5d07.png">

Else's resources are now packaged with plugdata!

**Comment by timothyschoen** [comment]
And Pd's example files as well now!
