### ISSUE TITLE
Home-compiled version of plugdata has serious performance issues

### ISSUE THREAD

**Issue by jyg** [plugdata-team/plugdata#374]
Hi,
Thank you so much for this fantastic project.
Unfortunately, I have serious performance issues with my patches  :-( , when using the plugdata version I compiled myself, following instructions on this site.

For example, try pd/doc/3.ausio.examples/I08.pvoc.reverb.pd 
In Pd Vanilla 0.53, it takes 1,7 % cpu power
In Plugdata, it takes 6,25 % cpu power
No GUI rendering here....
Lubuntu 20.04, testing plugdata standalone version

I may have missed something.
With plugdata 0.6.3  downloaded, everything is ok

**Comment by timothyschoen** [comment]
You're probably making a Debug build instead of a Release build. In Debug mode you will have more readable crash messages, at the expense of performance.

Pass "-DCMAKE_BUILD_TYPE=Release" to cmake, you should have better performance!

**Comment by jyg** [comment]
Thank you very much for taking the time to respond to this request ! 
I think I can close the issue now. sorry for the noise :-)

**Comment by tomara-x** [comment]
apology not accepted! i didn't know about this and it's very useful for me, so thanks for making noise
