### ISSUE TITLE
[function] doesn't delete points when a moving object is present

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#375]
when a bang is flickering in the patch you can't delete points. when removed, it works fine. look:

https://user-images.githubusercontent.com/86204514/212676480-486050ff-e29b-4f4c-8309-456fe9654928.mp4

**Comment by timothyschoen** [comment]
Well that's weird...

**Comment by alcomposer** [comment]
Looks like functionObject::updateValue() gets called when another object gets updated.

It's a virtual function in Object, so all objects have it, somehow it's getting called from another object.

**Comment by alcomposer** [comment]
Should be fixed with https://github.com/plugdata-team/plugdata/pull/385
@timothyschoen let me know if this disrupts other stuff? I think any mouse-up should be safely able to update the PD object?

**Comment by tomara-x** [comment]
definitely better, but it kinda feels like there's a window of time between the flickers where it's possible to delete a point, so if i try to speed up the metro, it's so much harder to delete them

try it out: [function-delete-point.pd.txt](https://github.com/plugdata-team/plugdata/files/10443884/function-delete-point.pd.txt)

**Comment by alcomposer** [comment]
Try latest develop.

**Comment by tomara-x** [comment]
yeah, perfect! nice work!

**Comment by alcomposer** [comment]
Hopefully, feels a bit like "we will meet again" territory.
