### ISSUE TITLE
[v0.6.4] [deken] Failed to start download

### ISSUE THREAD

**Issue by FlachyJoe** [plugdata-team/plugdata#376]
Hi,
Externals tab show a red *Failed to start download* message what ever external I try.
I'm using Debian sid with the OpenSuse repository.

**Comment by FlachyJoe** [comment]
How can I dig this problem ? Can PlugData show some log ?

**Comment by timothyschoen** [comment]
Hi, sorry, I'll take a look at this soon!

It doesn't keep a log, so you'll have to put some log statements into the code manually. I understand if this is too involved, in that case I'll do it myself in a couple of days.

**Comment by FlachyJoe** [comment]
Caught it !
It works as expected when I remove https://github.com/plugdata-team/plugdata/blob/ae9f29871ddcdb1aaa16128f273a8f348b0b5e30/Source/Dialogs/Deken.h#L94

10s delay is ok. Not sure why my ping is so slow…

**Comment by timothyschoen** [comment]
Thanks for working that out! I'll change it to 10 seconds then!
