### ISSUE TITLE
Compiled binaries disappear as soon as compilation finishes

### ISSUE THREAD

**Issue by JRSV** [plugdata-team/plugdata#383]
Hello,

today I started to test the compilation option and it seems to work great out of the box... terminal shows no errors. But as soon as the compilation finishes, the files get erased.

the terminal spits out this, I can't find anything pointing to what is going on. 

--> Generating C

=== Signal Order ===
__line~f
__tabhead~f {table:del-delay-d-rafa table_id:ZHP8hplN}
__var_k~f {k:-1.0 reverse:True step:-1.0}
__add~f
__varread~f {var_id:uMT6r0v0}
__mul~f
__varread~f {var_id:52m4lD5T}
__min~f
__var_k~f {k:0.0 step:0 reverse:False}
__max~f
__sub~f
__floor~f
__varread~f {var_id:gNbmXztE}
__var_k~f {k:0.0 step:0 reverse:False}
__lt~f
__and~f
__add~f
__cast~fi
__var_k~i {k:1 step:0 reverse:False}
__add~i {k:0}
__tabread~if {table:del-delay-d-rafa table_id:ZHP8hplN}
__tabread~if {table:del-delay-d-rafa table_id:ZHP8hplN}
__sub~f
__sub~f
__fma~f
__varwrite~f {var_id:YtNfOHdK}
__varwrite~f {var_id:yx9RJKCq}
__line~f
__tabhead~f {table:del-delay-d-rafa table_id:ZHP8hplN}
__var_k~f {k:-1.0 reverse:True step:-1.0}
__add~f
__varread~f {var_id:zNQgXZ1B}
__mul~f
__varread~f {var_id:w4KaC3AV}
__min~f
__var_k~f {k:0.0 step:0 reverse:False}
__max~f
__sub~f
__floor~f
__varread~f {var_id:zF8vrtpa}
__var_k~f {k:0.0 step:0 reverse:False}
__lt~f
__and~f
__add~f
__cast~fi
__var_k~i {k:1 step:0 reverse:False}
__add~i {k:0}
__tabread~if {table:del-delay-d-rafa table_id:ZHP8hplN}
__tabread~if {table:del-delay-d-rafa table_id:ZHP8hplN}
__sub~f
__sub~f
__fma~f
__varwrite~f {var_id:JoaTkndf}
__varwrite~f {var_id:fkyCQNaD}
__line~f
__tabhead~f {table:del-delay-d-rafa table_id:ZHP8hplN}
__var_k~f {k:-1.0 reverse:True step:-1.0}
__add~f
__varread~f {var_id:fMqxK7vP}
__mul~f
__varread~f {var_id:tZSUjyTc}
__min~f
__var_k~f {k:0.0 step:0 reverse:False}
__max~f
__sub~f
__floor~f
__varread~f {var_id:AvKleeqA}
__var_k~f {k:0.0 step:0 reverse:False}
__lt~f
__and~f
__add~f
__cast~fi
__var_k~i {k:1 step:0 reverse:False}
__add~i {k:0}
__tabread~if {table:del-delay-d-rafa table_id:ZHP8hplN}
__tabread~if {table:del-delay-d-rafa table_id:ZHP8hplN}
__sub~f
__sub~f
__fma~f
__varwrite~f {var_id:dW1I84tv}
__varwrite~f {var_id:gFNZuWjm}
__line~f
__tabhead~f {table:del-delay-d-rafa table_id:ZHP8hplN}
__var_k~f {k:-1.0 reverse:True step:-1.0}
__add~f
__varread~f {var_id:4LEaSrHt}
__mul~f
__varread~f {var_id:kf4fZwQ3}
__min~f
__var_k~f {k:0.0 step:0 reverse:False}
__max~f
__sub~f
__floor~f
__varread~f {var_id:ztKE4QXX}
__var_k~f {k:0.0 step:0 reverse:False}
__lt~f
__and~f
__add~f
__cast~fi
__var_k~i {k:1 step:0 reverse:False}
__add~i {k:0}
__tabread~if {table:del-delay-d-rafa table_id:ZHP8hplN}
__tabread~if {table:del-delay-d-rafa table_id:ZHP8hplN}
__sub~f
__sub~f
__fma~f
__varwrite~f {var_id:m4lclU6U}
__varwrite~f {var_id:ak9SzJHY}
__add~f
__line~f
__varread~f {var_id:srWwhnHf}
__fma~f
__tabwrite~f {table:del-delay-d-rafa table_id:ZHP8hplN}
__line~f
__tabhead~f {table:del-delay-d-rafa table_id:ZHP8hplN}
__var_k~f {k:-1.0 reverse:True step:-1.0}
__add~f
__varread~f {var_id:XjhXrFy8}
__mul~f
__varread~f {var_id:GwFImKr6}
__min~f
__var_k~f {k:0.0 step:0 reverse:False}
__max~f
__sub~f
__floor~f
__varread~f {var_id:TYHXN6ud}
__var_k~f {k:0.0 step:0 reverse:False}
__lt~f
__and~f
__add~f
__cast~fi
__var_k~i {k:1 step:0 reverse:False}
__add~i {k:0}
__tabread~if {table:del-delay-d-rafa table_id:ZHP8hplN}
__tabread~if {table:del-delay-d-rafa table_id:ZHP8hplN}
__sub~f
__sub~f
__fma~f
__varwrite~f {var_id:l82P3uCu}
__varwrite~f {var_id:Fx53fHjE}
__line~f
__tabhead~f {table:del-delay-d-rafa table_id:ZHP8hplN}
__var_k~f {k:-1.0 reverse:True step:-1.0}
__add~f
__varread~f {var_id:YMlsDUUm}
__mul~f
__varread~f {var_id:d9beuk3I}
__min~f
__var_k~f {k:0.0 step:0 reverse:False}
__max~f
__sub~f
__floor~f
__varread~f {var_id:69RlI5xA}
__var_k~f {k:0.0 step:0 reverse:False}
__lt~f
__and~f
__add~f
__cast~fi
__var_k~i {k:1 step:0 reverse:False}
__add~i {k:0}
__tabread~if {table:del-delay-d-rafa table_id:ZHP8hplN}
__tabread~if {table:del-delay-d-rafa table_id:ZHP8hplN}
__sub~f
__sub~f
__fma~f
__varwrite~f {var_id:aAvfi0DW}
__varwrite~f {var_id:C9MHPCCS}
__varread~f {var_id:YtNfOHdK}
__varread~f {var_id:JoaTkndf}
__varread~f {var_id:dW1I84tv}
__add~f
__varread~f {var_id:m4lclU6U}
__add~f
__varread~f {var_id:l82P3uCu}
__add~f
__varread~f {var_id:aAvfi0DW}
__add~f
__add~f
__line~f
__mul~f
__varwrite~f {var_id:srWwhnHf}
__varread~f {var_id:yx9RJKCq}
__varread~f {var_id:fkyCQNaD}
__varread~f {var_id:gFNZuWjm}
__add~f
__varread~f {var_id:ak9SzJHY}
__add~f
__varread~f {var_id:Fx53fHjE}
__add~f
__varread~f {var_id:C9MHPCCS}
__add~f
__add~f
__varread~f {var_id:4bVKfyWa}
__fma~f
__add~f
__line~f
__mul~f
__add~f
__add~f
AVX: 463.5 cycles / 57.9375 cycles per frame
     512 frames @ 1000MHz >= 29.66us
SSE: 412.5 cycles / 103.125 cycles per frame
     512 frames @ 1000MHz >= 52.80us
CPU% #Objs Object Type      Performance
==== ===== ================ ===========
10%  9     __line~f         Counter({'avx': 49.5, 'sse': 31.5})
 0%  6     __tabhead~f      Counter({'avx': 3.0, 'sse': 3.0})
 1%  18    __var_k~f        Counter({'avx': 9.0, 'sse': 9.0})
16%  26    __add~f          Counter({'avx': 78, 'sse': 78})
 6%  32    __varread~f      Counter({'avx': 32, 'sse': 32})
 8%  8     __mul~f          Counter({'avx': 40, 'sse': 40})
 3%  6     __min~f          Counter({'avx': 18, 'sse': 18})
 3%  6     __max~f          Counter({'avx': 18, 'sse': 18})
11%  18    __sub~f          Counter({'avx': 54, 'sse': 54})
 6%  6     __floor~f        Counter({'avx': 30, 'sse': 30})
 1%  6     __lt~f           Counter({'avx': 6, 'sse': 6})
 0%  6     __and~f          Counter({'avx': 3.0, 'sse': 3.0})
 1%  6     __cast~fi        Counter({'avx': 6, 'sse': 6})
 0%  6     __var_k~i        Counter({'avx': 3.0, 'sse': 3.0})
 2%  6     __add~i          Counter({'avx': 12, 'sse': 3.0})
10%  12    __tabread~if     Counter({'avx': 48, 'sse': 24})
 8%  8     __fma~f          Counter({'avx': 40, 'sse': 40})
 2%  13    __varwrite~f     Counter({'avx': 13, 'sse': 13})
 0%  1     __tabwrite~f     Counter({'avx': 1, 'sse': 1})
--> Generating DPF plugin
Total compile time: 1592.49ms
/tmp/temp_979f2080.sh: line 2: /root/.config/plugdata/Toolchain/scripts/anywhere-setup.sh: Permission denied
/root/.config/plugdata/Toolchain/bin/make all -C plugin/source
/root/.config/plugdata/Toolchain/bin/make -C dpf/utils/lv2-ttl-generator
make[1]: Entering directory '/home/jrsv/Desktop/2222/root/root/root/plugin/source'
make[1]: Entering directory '/home/jrsv/Desktop/2222/root/root/root/dpf/utils/lv2-ttl-generator'
cc lv2_ttl_generator.c -Wall -Wextra -pipe -MD -MP -fno-gnu-unique -fPIC -DPIC -DNDEBUG -O3 -ffast-math -fdata-sections -ffunction-sections -mtune=generic -msse -msse2 -mfpmath=sse -fvisibility=hidden -std=gnu99  -o ../lv2_ttl_generator -fdata-sections -ffunction-sections -Wl,-O1,--as-needed,--gc-sections -Wl,--strip-all  -Wl,--no-undefined -ldl
Compiling HeavyContext.cpp
Compiling HeavyDPF_linea_retardo_1.cpp
Compiling Heavy_linea_retardo_1.cpp
make[1]: Leaving directory '/home/jrsv/Desktop/2222/root/root/root/dpf/utils/lv2-ttl-generator'
Compiling HvHeavy.cpp
HvHeavy.cpp:24: warning: ignoring ‘#pragma mark ’ [-Wunknown-pragmas]
   24 | #pragma mark - Heavy Table
      | 
HvHeavy.cpp:45: warning: ignoring ‘#pragma mark ’ [-Wunknown-pragmas]
   45 | #pragma mark - Heavy Message
      | 
HvHeavy.cpp:127: warning: ignoring ‘#pragma mark ’ [-Wunknown-pragmas]
  127 | #pragma mark - Heavy Common
      | 
HvHeavy.cpp:294: warning: ignoring ‘#pragma mark ’ [-Wunknown-pragmas]
  294 | #pragma mark - Heavy Common
      | 
In file included from Heavy_linea_retardo_1.hpp:48,
                 from Heavy_linea_retardo_1.cpp:33:
HvSignalTabwrite.h: In function ‘void __hv_tabwrite_stoppable_f(SignalTabwrite*, float)’:
HvSignalTabwrite.h:77:15: warning: comparison of integer expressions of different signedness: ‘uint32_t’ {aka ‘unsigned int’} and ‘int’ [-Wsign-compare]
   77 |   if (o->head != HV_TABWRITE_STOPPED) {
      |               ^
In file included from Heavy_linea_retardo_1.hpp:51,
                 from Heavy_linea_retardo_1.cpp:33:
HvSignalTabread.h: In function ‘void __hv_tabread_stoppable_f(SignalTabread*, float*)’:
HvSignalTabread.h:141:15: warning: comparison of integer expressions of different signedness: ‘uint32_t’ {aka ‘unsigned int’} and ‘int’ [-Wsign-compare]
  141 |   if (o->head == ~0x0) {
      |       ~~~~~~~~^~~~~~~
In file included from Heavy_linea_retardo_1.hpp:48,
                 from HeavyDPF_linea_retardo_1.hpp:38,
                 from HeavyDPF_linea_retardo_1.cpp:34:
HvSignalTabwrite.h: In function ‘void __hv_tabwrite_stoppable_f(SignalTabwrite*, float)’:
HvSignalTabwrite.h:77:15: warning: comparison of integer expressions of different signedness: ‘uint32_t’ {aka ‘unsigned int’} and ‘int’ [-Wsign-compare]
   77 |   if (o->head != HV_TABWRITE_STOPPED) {
      |               ^
In file included from Heavy_linea_retardo_1.hpp:51,
                 from HeavyDPF_linea_retardo_1.hpp:38,
                 from HeavyDPF_linea_retardo_1.cpp:34:
HvSignalTabread.h: In function ‘void __hv_tabread_stoppable_f(SignalTabread*, float*)’:
HvSignalTabread.h:141:15: warning: comparison of integer expressions of different signedness: ‘uint32_t’ {aka ‘unsigned int’} and ‘int’ [-Wsign-compare]
  141 |   if (o->head == ~0x0) {
      |       ~~~~~~~~^~~~~~~
Compiling HvControlBinop.c
Compiling HvControlCast.c
Compiling HvControlDelay.c
Compiling HvControlPack.c
Compiling HvControlRandom.c
Compiling HvControlSlice.c
Compiling HvControlSystem.c
Compiling HvControlUnop.c
Compiling HvControlVar.c
Compiling HvLightPipe.c
Compiling HvMessage.c
Compiling HvMessagePool.c
HvMessage.c: In function ‘msg_getHash’:
HvMessage.c:151:16: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  151 |       return *((hv_uint32_t *) &f);
      |               ~^~~~~~~~~~~~~~~~~~~
Compiling HvMessageQueue.c
In file included from /usr/include/string.h:535,
                 from HvUtils.h:125,
                 from HvMessage.h:20,
                 from HvMessage.c:17:
In function ‘strncpy’,
    inlined from ‘msg_copyToBuffer’ at HvMessage.c:74:7:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:95:10: warning: ‘__builtin_strncpy’ specified bound depends on the length of the source argument [-Wstringop-truncation]
   95 |   return __builtin___strncpy_chk (__dest, __src, __len,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   96 |                                   __glibc_objsize (__dest));
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from HvMessage.h:20,
                 from HvMessage.c:17:
HvMessage.c: In function ‘msg_copyToBuffer’:
HvUtils.h:126:22: note: length computed here
  126 | #define hv_strlen(a) strlen(a)
      |                      ^~~~~~~~~
HvMessage.c:72:44: note: in expansion of macro ‘hv_strlen’
   72 |       const hv_size_t symLen = (hv_size_t) hv_strlen(msg_getSymbol(m,i)) + 1; // include the trailing null char
      |                                            ^~~~~~~~~
Compiling HvSignalLine.c
Compiling HvSignalTabread.c
Compiling HvSignalTabwrite.c
Compiling HvSignalVar.c
In file included from HvSignalTabread.c:17:
HvSignalTabread.h: In function ‘__hv_tabread_stoppable_f’:
HvSignalTabread.h:141:15: warning: comparison of integer expressions of different signedness: ‘uint32_t’ {aka ‘unsigned int’} and ‘int’ [-Wsign-compare]
  141 |   if (o->head == ~0x0) {
      |               ^~
Compiling HvTable.c
In file included from HvSignalTabwrite.c:17:
HvSignalTabwrite.h: In function ‘__hv_tabwrite_stoppable_f’:
HvSignalTabwrite.h:77:15: warning: comparison of integer expressions of different signedness: ‘uint32_t’ {aka ‘unsigned int’} and ‘int’ [-Wsign-compare]
   77 |   if (o->head != HV_TABWRITE_STOPPED) {
      |               ^~
HvSignalTabwrite.c: In function ‘sTabwrite_onMessage’:
HvSignalTabwrite.h:26:29: warning: operand of ‘?:’ changes signedness from ‘int’ to ‘unsigned int’ due to unsignedness of other operand [-Wsign-compare]
   26 | #define HV_TABWRITE_STOPPED -1 // ~0x0
      |                             ^~
HvSignalTabwrite.c:33:85: note: in expansion of macro ‘HV_TABWRITE_STOPPED’
   33 |           o->head = (msg_getFloat(m,0) >= 0.0f) ? (hv_uint32_t) msg_getFloat(m,0) : HV_TABWRITE_STOPPED;
      |                                                                                     ^~~~~~~~~~~~~~~~~~~
Compiling HvUtils.c
Compiling DistrhoPluginMain.cpp (LV2)
Compiling DistrhoPluginMain.cpp (VST2)
HvUtils.c: In function ‘hv_string_to_hash’:
HvUtils.c:45:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
   45 |     case 3: x ^= (str[2] << 16);
      |             ~~^~~~~~~~~~~~~~~~~
HvUtils.c:46:5: note: here
   46 |     case 2: x ^= (str[1] << 8);
      |     ^~~~
HvUtils.c:46:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
   46 |     case 2: x ^= (str[1] << 8);
      |             ~~^~~~~~~~~~~~~~~~
HvUtils.c:47:5: note: here
   47 |     case 1: x ^= str[0]; x *= n;
      |     ^~~~
Compiling DistrhoPluginMain.cpp (VST3)
Compiling DistrhoPluginMain.cpp (CLAP)
Compiling DistrhoPluginMain.cpp (JACK)
Creating VST2 plugin for linea_retardo_1
Creating CLAP plugin for linea_retardo_1
Creating VST3 plugin for linea_retardo_1
Creating LV2 plugin library for linea_retardo_1
Creating JACK standalone for linea_retardo_1
make[1]: Leaving directory '/home/jrsv/Desktop/2222/root/root/root/plugin/source'
Generate ttl data for 'linea_retardo_1_dsp', basename: 'linea_retardo_1_dsp'
Writing manifest.ttl... done!
Writing linea_retardo_1_dsp.ttl... done!

**Comment by timothyschoen** [comment]
Hmm normally it should move the binaries from the "bin" folder to the root of the output folder. I feel like that's where something is going wrong now. Thanks for reporting, I'll take a look soon!

**Comment by timothyschoen** [comment]
We've recently updated and tested the Heavy toolchain, everything does seem to work now. Let me know if this issue still happens though!

(If you want to try the new toolchain, use it together with the new v0.8.0-test release of plugdata)
