### ISSUE TITLE
daw freeze when passing number to [param] inlet

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#390]
tested on reaper, bitwig and carla (both vst and lv2)

edit: it happens when you hit 0. and also in reaper you need to be recording:
(you can't see it in the video, but i'm clicking around a lot :laughing:) 

https://user-images.githubusercontent.com/86204514/213423960-040ddec0-4842-458d-80c3-3cde09a3c014.mp4

~~btw, vst reliably crashes carla now, and it used to work fine for me when we were talking about it in the discord~~ (vst on carla works as of 32d7e58a4b5693e but this might need its own issue since it does crash when you remove plugdata from the patchbay)

**Comment by timothyschoen** [comment]
I'm rewriting the way parameters work, so this will probably get fixed soon!

**Comment by tomara-x** [comment]
nice! thank you thank you ^^

**Comment by tomara-x** [comment]
working smoothly now. as always, beautiful work! <3
