### ISSUE TITLE
creating new object while pin panel is active causes crash

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#393]
creating an empty object from the plus menu or by double-clicking while pin panel is active will cause both plugin or standalone to crash (doesn't happen when using ctrl-1 to create the object)

https://user-images.githubusercontent.com/86204514/213259284-3f1053cc-b3c9-4dec-b652-b2ccdae03258.mp4

~~speaking of which, what does the pin panel do anyways?!~~ oh! i figured it out hehe it keeps the console visible

**Comment by timothyschoen** [comment]
I'm not able to reproduce this on Mac, I'll try Linux tomorrow

**Comment by timothyschoen** [comment]
Does this still happen?

**Comment by tomara-x** [comment]
oh yeah, just activate pin panel, then double click. so weird

**Comment by alfonso73** [comment]
> oh yeah, just activate pin panel, then double click. so weird

I can confirm this on Win11. 
1. Activate pin panel
2. Double click in an empty new patch
3. Crash

**Comment by timothyschoen** [comment]
Fixed it!
