### ISSUE TITLE
[function] doesn't update output when clicking to add points

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#399]
you need to drag the point for the output to be updated. this is not the case in vanilla where a click (without a drag) will still update the output

https://user-images.githubusercontent.com/86204514/213415363-9ce5bc3b-4053-4efa-ade2-a081cbbb15b6.mp4

**Comment by Yzrsah** [comment]
@tomara-x I just wanted to share, check out https://www.cockos.com/licecap/ from the creators of Reaper, it's good for making animated screenshots on Windows or macOS.

**Comment by tomara-x** [comment]
oh that looks nice thanks! linux girl for life tho <3
