### ISSUE TITLE
"Couldn't find help file" on every object

### ISSUE THREAD

**Issue by alfonso73** [plugdata-team/plugdata#405]
Hi, it seems that there's  some kind of mess in the dir structure of PlugData so no help file can be found.

**Comment by tomara-x** [comment]
what version are you using? have you tried going to the .config folder (if you're on linux, i'm not sure where it is on other systems) and deleting the `0.x.x` folder (that's where help files are kept, if you delete it, they should be regenerated the next time you open plugdata)

**Comment by alfonso73** [comment]
I'm on Windows with develop 0.7.0.
I deleted it and has been regenerated. Now help files seems to work. But before closing the issue i'll do more tests.
