### ISSUE TITLE
Several abstractions cant'be found by parent patches

### ISSUE THREAD

**Issue by alfonso73** [plugdata-team/plugdata#406]
Hi, i guess it's some kind of wrong packaging of Else directories.
If i open manually the help file for Else's [voices] (i can't open it via righ click menu "help" see https://github.com/plugdata-team/plugdata/issues/405#issue-1549965539 ) the [voice] abstraction called by [clone] can't be found.
And infact no voice.pd file  is in the same directory of voices-help.pd.
Everything works in vanilla with latest Else from Deken.

**Comment by timothyschoen** [comment]
Found out what was causing this, I wasn't packaging the resources in the "Extra" folder of ELSE. If you grab the latest develop branch, and remove plugdata's folder, it should work!
