### ISSUE TITLE
else/ namespace makes all else objects "red" 

### ISSUE THREAD

**Issue by alfonso73** [plugdata-team/plugdata#407]
In various else help files, patches and abstractions there are some else objects instantiated with the else namespace (something as [else/adsr~] i.e.). They can't be found by PlugData i guess because there's not a folder actually called "else" in the PlugData library.

**Comment by timothyschoen** [comment]
Finally found a good way to solve this, so fix is coming soon!

**Comment by timothyschoen** [comment]
Fixed!

**Comment by alfonso73** [comment]
great!
