### ISSUE TITLE
Standalone for Mac OS X causing fan to kick in 

### ISSUE THREAD

**Issue by NeuroNoNeuro** [plugdata-team/plugdata#409]
App is open, nothing in it, fan is on and running hard.

**Comment by timothyschoen** [comment]
Hi!

What version are you using, and on what OS? What are your system specs?

**Comment by NeuroNoNeuro** [comment]
I was using the Mac OS X Universal download (since removed), and my system specs are as follows:

3.2 GHz 6-Core Intel Core i7
Intel UHD Graphics 630 1536 MB
16 GB 2667 MHz DDR4
Ventura 13.0

To be fair, not one of my computers over the past 20+ years has handled PureData or Max/MSP very well.  Could just be a 'me' thing :)

**Comment by alcomposer** [comment]
@timothyschoen has made some changes that could improve this. Can you take a look at nightly, or when 0.7.0 is released?
