### ISSUE TITLE
[text define] : fixing issue with notify-outlet

### ISSUE THREAD

**Issue by jyg** [plugdata-team/plugdata#413]
According to pd vanilla doc, _"Second outlet of `[text define]` notifies you when text changes. "_
This doesn't occur in plugdata when you close the text box after saving its content.
May I suggest a fix ? 
in Source/Objects/TextDefineObject.h, insert two lines in function `openTextEditor()` :
from line 67 :
   ```
                 if (result == 2) {
                        setText(lastText);
                        textEditor.reset(nullptr);

                        // enable notification on second outlet //
                        const char* target =static_cast<t_fake_text_define*>(ptr)->x_bindsym->s_name;
                        pd->sendMessage(target, "notify", {});
```
Not sure if I'm doing it right though...

**Comment by tomara-x** [comment]
i've tested it and this seems to work nicely! will send pr

**Comment by timothyschoen** [comment]
Should be fixed!
