### ISSUE TITLE
numboxes go beyond limit in saved patches

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#421]
that one was sneaky

https://user-images.githubusercontent.com/86204514/214150026-a76050b1-f12a-4873-94c4-4e1c0d56a918.mp4

**Comment by timothyschoen** [comment]
That's very sneaky! Should be fixed with e8f6fc1

I did a lot of refactoring on the GUI objects, so there's a chance there are more bugs like this

**Comment by tomara-x** [comment]
yep, perfect now

what i noticed since the new overhaul is that the iem objects don't init, and besides numboxes they don't have an initialize option in the sidebar

**Comment by timothyschoen** [comment]
> iem objects don't init, and besides numboxes they don't have an initialize option in the sidebar

Fixed!

**Comment by tomara-x** [comment]
those last 5 commits are giving me genuine happiness right now!
