### ISSUE TITLE
negative nonzero values for toggles

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#425]
i can't figure out why having a negative non-zero value for a toggle will make it not change it's appearance

https://user-images.githubusercontent.com/86204514/214344525-0100fb6a-232e-4740-9509-02d824f2c3d6.mp4

**Comment by alcomposer** [comment]
#430 should fix this
![toggle-nonzero](https://user-images.githubusercontent.com/12004932/214479176-eaecf04c-6ec9-4ba5-806d-5d6fd3c538d1.gif)

**Comment by tomara-x** [comment]
oh yeah! beautiful work! thank you

**Comment by alcomposer** [comment]
@tomara-x keep the bugs reports coming!
