### ISSUE TITLE
[bl.imp(2)~] and [bl.osc~] issues found while reviewing docs

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#429]
2. **do not open the help file of [bl.imp~] with your dsp on! it's so loud!**  
[bl.imp~] and [bl.imp2~] their help files say they have 3 or 4 inlets, yet they both only have 1 inlet. whether it's the help files or the objects themselves that need fixing, i think @porres knows best. also they both don't work when you give them arguments

3. bl.osc~ has an issue in plugdata. in vanila you can change its waveforms using the methods. but in plugdata, you can click those messages all you want, and it will stay on the initial triangle wave:
![Screenshot_2023-01-25_00-27-46-e](https://user-images.githubusercontent.com/86204514/214436779-08d0a086-4f55-4ce8-a44c-9ed1e61adb77.png)

**Comment by porres** [comment]
> do not open the help file of [bl.imp~] with your dsp on! it's so loud!

sounds ok on vanilla

> [bl.imp~] and [bl.imp2~] their help files say they have 3 or 4 inlets, yet they both only have 1 inlet. 

we have a new compiled version. I updated/fixed the help files upstream now

**Comment by tomara-x** [comment]
ooo you fixed this too! nice!

**Comment by porres** [comment]
Injadnfixed the help files and also updated the objects
