### ISSUE TITLE
Parameters in dialog box gets deleted after DAW project reopen 

### ISSUE THREAD

**Issue by alfonso73** [plugdata-team/plugdata#443]
Parameters in dialog box gets deleted after DAW project reopen even if they are still seen by the host.

![image](https://user-images.githubusercontent.com/3230434/214954166-919bf187-7b7c-4713-8fe0-d44994673e0f.png)

![image](https://user-images.githubusercontent.com/3230434/214954268-2379d68c-133c-4d08-8c8c-fa76f126912e.png)

**Comment by timothyschoen** [comment]
Fortunately, this is only a small bug, resizing the sidebar should make them visible again. I'll see how this could happen!

**Comment by timothyschoen** [comment]
This one should be fixed!
