### ISSUE TITLE
Objects disappears when resizing patch windows in "Presentation" mode

### ISSUE THREAD

**Issue by alfonso73** [plugdata-team/plugdata#455]
Objects disappears when resizing patch windows in "Presentation" mode

**Comment by alfonso73** [comment]
But if i enter edit mode then create a new object and delete it all the disappeared object appear again. Then goin' again to presentation mode and resizing the window the objects disappear again

**Comment by alcomposer** [comment]
This line is responsible for the hiding. I'm not sure of the behaviour we want here, obviously we don't want objects to hide when resizing. 

However I am thinking in `presentation` mode we want some objects to hide?

https://github.com/plugdata-team/plugdata/blob/c434ad416c5dde5f7679865e33bdc2748d8cf688/Source/Object.cpp#L385-L387

**Comment by alfonso73** [comment]
> This line is responsible for the hiding. I'm not sure of the behaviour we want here, obviously we don't want objects to hide when resizing. 
> 
> However I am thinking in `presentation` mode we want some objects to hide?
> 
> https://github.com/plugdata-team/plugdata/blob/c434ad416c5dde5f7679865e33bdc2748d8cf688/Source/Object.cpp#L385-L387

The thing is after resizing when in presentation mode the objects remain invisible after goin' out of presentation mode

**Comment by alcomposer** [comment]
Yes, because nothing sets them back to visible until edit mode is turned on. The setVisible line should probably be in a valuelistener for presentation mode?

**Comment by alfonso73** [comment]
Edit Mode OFF and Presentation Mode OFF

![image](https://user-images.githubusercontent.com/3230434/216414100-3ff1f378-756b-435a-8791-33ff71355be6.png)

Edit Mode OFF and Presentation Mode ON (subpatches, abstracions and objects remain visible...they shouldn't)

![image](https://user-images.githubusercontent.com/3230434/216414755-2fb4b7bc-63bf-48f6-aa7e-1823821afe78.png)

Edit Mode OFF and Presentation Mode ON and after a little resize of the windows subpatches, abstracions and objects become invisible as they should

![image](https://user-images.githubusercontent.com/3230434/216414896-bfb891e2-474b-49f8-b9a9-5c4c5cd1ccbd.png)

Edit Mode OFF and Presentation Mode OFF and subpatches, abstracions and objects stay invisible...they shouldn't

![image](https://user-images.githubusercontent.com/3230434/216415655-25651aaf-d968-4dd8-ae47-8fe074fd0881.png)

Edit Mode ON and Presentation Mode OFF and subpatches, abstracions and objects keep staying invisible...they shouldn't

![image](https://user-images.githubusercontent.com/3230434/216415957-0095b0de-5829-4245-9467-eb65458c9a1b.png)

I create an object...

![image](https://user-images.githubusercontent.com/3230434/216416354-79485425-d1a9-4ea6-8587-93da29e7eb97.png)

I move the created object and everything appears again as it should

![image](https://user-images.githubusercontent.com/3230434/216416680-37730814-f04f-4426-97b2-728bc78cba49.png)

**Comment by timothyschoen** [comment]
Fixed with 06e3526, thanks for reporting!

**Comment by timothyschoen** [comment]
now it's time to work on the audio parameters!
