### ISSUE TITLE
Add all properties/messages for GUI objects 

### ISSUE THREAD

**Issue by alfonso73** [plugdata-team/plugdata#459]
Adding all this would be great

![image](https://user-images.githubusercontent.com/3230434/215795087-8a6c860c-b1cb-4fee-b605-4dc4ad17d3e3.png)

![image](https://user-images.githubusercontent.com/3230434/215795199-eb214318-16aa-4ad7-810b-68a33b9b8b82.png)

check the hack for stepped slider...intersting and useful

![image](https://user-images.githubusercontent.com/3230434/215795594-ecbdb61e-095d-438f-a069-f2da73dc1394.png)

![image](https://user-images.githubusercontent.com/3230434/215795693-64fe6973-6c5b-43c6-ad84-3e857dbe636b.png)

**Comment by tomara-x** [comment]
does this include things like xticks/yticks and xlabels/ylabels for arrays? yes please!

**Comment by alfonso73** [comment]
Yeah would be great

![image](https://user-images.githubusercontent.com/3230434/215837179-fecd43ca-65e9-4684-981d-00f3b69119a0.png)

**Comment by alfonso73** [comment]
well actually a lot of array messages are already working
