### ISSUE TITLE
Add edit message to array and all other GUI objects

### ISSUE THREAD

**Issue by alfonso73** [plugdata-team/plugdata#461]
Adding edit message to array and all other GUI objects would be very useful for protecting from being moved or edited with mouse or keyboard GUI objects intended for monitoring purposes only.

**Comment by timothyschoen** [comment]
I believe the edit message to array already works right? I could add edit messages to other objects as well, though I can't save them to the patch so they would be lost upon save/load.

**Comment by timothyschoen** [comment]
I've confirmed that the edit message to array works. For now, I'm not planning to add additional edit messages to other objects, unless pd-vanilla also supports it for that object.
