### ISSUE TITLE
label height changes label width instead

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#491]
it also messes with [display]

https://user-images.githubusercontent.com/86204514/216865879-2515d537-e850-4e5e-9dfb-dbdbe2c53f36.mp4

**Comment by timothyschoen** [comment]
I think I just fixed this?

**Comment by timothyschoen** [comment]
Ah, forgot to push, it should be solved now

**Comment by tomara-x** [comment]
epic!
