### ISSUE TITLE
Set message does not update number box gui

### ISSUE THREAD

**Issue by alfonso73** [plugdata-team/plugdata#494]
As you can see in the video the actual data is set in the numbox that spit it out when banged. But the GUI does not update.
Slider works fine tho.

https://streamable.com/v4z52p

**Comment by timothyschoen** [comment]
Did you try after 1d107b7b03930f85b6c0dadee971a3ce5c2d42a6?

**Comment by alfonso73** [comment]
> Did you try after [1d107b7](https://github.com/plugdata-team/plugdata/commit/1d107b7b03930f85b6c0dadee971a3ce5c2d42a6)?

nope i'm still on the previous one...downloading now...

**Comment by alfonso73** [comment]
tested 1d107b7.
I have the path loading but with the num box disconnected from bang and print (see the error in plugdata console)
The numbox appears without inlet and outlet. I delete it create another one and as soon i try to connect it to bang i have a crash

https://streamable.com/cwp59p

**Comment by alfonso73** [comment]
those new issues aside https://github.com/plugdata-team/plugdata/issues/494#issuecomment-1419437850 and https://github.com/plugdata-team/plugdata/issues/494#issuecomment-1419455598 
set message for num box works correctly!

**Comment by timothyschoen** [comment]
> tested [1d107b7](https://github.com/plugdata-team/plugdata/commit/1d107b7b03930f85b6c0dadee971a3ce5c2d42a6). I have the path loading but with the num box disconnected from bang and print (see the error in plugdata console) The numbox appears without inlet and outlet. I delete it create another one and as soon i try to connect it to bang i have a crash
> 
> https://streamable.com/cwp59p

Looks like pd-vanilla also has some problems with this:

https://user-images.githubusercontent.com/44585538/217099712-f1a7f141-bf9c-455f-af43-e0a86b3698bc.mov

Still gonna see if I can fix this in plugdata though. The problem is that we don't live update the inlets/outlets when send/receive symbols get set.

**Comment by timothyschoen** [comment]
I've made it so that inlets/outlets also hide in plugdata when you have send/receive symbols, so there will be no more surprises after reloading the patch!
