### ISSUE TITLE
textfile and qlist don't display text window

### ISSUE THREAD

**Issue by DSBhproject** [plugdata-team/plugdata#498]
textfile and qlist don't display text window

**Comment by timothyschoen** [comment]
I'll take a look at that for the next version!

**Comment by tomara-x** [comment]
i find that the text window doesn't scroll unless you have a non-space character

https://user-images.githubusercontent.com/86204514/224858280-eeee5f5a-4de6-47fa-b20a-1f714ad2aa7d.mp4

**Comment by timothyschoen** [comment]
Oh yeah I added text editors for qlist and textfile!

@tomara-x I'll look at that scrolling issue!

**Comment by timothyschoen** [comment]
> i find that the text window doesn't scroll unless you have a non-space character

Is also fixed now!
