### ISSUE TITLE
Do we need a [r gui]-->[route keyboard] thing for parameters entering by keyboard in PlugData plugins?

### ISSUE THREAD

**Issue by alfonso73** [plugdata-team/plugdata#500]
Strange thing happens when i interact with Number Box and insert values via keyboard. I guess because the parameter write flag should be available for mouse interaction (for pure dragging GUi stuff) and for keyboard interaction (for entering values in num boxes).
Here's the video and the relevant parameter managing abstractions and main patch screencaps.
Ideally we'd need something like [r gui]-->[route keyboard]
https://streamable.com/2xfjcu 

![Sliders_and_Numbox_abstraction](https://user-images.githubusercontent.com/3230434/217228133-e5bb38a5-f098-403e-ad8c-3374a3ec9490.png)
![Single_parameter_abstraction](https://user-images.githubusercontent.com/3230434/217228141-1cc1e02a-a1c5-487f-8c46-db89e238685c.png)
![Main_patch_and_parameters](https://user-images.githubusercontent.com/3230434/217228148-95d6cb6f-e6fd-4838-9e54-159ed024c33d.png)

**Comment by timothyschoen** [comment]
Currently not planned, it might be better for users to implement this themselves. What we could do though, is explain how to do it in the documentation? Any solution we could offer would only work for a set number of GUIs anyway
