### ISSUE TITLE
Add all Camomile flags to DAW Parameters definition and implement a save/load for Parameter List pane

### ISSUE THREAD

**Issue by alfonso73** [plugdata-team/plugdata#501]
I think that for several reasons PlugData needs a kind of parameter based on discrete values. Camomile has it. In the Minimock example in Camomile there's in the txt file...

param -name OSC1 Waveform -list Triangular/Sawtooth Triangular/Sawtooth/Square/Wide Rectangular/Narrow Rectangular/Reverse Sawtooth

or

param -name OSC2 Octave -min -3 -max 3 -default 0 -nsteps 7;

So its a parameter based on a list.
BTW a lot of parameters managing in Camomile would be useful for significant feedback/interaction in the DAW like the various flags for setting unit labels (hz, db, etc.)

See this line

param -name Modulator Volume -label dB -min 0 -max 100 -default 0;

So things like -nsteps, -label, -list, -default would be great to include in PlugData's parameters pane.
And i'd add a way to save/load a parameter pane list.

**Comment by timothyschoen** [comment]
Unfortunately JUCE doesn't allow adjusting the label. Other issues should be fixed by the new "int", "log" and "exp" options.
