### ISSUE TITLE
add plugdata version to plugdata's m_pd.h

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#502]
I'd like to use this in the [else] object, I'm also using "pd-l2ork" version now

**Comment by timothyschoen** [comment]
<img width="328" alt="Screenshot 2023-02-11 at 04 08 37" src="https://user-images.githubusercontent.com/44585538/218235969-d2e0eb44-6182-466e-a483-383dce5369f8.png">

Done!

**Comment by porres** [comment]
Now Purr Data uses a "PD_FLAVOR" definition, I think it'd be nice you could do that too, see https://github.com/agraef/purr-data/blob/pd-else/pd/src/m_pd.h#L23

**Comment by porres** [comment]
like:

#define PD_FLAVOR "PlugData" ? 

:)

**Comment by porres** [comment]
see also https://github.com/pure-data/pure-data/issues/1898#issuecomment-1442396634

**Comment by timothyschoen** [comment]
Added both flags now!
