### ISSUE TITLE
Crash when duplicating outlet~

### ISSUE THREAD

**Issue by sevdh** [plugdata-team/plugdata#503]
This might already be fixed but just to be sure:

today's early morning build https://github.com/plugdata-team/plugdata/actions/runs/4110068266 crashes on macOS when duplicating (command D) the [outlet~] object:

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               plugdata [4985]
Path:                  /Applications/plugdata.app/Contents/MacOS/plugdata
Identifier:            com.plugdata.plugdata
Version:               0.7.0 (0.7.0)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               502

Date/Time:             2023-02-07 20:46:10.1497 +0100
OS Version:            macOS 12.6.3 (21G419)
Report Version:        12
Anonymous UUID:        71803FF8-D537-93A1-48CA-EB63CE79AB73

Sleep/Wake UUID:       117CD201-0FEC-459D-9313-6DF173DD5635

Time Awake Since Boot: 11000 seconds
Time Since Wake:       5808 seconds

System Integrity Protection: enabled

Crashed Thread:        0  JUCE Message Thread  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [4985]

VM Region Info: 0 is not in any region.  Bytes before following region: 4302110720
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      1006d0000-106ab8000    [ 99.9M] r-x/r-x SM=COW  ...acOS/plugdata

Kernel Triage:
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage

Thread 0 Crashed:: JUCE Message Thread Dispatch queue: com.apple.main-thread
0   plugdata                      	       0x1014b09f8 signal_setchansout + 24
1   plugdata                      	       0x1014e0554 voutlet_dsp + 120
2   plugdata                      	       0x1014e0554 voutlet_dsp + 120
3   plugdata                      	       0x1014b28d8 ugen_doit + 1628
4   plugdata                      	       0x1014b1be0 ugen_done_graph + 2444
5   plugdata                      	       0x1014c1c84 canvas_dodsp + 300
6   plugdata                      	       0x1014c1dbc canvas_start_dsp + 132
7   plugdata                      	       0x1014c0f98 canvas_resume_dsp + 32
8   plugdata                      	       0x1014c92c8 canvas_dopaste + 408
9   plugdata                      	       0x1014d393c canvas_duplicate + 828
10  plugdata                      	       0x1015183ec pd_typedmess + 1564
11  plugdata                      	       0x10158f654 libpd_duplicate + 68
12  plugdata                      	       0x100ad2b2c pd::Patch::duplicate()::$_6::operator()() const + 52
13  plugdata                      	       0x100ad2ad8 decltype(static_cast<pd::Patch::duplicate()::$_6&>(fp)()) std::__1::__invoke<pd::Patch::duplicate()::$_6&>(pd::Patch::duplicate()::$_6&) + 24
14  plugdata                      	       0x100ad2a90 void std::__1::__invoke_void_return_wrapper<void, true>::__call<pd::Patch::duplicate()::$_6&>(pd::Patch::duplicate()::$_6&) + 28
15  plugdata                      	       0x100ad2a68 std::__1::__function::__alloc_func<pd::Patch::duplicate()::$_6, std::__1::allocator<pd::Patch::duplicate()::$_6>, void ()>::operator()() + 28
16  plugdata                      	       0x100ad1624 std::__1::__function::__func<pd::Patch::duplicate()::$_6, std::__1::allocator<pd::Patch::duplicate()::$_6>, void ()>::operator()() + 28
17  plugdata                      	       0x1006fc11c std::__1::__function::__value_func<void ()>::operator()() const + 60
18  plugdata                      	       0x1006fbe1c std::__1::function<void ()>::operator()() const + 24
19  plugdata                      	       0x100a3a8e4 pd::Instance::sendMessagesFromQueue() + 104
20  plugdata                      	       0x100b5be28 PluginProcessor::messageEnqueued() + 100
21  plugdata                      	       0x100a3a0fc pd::Instance::enqueueFunction(std::__1::function<void ()> const&) + 76
22  plugdata                      	       0x100ab6fa0 pd::Patch::duplicate() + 76
23  plugdata                      	       0x1006df750 Canvas::duplicateSelection() + 744
24  plugdata                      	       0x100b02280 PluginEditor::perform(juce::ApplicationCommandTarget::InvocationInfo const&) + 972
25  plugdata                      	       0x100ee9078 juce::ApplicationCommandTarget::tryToInvoke(juce::ApplicationCommandTarget::InvocationInfo const&, bool) + 176
26  plugdata                      	       0x100ee83c4 juce::ApplicationCommandTarget::invoke(juce::ApplicationCommandTarget::InvocationInfo const&, bool) + 84
27  plugdata                      	       0x100e39d8c juce::ApplicationCommandManager::invoke(juce::ApplicationCommandTarget::InvocationInfo const&, bool) + 216
28  plugdata                      	       0x100eea1d0 juce::KeyPressMappingSet::invokeCommand(int, juce::KeyPress const&, bool, int, juce::Component*) const + 152
29  plugdata                      	       0x100eeaf70 juce::KeyPressMappingSet::keyPressed(juce::KeyPress const&, juce::Component*) + 284
30  plugdata                      	       0x100eded44 juce::ComponentPeer::handleKeyPress(juce::KeyPress const&) + 172
31  plugdata                      	       0x100edec88 juce::ComponentPeer::handleKeyPress(int, wchar_t) + 96
32  plugdata                      	       0x100f9a20c juce::NSViewComponentPeer::handleKeyEvent(NSEvent*, bool) + 504
33  plugdata                      	       0x100f99a28 juce::NSViewComponentPeer::redirectKeyDown(NSEvent*) + 88
34  plugdata                      	       0x100f9987c juce::NSViewComponentPeer::sendEventToInputContextOrComponent(NSEvent*) + 240
35  plugdata                      	       0x100f9c048 juce::JuceNSViewClass::JuceNSViewClass()::'lambda8'(objc_object*, objc_selector*, NSEvent*)::operator()(objc_object*, objc_selector*, NSEvent*) const + 64
36  plugdata                      	       0x100f9c0d0 juce::JuceNSViewClass::JuceNSViewClass()::'lambda8'(objc_object*, objc_selector*, NSEvent*)::__invoke(objc_object*, objc_selector*, NSEvent*) + 44
37  AppKit                        	       0x189baa668 -[NSView performKeyEquivalent:] + 196
38  AppKit                        	       0x18a159a98 -[NSWindow _commonPerformKeyEquivalent:conditionally:] + 84
39  AppKit                        	       0x18a0220f4 routeKeyEquivalent + 304
40  AppKit                        	       0x189a20e6c -[NSApplication(NSEvent) sendEvent:] + 1172
41  AppKit                        	       0x189cdb0f4 -[NSApplication _handleEvent:] + 76
42  AppKit                        	       0x1898a3008 -[NSApplication run] + 636
43  plugdata                      	       0x1011d10b4 juce::MessageManager::runDispatchLoop() + 128
44  plugdata                      	       0x1011d0fa8 juce::JUCEApplicationBase::main() + 316
45  plugdata                      	       0x1011d0e14 juce::JUCEApplicationBase::main(int, char const**) + 68
46  plugdata                      	       0x100c6fda4 main + 56
47  dyld                          	       0x10871d08c start + 520

**Comment by timothyschoen** [comment]
Should be fixed now, this was actually a bug in Pd-0.54, so I'll report it to them soon as well!

**Comment by sevdh** [comment]
It works fine!

Thanks a lot!
