### ISSUE TITLE
one-time crash during undo

### ISSUE THREAD

**Issue by sevdh** [plugdata-team/plugdata#508]
This is a one-time crash caused by doing an undo operation using yesterday's build: https://github.com/plugdata-team/plugdata/actions/runs/4118114275

I wasn't able to clearly reproduce the crash.

In this case I'm running the Intel version in Rosetta.

Let me know if sending crashes like this is helpful or not ;-)

Best!

Edwin

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               plugdata [7016]
Path:                  /Applications/plugdata.app/Contents/MacOS/plugdata
Identifier:            com.plugdata.plugdata
Version:               0.7.0 (0.7.0)
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               502

Date/Time:             2023-02-08 16:14:56.5959 +0100
OS Version:            macOS 12.6.3 (21G419)
Report Version:        12
Anonymous UUID:        71803FF8-D537-93A1-48CA-EB63CE79AB73

Sleep/Wake UUID:       B8FADA7F-A00D-44C0-A9B3-2A6EBE254E6D

Time Awake Since Boot: 35000 seconds
Time Since Wake:       6247 seconds

System Integrity Protection: enabled

Crashed Thread:        0  JUCE Message Thread  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00000000000000a0
Exception Codes:       0x0000000000000001, 0x00000000000000a0
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [7016]

VM Region Info: 0xa0 is not in any region.  Bytes before following region: 140722887950176
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      mapped file              7ffc99bf8000-7ffc9a234000 [ 6384K] r-x/r-x SM=COW  ...t_id=8670cedf

Thread 0 Crashed:: JUCE Message Thread Dispatch queue: com.apple.main-thread
0   plugdata                      	       0x102feabcc juce::HeapBlock<juce::ComponentListener*, false>::operator juce::ComponentListener**() const + 12
1   plugdata                      	       0x102feae25 juce::ArrayBase<juce::ComponentListener*, juce::DummyCriticalSection>::begin() + 21
2   plugdata                      	       0x102feb012 juce::Array<juce::ComponentListener*, juce::DummyCriticalSection, 0>::removeFirstMatchingValue(juce::ComponentListener*) + 50
3   plugdata                      	       0x102e33405 juce::ListenerList<juce::ComponentListener, juce::Array<juce::ComponentListener*, juce::DummyCriticalSection, 0> >::remove(juce::ComponentListener*) + 101
4   plugdata                      	       0x102e33394 juce::Component::removeComponentListener(juce::ComponentListener*) + 36
5   plugdata                      	       0x102746177 AutoCompleteComponent::componentBeingDeleted(juce::Component&) + 55
6   plugdata                      	       0x102fe6381 juce::Component::~Component()::$_2::operator()(juce::ComponentListener&) const + 33
7   plugdata                      	       0x102e29079 void juce::ListenerList<juce::ComponentListener, juce::Array<juce::ComponentListener*, juce::DummyCriticalSection, 0> >::call<juce::Component::~Component()::$_2>(juce::Component::~Component()::$_2&&) + 137
8   plugdata                      	       0x102e28c95 juce::Component::~Component() + 53
9   plugdata                      	       0x102ed90a9 juce::TextEditor::~TextEditor() + 585
10  plugdata                      	       0x102e57695 juce::TextEditor::~TextEditor() + 21
11  plugdata                      	       0x102ed9319 juce::TextEditor::~TextEditor() + 25
12  plugdata                      	       0x1029cb7fc std::__1::default_delete<juce::TextEditor>::operator()(juce::TextEditor*) const + 44
13  plugdata                      	       0x1029cb77c std::__1::unique_ptr<juce::TextEditor, std::__1::default_delete<juce::TextEditor> >::reset(juce::TextEditor*) + 92
14  plugdata                      	       0x1029cb719 std::__1::unique_ptr<juce::TextEditor, std::__1::default_delete<juce::TextEditor> >::~unique_ptr() + 25
15  plugdata                      	       0x1029cb4b5 std::__1::unique_ptr<juce::TextEditor, std::__1::default_delete<juce::TextEditor> >::~unique_ptr() + 21
16  plugdata                      	       0x1029cb8be TextBase::~TextBase() + 142
17  plugdata                      	       0x1029cb8f5 TextObject::~TextObject() + 21
18  plugdata                      	       0x1029ca275 TextObject::~TextObject() + 21
19  plugdata                      	       0x1029ca299 TextObject::~TextObject() + 25
20  plugdata                      	       0x102952ccc std::__1::default_delete<ObjectBase>::operator()(ObjectBase*) const + 44
21  plugdata                      	       0x10294072c std::__1::unique_ptr<ObjectBase, std::__1::default_delete<ObjectBase> >::reset(ObjectBase*) + 92
22  plugdata                      	       0x10294ef49 std::__1::unique_ptr<ObjectBase, std::__1::default_delete<ObjectBase> >::~unique_ptr() + 25
23  plugdata                      	       0x10293e6e5 std::__1::unique_ptr<ObjectBase, std::__1::default_delete<ObjectBase> >::~unique_ptr() + 21
24  plugdata                      	       0x10293eb6e Object::~Object() + 206
25  plugdata                      	       0x10293ebf5 Object::~Object() + 21
26  plugdata                      	       0x10293ec79 Object::~Object() + 25
27  plugdata                      	       0x1027526fc std::__1::default_delete<Object>::operator()(Object*) const + 44
28  plugdata                      	       0x1027524bc std::__1::unique_ptr<Object, std::__1::default_delete<Object> >::reset(Object*) + 92
29  plugdata                      	       0x102752919 std::__1::unique_ptr<Object, std::__1::default_delete<Object> >::~unique_ptr() + 25
30  plugdata                      	       0x102752555 std::__1::unique_ptr<Object, std::__1::default_delete<Object> >::~unique_ptr() + 21
31  plugdata                      	       0x10270e150 juce::OwnedArray<Object, juce::DummyCriticalSection>::remove(int, bool) + 256
32  plugdata                      	       0x10270c7c9 Canvas::synchronise(bool) + 937
33  plugdata                      	       0x102714f4e Canvas::undo() + 46
34  plugdata                      	       0x102b26baf PluginEditor::perform(juce::ApplicationCommandTarget::InvocationInfo const&) + 2687
35  plugdata                      	       0x102efe7c8 juce::ApplicationCommandTarget::tryToInvoke(juce::ApplicationCommandTarget::InvocationInfo const&, bool) + 168
36  plugdata                      	       0x102efdb3a juce::ApplicationCommandTarget::invoke(juce::ApplicationCommandTarget::InvocationInfo const&, bool) + 74
37  plugdata                      	       0x102e474fc juce::ApplicationCommandManager::invoke(juce::ApplicationCommandTarget::InvocationInfo const&, bool) + 252
38  plugdata                      	       0x102eff7e8 juce::KeyPressMappingSet::invokeCommand(int, juce::KeyPress const&, bool, int, juce::Component*) const + 120
39  plugdata                      	       0x102f00770 juce::KeyPressMappingSet::keyPressed(juce::KeyPress const&, juce::Component*) + 320
40  plugdata                      	       0x102ef4543 juce::ComponentPeer::handleKeyPress(juce::KeyPress const&) + 163
41  plugdata                      	       0x102ef448e juce::ComponentPeer::handleKeyPress(int, wchar_t) + 78
42  plugdata                      	       0x102fb2be0 juce::NSViewComponentPeer::handleKeyEvent(NSEvent*, bool) + 512
43  plugdata                      	       0x102fb2366 juce::NSViewComponentPeer::redirectKeyDown(NSEvent*) + 86
44  plugdata                      	       0x102fb6092 juce::JuceNSViewClass::JuceNSViewClass()::'lambda'(objc_object*, objc_selector*, objc_selector*)::operator()(objc_object*, objc_selector*, objc_selector*) const::'lambda'()::operator()() const::'lambda'()::operator()() const + 162
45  plugdata                      	       0x102fb5f7b juce::JuceNSViewClass::JuceNSViewClass()::'lambda'(objc_object*, objc_selector*, objc_selector*)::operator()(objc_object*, objc_selector*, objc_selector*) const::'lambda'()::operator()() const + 59
46  plugdata                      	       0x102fb5eb9 juce::JuceNSViewClass::JuceNSViewClass()::'lambda'(objc_object*, objc_selector*, objc_selector*)::operator()(objc_object*, objc_selector*, objc_selector*) const + 41
47  plugdata                      	       0x102fb5f35 juce::JuceNSViewClass::JuceNSViewClass()::'lambda'(objc_object*, objc_selector*, objc_selector*)::__invoke(objc_object*, objc_selector*, objc_selector*) + 37
48  AppKit                        	    0x7ff81c75710c -[NSTextInputContext(NSInputContext_WithCompletion) doCommandBySelector:completionHandler:] + 236
49  AppKit                        	    0x7ff81c681b19 -[NSKeyBindingManager(NSKeyBindingManager_MultiClients) interpretEventAsCommand:forClient:] + 2151
50  AppKit                        	    0x7ff81c68a5e2 __84-[NSTextInputContext _handleEvent:options:allowingSyntheticEvent:completionHandler:]_block_invoke_5 + 499
51  AppKit                        	    0x7ff81ce3752a __84-[NSTextInputContext _handleEvent:options:allowingSyntheticEvent:completionHandler:]_block_invoke_3.843 + 74
52  AppKit                        	    0x7ff81c68a3cc -[NSTextInputContext tryHandleEvent_HasMarkedText_withDispatchCondition:dispatchWork:continuation:] + 87
53  AppKit                        	    0x7ff81ce374b0 __84-[NSTextInputContext _handleEvent:options:allowingSyntheticEvent:completionHandler:]_block_invoke.840 + 251
54  HIToolbox                     	    0x7ff822c5a30f __TSMProcessRawKeyEventWithOptionsAndCompletionHandler_block_invoke_5 + 70
55  HIToolbox                     	    0x7ff822c6b3cc invocation function for block in DispatchEventToHandlers(EventTargetRec*, OpaqueEventRef*, HandlerCallRec*) + 110
56  AppKit                        	    0x7ff81ce32ab4 __55-[NSTextInputContext handleTSMEvent:completionHandler:]_block_invoke.310 + 583
57  AppKit                        	    0x7ff81c683888 __55-[NSTextInputContext handleTSMEvent:completionHandler:]_block_invoke_2 + 74
58  AppKit                        	    0x7ff81c683809 -[NSTextInputContext tryHandleTSMEvent_HasMarkedText_withDispatchCondition:dispatchWork:continuation:] + 87
59  AppKit                        	    0x7ff81c682e0e -[NSTextInputContext handleTSMEvent:completionHandler:] + 1821
60  AppKit                        	    0x7ff81c682680 _NSTSMEventHandler + 299
61  HIToolbox                     	    0x7ff822bfc34d DispatchEventToHandlers(EventTargetRec*, OpaqueEventRef*, HandlerCallRec*) + 1365
62  HIToolbox                     	    0x7ff822bfb79c SendEventToEventTargetInternal(OpaqueEventRef*, OpaqueEventTargetRef*, HandlerCallRec*) + 333
63  HIToolbox                     	    0x7ff822bfb63d SendEventToEventTargetWithOptions + 45
64  HIToolbox                     	    0x7ff822c567e3 SendTSMEvent_WithCompletionHandler + 442
65  HIToolbox                     	    0x7ff822c56c53 __SendUnicodeTextAEToUnicodeDoc_WithCompletionHandler_block_invoke + 393
66  HIToolbox                     	    0x7ff822c56aa5 __SendFilterTextEvent_WithCompletionHandler_block_invoke + 182
67  HIToolbox                     	    0x7ff822c56831 SendTSMEvent_WithCompletionHandler + 520
68  HIToolbox                     	    0x7ff822c565fc SendFilterTextEvent_WithCompletionHandler + 219
69  HIToolbox                     	    0x7ff822c562dd SendUnicodeTextAEToUnicodeDoc_WithCompletionHandler + 274
70  HIToolbox                     	    0x7ff822c56086 __utDeliverTSMEvent_WithCompletionHandler_block_invoke_2 + 281
71  HIToolbox                     	    0x7ff822c55ee6 __utDeliverTSMEvent_WithCompletionHandler_block_invoke + 362
72  HIToolbox                     	    0x7ff822c55d4e TSMKeyEvent_WithCompletionHandler + 609
73  HIToolbox                     	    0x7ff822c55ad2 __TSMProcessRawKeyEventWithOptionsAndCompletionHandler_block_invoke_4 + 250
74  HIToolbox                     	    0x7ff822c55951 __TSMProcessRawKeyEventWithOptionsAndCompletionHandler_block_invoke_3 + 257
75  HIToolbox                     	    0x7ff822c5571d __TSMProcessRawKeyEventWithOptionsAndCompletionHandler_block_invoke_2 + 285
76  HIToolbox                     	    0x7ff822c554cd __TSMProcessRawKeyEventWithOptionsAndCompletionHandler_block_invoke + 274
77  HIToolbox                     	    0x7ff822c4476a TSMProcessRawKeyEventWithOptionsAndCompletionHandler + 3490
78  AppKit                        	    0x7ff81ce373a0 __84-[NSTextInputContext _handleEvent:options:allowingSyntheticEvent:completionHandler:]_block_invoke_3.838 + 110
79  AppKit                        	    0x7ff81ce370f2 __204-[NSTextInputContext tryTSMProcessRawKeyEvent_orSubstitution:dispatchCondition:setupForDispatch:furtherCondition:doubleSpaceSubstitutionCondition:doubleSpaceSubstitutionWork:dispatchTSMWork:continuation:]_block_invoke.799 + 120
80  AppKit                        	    0x7ff81c68114e -[NSTextInputContext tryTSMProcessRawKeyEvent_orSubstitution:dispatchCondition:setupForDispatch:furtherCondition:doubleSpaceSubstitutionCondition:doubleSpaceSubstitutionWork:dispatchTSMWork:continuation:] + 245
81  AppKit                        	    0x7ff81c680b48 -[NSTextInputContext _handleEvent:options:allowingSyntheticEvent:completionHandler:] + 1422
82  AppKit                        	    0x7ff81c68057f -[NSTextInputContext _handleEvent:allowingSyntheticEvent:] + 105
83  plugdata                      	       0x102fb22c2 juce::NSViewComponentPeer::sendEventToInputContextOrComponent(NSEvent*)::'lambda0'()::operator()() const + 114
84  plugdata                      	       0x102fb216f juce::NSViewComponentPeer::sendEventToInputContextOrComponent(NSEvent*) + 127
85  plugdata                      	       0x102fb48cd juce::JuceNSViewClass::JuceNSViewClass()::'lambda8'(objc_object*, objc_selector*, NSEvent*)::operator()(objc_object*, objc_selector*, NSEvent*) const + 61
86  plugdata                      	       0x102fb4945 juce::JuceNSViewClass::JuceNSViewClass()::'lambda8'(objc_object*, objc_selector*, NSEvent*)::__invoke(objc_object*, objc_selector*, NSEvent*) + 37
87  AppKit                        	    0x7ff81c76d0c3 -[NSView performKeyEquivalent:] + 188
88  AppKit                        	    0x7ff81cd01de5 -[NSWindow _commonPerformKeyEquivalent:conditionally:] + 73
89  AppKit                        	    0x7ff81cbcc42c routeKeyEquivalent + 303
90  AppKit                        	    0x7ff81c5e5830 -[NSApplication(NSEvent) sendEvent:] + 1132
91  AppKit                        	    0x7ff81c89e18b -[NSApplication _handleEvent:] + 65
92  AppKit                        	    0x7ff81c466d3e -[NSApplication run] + 623
93  plugdata                      	       0x1031dd311 juce::MessageManager::runDispatchLoop() + 129
94  plugdata                      	       0x1031dd211 juce::JUCEApplicationBase::main() + 321
95  plugdata                      	       0x1031dd06c juce::JUCEApplicationBase::main(int, char const**) + 60
96  plugdata                      	       0x102c88363 main + 51
97  dyld                          	       0x20abc952e start + 462

**Comment by timothyschoen** [comment]
Nice, that's a very clear backtrace, it should be fixed now!

Sending crash reports is definitely helpful!
