### ISSUE TITLE
autocomplete makes it impossible to input abstraction names

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#512]
the way autocomplete starts over when you're typing the name of a non-existing object makes it impossible to type in the name of a local abstraction. try typing "emoji", you can't. (that's an abstraction i have) hopefully that's clear, i'm not fully awake rn

**Comment by tomara-x** [comment]
well not impossible, just annoyingly difficult (had to open in text editor and add it in)

**Comment by tomara-x** [comment]
so for some words it does work but not for others:


https://user-images.githubusercontent.com/86204514/217992727-b52fda6a-1849-43c8-8d09-025f64908c60.mp4

**Comment by timothyschoen** [comment]
Should be fixed!

If the suggestion doesn't complete the text that you've already typed, you now need to explicitly move to the suggestions by using the up/down key, which allows you to enter abstractions normally again!
