### ISSUE TITLE
[function] points can get "stuck" behind the inlet/outlet

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#513]
i don't know if you've ever ran into this, but sometimes if you have a point close enough to the inlet or outlet it can get very difficult to "catch" that point and move it. sure you can bang the output of function and edit the value of that point, but any possibility to make that easier using the ui?
see this third point? it's impossible to move it by dragging normally
![Screenshot_2023-02-09_15-26-29](https://user-images.githubusercontent.com/86204514/217825259-b4ca8bca-c238-459c-9c6c-dd813c73e7b4.png)

**Comment by tomara-x** [comment]
lol i guess a workaround for my situation is to give function send and receive symbols :p

**Comment by timothyschoen** [comment]
Fixed, inlets/outlets now don't intercept any mouse activity at all when locked.
