### ISSUE TITLE
Array GUI not always updating visually

### ISSUE THREAD

**Issue by alfonso73** [plugdata-team/plugdata#518]
While doing some quick experiment for a [bonk~] based onset detection patch for buffers i've found a strange "bug" the table at the top is correctly updated in PD vanilla but not in PlugData (it's a big table of 100.000 values that i made to check visually where the onset transients are detected in the provided audio buffer)
https://streamable.com/2y65mh vanilla working correctly
https://streamable.com/kdplvg PlugData not updating visually the upper table
Btw values are actually written to the table. It's just a visualization problem. Given that the table's size  is 100.000 values it's probably a matter of scaling to the few pixels the array Gui width actually  is.

**Comment by timothyschoen** [comment]
Is this still a thing? I tried very large arrays, it seems to work now!

**Comment by timothyschoen** [comment]
Seems to be fixed?
