### ISSUE TITLE
relative grid vertical/horizontal freeze

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#530]
https://user-images.githubusercontent.com/86204514/218396031-a90439df-dc3d-436d-999c-09e7638f7fe0.mp4

i don't know how to describe it. if it's locked on something vertical, and you move horizontally, the movement doesn't happen unless you move also vertically?

[edit: better video]

https://user-images.githubusercontent.com/86204514/218396963-0579b01a-5b37-49ec-9b3d-e007e4d356de.mp4

**Comment by timothyschoen** [comment]
I think I fixed it with 1011b6e4dbbf15c5bfbd58624761d64582beaee1

**Comment by tomara-x** [comment]
mmm sublime work as usual!
only thing left is when it's horizontal locked, everything else is smooth

https://user-images.githubusercontent.com/86204514/218486031-152a225d-a222-41c4-8e21-47f7e9bd8695.mp4
