### ISSUE TITLE
with mouse selection , object slides itself diagonally to the bottom right of the interface

### ISSUE THREAD

**Issue by maxence-mercier** [plugdata-team/plugdata#531]
Hello

On Macbook pro M1 max, when I edit a patch, if I select an object with the mouse and I want to move it, it slides all by itself diagonally to the bottom right of the interface. I have tried several times, with the editor or as a vst plugin, the phenomenon occurs again and prevents me from editing a patch.

**Comment by timothyschoen** [comment]
Hi, thanks for reporting.

What plugdata version are you using, v0.6.4 or v0.7.0? I've never seen this happen before, so maybe it might be related to the DAW you're using as well.

**Comment by maxence-mercier** [comment]
I'm sorry for this weird problem, I don't encounter it on any other software. I will try it on another machine. Anyway, congratulations for your initiative which gives PD a serious boost! I use 0.6.2

**Comment by timothyschoen** [comment]
Ah, in that case, I recommend updating, there has been a lot of progress since 0.6.2, so it's likely that it's already fixed.

Over here you can find the latest stable and nightly builds:

https://plugdata.org/download.html
