### ISSUE TITLE
[FR] Differentiate Subpatch objects graphically  

### ISSUE THREAD

**Issue by alcomposer** [plugdata-team/plugdata#550]
Subpatch objects (starting with `PD`) enable a user to click on, and open up another patcher, that is nested in the parent patch.

However there is currently no visual way that we display these teleporting objects.

It helps to see visually at a glance when they are used, so that a user can see the layout and understand how the patch works.

Here is a suggestion, to use a triangle, with a chevron positioned to the right of the object to symbolise that these objects open an external patch. For objects that simply open a floating window, use only the triangle and omit the chevron:
![image10](https://user-images.githubusercontent.com/12004932/219545587-004440aa-b504-4f03-898d-007cbe65b761.png)

**Comment by timothyschoen** [comment]
Maybe having a hover colour on the text would be nice, that way it's clear, and it also doesn't mess with the patch formatting. What do you think?

**Comment by alcomposer** [comment]
Maybe. What I like about having a display for this is it's clearer when looking over the whole patch.

Otherwise a user needs to hover over objects that they think could open up. 

If we have it as an optional overlay, then it would be up to the user if they feel it's useful to them.

I don't think it would mess up the format too much. At least nowhere near as much as different fonts.

**Comment by timothyschoen** [comment]
Not planned for now, maybe someday if we find a better way to do it
