### ISSUE TITLE
Zoomed in: problem creating selections by dragging the mouse

### ISSUE THREAD

**Issue by sevdh** [plugdata-team/plugdata#554]
When zoomed in (for example to 140%) creating selections by dragging the mouse has some unpredictable behaviour and it seems that the zoom factor is not properly taken into account in the selection and scrolling behaviour.

The attached video show that at:
00:01 - at the beginning of pressing down the mouse button the displayed patch jumps/scrolls unexpectedly.
00:05 - while dragging to the right the selection widens unexpectedly
00:07 - while dragging further to the right the displayed patch doesn't scroll further to the right and we can not extend the selection further.
00:13 - while making a downward selection the displayed patch jumps all of a sudden to a different position. 
00:16 - it's not possible to extend the selection further downwards and the patch doesn't scroll.
00:24 - repetition of 00:13
00:29 - same issue as 00:01
00:33 - same issue as 00:05

https://user-images.githubusercontent.com/16959264/219873956-1bb5c761-ae77-4da6-8a06-faf4051fbc79.mov

I've also attached the patch:
[mouse selection test at zoom 140 percent.pd.zip](https://github.com/plugdata-team/plugdata/files/10774632/mouse.selection.test.at.zoom.140.percent.pd.zip)

**Comment by timothyschoen** [comment]
Should be fixed, I implemented to auto-scrolling manually instead of letting JUCE handle it, this bug doesn't happen anymore and it also feels a lot smoother.

While I was working on this, I also made the scrollbars auto-hide when you're not scrolling.

**Comment by sevdh** [comment]
Much smoother indeed!Great work.On 21 Feb 2023, at 16:07, Timothy Schoen ***@***.***> wrote:﻿
Should be fixed, I implemented to auto-scrolling manually instead of letting JUCE handle it, this bug doesn't happen anymore and it also feels a lot smoother.
While I was working on this, I also made the scrollbars auto-hide when you're not scrolling.
