### ISSUE TITLE
Can't type decimals when using PlugData as a VST3 plugin in Ardour 6.

### ISSUE THREAD

**Issue by alexdrymonitis** [plugdata-team/plugdata#559]
When using PlugData in standalone, I  can type any value I want in objects and messages. When I use it inside Ardour6 as a VST3 plugin, all decimal digits are trimmed out and the value left in objects and messages is the integral part only.
I'm on UbuntuStudio 22.04, with PlugData 0.6.4.

**Comment by tomara-x** [comment]
do you mean something like this?
![Screenshot_2023-02-20_13-13-29](https://user-images.githubusercontent.com/86204514/220090108-1765ec00-7ac1-4c08-adf5-cf5e4b1d8c65.png)

this works in 0.7.0 (nightly build) (but i'm also using ardour 7 so i don't know if that's a factor)

**Comment by alexdrymonitis** [comment]
Yes, this is what I mean. Where do I get the nightly build?

**Comment by tomara-x** [comment]
you can get it from here: https://plugdata.org/download.html
it gets updated whenever any change is made to the code ;)

**Comment by alexdrymonitis** [comment]
Ok, I downloaded the nightly built which works find in standalone, but in Ardour, even though the plugin manager can see the plugdata.vst3 and plugdata-fx.vst3 files that I placed in ~/.vst3, they can't be favorited (I couldn't do that with PlugData0.6.4 either), nor can I load them to a session through the plugin selector. Any ideas?

**Comment by tomara-x** [comment]
okay there were some changes in ardour 7 so this might not be helpful. you say they're there in the plugin manager, but what does it say in their status column? does it say, "ok" or something like "stale" or "error" or "updated"?
![Screenshot_2023-02-20_13-59-36](https://user-images.githubusercontent.com/86204514/220100511-6de3fa15-3bdf-400f-93e2-927624261bf6.png)
if it says stale or updated you just need to select it and click re-scan selected (i think, i hope that works)

**Comment by alexdrymonitis** [comment]
That did the trick thank you! Although, I think the issue is a bit different. I can create objects and messages with floating point values, but I can't edit objects with floating point values, I get the integral then. If a create a new object, it works fine. I guess I have to close this issue and open another one.
