### ISSUE TITLE
Middle Mousebutton always should pan

### ISSUE THREAD

**Issue by alcomposer** [plugdata-team/plugdata#562]
Middle mouse button should always pan, regardless if over object or not.

**Comment by timothyschoen** [comment]
I don't have a middle mouse button so I'm not able to test this very often :)

**Comment by timothyschoen** [comment]
Ohh wow I now see that there is a "setScrollOnDragEnabled()" function on Viewport! So if you have some time, you could implement better middle-mouse pan using that.

**Comment by alcomposer** [comment]
Mainly this issue is about objects taking the middle mouse click, such as object, iolet, gui etc.

However I did test `setScrollOnDragEnabled()` however that is inertial scrolling by default? I don't think there is a setting in Juce for this.
![Uploading inertia.gif…]()

**Comment by timothyschoen** [comment]
i merged your draft and fixed it by not making child component receive events when middle mouse is down.

I've also mapped space to do the same thing as middle-mouse pan.
