### ISSUE TITLE
slider doesn't work when min and max values are inverted

### ISSUE THREAD

**Issue by jyg** [plugdata-team/plugdata#565]
Unlike pd vanilla, where you can have a slider with min and max values inverted (min_val > max_val), in plugdata it makes the slider freeze.
![image](https://user-images.githubusercontent.com/1431894/220472892-f3a90be7-6ef0-4748-871e-f9b3c03d9d31.png)

**Comment by timothyschoen** [comment]
Thanks for fixing this!
