### ISSUE TITLE
Patch parameters bugs

### ISSUE THREAD

**Issue by t-scale** [plugdata-team/plugdata#568]
Hey,

Using the latest nightly build (0.7.0), parameters do get saved with the patch in standalone but it takes two steps for them to appear,
it's easier to demonstrate with the following gif:

![plugdata](https://user-images.githubusercontent.com/4723347/220622618-ac2cd53a-e204-4049-ab3d-dca78e46c71c.gif)

They do not load or appear after those steps in VST3 or AU format.
The parameter numbers increment after being deleted, there is also a 2 or 3 second freeze in between (only in Renoise).
Tried in both Renoise and Reaper:

Renoise:
![plugdatarenoise](https://user-images.githubusercontent.com/4723347/220633709-06fa3fbb-59a9-4551-89cd-2e4ea7388553.gif)

Reaper:
![plugdatareaper](https://user-images.githubusercontent.com/4723347/220634456-c1dbcc44-89e3-4f9b-aec2-00e99e90f2e9.gif)

macOS 11.7.4 (Big Sur), x64

**Comment by t-scale** [comment]
Tried with the stable 0.7 and the bug is still there.
Now, in standalone, all the parameters get loaded up but their names and ranges don't unless I add and delete one.
The iteration still happens, as well.

![plugdatabug](https://user-images.githubusercontent.com/4723347/223053157-eb680909-9bfd-4a05-ad45-3ce936bbe878.gif)

In VST3, AU, LV2 and CLAP parameters don't load at all.

**Comment by timothyschoen** [comment]
Testing the latest nightly builds, it appears parameters are reloading correctly for me under macOS (Logic) and Linux (Reaper)
