### ISSUE TITLE
save warning missing on unsaved patch close

### ISSUE THREAD

**Issue by alcomposer** [plugdata-team/plugdata#579]
In newest develop 5f61f29, the save warning when closing a patch is no longer triggered.

**Comment by alcomposer** [comment]
Happens regardless of if patch is saved or unsaved:

![no-save-warning](https://user-images.githubusercontent.com/12004932/221392561-2eefac40-cd5b-4575-82d9-edb1673990f9.gif)

**Comment by timothyschoen** [comment]
Fixed!

**Comment by tomara-x** [comment]
this does work when you click the x button or try to quit plugdata, but if you try closing the patch by pressing ctrl+w it closes without asking

**Comment by tomara-x** [comment]
the same happens when using "close patch" from the menu

https://user-images.githubusercontent.com/86204514/222898078-8d30d052-cd32-440b-8e99-e66b4da09d8e.mp4

**Comment by FlachyJoe** [comment]
Is #631 related ?
