### ISSUE TITLE
[FR][BUG] multiple selected objects across split & no identification of active split

### ISSUE THREAD

**Issue by alcomposer** [plugdata-team/plugdata#581]
Currently (in 5f61f298) with the new split feature, we need:

* Ability to see which split is active, to add new objects / set `edit | lock | run` mode etc.
* Objects can be selected in both splits, without knowing which split is currently active
![whichone?](https://user-images.githubusercontent.com/12004932/221103804-3f11ce24-949c-42a7-8512-32ac8a03bc01.gif)
I suggest that we highlight the currently active split view: (only in split mode)
![split-mode-highlight-active](https://user-images.githubusercontent.com/12004932/221104452-a77b88c1-004c-42f6-ab22-548350876bdc.png)
NOTES:
* clicking on any object / canvas / tab moves to that split selection

**Comment by timothyschoen** [comment]
You fixed it! And I also fixed grabbing focus when clicking on objects/connections.
