### ISSUE TITLE
no mouse indicator when grabbing gop veiwport

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#586]
mouse doesn't change to the grabby thingy

https://user-images.githubusercontent.com/86204514/221268901-3d5c39c1-46e3-452a-8886-8ccda25cc832.mp4

**Comment by alcomposer** [comment]
This would be intentional? I think hand cursor should only be used for pan dragging the canvas.

**Comment by tomara-x** [comment]
there used to be this thing:

![Screenshot_2023-02-25_04-09-11](https://user-images.githubusercontent.com/86204514/221330579-d5bab915-c01f-4fba-8926-f2c61850018d.png)

it makes it easier to grab them (i think, maybe it's just placebo lol), but also indicates that "oh this is a thing that can be moved"

**Comment by alcomposer** [comment]
Hm, I suppose we can use that cursor for this, as we are now using hand for canvas. Looks like a good solution!

**Comment by timothyschoen** [comment]
Fixed! I do actually like the hand more, so I did that for now, but we can still change it. I think the user can easily understand from context that it's not the same thing as mouse-panning.
