### ISSUE TITLE
GOP doesn't regain GUI when opened in split and parent at same time

### ISSUE THREAD

**Issue by alcomposer** [plugdata-team/plugdata#589]
When we open a GOP in split view, and the parent in the other split view, then close the opened GOP, the GUI does not regenerate of the GOP.

![graph_opened.gif](https://user-images.githubusercontent.com/12004932/221363631-52e0d81c-8b02-45b3-895f-b35833b53db0.gif)

**Comment by timothyschoen** [comment]
Should be fixed!
