### ISSUE TITLE
[FR] new multi-connection from non-selected iolet should select

### ISSUE THREAD

**Issue by alcomposer** [plugdata-team/plugdata#590]
We can currently drag a new connection from an non-selected object iolet, while holding shift, but the other selected iolets will generate new connections but not the non-selected one.

If a user drags a new connection from a non-selected iolet, the object should also become selected.

See current behaviour below:
![drag-unselected-iolet-also-selects](https://user-images.githubusercontent.com/12004932/221391428-107bd818-4811-49f5-8b0e-11272c4dd4eb.gif)

**Comment by timothyschoen** [comment]
Fixed!
