### ISSUE TITLE
cyclone help files issues

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#599]
- cyclone comments used for object names and descriptions display wrong
- [setdsp~] does work, but [cyclone/setdsp~] does not
- [cyclone/number~] too

![Screenshot_2023-02-26_21-57-05](https://user-images.githubusercontent.com/86204514/221433862-9c00e594-38aa-41e9-a38a-22e1882cead6.png)

**Comment by timothyschoen** [comment]
Fixed, after you clear out plugdata's appdata folder. I'll make sure to set the version name to v0.7.0-0 when releasing, to make sure everyone really gets the latest abstractions and documentation.

**Comment by tomara-x** [comment]
oh yes! this is a great idea!
