### ISSUE TITLE
multi.vsl crashing on macOS

### ISSUE THREAD

**Issue by broadskins** [plugdata-team/plugdata#607]
When sending a message to set the number sliders to a multi.vsl it doesn't set the right number, and Plugdate crashes. Attached is a crash report.
[Plugdata multivsl crash report 27 02 23.txt](https://github.com/plugdata-team/plugdata/files/10845004/Plugdata.multivsl.crash.report.27.02.23.txt)

**Comment by timothyschoen** [comment]
Hi! I see you're using plugdata v0.6.4, I would recommend trying in the plugdata v0.7.0 pre-release, which is about to be released. I tried it in v0.7.0, it appears to be fixed!

You can get it here, under Nightly: https://plugdata.org/download.html

**Comment by broadskins** [comment]
Nice - will try that now!

**Comment by broadskins** [comment]
Still getting some weird behaviour with the multi.vsl. If I try to change the number of sliders with a message ("n 6" for instance) it doesn't change the number of sliders in the parent patch, but does change the number inside the multi.vsl object. Also, if I click on clear inside the multi.vsl object Plugdata crashes.
