### ISSUE TITLE
crash report without specific cause

### ISSUE THREAD

**Issue by sevdh** [plugdata-team/plugdata#611]
This is a crash report while patching with the nightly version. I'm sorry I don't have a specific cause:

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               plugdata [36461]
Path:                  /Applications/plugdata.app/Contents/MacOS/plugdata
Identifier:            com.plugdata.plugdata
Version:               0.7.0 (0.7.0)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               502

Date/Time:             2023-02-28 08:38:40.9676 +0100
OS Version:            macOS 12.6.3 (21G419)
Report Version:        12
Anonymous UUID:        71803FF8-D537-93A1-48CA-EB63CE79AB73

Sleep/Wake UUID:       638B644F-ABDF-4A81-B68E-DD5BB09FA522

Time Awake Since Boot: 290000 seconds
Time Since Wake:       4257 seconds

System Integrity Protection: enabled

Crashed Thread:        0  JUCE Message Thread  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x3ff0000000000000 -> 0xffff800000000000 (possible pointer authentication failure)
Exception Codes:       0x0000000000000001, 0x3ff0000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [36461]

VM Region Info: 0xffff800000000000 is not in any region.  Bytes after previous region: 18446497782568058881  
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      MALLOC_NANO (reserved)   600018000000-600020000000 [128.0M] rw-/rwx SM=NUL  ...(unallocated)
--->  
      UNUSED SPACE AT END

Thread 0 Crashed:: JUCE Message Thread Dispatch queue: com.apple.main-thread
0   plugdata                      	       0x1008fb2b4 Connection::popPathState() + 72
1   plugdata                      	       0x10088e1b8 Canvas::synchronise(bool) + 2244
2   plugdata                      	       0x10088e1b8 Canvas::synchronise(bool) + 2244
3   plugdata                      	       0x100894180 Canvas::removeSelection() + 768
4   plugdata                      	       0x100cd4338 PluginEditor::perform(juce::ApplicationCommandTarget::InvocationInfo const&) + 848
5   plugdata                      	       0x1010e86cc juce::ApplicationCommandTarget::tryToInvoke(juce::ApplicationCommandTarget::InvocationInfo const&, bool) + 176
6   plugdata                      	       0x1010e7a18 juce::ApplicationCommandTarget::invoke(juce::ApplicationCommandTarget::InvocationInfo const&, bool) + 84
7   plugdata                      	       0x101039394 juce::ApplicationCommandManager::invoke(juce::ApplicationCommandTarget::InvocationInfo const&, bool) + 216
8   plugdata                      	       0x1010e9770 juce::KeyPressMappingSet::invokeCommand(int, juce::KeyPress const&, bool, int, juce::Component*) const + 152
9   plugdata                      	       0x1010ea510 juce::KeyPressMappingSet::keyPressed(juce::KeyPress const&, juce::Component*) + 284
10  plugdata                      	       0x1010de398 juce::ComponentPeer::handleKeyPress(juce::KeyPress const&) + 172
11  plugdata                      	       0x1010de2dc juce::ComponentPeer::handleKeyPress(int, wchar_t) + 96
12  plugdata                      	       0x1011997ac juce::NSViewComponentPeer::handleKeyEvent(NSEvent*, bool) + 504
13  plugdata                      	       0x101198fc8 juce::NSViewComponentPeer::redirectKeyDown(NSEvent*) + 88
14  plugdata                      	       0x101198e1c juce::NSViewComponentPeer::sendEventToInputContextOrComponent(NSEvent*) + 240
15  plugdata                      	       0x101198cc0 juce::JuceNSViewClass::JuceNSViewClass()::'lambda6'(objc_object*, objc_selector*, NSEvent*)::operator()(objc_object*, objc_selector*, NSEvent*) const::'lambda'()::operator()() const + 72
16  plugdata                      	       0x101198bf0 juce::JuceNSViewClass::JuceNSViewClass()::'lambda6'(objc_object*, objc_selector*, NSEvent*)::operator()(objc_object*, objc_selector*, NSEvent*) const + 52
17  plugdata                      	       0x101198c6c juce::JuceNSViewClass::JuceNSViewClass()::'lambda6'(objc_object*, objc_selector*, NSEvent*)::__invoke(objc_object*, objc_selector*, NSEvent*) + 44
18  AppKit                        	       0x1ba783e88 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 5908
19  AppKit                        	       0x1ba78250c -[NSWindow(NSEventRouting) sendEvent:] + 348
20  AppKit                        	       0x1ba7814b4 -[NSApplication(NSEvent) sendEvent:] + 2780
21  AppKit                        	       0x1baa3b0f4 -[NSApplication _handleEvent:] + 76
22  AppKit                        	       0x1ba603008 -[NSApplication run] + 636
23  plugdata                      	       0x1013d058c juce::MessageManager::runDispatchLoop() + 128
24  plugdata                      	       0x1013d0480 juce::JUCEApplicationBase::main() + 316
25  plugdata                      	       0x1013d02ec juce::JUCEApplicationBase::main(int, char const**) + 68
26  plugdata                      	       0x100e6fb68 main + 56
27  dyld                          	       0x107dbd08c start + 520

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x000000013a692d60   x1: 0x000000000000002a   x2: 0x000000013a68ff50   x3: 0x000000013a68ff50
    x4: 0x0000000000000001   x5: 0x0000000000000000   x6: 0x0000000211b03228   x7: 0x00000001b799c6cc
    x8: 0x3ff0000000000000   x9: 0x000000000000002a  x10: 0x0000000000000000  x11: 0x00000000000007fd
   x12: 0x0000000000000057  x13: 0x0000000067fffffc  x14: 0x0000000068000000  x15: 0x00000000680007fc
   x16: 0x00000001008deed4  x17: 0xbd61000211b03290  x18: 0x0000000000000000  x19: 0x000000013a7129d0
   x20: 0x000060000537c900  x21: 0x0000000201e5ba7b  x22: 0x000000013a712510  x23: 0x0000000201e216d1
   x24: 0x0000000201d9d160  x25: 0x000000000000000a  x26: 0x000000002bd80025  x27: 0x0000000000000000
   x28: 0x00000000000000fc   fp: 0x000000016f57e230   lr: 0x000000010088e1b8
    sp: 0x000000016f57e100   pc: 0x00000001008fb2b4 cpsr: 0x80001000
   far: 0x3ff0000000000000  esr: 0x92000004 (Data Abort) byte read Translation fault

**Comment by timothyschoen** [comment]
I just received the same one from someone else as well, I'm hoping to fix this before the v0.7.0 release, but it's still unclear to me what's causing this

**Comment by timothyschoen** [comment]
Do you happen to know if you were testing before or after f34a818377baf776ebae121ffdfe342afac65525?

That was my attempt at fixing this bug, I'm not sure if it helps because I can't reliably reproduce it. If you tested before this fix, then we can hope this never happens again anymore.

**Comment by sevdh** [comment]
It happened with a version that I've installed yesterday (Tuesday) morning at 07:39. It means that it was before your possible fix. I'll update to the latest nightly.

**Comment by timothyschoen** [comment]
I've now really fixed it with 31d6000eb43a80f72b2cc74771767396b6cca007
