### ISSUE TITLE
Linux: Can't press ctrl-n when first open plugdata

### ISSUE THREAD

**Issue by alcomposer** [plugdata-team/plugdata#613]
When we first open plugdata, we can't press `ctrl-n` to make a new patch, only after we have added patches.

It will also work if we then close all patches, but only after we have done so.

**Comment by alcomposer** [comment]
Even with this fix, when I open plugdata, unless I click first somewhere on the app, I can't do `ctrl-n`.

**Comment by Nejrup** [comment]
> Even with this fix, when I open plugdata, unless I click first somewhere on the app, I can't do `ctrl-n`.

Works in macOS.. can you check if 'content->grabKeyboardFocus();' is called on your Linux build?

**Comment by timothyschoen** [comment]
Is this still an issue? It works over here on macOS

**Comment by alcomposer** [comment]
Yes, still issue on Linux.

**Comment by dromer** [comment]
Same for `ctrl+o`. Only after you've manually created a new, or opened an existing, patch do these key combos work.

**Comment by timothyschoen** [comment]
https://github.com/plugdata-team/plugdata/blob/7f8585515435c802722fb5260d9652db748e4240/Source/PluginEditor.cpp#L292 

Fixed it for me

**Comment by dromer** [comment]
Yay! works for both `ctrl+n` and `ctrl+o` !
