### ISSUE TITLE
subpatch responds to [vis 1( message only if parent patch is visible.

### ISSUE THREAD

**Issue by jyg** [plugdata-team/plugdata#615]
by parent patch visible, I mean either it's opened in a new tab, OR because GOP is enabled so that it's painted in grandparent patch.
Unlike Pd vanilla, where encapsulation level of subpatch or abstraction doesn't mind.
[TestVisMessageDepth.pd.txt](https://github.com/plugdata-team/plugdata/files/10862395/TestVisMessageDepth.pd.txt)

joined test patch (with .txt extension to remove)

**Comment by jyg** [comment]
Same behaviour for [key], I suppose.

**Comment by timothyschoen** [comment]
yeah this is a big problem unfortunately. Loading the GUIs all objects, even if they are inside a subpatch/abstraction, makes plugdata incredibly slow. But that does mean that objects that require extra input from plugdata won't work.

We could maybe mark some objects as "always create", and create minimal wrappers for those that are always loaded on the top-level canvas. I experimented with such a system on [this](https://github.com/plugdata-team/plugdata/tree/proxy-obj-test) branch, but it's still far from working.

**Comment by jyg** [comment]
Meanwhile, the workaround is to be aware of that and to put the subpatch inside a visible (or gop-enabled) parent patch. For my goals (getting popup menus) it's ok as it is. Thanks

**Comment by timothyschoen** [comment]
Fixed!
