### ISSUE TITLE
Conflict between Live-Coding-Toolkit-for-Pure-Data's cycle.pd  and cyclone 0.6-1's

### ISSUE THREAD

**Issue by bencharp** [plugdata-team/plugdata#618]
Hello,

Background: 
I'm trying to reproduce the patch from the video  [Live Coding Toolkit for Pure Data - Part 10 by Andrew R. Brown](https://youtu.be/1hyn5W6L8sI) in plugdata.

In the video the [cycle] object used in the patch is the one from the Live-Coding-Toolkit-for-Pure-Data.
In plugdata, the [cycle] object that is loaded is the one coming from cyclone 0.6-1.
When testing under Pure-Data with Cyclone 0.7-0, the [cycle] object used is indeed the one from the toolkit and to use the one from Cyclone, I've juste have to call it with the external's name [cyclone/cycle]

Is the next Plugdata's version will come with  Cyclone's update or is there a possibility to replace cyclone 0.6-1 by the 0.7-0?

Thanks for all this great job

**Comment by timothyschoen** [comment]
Hi!

plugdata's develop branch is already using cyclone v0.7.0, so I hope that will solve your problems. If you get a nightly build from [here](https://plugdata.org/download.html), you can already try it out, but it will be released in a few days.

**Comment by bencharp** [comment]
Hi,

I saw that version 0.7-0 was released but I prefer to wait until it is available on the OBS.

Thanks again for this great job

**Comment by bencharp** [comment]
Hi,

I have the same problem with plugdata 0.7-0.

In Plugdata, the [cycle] object called by default is the cyclone object.
In Pure-Data, the default [cycle] object is the one from [Live-Coding-Toolkit-for-Pure-Data](https://github.com/algomusic/Live-Coding-Toolkit-for-Pure-Data).

Do you have any idea how to reproduce the behavior of Pure-Data in Plugdata? Or should I turn to[ Andrew Brown (algomusic)](https://github.com/algomusic) the author of the toolkit?

Thanks again for your attention

**Comment by tomara-x** [comment]
i see this is an abstraction, as a workaround, one way to load it and not the cyclone/cycle is to use the path to it (in my case i've put it in the same folder as the patch i'm testing in)

![Screenshot_2023-03-14_01-17-38](https://user-images.githubusercontent.com/86204514/224853150-1d76336e-c21d-4ebf-b39f-ab0912eceb83.png)

**Comment by timothyschoen** [comment]
I guess you'll need @tomara-x's workaround for this, unfortunately there is no real way to solve this, since it's a naming clash.

**Comment by bencharp** [comment]
I confirm that @tomara-x's solution seems to solve the problem. 
I would like to try to understand why this naming clash occurs in Plugdata and not in Pure-Data. 
Maybe the fact that Cyclone is directly integrated into Plugdata and not added as an external as in Pure-Data, change the priority between objects...
