### ISSUE TITLE
[bug] 1:1 object snap mode resize issue

### ISSUE THREAD

**Issue by alcomposer** [plugdata-team/plugdata#622]
When `snap to object` is enabled, resizing 1:1 ratio objects can't be resized correctly on top right & bottom left corner

[](https://user-images.githubusercontent.com/12004932/222338103-66a2d03e-1432-423e-a035-eea77e1dc8ca.mp4)

This code changes the size, do we need to do this at all?
https://github.com/plugdata-team/plugdata/blob/0f6464cfd5b9b8382692773c0c0026d57cb007b2/Source/ObjectGrid.cpp#L163-L167

**Comment by timothyschoen** [comment]
Should be fixed. Also improved some other things around the grid. The code is even messier now, but it works a bit better. Still planning to clean it up!
