### ISSUE TITLE
split right on the parent patch closes the subpatch

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#623]
instead of sending the parent patch to the right split, it simply closes the child

https://user-images.githubusercontent.com/86204514/222339218-465385d5-fb3c-4db2-b756-68084b1562db.mp4

---
more fun stuff when you try it with an existing split. it closes the subpatch, and swaps the patches across splits

https://user-images.githubusercontent.com/86204514/222339774-5a6f5750-7e0f-4bd0-acde-7d23a7c38ab8.mp4

**Comment by timothyschoen** [comment]
Should be fixed!
