### ISSUE TITLE
number box's font size decreasing unexpectedly

### ISSUE THREAD

**Issue by sevdh** [plugdata-team/plugdata#625]
When in edit mode: Click in the middle of a not selected number box, keep the mouse button pressed, move the mouse up (or down).

The font size of the number box will decrease half of the times you do this. The other half of the times you will start dragging the object around which I think is the expected behavior.

To test it you have to make sure that the number box is deselected before clicking (again).

**Comment by alcomposer** [comment]
Would you be able to provide a screencapture of this issues?

**Comment by sevdh** [comment]
This issue has (somehow) already been solved in the latest nightly!

However, one thing is still a bit funny: when you select a number box and drag one of the corners outwards to enlarge it, it starts from a size smaller than the current size:

https://user-images.githubusercontent.com/16959264/222724205-0da86be5-15d4-4f8a-b438-dad01af2381d.mov

**Comment by sevdh** [comment]
One more video:
https://user-images.githubusercontent.com/16959264/222725021-e5f39d1f-2f05-4289-bb66-df9cbec63f67.mov

**Comment by timothyschoen** [comment]
Thanks! Fixed with 15bd449c5a0d3a4c074e3821cf4640be62691681
