### ISSUE TITLE
Error when creating clock

### ISSUE THREAD

**Issue by broadskins** [plugdata-team/plugdata#629]
When I try to create a clock object I get the following error:

else/canvas.name -env 1
... couldn't create

This is with last few nightly updates, pretty certain it didn't happen with stable.

**Comment by tomara-x** [comment]
thank you for reporting this! this is happening because in the latest else update the [canvas.name] object was removed, and it's used inside of the [clock] abstraction. i think porres is going to add canvas.name back

**Comment by porres** [comment]
I did readd it

**Comment by timothyschoen** [comment]
Fixed!
