### ISSUE TITLE
[Issue] [; pd verifyquit< close without warning

### ISSUE THREAD

**Issue by FlachyJoe** [plugdata-team/plugdata#631]
Hi,
in pure-data a [; pd verifyquit< message ask user to save and close the app
in PlugData it acts as [; pd quit< and close without warning

**Comment by FlachyJoe** [comment]
PING ?

With 0.7 [; pd verifyquit( do nothing !

I'm trying to use standalone PlugData embedded in FreeCAD and I have no possibility to close it correctly from the host.
![image](https://user-images.githubusercontent.com/10371513/224109806-c6fc1aa4-0e35-4952-82aa-b07bf3369b74.png)

**Comment by timothyschoen** [comment]
Hi, I'll take a look soon! I didn't do anything to make verifyquit or quit work, so it was probably a coincidences (or bug) that it did work before.

I'll implement this before v0.7.1!

**Comment by timothyschoen** [comment]
I've just implemented this for the standalone version, I'm not sure if a plugin is allowed to self-destruct. If you send a quit or verifyquit message in the DAW, it will not print a warning to the console saying that it's unsupported. Other than that, it works!
