### ISSUE TITLE
Fix open/click messages to various ELSE objects

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#635]
this is unrelated to else/click -> https://github.com/plugdata-team/plugdata/issues/634 because I mean objects that are not using this object but calling an internal click function on the code, like [initmess] (that I mentioned in another issue, see --> https://github.com/plugdata-team/plugdata/issues/633 ) and now I tested [sfont~] and [loadbanger]. I now think no objects in ELSE have the click function enabled.

**Comment by timothyschoen** [comment]
Fixed!

**Comment by porres** [comment]
I can confirm with the current nightly build that else/click works and so does [imitmess], but I tried clicling in [sfont~] and [loadbanger] and it didn't work, so I'd ask you to check if all are really working.

maybe reopen this?

**Comment by porres** [comment]
Click should also be enabled in else's loadbanger and cyclone's loadmess. The other cases require other functionalities enabled that don't seem to be working either.


ELSE:
- lb/loadbanger
- colors (but 'pick' message is not working either
- midi (open message not working either)
- openfile (seems not ported/supported yet)
- rec  (open message not working either)
- sfont~ (open message not working either)

cyclone:
- loadmess
- capture (open message not working either)
- coll (open message not working either)
- prob (no open message to not work either)
- seq (read message not working either)
- table (open message not working either)

read/open message either open a text window or call a dialog to choose a file

**Comment by porres** [comment]
again, tested with latest nightly build

**Comment by timothyschoen** [comment]
Thanks for finding these!

**Comment by timothyschoen** [comment]
These all work now, except for [coll], for which I'll open a new issue.

**Comment by porres** [comment]
yay!
