### ISSUE TITLE
[namecanvas] not working (also [canvas.setname])

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#636]
I'm trying [namecanvas]'s help flle and it doesn't seem to work.

canvas.setname doesn't seem to be working either

**Comment by timothyschoen** [comment]
I think [namecanvas] does work, but plugdata doesn't fully support dynamic patching yet:


https://user-images.githubusercontent.com/44585538/222901192-46aa826d-a0b7-42d8-986b-46903b2f43f1.mov


If you create/delete an object, you can manually refresh the patch. From v0.7.1 on, dynamic patching will supported!

**Comment by jyg** [comment]
In order to refresh the main patch, you can send [vis 1(  then [vis 0( to a subpatch. It will refresh the main patch. So, for me, we are near full dynamic patching support !

**Comment by timothyschoen** [comment]
This was fixed in v0.7.1
