### ISSUE TITLE
[FR] show "*" in filename when patch has unsaved changes

### ISSUE THREAD

**Issue by alcomposer** [plugdata-team/plugdata#637]
When a patch has unsaved changes, it would be very useful to display an asterisk in the file name display: `* voice.pd` when a user saves it, the asterisk disappears, here is example of blender:

[](https://user-images.githubusercontent.com/12004932/222881769-8b8ba3d8-ebd0-417e-9fdf-602a5cc11051.mp4)

**Comment by jaffasplaffa** [comment]
In general I find saving a bit confusing in Plugdata.

When I load a patch and save it to disc, via Plugdata and choose a destination to save it to and then afterwards save Logic and then reopen the Logic project, it does not open the right PD patch. I have to load the PD patch in Plugdata again, manually, to be able to load the right PD patch.

It's a bit confusing, I am not sure if the PD patch being used, is the one I saved to disc or the PD patch is somehow stored/embedded in Plugdata.

**Comment by jyg** [comment]
> In general I find saving a bit confusing in Plugdata, when using it as a plugin.
> 
> When I load a patch and save it to disc via Plugdata plugin and choose a destination to save it to and then afterwards save Logic and then reopen the Logic project, it does not open the PD patch I save to disc. I have to load the PD patch in Plugdata again, manually, to be able to load the right PD patch, that I save to disc.
> 
> It's a bit confusing, I am not sure if the PD patch being used, is the one I saved to disc or the PD patch is somehow stored/embedded in Plugdata or with the Logic project.

I think this is a precious feature, as it enables to save presets and state saving of patch with diff

> In general I find saving a bit confusing in Plugdata, when using it as a plugin.
> 
> When I load a patch and save it to disc via Plugdata plugin and choose a destination to save it to and then afterwards save Logic and then reopen the Logic project, it does not open the PD patch I save to disc. I have to load the PD patch in Plugdata again, manually, to be able to load the right PD patch, that I save to disc.
> 
> It's a bit confusing, I am not sure if the PD patch being used, is the one I saved to disc or the PD patch is somehow stored/embedded in Plugdata or with the Logic project.

I think on the contrary that this is a feature, useful when you want to save presets, or different states of a patch inside different tracks in your DAW. Maybe it should be more clarified somewhere in the doc. 
I discovered that with plugin version of Plugdata you can create a patch on the fly on a track, and just save your DAW session without having to explicitly save the patch with a filename and path.

**Comment by alcomposer** [comment]
Saving is important to PD, as abstractions only update in parent if they are saved.

**Comment by jaffasplaffa** [comment]
"I think on the contrary that this is a feature, useful when you want to save presets, or different states of a patch inside different tracks in your DAW".

If you want to use different versions of a patch, just make a preset system, saving preset data to txt files. Or use savestate object, which allows you to reuse abstractions, with different settings. Works perfectly, I started using savestate for all my preset systems these days. There is just no easy way around presets in PD or loading the same patch many times. I prefer to just do the work, that needs to be done to make it work.

I would much rater prefer that I just get the right patch every time as I prefer to save my patch to disc. I really don't like the idea of working on a PD patch that's embedded into Plugdata/Logic, that's not saved anywhere. It makes no sense to me. There is also some issue with using embedded patches, you can't really use abstractions, cause Plugdata would not know where to look for the abstraction, cause that embedded patch has no location.

Most of the stuff I do in a patch I am working on, I do in the old version of PD, cause it's easier, Plugdata and UI elements is, in my experience from the last couple of days, a bit hard to work with, Plugdata crashed hundreds of times over the last couple of days, especially when editing UI elements or doing something UI related. So I am juggling between old PD and Logic with Plugdata. I am getting the results I'd like, but it's kind of challenging, when you also have to take alternate versions of PD patches, that's not saved anywhere into consideration into the equation too.

And that's where some of the issues sneak in. If I save a PD patch in old PD and then open Logic, to test if it's working, if I want to open the exact same patch, with the exact same settings, I have to first open Logic then close the patch in Plugdata and then load it again or else it loads some kind of alternate version of the patch. THis also leads to confusion if you then save the patch inside PLugdata in Logic. Then suddenly you may or may not have overwritten the actual patch you wanted to load or maybe it's save as an embedded patch. It's hard to say when it really does what and I experienced that many times over the last days, saving the wrong version of the patch and then loose work. It's not enough to just open Logic and count on the right PD patch is loaded, every time you have to close the patch in Plugdata inside Logic and then open it again, that is the only way to be 100% sure that you are using the right patch. Personally I find that a bit challenging. In the development stage you test if your new idea works many, many times and there is just some things that makes it troublesome, for example the alternate patch issue.

I did install the latest version yesterday and that did do a difference, I did not have as many crashes yesterday as I did the day before, the day before I had to give up working on my patch, cause Plugdata just crashed every time I did any edit. Then I started using old PD for most of the edits and changes and that also helped a bit.

We are moving in the right direction, getting a lot better, though. The newest version is absolutely the most stable version yet and patching experience is also a lot better :)

**Comment by jyg** [comment]
> . I really don't like the idea of working on a PD patch that's embedded into Plugdata/Logic, that's not saved anywhere. It makes no sense to me. There is also some issue with using embedded patches, you can't really use abstractions, cause Plugdata would not know where to look for the abstraction, cause that embedded patch has no location.


I agree. This was only for me a way of realizing that Plugdata saved the patches locally in the DAW session space. I can figure the trouble with loading abstractions.

> > It's a bit confusing, I am not sure if the PD patch being used, is the one I saved to disc or the PD patch is somehow stored/embedded in Plugdata or with the Logic project.
>
May be a "Reload all patches" button in Plugdata ?

However, with [savestate] you can make a  presets saving system and store different presets IN your patch -- I can understand that as a "factory preset"feature --, but I'm not sure that all instances of your patch in all your projects should  have to share the same presets stored within your original patch.
Anyway, I agree that there is some design discussion to develop here :)

PS you can see my PR  here https://github.com/plugdata-team/plugdata/pull/648

**Comment by jaffasplaffa** [comment]
"However, with [savestate] you can make a presets saving system and store different presets IN your patch -- I can imagine that as a "factory preset"feature --, but I'm not sure that all instances of your patch in all your projects should have to share the same presets stored within your original patch."

I agree and tought a bit about it yesterday. I think I am just gonna have a main patch, with the abstraction loaded inside, for each instance of the Plugdata that I want to use the abs in. Like main1, main2, etc. It's a work around, but I think it's what I feel most comfortable with atm.

I also do see the benefit of just opening and instance of Plugdata in you daw and start patching, but mostly in the beginning stage where you just want to get going. But once you start to make something complicated, it pretty much always involves abstractions, where a location on disc is needed, so overall, I am in most favour of making sure it loads the right patch from disc, not an embedded version of the patch, to me that's what most important in the longer run. That's my experience at least. But yeah, I think it's good to have a debate about it :) 

Yes, a reload patch would make it easier, I think, easier than now, where you have to close open the patch inside Plugdata to make sure it's loading the correct version.

Anyway, I really do think there has been a lot of progress done with the 0.7 pre-release ;)

**Comment by timothyschoen** [comment]
There is now a * in the name if a patch has changed.

@jaffasplaffa I'll also take a look at the issues you're experiencing soon, I do agree that the way patch saving works in the DAW right now is confusing.

**Comment by jyg** [comment]
> There is now a * in the name if a patch has changed.
> 
> @jaffasplaffa I'll also take a look at the issues you're experiencing soon, I do agree that the way patch saving works in the DAW right now is confusing.

I opened a specific thread for this :
https://github.com/plugdata-team/plugdata/issues/758
