### ISSUE TITLE
Playhead does not seem to work when using the PlugdataMidi plugin in Logic!

### ISSUE THREAD

**Issue by jaffasplaffa** [plugdata-team/plugdata#639]
Hey :) 

I am trying to create a midi plugin with Plugdata, that I can use it Logic.

But I am experiencing an issue with playhead abstraction. When I load playhead in Plugdata or PlugdataFx, playhead works correctly, but when I try using playhead in PlugdataMidi, it doesn't work, no data comes out the outputs.

Just thought I'd mention it. I have not tried in other DAWs, only Logic.

I am using Logic 10.7.7 on OSX 12.6.3(M1) and Plugdata 0.6.4.

Jakob

**Comment by timothyschoen** [comment]
Hi!

I'm pretty sure this is because either the AU MIDI format doesn't support playhead info at all, or because JUCE hasn't implemented it. Either way, it's outside of my control :(

Nice that you're using the MIDI plugin though, I like to use it as well to make cool arpeggios

**Comment by jaffasplaffa** [comment]
Hey again!

This is embarrassing. I had not loaded an instrument on the channel strip I loaded PlugdataMidi on, which was the reason it did not work. 

I loaded an instrument and now it seems to work.

I apologise, this was my mistake.

Jakob

**Comment by jaffasplaffa** [comment]
On a side note:

Been working a lot with Plugdata this night, on this sequencer, first time I really dive in to make something bigger that I really like to use as a plugin. But I am experiencing so many crashes, I had like 30 crashes within the last 3-4 hours.

Spend a long time working on something, which is inside a subpatch(Not an abstraction) and when I then select the main patch, that contains the subpatch to save it, then Plugdata crashes. I redid this same thing many times in a row, crash every time. 

I can't move on atm. This happens in both plugin and stand alone version.

Can I supply some crash data from Logic or something to get some help? Should I start a new thread for this?

**Comment by jaffasplaffa** [comment]
I've recorded s snippet of video that shows the issue. Everytime I try to go back to the main patch, Plugdata crashes, no matter what I do:

https://youtu.be/-r9Io_rMlZI
