### ISSUE TITLE
[bug] heavy autocomplete deletes letters 

### ISSUE THREAD

**Issue by alcomposer** [plugdata-team/plugdata#640]
This is a strange bug, when entering in text object in Heavy mode, some keys will delete the autocomplete text area:

[](https://user-images.githubusercontent.com/12004932/222941184-4f066e96-c85f-44b0-a8c9-a6243a61067d.mp4)

**Comment by JoshuaACNewman** [comment]
It's jarring the way it is right now, but it's because there's no object in compile mode with that sequence.

**Comment by alcomposer** [comment]
Not sure. If we write a long string then it's fine (that doesn't match)

I think we only have autocomplete suggestions below, and allow a user to up / down arrow key to the chosen autocomplete entry.

**Comment by timothyschoen** [comment]
Fixed with 15b9f60b63853233cd0a601fc522bf13df133f5a
