### ISSUE TITLE
asking help for else/midi gives vanila's midi-help.pd file

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#641]

**Comment by timothyschoen** [comment]
Is it possible to rename the else/midi helpfile to else-midi-help.pd, or something like that? It's hard to find another way around. I could just change it my ELSE files, but I'm sure I'm gonna forget that when I upgrade ELSE...

**Comment by tomara-x** [comment]
rename [else/message]'s help file too? same issue there

**Comment by porres** [comment]
I guess we can have an 'ifdef' in the object's code to ask for a different/renamed file in plugdata, and I assume you can easily copy and rename the help file with some script in compilation time.

maybe you can also do that for vanilla objects

I wouldn't like to change the object name or help file name :( sorry

**Comment by timothyschoen** [comment]
Fixed!
