### ISSUE TITLE
bicoeff's resonance control

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#645]
bicoeff's resonance control is only there for 'eq' and shelves allow it. These are sidebands in the interface that disappear.

**Comment by timothyschoen** [comment]
<img width="523" alt="Screenshot 2023-03-09 at 13 51 19" src="https://user-images.githubusercontent.com/44585538/224028433-9cf4116d-2adf-475a-96e5-da0874d94e7a.png">

Not sure I understand. The "lowpass"/other modes in plugdata already have no resonance right?

**Comment by timothyschoen** [comment]
Aaah I get it now, thanks!

**Comment by timothyschoen** [comment]
Fixed with 5db2849a09b71d29c09412aaca4302b852b4fde4
