### ISSUE TITLE
guis inside a GOP'ed subpatch don't receive mouse events

### ISSUE THREAD

**Issue by jyg** [plugdata-team/plugdata#653]
EDIT2 : tested with commit fec54392dcca85533a57a4505fb4c8fd9c220a6a 
~~EDIT: tested with commit https://github.com/plugdata-team/plugdata/commit/6cf3c224b2c47b3a9b4a316b670cf990aae8c8f3~~

Guis, inside a GOP'ed subpatch, don't receive mouse events , except if we are  in presentation mode,  or in edition mode while pressing ctrl key.
~~Radio GUI receives mouse  events (sends values on its outlet) but the drawing is not refreshed at all.~~

EDIT3 : When on presentation mode, after you pressed and released the CTRL Key (linux), Guis inside GOP subpatch don't respond anymore .

tested on Linux ubuntu 20.04 and on Mac OS 11.4

![Peek 08-03-2023 22-28](https://user-images.githubusercontent.com/1431894/224141477-59be18d1-1ebb-491e-aaa1-44963440a6a2.gif)

[dynamic_abstract.pd.txt](https://github.com/plugdata-team/plugdata/files/10941577/dynamic_abstract.pd.txt)

**Comment by tomara-x** [comment]
on latest it works in all cases except when a patch is reloaded and in run mode

https://user-images.githubusercontent.com/86204514/224896948-bd0b729d-e1cc-4956-9d99-ac2ffd9d4c5e.mp4

**Comment by jyg** [comment]
Indeed. But no need to reload patch. Cut the graph with GUI inside and re-paste it.
![Bug14-03-2023 11-42](https://user-images.githubusercontent.com/1431894/224976437-5d2f1833-86c3-400c-9958-e08a2fb12fc0.gif)

**Comment by timothyschoen** [comment]
Fixed!

**Comment by jyg** [comment]
Thanks a lot ! Much better !
For me there is still an small issue when I open a patch, if I get in locked mode by clicking to the edit mode icon.
https://github.com/plugdata-team/plugdata/issues/705
But I can survive even with it !
