### ISSUE TITLE
gui objects don't update when they receive input

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#655]
👻

https://user-images.githubusercontent.com/86204514/224184382-4d4147f1-d5c3-407f-9114-f508964b7f9c.mp4

**Comment by alcomposer** [comment]
Related to the recent refactoring, direction display also fell off as well, @timothyschoen.

**Comment by tomara-x** [comment]
i do have the arrows, they're just working with alt instead of the diode button now. it does get overwhelming, but my patch is extra dense hehe
kinda weird that they're displayed by default tho, and when you press (and release) alt they're hidden again

**Comment by tomara-x** [comment]
hbout like we make it with the grid? one button that opens a menu, and you choose which modes you want from there. could have checkboxes for object number, arrows, perhaps more info features in the future like connection order, or mouse position coordinates

**Comment by alcomposer** [comment]
No, this is a great idea. A view button. Blender has something identical. 

Let's steal it.

**Comment by tomara-x** [comment]
related to gui objects: [pic] also doesn't update when sending it open messages

**Comment by timothyschoen** [comment]
Should be fixed
