### ISSUE TITLE
[FR] Overlay menu / toggle button

### ISSUE THREAD

**Issue by alcomposer** [plugdata-team/plugdata#663]
Currently we are able to show object index & cable direction via `alt` key.

However, there will be more overlays that we will want to show, and users may not want to show all overlays at the same time, as they can become overwhelming to the user. Especially if they are not related to the task the user is using the overlay display for.

This feature request covers an "Overlay Menu / Toggle Button" that allows the user to select which overlays are displayed when the Overlay Toggle Button, or alt key is pressed.

Overlays to include can be, but not limited to:
* Object Index
* Object XY Coordinate on canvas
* Canvas dashed window rectangle
* Object activation state (highlight objects as data passes through them- bangs etc)
* Connection Order (when more than one connection is exiting from an outlet)
* Connection Direction

**UPDATE**
Here is a mockup of overlay menu popup:
![overlay-dropdown](https://user-images.githubusercontent.com/12004932/226149807-720ae2d2-08b5-4364-bdfd-e37a0484c95e.png)

An example of different overlays selected for different modes / alt:

![overlay-dropdown-active](https://user-images.githubusercontent.com/12004932/226150280-4c475136-7147-4453-bfa9-fa2ed637b5a6.png)

Below is an example of Blenders Overlay menu / toggle:

[](https://user-images.githubusercontent.com/12004932/224460671-b3c18eb4-9c10-4bf8-a81c-7bf38de0b686.mp4)

**Comment by tomara-x** [comment]
idk about connection order tho. you should never rely on that, or need it (i think)

**Comment by tomara-x** [comment]
since you opened this here, what do you think about compiled mode being added to this list?

**Comment by alcomposer** [comment]
> idk about connection order tho. you should never rely on that, or need it (i think)
I think that it's a good debugging tool, if someone thinks that a dual connection isn't causing issues, it very well may.
As for reliability, connection order is super important, and is used for quite a few things in PD, so I think connection order is reliable, and reproducible.

> since you opened this here, what do you think about compiled mode being added to this list?
Hm, I did think about that. I think Heavy mode is more than an overlay, as it restricts new object creation. Where it is makes sense for now.

**Comment by tomara-x** [comment]
aah yeah you're right, be good for debugging. wonder why it doesn't work --> see order --> realize it needs a trigger

**Comment by alcomposer** [comment]
There was a discussion about allowing users to change the order via contextual menu on connection index number. 

Not sure, but showing order (that already exists) is useful even by itself!

**Comment by timothyschoen** [comment]
> Currently we are able to show object index & cable direction via `alt` key.
> 
> However, there will be more overlays that we will want to show, and users may not want to show all overlays at the same time, as they can become overwhelming to the user. Especially if they are not related to the task the user is using the overlay display for.
> 
> This feature request covers an "Overlay Menu / Toggle Button" that allows the user to select which overlays are displayed when the Overlay Toggle Button, or alt key is pressed.
> 
> Overlays to include can be, but not limited to:
> 
>     * Object Index
> 
>     * Object XY Coordinate on canvas
> 
>     * Object activation state (highlight objects as data passes through them- bangs etc)
> 
>     * Connection Order (when more than one connection is exiting from an outlet)
> 
>     * Connection Direction
> 
> 
> Below is an example of Blenders Overlay menu / toggle:

I personally still believe that having a single button to show useful debugging information is a better solution. I don't see the point in having this visible for an extended period of time, when instead you could have a button to show it whenever you actually need it.

But like I said, I'm willing to budge on this if people disagree with me

**Comment by alcomposer** [comment]
It would be one button. 

However a user could choose how much debug info to add to the overlay.

**Comment by ludnny** [comment]
> I personally still believe that having a single button to show useful debugging information is a better solution. I don't see the point in having this visible for an extended period of time, when instead you could have a button to show it whenever you actually need it.
> 
> But like I said, I'm willing to budge on this if people disagree with me

I can see some use cases where a toggle Overlay (like in the Blender example) could be useful.

I really would love to see PlugData or Vanilla being usable with keyboard only, no mouse.
In that case, the Object Index would be always on, and there would be a way to use the numpad to select an object ID and then modify it's value, it's connections or it's content. 

By the way congratulations for the release 0.7, that's an incredible achievement !
