### ISSUE TITLE
[aesthetic] we don't snap to visible grid points in infinite canvas mode

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#675]
https://user-images.githubusercontent.com/86204514/224610118-41bba32b-f1d2-45f5-8697-70db86b52acb.mp4

https://user-images.githubusercontent.com/86204514/224610128-f0df1727-a950-44c5-82f3-763024ca5901.mp4

**Comment by timothyschoen** [comment]
Fixed!
