### ISSUE TITLE
Keyboard object size bugs deux

### ISSUE THREAD

**Issue by alcomposer** [plugdata-team/plugdata#686]
Keyboard gets wrong width depending on other objects / canvas updates:

https://user-images.githubusercontent.com/12004932/224884713-39be36b1-915c-4d68-a268-401264493641.mp4

**Comment by tomara-x** [comment]
for me it's a black area. it also appears when it's duplicated or moved with arrow keys

**Comment by alcomposer** [comment]
I'm thinking if keyboard is fixed up to use keyWidth (`elseKeyboard->x_space` * numWhiteKeys()`) this issue will go away.

**Comment by timothyschoen** [comment]
> I'm thinking if keyboard is fixed up to use keyWidth (`elseKeyboard->x_space` * numWhiteKeys()`) this issue will go away.

Did this, think it's fixed now!
