### ISSUE TITLE
Please add an option to set comments' text to a different colour to regular text in objects

### ISSUE THREAD

**Issue by r4dian** [plugdata-team/plugdata#699]
Comments can barely be seen in the Max theme.

( Setting all text in this theme to about #8C8C8C is a workaround, but lowers the contrast of text on objects. )

**Comment by timothyschoen** [comment]
Hi, I've made some improvements to this:

- canvas text colour id is not used in settings panels anymore, that was a mistake
- Added colour id for comment

I think that should solve it!
