### ISSUE TITLE
[bug] Disable zoom if nothing loaded

### ISSUE THREAD

**Issue by alcomposer** [plugdata-team/plugdata#704]
We can currently set zoom when there are no patches loaded.
New patches take on this zoom level, and when creating a split, the zoom will default to 100%.

We should make all new patches with default 100% zoom, and allow user to change.

We should also turn off zoom when no patches are loaded, and display 100% greyed out.

**Comment by tomara-x** [comment]
> We should make all new patches with default 100% zoom, and allow user to change.

why not the zoom level saved in settings file? i'm always on 100, but i guess some peeps with larger/smaller displays might want a different default when they open something new?

**Comment by alcomposer** [comment]
It would have to be a `defualt zoom setting` as we can have multiple zooms per patch, so which one do we choose? 

Zooming is also very easy, and a dynamic user event that happens throughout the usage of the software.

**Comment by timothyschoen** [comment]
This has been done already right?
