### ISSUE TITLE
Support for small laptop displays

### ISSUE THREAD

**Issue by erroreyes** [plugdata-team/plugdata#710]
Hello,

It would be great to have a way to make the general plugdata UI and L&F larger to support smaller laptop displays and HiDPI. While the actual objects and widgets in a graph can be zoomed in and out as needed, the menu items, panels, buttons, etc, are really hard to read without squinting.

Kubuntu 22.10
Plasma 5.27.3
Display 1920x1080

**Comment by timothyschoen** [comment]
We'll add a global scale soon!

**Comment by timothyschoen** [comment]
<img width="999" alt="Screenshot 2023-03-19 at 15 33 49" src="https://user-images.githubusercontent.com/44585538/226182976-5ecb6f4f-f65d-45fc-ab86-4e1538f7d3e7.png">

Added a global scale option!
