### ISSUE TITLE
Only standalone version when downloading plugdata (Linux, Debian 11)

### ISSUE THREAD

**Issue by bazilmuzik** [plugdata-team/plugdata#712]
Hello !

I downloaded and installed plugdata using the indicated commands for Linux distributions, and there's only the standalone app. No vst3/lv2/clap folders... Apparently these are missing from the build.

**Comment by erroreyes** [comment]
Per `README`, there are **3 packages**, `plugdata`, `plugdata-vst3`, and `plugdata-lv2`, or "lv2-plugdata and vst3-plugdata on some distros.". With `apt`, that means entering:

```bash
sudo apt install plugdata plugdata-vst3 plugdata-lv2
```

**Comment by timothyschoen** [comment]
I've made this more clear in the README now, so hopefully people can find it more easily.

If you want the CLAP version you can also download the zip file for your distro from here: https://github.com/plugdata-team/plugdata/releases/tag/v0.7.0

We'll create a CLAP build on OBS soon!
