### ISSUE TITLE
Deleting connection doesn't mark patch as changed *

### ISSUE THREAD

**Issue by alcomposer** [plugdata-team/plugdata#713]
In regard to, #637. Pulling away a patch cord connection doesn't flag the patch as changed `*` 
Further, when the patch does get flagged as unsaved, resetting the patch to the original state should unflag it as changed.

https://user-images.githubusercontent.com/12004932/226066344-cb9d9caa-1a6d-4f4e-8149-ad819ea350d0.mp4

**Comment by timothyschoen** [comment]
Fixed!
