### ISSUE TITLE
[ux] when alt-dragging an object it's not placed where it really is

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#715]
you can see the phantom of the actual location by using the selection, and it will jump to that location once you place a new object or it's moved with arrow keys

https://user-images.githubusercontent.com/86204514/226104899-71f80235-6507-4828-8e9f-2bcaa17e822e.mp4

or when making a connection

https://user-images.githubusercontent.com/86204514/226104959-3b6d1d75-10ff-47f7-8389-18e5ec7025b5.mp4

**Comment by timothyschoen** [comment]
Fixed!

**Comment by tomara-x** [comment]
speed of ~~mercury~~ timothy!
