### ISSUE TITLE
CTRL/CMD+W (Close Tab Shortkey) closes unsaved tab without warning

### ISSUE THREAD

**Issue by maxela-2001** [plugdata-team/plugdata#717]
Device: MacBook Pro 14" (M1 Pro)
OS: macOS 13.2.1
plugdata version: 0.7.0

---
_Steps to Recreate:_
- Select "New Patch" from screen
- Make some changes
- Press the Close Tab Shortkey, by default Command+W on macOS

_Expected Behaviour:_
- Prompt "Save Changes to 'Untitled Patch'?", just like closing tab via mouse click.

_Actual behaviour:_
- Closes tab **without any warning.**

---

_Consequences:_
- Loss of unsaved work caused by mistouch.

_Possible Workaround:_
- Disable Close Tab Shortkey.

**Comment by timothyschoen** [comment]
Hi, I think this is already fixed in v0.7.1, you can try it by downloading a nightly build from [here](https://plugdata.org/download.html)

**Comment by timothyschoen** [comment]
I've confirmed that cmd+w will ask you to save the patch in v0.7.1 :)
