### ISSUE TITLE
Graph width/height 

### ISSUE THREAD

**Issue by Nejrup** [plugdata-team/plugdata#722]
The window with/height introduced in #711 & #716 setting is a bit confusing. Should it be replaced with graph width/height if 'Is Graph'? or could we just use the Graph size for both scenarios? @alcomposer

**Comment by alcomposer** [comment]
Hm, I think graph size would be confusing? As even a GOP has a window size (just it's not that useful to us).

Personally I think we should keep them as they are in PD-Vanilla. Separate concepts.

**Comment by alcomposer** [comment]
Yeah, I think this is what @timothyschoen would like. This makes sense to me.
