### ISSUE TITLE
canvas.active doesn't trigger when you switch between tabs inside plugdata

### ISSUE THREAD

**Issue by jyg** [plugdata-team/plugdata#740]
It triggers when you switch to another app, but not when you switch between tabs inside plugdata.

**Comment by timothyschoen** [comment]
Canvas.active doesn't measure which tab is visible, it measures whether the canvas has keyboard focus. I think this is the same in Pd, but since there is more stuff in a window that you can click in plugdata, it's a bit less clear.

**Comment by jyg** [comment]
Ah ok. Yes indeed, it 's consistent with pd vanilla else. I didn't check that.
How can I retrieve keyboard events  only in the  specific patch that has focus ?
