### ISSUE TITLE
Palettes visibility on start issue

### ISSUE THREAD

**Issue by alcomposer** [plugdata-team/plugdata#745]
When starting plugdata, palettes are visible when visibility setting is false.

https://user-images.githubusercontent.com/12004932/227833282-87725c94-faed-4549-a656-a517588fc114.mp4

**Comment by alcomposer** [comment]
this issue returns with: [e831fb1](https://github.com/plugdata-team/plugdata/commit/e831fb17773e06b124e5fd0efd49bd8a0ecee207)

**Comment by timothyschoen** [comment]
Fixed!
