### ISSUE TITLE
[FR] add feature to else/canvas.mouse

### ISSUE THREAD

**Issue by jyg** [plugdata-team/plugdata#751]
I would suggest to add a feature to [canvas.mouse]. I need to know the mouse position on parent canvas, even in edit mode. In pd Vanilla, I use [iemguts/canvasreceive] object. Looking for an equivalent in plugdata, [canvas.mouse] should be a good candidate, but doesn't output anything in editmode. This PR adds this feature, that would be enabled only if there is a third non-zero argument in object creation. (TODO : add tooltips description, etc..)

See discussion about it in this closed PR https://github.com/plugdata-team/plugdata/pull/747#issuecomment-1482658816
The proposed mods are here https://github.com/plugdata-team/plugdata/commit/6fdb66c38fa02d3cfba11c457f6f67925ccde557

**Comment by porres** [comment]
please close this, I just merged it, and make future requests just in the ELSE repository please
