### ISSUE TITLE
crash when opening help patch

### ISSUE THREAD

**Issue by sevdh** [plugdata-team/plugdata#753]
Current nightly on macOS:
Create an object (for example [print]) and open the help patch.
This results in the following crash:

Process:               plugdata [23852]
Path:                  /Applications/plugdata.app/Contents/MacOS/plugdata
Identifier:            com.plugdata.plugdata
Version:               0.7.1 (0.7.1)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               502

Date/Time:             2023-03-25 09:33:03.9251 +0100
OS Version:            macOS 12.6.3 (21G419)
Report Version:        12
Anonymous UUID:        71803FF8-D537-93A1-48CA-EB63CE79AB73

Sleep/Wake UUID:       5CC921EF-724E-4EF2-878B-4F592C7616C0

Time Awake Since Boot: 210000 seconds
Time Since Wake:       792 seconds

System Integrity Protection: enabled

Crashed Thread:        0  JUCE Message Thread  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_PROTECTION_FAILURE at 0x000000016f34bec0
Exception Codes:       0x0000000000000002, 0x000000016f34bec0
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [23852]

VM Region Info: 0x16f34bec0 is in 0x16bb48000-0x16f34c000;  bytes after start: 58736320  bytes before end: 319
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      MALLOC_MEDIUM (reserved)    167800000-168000000    [ 8192K] rw-/rwx SM=NUL  ...(unallocated)
      GAP OF 0x3b48000 BYTES
--->  STACK GUARD                 16bb48000-16f34c000    [ 56.0M] ---/rwx SM=NUL  ... for thread 0
      Stack                       16f34c000-16fb48000    [ 8176K] rw-/rwx SM=PRV  thread 0

Kernel Triage:
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage

Thread 0 Crashed:: JUCE Message Thread Dispatch queue: com.apple.main-thread
0   libsystem_malloc.dylib        	       0x193f3f6b0 _malloc_zone_malloc + 4
1   libsystem_c.dylib             	       0x193fdad24 __opendir_common + 64
2   libsystem_c.dylib             	       0x194026930 __opendir2 + 80
3   plugdata                      	       0x100899370 FastDirectoryIterator::FastDirectoryIterator(juce::File const&, bool) + 420
4   plugdata                      	       0x10089970c FastDirectoryIterator::recurse(juce::File const&) + 104
5   plugdata                      	       0x1008998c8 FastDirectoryIterator::recurse(juce::File const&) + 548
6   plugdata                      	       0x1008998c8 FastDirectoryIterator::recurse(juce::File const&) + 548
....... (the above line keeps repeating)

**Comment by timothyschoen** [comment]
Fixed!
