### ISSUE TITLE
The way plugdata-plugin saves a patch in a host session

### ISSUE THREAD

**Issue by jyg** [plugdata-team/plugdata#758]
This is not a bug report, but the documentation may report this behaviour so that everybody should be aware of it.
(Tested with Reaper, linux)
### Modifying a patch from host
-create a DAW session with plugdata fx 
- open an existing patch, say,  _/home/user/my_patch.pd_
- edit it, change something.
- save the DAW session
- plugdata says  "saved to /home/user/my_patch.pd"
- close the DAW session
- if you reopen  _/home/user/my_patch.pd_ from standalone, you can see it has been updated with the changes

Now : 
- reopen the DAW
- edit the , change something.
- save the DAW session
- plugdata says  "saved to /tmp/my_patch.pd"
- close the DAW session
- if you reopen  _/home/user/my_patch.pd_ from standalone, you can see it has **not** been updated with the changes
- if you reopen  the DAW session, you can see that the changes have been saved locally.
- Now, in the plugdata-fx window, click "save" : the original _/home/user/my_patch.pd_ will be updated, and also every time you save the DAW session.

If you want your _original_ patch to be explicitly saved once you edited it in the DAW, you have to explicitly save it from plugdata menu. 
Anyway, the plugdata console says explicitly where the patch is saved.  _/tmp/my_patch.pd_  means locally.

I suppose that any other opened fx-instances of patch are not refreshed nor updated, in the same way you could run several instances of puredata program with the same patch. ( I assume this but didn't check it.)

### Modifying a patch from standalone

- You have to explicitly reload all fx-instances of patch in order to reflect changes made outside. 
(see https://github.com/plugdata-team/plugdata/issues/637#issuecomment-1458001108)
- May be there should be a button for doing that ? such as "refresh all opened instances of this patch"

**Comment by timothyschoen** [comment]
I think the problem is that we store the patch inside the DAW project instead of just having it be a file link. Maybe we should have a setting, load patches from files or load patches from state?

Alternatively, we could do this:
- By default, open patches from file location instead from DAW state
- If the file was moved/doesn't exist anymore, ask the user to locate it manually, or load from state
-  (we store the patch to DAW state as well, as a kind of backup)
- If you close the DAW without saving the patch to a file, it should also automatically load from state

I think there's no ideal solution here unfortunately... But this could help

**Comment by timothyschoen** [comment]
I've found a way to make sure the patch will find abstractions/resources, while not actually loading the file from disk.

So that should mean you no longer need to save the patch to file, it can just load it directly out of your DAW project :)

**Comment by jyg** [comment]
Hi,
I wonder if the daw_storage abstraction has any use now, given that we can now store state of the main patch in the daw session using native [savestate] object.  
Just keeping [daw_storage] for "backward compatibility", as some users are using it in their plugins ? (for example https://discord.com/channels/993531159956955256/993531288273297500/1363745982617092137)
This point should be documented somewhere : "do not use anymore daw_storage object, use savestate instead" .



Or am I wrong ?
