### ISSUE TITLE
[FR] Option for displaying arguments of an abstraction when you are editing it

### ISSUE THREAD

**Issue by jyg** [plugdata-team/plugdata#759]
When you have an instance of an abstraction with arguments, is there a way to see its arguments ($1, $2, etc..) in the patch window title when you edit that abstraction, as pd-vanilla does ?
(even temporarly, when pressing alt- key, should be good)

**Comment by timothyschoen** [comment]
https://github.com/plugdata-team/plugdata/assets/44585538/2db20452-bf19-410e-9eb5-bc5c9a8cb45d

You mean like this? It already kind of did it, but the spaces were missing, that's fixed now. If there is some context where this does not work yet, please let me know!
