### ISSUE TITLE
palette selection menu doesn't update after changing theme

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#761]
https://user-images.githubusercontent.com/86204514/227782445-75220ed5-6c6c-4902-9ad9-4d8bcb9968d0.mp4

**Comment by timothyschoen** [comment]
Fixed because I've removed the palette selection menu (and hide button) because it was too confusing. It was a cool idea, but in reality, too complicated for users to understand.

**Comment by tomara-x** [comment]
yeah, the ability to scroll the palette bar does replace the need for them, so this is good
