### ISSUE TITLE
documentation search issue

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#764]
searching for docs in sidebar doesn't return some existing files

https://user-images.githubusercontent.com/86204514/227816995-a3d45163-5829-4e99-8bf6-73e6394b11d6.mp4

**Comment by timothyschoen** [comment]
Fixed!

**Comment by tomara-x** [comment]
does it work right for you? for me it just shows everything, and then if i try again it shows nothing

**Comment by tomara-x** [comment]
yea, something gone wrong in cf51b09e8b99a

**Comment by timothyschoen** [comment]
I think I really fixed it now?

**Comment by tomara-x** [comment]
nice work! this does fix the search finding the right files
but when you try searching for a word that doesn't exist, and then remove it, search is now completely broken til you restart plugdata

https://user-images.githubusercontent.com/86204514/229386295-8a0bb76f-bbc9-437a-8b4c-ce1429f20e2d.mp4

**Comment by timothyschoen** [comment]
Fixed it! turns out, I was not closing files, so after a while it would hit the maximum allowed of files open on Linux. This is also why opening files stops working after this happens!
