### ISSUE TITLE
keyboard doesn't output note-off when sliding to another key

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#782]
you can see that when released on the a key, we get `69 0`
but when sliding to b, we get `71 0`, then `71 on`, and when releasing, `71 0` again, but 69 never ends

https://user-images.githubusercontent.com/86204514/228985729-582007f9-32b3-4097-b634-5fc1091ca4b5.mp4

**Comment by timothyschoen** [comment]
Fixed with 85652bab7de3ac88c80f5e8a8b73e409b9a167e4
