### ISSUE TITLE
peculiar behavior related to zoom level

### ISSUE THREAD

**Issue by sevdh** [plugdata-team/plugdata#790]
Three issues related to zoom level:

For example at zoom level 160%:
- Moving the canvas around using two-finger-movement  on the trackpad of a macbook pro results in moving the canvas in very different directions than the actual finger movement itself.
- Moving the canvas with the vertical scroll bar sometimes also results in horizontal movement of the canvas(!). This happens in  particular after moving the canvas with two fingers on the trackpad.
- opening Plugdata (also with zoom level 160%) and starting a new patch shows the horizontal canvas limit at 25% of the vertical screen space.

**Comment by timothyschoen** [comment]
I've made some improvements to make it zoom to the correct point, it's still not perfect, but a bit better. It's still shaky when you zoom out <100% though.

I'll also fix those other issues!

**Comment by timothyschoen** [comment]
https://user-images.githubusercontent.com/44585538/230748400-4730c4d2-5ee6-471c-9981-c9ff7f73d361.mov

Getting better!

**Comment by timothyschoen** [comment]
Should all be fixed now!
