### ISSUE TITLE
else/pic  doesn't take care of [declare -path] in palette

### ISSUE THREAD

**Issue by jyg** [plugdata-team/plugdata#795]
I'm not sure if this is specific to [pic] or a problem with palette initialization...
It seems that when a palette is loaded with a [pic] inside, this [pic] object, on startup, doesn't take account of additional [declare -path ..] objects included in this palette to retrieve the image file. Resulting in loading an image with size = (0,0). 
Everything is ok in a standard patch.
On the other hand, in palette, [declare -path ] is taken in account for retrieving and loading abstractions that are in a specific folder.

https://user-images.githubusercontent.com/1431894/230596355-0be67671-3306-4dca-9f8e-9bb789f22979.mp4

**Comment by timothyschoen** [comment]
Since the old palette system has been replaced, this is no longer a thing
