### ISSUE TITLE
flags don't show up in reference 

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#804]
![Screenshot_2023-04-13_02-33-14](https://user-images.githubusercontent.com/86204514/231615285-0cdac8b6-49cd-42f1-9170-29e2dc9602f7.png)
![Screenshot_2023-04-13_02-34-40](https://user-images.githubusercontent.com/86204514/231615388-7114cc9b-f7b0-440d-858b-4c9f1b40e8eb.png)

**Comment by timothyschoen** [comment]
Fixed!
