### ISSUE TITLE
plugin mode allows editing the patch after closing and reopeing the window

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#813]
bitwig and reaper on linux

https://user-images.githubusercontent.com/86204514/231916348-445a791b-9663-4a67-a11c-4c206b6936c6.mp4

https://user-images.githubusercontent.com/86204514/231916358-d918c018-8763-40c4-bec6-60861c8d5526.mp4

**Comment by timothyschoen** [comment]
Fixed!
