### ISSUE TITLE
closing plugin window can leave you in a fake edit mode

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#814]
sometimes it's after closing the window, other times it's after duplicating an object. those are the cases i ran into it. you'll be clicking but not really selecting the objects, you're actually interacting with them

[edit2: actually, close window, reopen it, then duplicate an object, now the only way out is to switch to run mode and back]

https://user-images.githubusercontent.com/86204514/231919534-61a905c9-7f26-4cb4-8bd1-6f7b02325865.mp4

.
this shows it better

https://user-images.githubusercontent.com/86204514/231922870-318e69c3-5c84-4716-9d03-ca8575c8081a.mp4

**Comment by timothyschoen** [comment]
Fixed!
