### ISSUE TITLE
where is 'test audio and midi' example?

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#827]

**Comment by tomara-x** [comment]
a bit hidden, it's in Documentation/7.stuff/tools/testtone.pd

**Comment by porres** [comment]
this and cpu test could be called from the menu like in vanilla

**Comment by agraef** [comment]
Agreed. Vanilla users will expect to find these in the menu. It's probably the first thing they will be looking for if they're new to plugdata. At least there should be a quick access to these in the documentation browser, preferably at the top level.

**Comment by porres** [comment]
@timothyschoen since you're rocking and stuff, please check this out, should be simple.

I worked a lot on this patch for the new release and I think it looks pretty cool now!

**Comment by timothyschoen** [comment]
I would like to make this more easily available, but I'm also trying to keep the main menu as minimal as possible.

I think I prefer what @agraef suggested, putting them at the top-level of the documentation panel.

**Comment by porres** [comment]
seems a bit out of place but much better than way hidden :) where are the audio settings in plugdata btw?

**Comment by timothyschoen** [comment]
> seems a bit out of place but much better than way hidden :) where are the audio settings in plugdata btw?

Main menu -> Settings is where all the settings are :)

**Comment by porres** [comment]
so this would be a nice place to have this

![Screen Shot 2023-10-02 at 16 08 16](https://github.com/plugdata-team/plugdata/assets/5360142/55005451-37b1-4c54-ac3f-4577c285177b)

**Comment by porres** [comment]
what is the status bar?

**Comment by timothyschoen** [comment]
<img width="1006" alt="Screenshot 2023-10-03 at 18 51 35" src="https://github.com/plugdata-team/plugdata/assets/44585538/18a1b692-2add-4bfa-bc2c-025279330aaf">

It would go here

**Comment by porres** [comment]
I see, but you would simply just always print the cpu usage value, right?

**Comment by alcomposer** [comment]
One idea is to have a meter that shows the value over time. Possibly without the number as it could be distracting.

Clicking a chevron to the side would show more detailed info, and possibly a longer timeframe. Not sure.

A meter like this (not my mockup, for example only):
![IMG_20231004_054714.jpg](https://github.com/plugdata-team/plugdata/assets/12004932/e7fed61e-8af7-4448-a4b5-568084b059bd)

**Comment by porres** [comment]
> We already have audio testing in the settings panel

That one is quite modest and doesn't really compare to the more detailed testing patch, with input and output control for groups of 8 channels. This is really important to check in which audio input some audio card input is coming into Pd, or out as well, like when you have more than two ins and outs.

But then, I was checking it, and I don't see how to add more channels for in/output, like you can in Pd's settings. What's the deal?

**Comment by timothyschoen** [comment]
<img width="345" alt="Screenshot 2023-10-13 at 04 05 50" src="https://github.com/plugdata-team/plugdata/assets/44585538/783703a8-0aa7-4479-8448-69d1ec23fb66">

CPU meter has been added btw!

You should be able to add channels by enabling/disabling them from the list in settings:

<img width="607" alt="Screenshot 2023-10-13 at 04 07 05" src="https://github.com/plugdata-team/plugdata/assets/44585538/51519a74-69bb-4cd7-8824-bfbbb4023203">
