### ISSUE TITLE
dac out not functioning in Ableton 11

### ISSUE THREAD

**Issue by Woolton** [plugdata-team/plugdata#830]
Using version 0.7.0 on Windows 11, in Ableton 11, midi input produces no  audio output. Not sure if I am supposed to have set something or if `dac` and `output` do not work in vst mode.

**Comment by tomara-x** [comment]
they should work.. could we have a picture of the setup maybe? are you getting the midi indicator to light up in plugdata?

https://user-images.githubusercontent.com/86204514/232284010-54c93f60-5117-4b6f-903e-fad715202a85.mp4

**Comment by Woolton** [comment]
After some more investigation, it seems pd-extended and purr-data scripts simply don't work. After making a new patch and trying some classic pure data scripts, I got sound to work
