### ISSUE TITLE
Save and Compile/Export not working in OpenSuse Tumbleweed

### ISSUE THREAD

**Issue by michaelmariaott** [plugdata-team/plugdata#844]
I installed PlugData from the repository in OpenSuse Tumbleweed. The Save/Save as... Buttons and the Compile/Export buttons do not work. The do nothing (no error messages or other reactions). 

```
OS: openSUSE Tumbleweed  
Host: 20L6S6LP00 ThinkPad 
Kernel: 6.2.10-1-default 
Resolution: 1920x1080 
DE: Xfce 4.18 
CPU: Intel i7-8650U (8)  
GPU: Intel UHD Graphics  
GPU: NVIDIA GeForce MX15 
Memory: 2296MiB / 31834M
```

**Comment by timothyschoen** [comment]
Strange, are you using v0.7.0 or a nightly build? I haven't tested plugdata on OpenSUSE specifically, so I'll do that soon!

**Comment by michaelmariaott** [comment]
I'm using v0.7.0, but I just tried nightly and have the same problems there.

**Comment by phoracek** [comment]
Hi all, I have the same issue on my Fedora 38, using both the standalone binary from v0.7.0 plugdata-Fedora-37-x64.tar.gz and the latest `main` branch. Everything else seems to work fine.

**Comment by timothyschoen** [comment]
> Hi all, I have the same issue on my Fedora 38, using both the standalone binary from v0.7.0 plugdata-Fedora-37-x64.tar.gz and the latest `main` branch. Everything else seems to work fine.

Interesting, I'm using Fedora 37 (on arm) myself, and I don't have this problem. I wonder if this is related to JUCE not working on more recent Linux distros?

Another thing that might be relevant, are you using Wayland or X11?

**Comment by phoracek** [comment]
I'm using X11. Curiously, the "Open" dialog worked fine, so I messed with the function a little and noticed that if I remove `FileBrowserComponent::warnAboutOverwriting` flag from https://github.com/plugdata-team/plugdata/blob/main/Source/PluginEditor.cpp#L434, then the dialog pops up.

**Comment by timothyschoen** [comment]
Good to know, I'll make sure that flag isn't set on Linux! Thanks for investigating!

**Comment by timothyschoen** [comment]
I've addressed this for save with 1eabc725fba6d3cf77db511fc4221eaad1a90702, I'll make sure to do this anywhere we use the save dialog.

**Comment by timothyschoen** [comment]
This should be fixed :)

**Comment by KottV** [comment]
I know I'm late but it was Zenity bug https://gitlab.gnome.org/GNOME/zenity/-/issues/55
