### ISSUE TITLE
GraphOnParent

### ISSUE THREAD

**Issue by NuttyMonk** [plugdata-team/plugdata#846]
Hi,

GraphOnParent isn't showing it's inernal controls on the Parent.

I'm using v 0.7.0 on Windows 10

Cheers

**Comment by NuttyMonk** [comment]
I've been able to do a workaround by adjusting the code for the pd file in a text editor

> #X coords 0 -1 1 1 100 110 1 264 76;

That final "1" before the "264" value was set to 0.  Making it 1 turned the patch into a GOP patch.

**Comment by jamshark70** [comment]
To be more precise:

In PlugData, you can create a graph-on-parent *subpatch* from the + menu.

But if you create a new patch to use as an *abstraction*, there is no way in PlugData to set its graph-on-parent properties at the top level... but it needs to be at the top level. (You can right-click the top level canvas and Properties, but *nothing happens*, so there's no way to set graph-on-parent here.)

You can hack the pd file as stated above. Or you can create the abstraction in regular Pd and then use it in PlugData.

Top-level canvas properties need to be available.

**Comment by NuttyMonk** [comment]
Hi jamshark70,

i created a new file in puredata and set it to be a GOP in it's canvas properties.  I then saved it like that, completely empty.  I can now use this as an abstraction template in plugdata.  An easier workaround.

Thanks for your help.
