### ISSUE TITLE
[knob] clicking changes value

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#871]
when you click (and not drag) value changes. it gets increased if the position is > half the range, and vice versa.. it's like it's falling to the nearest end hehe

https://user-images.githubusercontent.com/86204514/236688991-2a68199c-b059-4ae4-866c-97c1822aae9a.mp4

**Comment by timothyschoen** [comment]
Looks a lot like a bug in JUCE, I'll report it to them!

**Comment by timothyschoen** [comment]
> Looks a lot like a bug in JUCE, I'll report it to them!

Nope, it was our fault, but @alcomposer fixed it now!
