### ISSUE TITLE
List of unresponsive object methods

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#884]
- [note]
  - [x] justification
  - [x] size
- [vsl/hsl]
  - [x] orientation
- [knob]
  - [x] init
  - [x] bgcolor
  - [x] fgcolor
  - [x] arccolor
  - [x] outline

i'll try to see what i can do with knob tomorrow, and maybe see what you did in radio and copy it to slider. but i can't figure out the [note] ones

**Comment by timothyschoen** [comment]
Fixed these!

**Comment by tomara-x** [comment]
woooo! yess! <3
