### ISSUE TITLE
doc parsing has an issue with parentheses 

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#893]
not sure how frequent it is, but when a description has parentheses like this
![Screenshot_2023-05-19_04-35-54](https://github.com/plugdata-team/plugdata/assets/86204514/b6edb32d-0b9f-432f-8ad5-2e57c3b649e2)
it appears like this:
![Screenshot_2023-05-19_04-33-08](https://github.com/plugdata-team/plugdata/assets/86204514/0b2fa944-6cd2-46e1-94dd-b0b41922dfad)

**Comment by timothyschoen** [comment]
The real problem is that "default:" is a valid marker name for "flags". So I think we probably want to put these defaults on their own line.

**Comment by tomara-x** [comment]
got it. i'll get to them soon

**Comment by tomara-x** [comment]
are you sure about putting them on a separate line? i tried and it makes them disappear completely.. does that mean you'll need to adjust something?

**Comment by timothyschoen** [comment]
I think the python parsing script requires it, but maybe plugdata isn't doing anything with it yet? I'll take a look tomorrow

**Comment by timothyschoen** [comment]
Fixed, it now shows (default: x) after the description if the default value is defined!

**Comment by tomara-x** [comment]
you're doing amazing, homie! <3
