### ISSUE TITLE
Unable to start - segmentation fault

### ISSUE THREAD

**Issue by jcsekinger** [plugdata-team/plugdata#895]
Plugdata doesn’t start _anymore_ in Manjaro (plugdata-bin 0.7.1-4). 
Here is the output in the terminal (bash): Erreur de segmentation (core dumped) / (fish): Job 1, 'plugdata' terminated by signal SIGSEGV (Erreur de frontière d'adresse).
what can I do ? thank you !

**Comment by timothyschoen** [comment]
Is this with the standalone or the plugin, or both?

What I've seen help in the past, is removing plugdata's settings file, located at ~/.config/plugdata/Settings.xml

**Comment by jcsekinger** [comment]
both
(thank you)
