### ISSUE TITLE
Manjaro: Due to new path added in settings, unable to start

### ISSUE THREAD

**Issue by jcsekinger** [plugdata-team/plugdata#897]
In Manjaro, I have a " segmentation fault " each time I add a path in "settings". (plugdata 0.7.1-4)

**Comment by timothyschoen** [comment]
Good to know, thanks for figuring that out! I'll take a look at what's causing this right now.

**Comment by timothyschoen** [comment]
There have been some improvements to the paths, including a check to make sure the path is valid, and a rewritten paths settings. Does this issue still occur on the latest nightly builds?
