### ISSUE TITLE
show nightly build version in the downloaded nightly build app using commit number and make it clear it is not a stable version

### ISSUE THREAD

**Issue by porres** [plugdata-team/plugdata#904]

**Comment by timothyschoen** [comment]
<img width="252" alt="Screenshot 2023-05-20 at 13 53 06" src="https://github.com/plugdata-team/plugdata/assets/44585538/e8c3fd6d-8488-498a-91d4-a3cf334f0325">

Done, it should now show this unless it's a stable version :)
