### ISSUE TITLE
messbox issues

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#918]
- [x] dollar signs are not substituted (and it doesn't output when it receives anything)
- [x] comma separated messages aren't sent sequentially like a normal message box (we get literal "," instead)
- [x] semicolons are also taken literally (no send to the symbol)
- [x] saved font size isn't loaded when loading a patch (have to go to edit mode and select the object for it to load that)

**Comment by timothyschoen** [comment]
I think some of these are fixed, but not all of them right?

**Comment by tomara-x** [comment]
oh no, those are the ones i didn't know how to fix. it's really a mess box

**Comment by timothyschoen** [comment]
Should all be fixed by f4c57e5de80691b64a46e2f2a2333334de808a0d
