### ISSUE TITLE
Two requests for clone

### ISSUE THREAD

**Issue by Omar-Misa** [plugdata-team/plugdata#928]
Hi,
Thanks for bringing PlugData into the world.  i recommend it as often as fitting for the conversation.

Here are a couple of items relating to the clone object:
1.  The "vis" message, used to view a particular instance, has no effect.
2. Pure Data vanilla shows clone's instance and creation arguments in its title.  Is it possible to have the same in Plug Data?  i appreciate that this is only relevant when item no.1 in this list is satisfied.

**Comment by timothyschoen** [comment]
https://github.com/plugdata-team/plugdata/assets/44585538/b77cd29e-a728-4f70-bae4-eb9f8cbb1bd0


Fixed it!

**Comment by Omar-Misa** [comment]
Thank you!  Your efforts are appreciated and PlugData's fast-paced evolution is evident in its nightly builds.
