### ISSUE TITLE
rearranging iolets in subpatch doesn't update connections

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#938]
https://github.com/plugdata-team/plugdata/assets/86204514/2509d236-4eea-4e73-a7a5-51a8226805d2

https://github.com/plugdata-team/plugdata/assets/86204514/29df69fc-c229-427a-ae06-f34db951b033

**Comment by 60-hz** [comment]
Also I see that swaping those [inlet]  in subpatch will make another issues later on, on the main patch. If Inserting a connection (using Shift key) in main patch, a double connection is made and an error message appear when selecting the first one:
"consistency check failed: non-existent connection"

<img width="841" alt="Capture d’écran 2023-07-14 à 11 46 18" src="https://github.com/plugdata-team/plugdata/assets/5449719/7ff28f0a-ba6c-4e23-977a-e9a2e3bec698">

**Comment by timothyschoen** [comment]
Fixed!

**Comment by tomara-x** [comment]
oooo someone's on fire today!!
