### ISSUE TITLE
plugdata crashes ableton on MacOS

### ISSUE THREAD

**Issue by michal-cab** [plugdata-team/plugdata#948]
MacOS 13.01 / M1 / Ableton 11

plugdata instance is loaded and in patch where are objects [env~] or [fiddle~] is working.\
trying to close plugdata window will crash ableton. when objects [env~] or [fiddle~] are removed it is possible
to close plugdata window with no crash...

**Comment by michal-cab** [comment]
(just adding that same patch works ok on linux and ardour :))

**Comment by timothyschoen** [comment]
Thanks for reporting, I'll take a look at this! Might be related to those specific objects?

**Comment by michal-cab** [comment]
yup - not sure, we were trying to remove different objects from that simple patch and it was still crashing till we tried to remove [env~] or [fiddle~]. patch follows and adding that under MacOS we were working with latest stable version 0.7.1  
[send_audio_plugdata2.zip](https://github.com/plugdata-team/plugdata/files/11936872/send_audio_plugdata2.zip)

**Comment by SloBloLabs** [comment]
plugdata 0.8.2 / Ableton 11 / MacOS 14.2.1 on M1
drag a fresh intrument plugin on an empty midi channel and clicking any object on the left makes it all crash:

Crashed Thread:        0  MainThread  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000040
Exception Codes:       0x0000000000000001, 0x0000000000000040

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [41182]

VM Region Info: 0x40 is not in any region.  Bytes before following region: 4340449216
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      102b60000-10747c000    [ 73.1M] r-x/r-x SM=COW  ...ts/MacOS/Live

Thread 0 Crashed:: MainThread Dispatch queue: com.apple.main-thread
0   plugdata                      	       0x17b14934c ZoomableDragAndDropContainer::startDragging(juce::var const&, juce::Component*, juce::ScaledImage const&, bool, juce::Point<int> const*, juce::MouseInputSource const*, bool) + 3264
1   plugdata                      	       0x17b14934c ZoomableDragAndDropContainer::startDragging(juce::var const&, juce::Component*, juce::ScaledImage const&, bool, juce::Point<int> const*, juce::MouseInputSource const*, bool) + 3264
2   plugdata                      	       0x17b1cfe20 ObjectDragAndDrop::mouseDrag(juce::MouseEvent const&) + 696
3   plugdata                      	       0x17af4f2f4 juce::detail::MouseInputSourceImpl::setPointerState(juce::detail::PointerState const&, juce::Time, bool) + 1144
4   plugdata                      	       0x17af83d90 juce::ComponentPeer::handleMouseEvent(juce::MouseInputSource::InputSourceType, juce::Point<float>, juce::ModifierKeys, float, float, long long, juce::PenDetails, int) + 484
5   plugdata                      	       0x17af7e7a0 juce::JuceNSViewClass::mouseDragged(objc_object*, objc_selector*, NSEvent*) + 304
6   AppKit                        	       0x18e845308 -[NSWindow _handleMouseDraggedEvent:] + 52
7   AppKit                        	       0x18ded27f0 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 448
8   AppKit                        	       0x18ded245c -[NSWindow(NSEventRouting) sendEvent:] + 284
9   AppKit                        	       0x18e57f9f4 -[NSApplication(NSEventRouting) sendEvent:] + 1604
10  Live                          	       0x103c2e8fc 0x102b60000 + 17623292
11  AppKit                        	       0x18e1ce908 -[NSApplication _handleEvent:] + 60
12  AppKit                        	       0x18dd99d74 -[NSApplication run] + 512
13  Live                          	       0x103c3c068 0x102b60000 + 17678440
14  dyld                          	       0x18a16d0e0 start + 2360

**Comment by timothyschoen** [comment]
> plugdata 0.8.2 / Ableton 11 / MacOS 14.2.1 on M1 drag a fresh intrument plugin on an empty midi channel and clicking any object on the left makes it all crash:
> 
> Crashed Thread: 0 MainThread Dispatch queue: com.apple.main-thread
> 
> Exception Type: EXC_BAD_ACCESS (SIGSEGV) Exception Codes: KERN_INVALID_ADDRESS at 0x0000000000000040 Exception Codes: 0x0000000000000001, 0x0000000000000040
> 
> Termination Reason: Namespace SIGNAL, Code 11 Segmentation fault: 11 Terminating Process: exc handler [41182]
> 
> VM Region Info: 0x40 is not in any region. Bytes before following region: 4340449216 REGION TYPE START - END [ VSIZE] PRT/MAX SHRMOD REGION DETAIL UNUSED SPACE AT START ---> __TEXT 102b60000-10747c000 [ 73.1M] r-x/r-x SM=COW ...ts/MacOS/Live
> 
> Thread 0 Crashed:: MainThread Dispatch queue: com.apple.main-thread 0 plugdata 0x17b14934c ZoomableDragAndDropContainer::startDragging(juce::var const&, juce::Component*, juce::ScaledImage const&, bool, juce::Point const*, juce::MouseInputSource const*, bool) + 3264 1 plugdata 0x17b14934c ZoomableDragAndDropContainer::startDragging(juce::var const&, juce::Component*, juce::ScaledImage const&, bool, juce::Point const*, juce::MouseInputSource const*, bool) + 3264 2 plugdata 0x17b1cfe20 ObjectDragAndDrop::mouseDrag(juce::MouseEvent const&) + 696 3 plugdata 0x17af4f2f4 juce::detail::MouseInputSourceImpl::setPointerState(juce::detail::PointerState const&, juce::Time, bool) + 1144 4 plugdata 0x17af83d90 juce::ComponentPeer::handleMouseEvent(juce::MouseInputSource::InputSourceType, juce::Point, juce::ModifierKeys, float, float, long long, juce::PenDetails, int) + 484 5 plugdata 0x17af7e7a0 juce::JuceNSViewClass::mouseDragged(objc_object*, objc_selector*, NSEvent*) + 304 6 AppKit 0x18e845308 -[NSWindow _handleMouseDraggedEvent:] + 52 7 AppKit 0x18ded27f0 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 448 8 AppKit 0x18ded245c -[NSWindow(NSEventRouting) sendEvent:] + 284 9 AppKit 0x18e57f9f4 -[NSApplication(NSEventRouting) sendEvent:] + 1604 10 Live 0x103c2e8fc 0x102b60000 + 17623292 11 AppKit 0x18e1ce908 -[NSApplication _handleEvent:] + 60 12 AppKit 0x18dd99d74 -[NSApplication run] + 512 13 Live 0x103c3c068 0x102b60000 + 17678440 14 dyld 0x18a16d0e0 start + 2360

Should be fixed on the latest nightly builds!

**Comment by SloBloLabs** [comment]
Confirm it is working now with update 0.8.3 delivered by homebrew.

**Comment by timothyschoen** [comment]
(unless this is still happening, then you may reopen this)
