### ISSUE TITLE
Windows 10 plug in version ignores spacebar  when editing 

### ISSUE THREAD

**Issue by JRSV** [plugdata-team/plugdata#954]
Hello Plug Data team

I have installed Plug-Data 0.7.1 and when I load it in reaper as a plugin it does not allow me to write spaces in the objects. I want to write [route /giro] but it ignores all attempts to write a blank space after "route"

**Comment by timothyschoen** [comment]
Hi!

In reaper, you'll have to enable "send all keyboard input to plugin" to have stuff like spacebar and keyboard shortcuts work properly.

**Comment by JRSV** [comment]
oh!! great! thanks
