### ISSUE TITLE
Clicking on [array define] in run mode crashes plugdata 

### ISSUE THREAD

**Issue by Eric-Lennartson** [plugdata-team/plugdata#963]
I'm working from a 2015 MacBook Pro using macOS 12.6.6

To replicate
- create an array using [array define]
- enter run mode and attempt to view the array by clicking on array define
- if it doesn't crash at first just close the gui and try a few more times

It usually crashes immediately for me, although sometimes I have been able to view the array.

**Comment by timothyschoen** [comment]
Thanks for reporting, I think it should be fixed with 1d09006d0e6f47b383999e1ecd17dc327da24a00
