### ISSUE TITLE
numbox width changes after saving

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#977]
when the height is changed, it keeps expanding in width with every save until it reaches a certain point

smol:

https://github.com/plugdata-team/plugdata/assets/86204514/9a4f88be-fb47-41d9-9542-79a35d3737c5

beeeeg:

https://github.com/plugdata-team/plugdata/assets/86204514/0e85f47f-2178-45ae-a507-37f65fd5094e

**Comment by timothyschoen** [comment]
Should be fixed with 1b12b41bac3b04df7e2fec5a3dc18530641fab93! 

There is still some rounding that happens on numbox size when you save/reload, you can also see this when duplicating. But at least it won't keep expanding forever anymore!
