### ISSUE TITLE
descriptions are numbered incorrectly in reference

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#984]
![Screenshot_2023-07-28_22-55-34](https://github.com/plugdata-team/plugdata/assets/86204514/87973066-1f7c-458e-8027-7ddf30ab81fd)
![Screenshot_2023-07-28_22-54-42](https://github.com/plugdata-team/plugdata/assets/86204514/a96336d4-2af5-4a8d-b25d-b789c4dcf09a)

**Comment by timothyschoen** [comment]
Oh yeah and this should have a real layout too instead of text dump

**Comment by timothyschoen** [comment]
<img width="898" alt="Screenshot 2023-08-13 at 05 50 19" src="https://github.com/plugdata-team/plugdata/assets/44585538/2101673d-8c5e-48ff-ae34-9385baff1fa5">

Fixed!

**Comment by tomara-x** [comment]
yesss! hahaha! yessss! i like what i see!

**Comment by timothyschoen** [comment]
> yesss! hahaha! yessss! i like what i see!

Ikr, now you'll actually want to use this panel
