### ISSUE TITLE
Editing a patch in the plugin GUI freezes Ardour

### ISSUE THREAD

**Issue by agraef** [plugdata-team/plugdata#989]
E.g., start with plugdata.lv2, create an empty patch, create an automation param and then drag it into the canvas. This freezes the plugin window and Ardour, so that I have to kill it. 100% reproducible for me. Works fine in the standalone.

This is with Ardour 7.5.202, plugdata from git (https://github.com/plugdata-team/plugdata/commit/dc7b59a3cb7dd8b533b7a88e6c6617d9048a5c8e).

(This might have already been reported, if so, then sorry. I just didn't have the time to dig through the past tickets.)

![plugdata-bug](https://github.com/plugdata-team/plugdata/assets/2853977/6bf7caf9-3789-40f2-945f-277361f974ad)

**Comment by agraef** [comment]
Actually, this bug doesn't seem to be related to the drag operation. The lockup happens whenever I add a [param] object to a new patch. Incidentally, the same happens when I try to create an [output~] object. Same in both Ardour and Carla. So I'm not sure whether the lockup is due to editing per se, or whether it's just the insertion of some kinds of objects which causes the issue.

**Comment by agraef** [comment]
This weird issue does *not* arise in 0.7.0, so it seems to be a recent regression.

**Comment by timothyschoen** [comment]
Is this still happening?

**Comment by agraef** [comment]
Seems to be fixed on HEAD, at least I can't reproduce it anymore.
