### ISSUE TITLE
[keyup]/[keydown] output inconsistent on Windows

### ISSUE THREAD

**Issue by nuoun** [plugdata-team/plugdata#992]
Tested on Win 10 on the latest nightly standalone version, the output of these two objects seems to use some ascending value format where Pd vanilla or plugdata on Debian Linux version outputs just the decimal ASCII values of alphanumeric keys as expected. 
For example, key 'a' outputs 65 and key 'z' outputs 90 which should be 97 and 122.

And as an aside, shift key seems to get ignored on Windows which is probably related.

Edit: Oops. title should read [key]/[keyup]

**Comment by timothyschoen** [comment]
Ahh I see, the alphanumeric characters are offset by 32. This was also a problem on macOS before, so now I applied the same solution for Windows :)
